import {describe,it,expect,vi} from "vitest";
import {deflateSync} from "node:zlib";
import {GenerateImageInputSchema,RenderChartInputSchema,RenderDiagramInputSchema,ImageProviderConfigUpdateSchema} from "@tracegraph/contracts";
import {ConfigurableImageProvider} from "./provider.js";
import {strictImageBase64,verifyRasterImage} from "./image-bytes.js";
import {createMediaInstructionAdapter,createMediaTaskTitle} from "./tool-extension.js";
import {MediaOperationSchema} from "@tracegraph/contracts";
import {renderChart,renderDiagram} from "./render.js";
function crc(bytes:Uint8Array){let value=0xffffffff;for(const byte of bytes){value^=byte;for(let i=0;i<8;i++)value=(value>>>1)^((value&1)?0xedb88320:0);}return(value^0xffffffff)>>>0;}
function chunk(type:string,body:Buffer){const value=Buffer.alloc(body.length+12);value.writeUInt32BE(body.length);value.write(type,4);body.copy(value,8);value.writeUInt32BE(crc(value.subarray(4,-4)),value.length-4);return value;}
function png(){const header=Buffer.alloc(13);header.writeUInt32BE(2,0);header.writeUInt32BE(2,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from("89504e470d0a1a0a","hex"),chunk("IHDR",header),chunk("IDAT",deflateSync(Buffer.from([0,255,0,0,255,0,255,0,255,0,0,0,255,255,255,255,255,255]))),chunk("IEND",Buffer.alloc(0))]);}
const image=png(),base64=image.toString("base64"),input=GenerateImageInputSchema.parse({prompt:"A deterministic PNG protocol fixture"});
function provider(payload:unknown,protocol:"openai-images"|"openai-responses"|"openai-chat-images"="openai-images",status=200){const request=vi.fn(async()=>new Response(JSON.stringify(payload),{status}));const value=new ConfigurableImageProvider({resolveCredential:async()=>"dummy-isolated-image-key",fetch:request});value.configure({protocol,base_url:"http://127.0.0.1:18081/v1",model:"fixture-image",credentialRef:"${secret:MEDIA_FIXTURE}"});return{value,request};}
describe("MEDIA-094 bounded output and explicit image protocols",()=>{
  it("uses friendly titles while hashing the complete typed media intent for exact retries",()=>{const first=MediaOperationSchema.parse({kind:"chart",title:"Friendly chart",chart_type:"bar",labels:["one"],values:[1]});const changed=MediaOperationSchema.parse({...first,values:[2]});expect(createMediaTaskTitle(first)).toBe("Create chart: Friendly chart");expect(createMediaTaskTitle(MediaOperationSchema.parse({kind:"generate",prompt:"An image\nwith spaces"}))).toBe("Create image: An image with spaces");expect(createMediaInstructionAdapter(first).name).toBe(createMediaInstructionAdapter(first).name);expect(createMediaInstructionAdapter(first).name).not.toBe(createMediaInstructionAdapter(changed).name);});
  it("accepts fully decoded PNG with CRC/IDAT checks and rejects damaged/truncated or prose output",()=>{expect(verifyRasterImage(image)).toMatchObject({mimeType:"image/png",width:2,height:2});const damaged=Buffer.from(image);damaged[damaged.length-5]=damaged[damaged.length-5]!^1;for(const bytes of [damaged,image.subarray(0,-1),Buffer.from("I created an image"),Buffer.from("<svg>script</svg>")])expect(()=>verifyRasterImage(bytes)).toThrow();});
  it("rejects noncanonical base64, whitespace, data URLs and signature-only PNG",()=>{for(const value of ["",base64+"\n","data:image/png;base64,"+base64,"@@@@","AAAA=",base64.slice(0,-1)])expect(()=>strictImageBase64(value)).toThrow();expect(()=>verifyRasterImage(Buffer.from("89504e470d0a1a0a00000000","hex"))).toThrow();});
  it("declares PNG only and rejects unbounded/mismatched chart, diagram and credential endpoints",()=>{expect(()=>GenerateImageInputSchema.parse({prompt:"test",format:"jpeg"})).toThrow();expect(()=>RenderChartInputSchema.parse({title:"bad",chart_type:"bar",labels:["a"],values:[1,2]})).toThrow();expect(()=>RenderChartInputSchema.parse({title:"bad",chart_type:"bar",labels:["a"],values:[Infinity]})).toThrow();expect(()=>RenderDiagramInputSchema.parse({title:"bad",nodes:[{id:"a",label:"one"}],edges:[{from:"a",to:"missing"}]})).toThrow();for(const base_url of ["http://remote.invalid/v1","https://secret@provider.invalid/v1","https://provider.invalid/v1?key=secret"])expect(()=>ImageProviderConfigUpdateSchema.parse({protocol:"openai-images",base_url,model:"test"})).toThrow();});
  it.each(["openai-images","openai-responses","openai-chat-images"] as const)("validates actual bytes through %s without reading response prose",async protocol=>{const payload=protocol==="openai-images"?{data:[{b64_json:base64}]}:protocol==="openai-responses"?{status:"completed",output:[{type:"image_generation_call",status:"completed",result:base64}]}:{choices:[{message:{content:"untrusted explanatory text",images:[{image_url:{url:"data:image/png;base64,"+base64}}]}}]};const{value,request}=provider(payload,protocol);const result=await value.generate(input);expect(Buffer.from(result.bytes)).toEqual(image);expect(request).toHaveBeenCalledOnce();const [url,init]=request.mock.calls[0] as unknown as [string,RequestInit];expect(url.endsWith(protocol==="openai-images"?"/images/generations":protocol==="openai-responses"?"/responses":"/chat/completions")).toBe(true);expect(init.redirect).toBe("error");const body=JSON.parse(String(init.body));if(protocol==="openai-images")expect(body).toMatchObject({n:1,output_format:"png"});if(protocol==="openai-responses")expect(body.tools[0]).toMatchObject({type:"image_generation",output_format:"png"});});
  it.each([{data:[{url:"https://provider.invalid/generated.png"}]},{data:[{b64_json:Buffer.from("A code snippet creating a PNG").toString("base64")}]},{data:[{b64_json:"@@@@"}]},{data:[]},{data:[{b64_json:base64},{b64_json:base64}]}])("fails closed for false-success response %#",async payload=>{const{value}=provider(payload);await expect(value.generate(input)).rejects.toMatchObject({code:"image_output_invalid",outcome:"failure"});});
  it("rejects native text-only/image URL and incomplete Responses output",async()=>{for(const [protocol,payload] of [["openai-chat-images",{choices:[{message:{content:"Here is code for an image"}}]}],["openai-chat-images",{choices:[{message:{images:[{image_url:{url:"https://provider.invalid/image.png"}}]}}]}],["openai-responses",{status:"incomplete",output:[{type:"image_generation_call",status:"completed",result:base64}]}]] as const){await expect(provider(payload,protocol).value.generate(input)).rejects.toMatchObject({code:"image_output_invalid"});}});
  it("reports an actionable unsupported raster format",async()=>{const{value}=provider({choices:[{message:{images:[{image_url:{url:"data:image/jpeg;base64,/9j/2Q=="}}]}}]},"openai-chat-images");await expect(value.generate(input)).rejects.toMatchObject({code:"image_format_unsupported"});});
  it("returns safe authentication/rate/failure and unknown server outcomes without leaking error response bodies",async()=>{for(const [status,code,outcome] of [[401,"image_authentication_failed","failure"],[429,"image_rate_limited","failure"],[500,"image_http_500","unknown"]] as const){const{value,request}=provider({error:{message:"dummy-isolated-image-key private payload"}},"openai-images",status);await expect(value.generate(input)).rejects.toMatchObject({code,outcome,message:expect.not.stringContaining("dummy-isolated-image-key")});expect(request).toHaveBeenCalledOnce();}});
  it("does not retry a transport timeout after dispatch",async()=>{const request=vi.fn(async(_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init!.signal!.addEventListener("abort",()=>reject(new Error("dummy-isolated-image-key")),{once:true})));const value=new ConfigurableImageProvider({resolveCredential:async()=>"dummy-isolated-image-key",fetch:request,timeoutMs:15});value.configure({protocol:"openai-images",base_url:"http://127.0.0.1:18081",model:"fixture",credentialRef:"${secret:MEDIA_FIXTURE}"});await expect(value.generate(input)).rejects.toMatchObject({code:"image_outcome_unknown",outcome:"unknown"});expect(request).toHaveBeenCalledOnce();});
  it("pre-dispatch cancellation sends no request",async()=>{const{value,request}=provider({data:[{b64_json:base64}]});const abort=new AbortController();abort.abort();await expect(value.generate(input,{signal:abort.signal})).rejects.toMatchObject({code:"image_cancelled",outcome:"failure"});expect(request).not.toHaveBeenCalled();});
  it("rejects XML controls, lone surrogates and coordinate overflow before rendering",()=>{for(const title of ["\u0000","\u0001","\uD800","\uFFFF"]){expect(()=>renderChart({title,chart_type:"bar",labels:["a"],values:[1]})).toThrow();expect(()=>renderDiagram({title,nodes:[{id:"a",label:"a"}],edges:[]})).toThrow();}expect(()=>renderChart({title:"huge",chart_type:"line",labels:["a","b"],values:[1e308,-1e308]})).toThrow();});
  it("renders real bounded SVG and escapes hostile labels instead of accepting executable SVG/script",()=>{const title='<script>alert("secret")</script>';for(const output of [renderChart({title,chart_type:"bar",labels:['a" onload="alert(1)','negative'],values:[3,-2]}),renderDiagram({title,nodes:[{id:"a",label:"<foreignObject>hi</foreignObject>"},{id:"b",label:"Result"}],edges:[{from:"a",to:"b"}]})]){const content=Buffer.from(output.bytes).toString();expect(content).toContain('xmlns="http://www.w3.org/2000/svg"');expect(content).not.toMatch(/<script|<foreignObject|onload="|href=|url\(/u);expect(output.mimeType).toBe("image/svg+xml");}});
});
