import {describe,it,expect,afterEach,vi} from "vitest";
import {mkdtemp,mkdir,rm,readFile,writeFile} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createAgentRuntime,type AgentRuntime,type AgentRuntimeOptions} from "../../domains/runtime/runtime.js";
import {ExtensionManager} from "../../domains/extensions/manager.js";
import {createCoreToolRegistry} from "../../domains/tools/registry.js";
import {createReadonlyWorkspaceHandle} from "../../kernel/workspace.js";
import {createMediaToolsExtension,createMediaInstructionAdapter} from "./tool-extension.js";
import {createEffectivePermissionPolicy} from "@tracegraph/tool";
import {BUILTIN_PERMISSION_PRESETS} from "@tracegraph/contracts";
import {verifyRasterImage} from "./image-bytes.js";
import {ConfigurableImageProvider,ImageProviderError} from "./provider.js";
import {ReceiptSchema,MediaOperationSchema,type MediaOperation,type WorkspaceHandle} from "@tracegraph/contracts";
const roots:string[]=[],runtimes:AgentRuntime[]=[];
afterEach(async()=>{for(const runtime of runtimes.splice(0)){await runtime.shutdownRuns?.();await runtime.shutdownBackgroundWork?.();}await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})));});
async function fixture(provider:Parameters<typeof createMediaToolsExtension>[0]={generate:async()=>{throw new Error("Unexpected image provider call");}},sandboxMode:"workspace-write"|"read-only"="workspace-write",denyImages:boolean|"ask"=false,approvalAnswerer?:AgentRuntimeOptions["approvalAnswerer"]) {const root=await mkdtemp(join(tmpdir(),"outlive-media-runtime-"));roots.push(root);const projectRoot=join(root,"workspace");await mkdir(projectRoot);await writeFile(join(projectRoot,"unchanged.txt"),"No media tool may modify project files\n");const original=await createReadonlyWorkspaceHandle({projectId:"chat:media-fixture",root:projectRoot});const workspace:WorkspaceHandle={...original,capabilities:{index:false,read:false,search:false,run_command:false,preview_patch:false,commit_patch:false,test:false}};const manager=new ExtensionManager({toolRegistry:createCoreToolRegistry()});await manager.activate(createMediaToolsExtension(provider));const runtime=await createAgentRuntime({dataDir:join(root,"data"),extensionManager:manager,sandboxMode,...(approvalAnswerer?{approvalAnswerer}:{}),...(denyImages?{permissionPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS[sandboxMode],rules:[{rule_id:"rule:deny-external-images",priority:100,when:{tool:"generate_image"},then:denyImages==="ask"?"ask":"deny",explanation:"Fixture Host policy denies external image requests"}]})}:{})});runtimes.push(runtime);return{root,runtime,workspace,manager};}
async function start(state:Awaited<ReturnType<typeof fixture>>,value:unknown,command="command:media"){const operation=MediaOperationSchema.parse(value);return state.runtime.startRun({command_id:command,project_id:state.workspace.project_id,workspace:state.workspace,task:JSON.stringify(operation),mode:"execute"},{model:createMediaInstructionAdapter(operation),backgroundModelDerivation:false});}
async function terminal(runtime:AgentRuntime,id:string){const deadline=Date.now()+5000;while(Date.now()<deadline){const run=await runtime.getProjection(id);if(!["created","indexing","running","executing","planning","queued"].includes(run.status))return run;await new Promise(done=>setTimeout(done,5));}throw new Error("Media Run did not settle");}
const chart={kind:"chart",title:"External file oracle",chart_type:"bar",labels:["One","Two"],values:[4,9]} as const;
describe("MEDIA-094 actual Runtime receipts and Artifact scope",()=>{
 it("requires actual approval before provider dispatch and keeps plan mode provider-free",async()=>{
  const bytes=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAEklEQVR4nGP4z8DwHwyBNBgAAEnICff5q7YNAAAAAElFTkSuQmCC","base64");
  let allow!:()=>void;const gate=new Promise<"allowed-once">(done=>{allow=()=>done("allowed-once");});const generate=vi.fn(async()=>verifyRasterImage(bytes));const state=await fixture({generate},"read-only","ask",()=>gate);
  const awaiting=await terminal(state.runtime,(await start(state,{kind:"generate",prompt:"Explicit approval fixture"},"command:image-approval")).run_id);
  expect(awaiting.status).toBe("awaiting_approval");expect(generate).not.toHaveBeenCalled();
  expect(awaiting.timeline.some(event=>event.type==="approval.requested"&&event.data.tool_name==="generate_image")).toBe(true);allow();
  await expect.poll(async()=> (await state.runtime.getProjection(awaiting.run_id)).status).toBe("completed");
  const done=await state.runtime.getProjection(awaiting.run_id);expect(done.status).toBe("completed");expect(generate).toHaveBeenCalledOnce();expect(done.artifact_refs.some(ref=>ref.mime_type==="image/png")).toBe(true);
  const operation=MediaOperationSchema.parse({kind:"generate",prompt:"Plan mode must not dispatch"});const plan=await state.runtime.startRun({command_id:"command:image-plan",project_id:state.workspace.project_id,workspace:state.workspace,task:"Plan image",mode:"plan"},{model:createMediaInstructionAdapter(operation),backgroundModelDerivation:false});
  await terminal(state.runtime,plan.run_id);expect(generate).toHaveBeenCalledOnce();
 });
 it("creates scoped actual SVG through no-filesystem plain chat, with normal Tool/Observation/Ledger refs",async()=>{const state=await fixture();const run=await terminal(state.runtime,(await start(state,chart)).run_id);expect(run.status).toBe("completed");const completed=run.timeline.find(event=>event.type==="tool.completed");expect(completed).toBeDefined();const receipt=ReceiptSchema.parse(completed!.data.receipt);expect(receipt).toMatchObject({tool_name:"render_chart",business_status:"success",code:"media_artifact_created"});const ref=receipt.artifact_refs.find(ref=>ref.mime_type==="image/svg+xml")!;expect(ref).toBeDefined();expect(run.artifact_refs).toContainEqual(ref);const content=await state.runtime.getArtifactContent({artifactId:ref.artifact_id,runId:run.run_id,projectId:run.project_id});expect(content.status).toBe("available");if(content.status==="available")expect(Buffer.from(content.bytes).toString()).toContain("<svg");expect(await readFile(join(state.workspace.real_root,"unchanged.txt"),"utf8")).toBe("No media tool may modify project files\n");expect(JSON.stringify(run)).not.toContain("data:image");const modelStarted=run.timeline.find(event=>event.type==="model.request_started");expect(modelStarted).toBeDefined();});
 it("exact command retries return the same Run and reject a changed typed operation",async()=>{const state=await fixture();const first=await start(state,chart);await terminal(state.runtime,first.run_id);expect((await start(state,chart)).run_id).toBe(first.run_id);await expect(start(state,{...chart,values:[5,10]})).rejects.toMatchObject({code:"command_id_conflict"});});
 it("binary reads reject other Run/project locators and corruption before any bytes escape",async()=>{const state=await fixture();const first=await terminal(state.runtime,(await start(state,chart)).run_id);const ref=first.artifact_refs.find(ref=>ref.mime_type==="image/svg+xml")!;const second=await terminal(state.runtime,(await start(state,chart,"command:second")).run_id);expect(await state.runtime.getArtifactContent({artifactId:ref.artifact_id,runId:second.run_id,projectId:second.project_id})).toMatchObject({status:"unavailable",reason:"out_of_scope"});expect(await state.runtime.getArtifactContent({artifactId:ref.artifact_id,runId:first.run_id,projectId:"project:outside"})).toMatchObject({status:"unavailable",reason:"out_of_scope"});const {readdir}=await import("node:fs/promises");const artifacts=join(state.root,"data","artifacts");const names=await readdir(artifacts);const metadataFiles=names.filter(name=>name.endsWith(".json"));let file:string|undefined;for(const name of metadataFiles){const metadata=JSON.parse(await readFile(join(artifacts,name),"utf8"));if(metadata.artifact_id===ref.artifact_id)file=name;}expect(file).toBeDefined();if(file){await writeFile(join(artifacts,file.replace(/\.json$/u,".data")),"corrupted");expect(await state.runtime.getArtifactContent({artifactId:ref.artifact_id,runId:first.run_id,projectId:first.project_id})).toMatchObject({status:"corrupt"});}});
 it("explicit Host image policy is denied before the provider, while local SVG still succeeds",async()=>{const generate=vi.fn(async()=>{throw new Error("Must not dispatch");});const state=await fixture({generate},"read-only",true);const run=await terminal(state.runtime,(await start(state,{kind:"generate",prompt:"A PNG"})).run_id);expect(run.status).toBe("failed");expect(generate).not.toHaveBeenCalled();expect(run.artifact_refs.some(ref=>ref.mime_type==="image/png")).toBe(false);expect((await terminal(state.runtime,(await start(state,chart,"command:local")).run_id)).status).toBe("completed");});
 it("unknown external outcome dispatches once and records no successful image Artifact",async()=>{const generate=vi.fn(async()=>{throw new ImageProviderError("image_outcome_unknown","unknown","Unknown provider outcome; inspect before retrying");});const state=await fixture({generate});const run=await terminal(state.runtime,(await start(state,{kind:"generate",prompt:"Unknown provider fixture"})).run_id);expect(generate).toHaveBeenCalledOnce();const receipt=run.timeline.find(event=>event.type==="tool.unknown")?.data.receipt;expect(receipt).toMatchObject({business_status:"unknown",code:"image_outcome_unknown",artifact_refs:[]});expect(run.artifact_refs.some(ref=>ref.mime_type==="image/png")).toBe(false);});
 it("Run binds an immutable image provider before its first tool step and retains the old key until terminal",async()=>{let releaseModel!:()=>void;const gate=new Promise<void>(done=>{releaseModel=done;});const used:string[]=[];const resolveCredential=vi.fn(async(reference:string)=>{used.push(reference);return "dummy-image-key";});const provider=new ConfigurableImageProvider({resolveCredential,fetch:vi.fn(async()=>new Response(JSON.stringify({data:[{b64_json:"invalid"}]})))});provider.configure({protocol:"openai-images",base_url:"http://127.0.0.1:18081",model:"first",credentialRef:"${secret:FIRST}"});const state=await fixture(provider);const operation=MediaOperationSchema.parse({kind:"generate",prompt:"Config binding oracle"});const base=createMediaInstructionAdapter(operation);const run=await state.runtime.startRun({command_id:"command:binding",project_id:state.workspace.project_id,workspace:state.workspace,task:"binding",mode:"execute"},{model:{name:"binding-fixture",decide:async input=>{if(input.turn===1)await gate;return base.decide(input);}}});provider.configure({protocol:"openai-images",base_url:"http://127.0.0.1:18082",model:"second",credentialRef:"${secret:SECOND}"});const cleanup=vi.fn(async()=>undefined);provider.retireCredential("${secret:FIRST}",cleanup);expect(cleanup).not.toHaveBeenCalled();releaseModel();await terminal(state.runtime,run.run_id);expect(used).toEqual(["${secret:FIRST}"]);expect(cleanup).toHaveBeenCalledOnce();});
 it.each([{timeoutMs:99999},{capability:"commit_patch"},{requiresApproval:true},{workspaceIndependent:false}] as const)("refuses a Run executor binding that changes trusted Tool authority %# and releases acquired leases",async mutation=>{const state=await fixture();const definition=state.manager.toolRegistry.get("render_chart")!;const release=vi.fn();definition.forRun=()=>({definition:{...definition,...mutation},release});await expect(start(state,chart)).rejects.toThrow("authority");expect(release).toHaveBeenCalledOnce();await expect(state.manager.deactivate("@tracegraph/media-tools")).resolves.toBeDefined();});
 it("releases immutable Tool leases once on terminal and once after explicit cancellation, without creating output",async()=>{const state=await fixture();const definition=state.manager.toolRegistry.get("render_chart")!;const release=vi.fn();definition.forRun=()=>({definition:{...definition},release});await terminal(state.runtime,(await start(state,chart)).run_id);expect(release).toHaveBeenCalledOnce();
 const waiting=createMediaInstructionAdapter(MediaOperationSchema.parse(chart));const run=await state.runtime.startRun({command_id:"command:cancel",project_id:state.workspace.project_id,workspace:state.workspace,task:"Cancel before local render",mode:"execute"},{model:{name:"cancel-binding-fixture",decide:async input=>{await new Promise<void>(done=>{if(input.signal?.aborted)done();else input.signal?.addEventListener("abort",()=>done(),{once:true});});return waiting.decide(input);}}});const cancelled=await state.runtime.stop({type:"stop",command_id:"command:stop",run_id:run.run_id,project_id:run.project_id});expect(cancelled.status).toBe("cancelled");expect(release).toHaveBeenCalledTimes(2);expect(cancelled.artifact_refs.some(ref=>ref.mime_type==="image/svg+xml")).toBe(false);});

 it("scoped media publication does not grant project reads or writes to the next model step",async()=>{const state=await fixture();const media=createMediaInstructionAdapter(MediaOperationSchema.parse(chart));const advertised:string[]=[];const run=await state.runtime.startRun({command_id:"command:no-fs-grant",project_id:state.workspace.project_id,workspace:state.workspace,task:"Attempt a project read after rendering",mode:"execute"},{model:{name:"no-fs-grant-oracle",decide:async input=>{advertised.push(...input.toolSchemas.map(tool=>tool.name));if(input.turn===1)return media.decide(input);return{decision_id:"decision:attempt-project-read",kind:"tool_call",public_reason:"Negative fixture attempts a project read",evidence_refs:[],risk:"low",tool_call:{action_id:"action:attempt-project-read",tool_name:"read_file",arguments:{path:"unchanged.txt"}}};}}});const completed=await terminal(state.runtime,run.run_id);expect(advertised).toContain("render_chart");expect(advertised).not.toContain("read_file");expect(advertised).not.toContain("commit_patch");expect(completed.status).toBe("failed");expect(completed.timeline.some(event=>event.type==="tool.started"&&event.data.tool_name==="read_file")).toBe(false);expect(JSON.stringify(completed)).not.toContain("No media tool may modify project files");});

});
