// @vitest-environment jsdom
import { webcrypto } from "node:crypto";
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ComputerStatusSchema, HostCapabilitiesSchema, type ComputerObservation } from "@tracegraph/contracts";
import { DemoTraceGraphClient, type WorkbenchClient } from "./client";
import { LanguageProvider } from "./i18n";
import { ComputerSettings } from "./components/ComputerSettings";

const target = { application_id: "app-editor", pid: 123, title: "Editor", identity: `sha256:${"a".repeat(64)}`, window_id: "window-one" };
const grant = { grant_id: "grant-one", application_id: target.application_id, identity: target.identity, duration: "always", state: "active", granted_at: "2026-10-05T01:00:00Z" };
const lease = { lease_id: "lease-one", grant_id: "grant-one", target, state: "active", generation: 9, created_at: "2026-10-05T01:00:00Z", expires_at: "2026-10-05T01:10:00Z" };
const status = () => ComputerStatusSchema.parse({ platform: "darwin", backend_available: true, accessibility: true, screen_capture: true, input_monitoring: true, locked: false, human_grant_available: true, grants: [grant], lease });
const capabilities = () => HostCapabilitiesSchema.parse({ profile_id: "profile-one", protocol_version: "test", capabilities: ["computer.read", "computer.targets", "computer.grant", "computer.revoke", "computer.lease", "computer.observe", "computer.action", "computer.capture.read", "computer.receipt.read"].map((operation) => ({ operation, state: "available", scope: "profile" })) });
let node: HTMLDivElement, root: Root;
const find = (label: string) => [...node.querySelectorAll<HTMLButtonElement>("button")].find((button) => button.textContent?.trim() === label)!;
const click = async (label: string) => { expect(find(label)).toBeDefined(); await act(async () => find(label).click()); };
const choose = async (value: string) => { const input = node.querySelector<HTMLSelectElement>('[aria-label="Computer application window"]')!; await act(async () => { Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype, "value")!.set!.call(input, value); input.dispatchEvent(new Event("change", { bubbles: true })); }); };
const clientFixture = () => { const client: WorkbenchClient = new DemoTraceGraphClient(); client.getComputerStatus = vi.fn(async () => status()); client.listComputerTargets = vi.fn(async () => status().lease ? [status().lease!.target, { ...status().lease!.target, window_id: "window-two", title: "Second editor window" }] : []); return client; };
const render = async (client: WorkbenchClient, readOnly = false) => { await act(async () => root.render(<LanguageProvider><ComputerSettings client={client} capabilities={capabilities()} online readOnly={readOnly} /></LanguageProvider>)); };
beforeEach(() => { Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true }); window.localStorage.clear(); window.localStorage.setItem("tracegraph.language", "en"); vi.stubGlobal("crypto", { randomUUID: webcrypto.randomUUID.bind(webcrypto), subtle: webcrypto.subtle }); node = document.createElement("div"); document.body.append(node); root = createRoot(node); });
afterEach(async () => { await act(async () => root.unmount()); node.remove(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });

describe("Native computer settings authority and receipts", () => {
  it("reads status without granting or acquiring input and sends only the exact native target through the trusted grant controller", async () => {
    const client = clientFixture(); client.requestComputerGrant = vi.fn(async () => status().grants[0]!); client.acquireComputerLease = vi.fn(async () => status().lease!); await render(client); expect(client.requestComputerGrant).not.toHaveBeenCalled(); expect(client.acquireComputerLease).not.toHaveBeenCalled(); await choose("app-editor:123:window-one"); await click("Request application permission"); expect(client.requestComputerGrant).toHaveBeenCalledExactlyOnceWith({ command_id: expect.any(String), target: status().lease!.target, duration: "once" }); expect(client.acquireComputerLease).not.toHaveBeenCalled();
  });

  it("requires the exact leased window and posts the admitted lease generation without claiming business completion", async () => {
    const client = clientFixture(); client.computerAction = vi.fn<NonNullable<WorkbenchClient["computerAction"]>>(async (input) => ({ command_id: input.command_id, status: "posted", code: "native_input_posted_unverified", target: status().lease!.target, lease_generation: input.expected_generation, message: "Posted" })); await render(client); expect(find("Send exact native input").disabled).toBe(true); await choose("app-editor:123:window-two"); expect(find("Send exact native input").disabled).toBe(true); await choose("app-editor:123:window-one"); await act(async () => node.querySelector<HTMLFormElement>(".computer-input-form")!.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }))); expect(client.computerAction).toHaveBeenCalledExactlyOnceWith({ command_id: expect.any(String), lease_id: "lease-one", expected_generation: 9, action: { kind: "key", key: "Enter", modifiers: [] } }); expect(node.textContent).toContain("Native input was posted. Observe the application to verify the result."); expect(node.textContent).not.toContain("Business operation succeeded");
  });

  it("keeps unknown input locked, allows explicit observation and safety release, and never turns an unknown receipt into success", async () => {
    const client = clientFixture(); let original = ""; client.computerAction = vi.fn<NonNullable<WorkbenchClient["computerAction"]>>(async (input) => { original = input.command_id; return { command_id: original, status: "unknown", code: "computer_input_outcome_unknown", target: status().lease!.target, lease_generation: 9, message: "Unknown" }; }); client.getComputerCommandReceipt = vi.fn<NonNullable<WorkbenchClient["getComputerCommandReceipt"]>>(async (id) => ({ command_id: id, state: "completed", result: { command_id: id, status: "unknown", code: "computer_input_outcome_unknown", target: status().lease!.target, lease_generation: 9, message: "Unknown" } })); client.releaseComputerLease = vi.fn(async () => ({ ...status().lease!, state: "released" as const })); client.observeComputer = vi.fn<NonNullable<WorkbenchClient["observeComputer"]>>(async () => ({ target: status().lease!.target, source: "native-accessibility", elements: [], truncated: false, captured_at: "2026-10-05T01:02:00Z", artifact: { artifact_id: "observation-one", kind: "tool_output", content_hash: `sha256:${"b".repeat(64)}`, mime_type: "application/json", byte_length: 10, project_id: "computer:profile", run_id: "computer:run", created_at: "2026-10-05T01:02:00Z" } })); await render(client); await choose("app-editor:123:window-one"); await act(async () => node.querySelector<HTMLFormElement>(".computer-input-form")!.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }))); expect(find("Send exact native input").disabled).toBe(true); expect(find("Release input control").disabled).toBe(false); await click("Inspect original computer command"); expect(client.getComputerCommandReceipt).toHaveBeenCalledExactlyOnceWith(original); expect(find("Send exact native input").disabled).toBe(true); await click("Observe application"); expect(client.observeComputer).toHaveBeenCalledOnce(); expect(client.computerAction).toHaveBeenCalledOnce(); await click("Release input control"); expect(client.releaseComputerLease).toHaveBeenCalledExactlyOnceWith({ command_id: expect.any(String), lease_id: "lease-one" }); expect(client.computerAction).toHaveBeenCalledOnce();
  });

  it("explains the exact missing platform permission and keeps input disabled", async () => {
    const client = clientFixture(); client.getComputerStatus = vi.fn(async () => ({ ...status(), input_monitoring: false, screen_capture: false })); client.computerAction = vi.fn(async () => { throw new Error("Must not send"); }); await render(client); await choose("app-editor:123:window-one"); expect(find("Send exact native input").disabled).toBe(true); expect(node.textContent).toContain("Allow Input Monitoring for the Outlive Agent helper"); expect(node.textContent).toContain("Allow Screen Recording for the Outlive Agent helper"); expect(client.computerAction).not.toHaveBeenCalled();
  });

  it("does not mount mismatched capture bytes or claim that window pixels were displayed", async () => {
    const client = clientFixture(); const observation: ComputerObservation = { target: status().lease!.target, source: "native-accessibility", elements: [], truncated: false, captured_at: "2026-10-05T01:02:00Z", artifact: { artifact_id: "observation-one", kind: "tool_output", content_hash: `sha256:${"b".repeat(64)}`, mime_type: "application/json", byte_length: 10, project_id: "computer:profile", run_id: "computer:run", created_at: "2026-10-05T01:02:00Z" }, capture_artifact: { artifact_id: "capture-one", kind: "image/png", content_hash: `sha256:${"c".repeat(64)}`, mime_type: "image/png", byte_length: 4, project_id: "computer:profile", run_id: "computer:run", created_at: "2026-10-05T01:02:00Z" } }; client.observeComputer = vi.fn(async () => observation); client.getComputerCapture = vi.fn(async () => ({ sha256: `sha256:${"d".repeat(64)}`, bytes: Uint8Array.from([1, 2, 3, 4]) })); const create = vi.fn(); Object.defineProperty(URL, "createObjectURL", { configurable: true, value: create }); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: vi.fn() }); await render(client); await choose("app-editor:123:window-one"); await click("Observe application"); await click("Preview verified window pixels"); expect(client.getComputerCapture).toHaveBeenCalledExactlyOnceWith({ grant_id: "grant-one", target: status().lease!.target, artifact: observation.capture_artifact }); expect(create).not.toHaveBeenCalled(); expect(node.querySelector("img")).toBeNull(); expect(node.textContent).toContain("does not match its verified Artifact");
  });

  it("never grants, observes or sends native input in Replay", async () => {
    const client = clientFixture(); client.requestComputerGrant = vi.fn(async () => status().grants[0]!); client.observeComputer = vi.fn(async () => { throw new Error("Must not observe"); }); client.computerAction = vi.fn(async () => { throw new Error("Must not send"); }); await render(client, true); await choose("app-editor:123:window-one"); expect(find("Request application permission").disabled).toBe(true); expect(find("Observe application").disabled).toBe(true); expect(find("Send exact native input").disabled).toBe(true); expect(client.requestComputerGrant).not.toHaveBeenCalled(); expect(client.observeComputer).not.toHaveBeenCalled(); expect(client.computerAction).not.toHaveBeenCalled();
  });
});
