// @vitest-environment jsdom
import { createHash, webcrypto } from "node:crypto";
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { BrowserStatusSchema, GoalSnapshotSchema, HostCapabilitiesSchema, type BrowserObservation, type GoalSnapshot } from "@tracegraph/contracts";
import { DemoTraceGraphClient, type WorkbenchClient } from "./client";
import { LanguageProvider } from "./i18n";
import { BrowserPanel } from "./components/BrowserPanel";
import { GoalWorkspace } from "./components/GoalWorkspace";

let node: HTMLDivElement, root: Root;
const caps = (operations: string[]) => HostCapabilitiesSchema.parse({ profile_id: "test-profile", protocol_version: "test", capabilities: operations.map((operation) => ({ operation, state: "available", scope: "project" })) });
const browserCaps = () => caps(["browser.read", "browser.command", "browser.grant", "browser.observe", "browser.evidence.read"]);
const goalCaps = () => caps(["goals.read", "goals.write"]);
const browserStatus = () => BrowserStatusSchema.parse({ available: true, human_grant_available: true, runtime: "bundled", grants: [{ grant_id: "grant-one", revision: 2, label: "Project site", project_id: "project-one", origins: ["https://example.com"], duration: "always", state: "active", created_at: "2026-10-05T01:00:00Z" }], tabs: [{ tab_id: "tab-one", project_id: "project-one", grant_id: "grant-one", url: "https://example.com/", title: "Project page", state: "agent", revision: 7 }] });
const goalSnapshot = (patch: Partial<GoalSnapshot> = {}) => GoalSnapshotSchema.parse({ schema_version: "outlive.goal.v1", goal_id: "goal-one", revision: 4, proposal_revision: 2, approved_proposal_revision: null, proposal: { project_id: "project-one", title: "Deliver login", objective: "Implement and verify login", done_conditions: ["Login works", "Tests pass"], budget: { max_tokens: 5000, max_time_ms: 60000 } }, status: "awaiting_approval", created_at: "2026-10-05T01:00:00Z", updated_at: "2026-10-05T01:00:00Z", run_ids: [], active_run_id: null, budget: { limits: { max_tokens: 5000, max_time_ms: 60000 }, charged_tokens: 100, held_tokens: 0, held_request_count: 0, reported_input_tokens: 70, reported_output_tokens: 30, elapsed_ms: 2000, request_count: 1, unknown_request_count: 0, stop_reason: null }, last_run_status: null, final_accepted_at: null, receipt_event_id: "receipt-one", ...patch });
const find = (label: string) => [...node.querySelectorAll<HTMLButtonElement>("button")].find((button) => button.textContent?.trim() === label || button.getAttribute("aria-label") === label)!;
const click = async (label: string) => { expect(find(label)).toBeDefined(); await act(async () => find(label).click()); };
const input = async (label: string, value: string) => { const element = node.querySelector<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(`[aria-label="${label}"]`)!; expect(element).not.toBeNull(); await act(async () => { const prototype = element instanceof HTMLSelectElement ? HTMLSelectElement.prototype : element instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(prototype, "value")!.set!.call(element, value); element.dispatchEvent(new Event(element instanceof HTMLSelectElement ? "change" : "input", { bubbles: true })); }); };
const wait = async (condition: () => boolean) => { for (let i = 0; i < 30 && !condition(); i++) await act(async () => { await new Promise((done) => setTimeout(done, 5)); }); expect(condition()).toBe(true); };
beforeEach(() => { Object.assign(globalThis, { IS_REACT_ACT_ENVIRONMENT: true }); window.localStorage.clear(); window.localStorage.setItem("tracegraph.language", "en"); node = document.createElement("div"); document.body.append(node); root = createRoot(node); vi.stubGlobal("crypto", { randomUUID: webcrypto.randomUUID.bind(webcrypto), subtle: webcrypto.subtle }); vi.spyOn(window, "confirm").mockReturnValue(true); });
afterEach(async () => { await act(async () => root.unmount()); node.remove(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
const drawBrowser = async (client: WorkbenchClient, readOnly = false) => { await act(async () => root.render(<LanguageProvider><BrowserPanel client={client} projectId="project-one" capabilities={browserCaps()} online readOnly={readOnly} onDiagnostics={vi.fn()} /></LanguageProvider>)); };
const drawGoal = async (client: WorkbenchClient, readOnly = false, initialCreate = false) => { await act(async () => root.render(<LanguageProvider><GoalWorkspace client={client} projectId="project-one" sessionId="session-one" capabilities={goalCaps()} online readOnly={readOnly} initialCreate={initialCreate} onClose={vi.fn()} /></LanguageProvider>)); };

describe("Controller-backed Browser and Goal UI", () => {
  it("does not grant or open on page load and requests only the exact project origin through the trusted confirmation controller", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.getBrowserStatus = vi.fn(async () => browserStatus()); client.requestBrowserGrant = vi.fn(async () => browserStatus().grants[0]!); client.browserCommand = vi.fn<NonNullable<WorkbenchClient["browserCommand"]>>(async (request) => ({ command_id: request.command_id, status: "succeeded" }));
    await drawBrowser(client); expect(client.browserCommand).not.toHaveBeenCalled(); expect(client.requestBrowserGrant).not.toHaveBeenCalled(); await input("Browser permission label", "Project website"); await input("Browser address", "https://example.com/specific/path"); await click("Request browser permission");
    expect(client.requestBrowserGrant).toHaveBeenCalledExactlyOnceWith({ command_id: expect.any(String), project_id: "project-one", label: "Project website", origins: ["https://example.com"], duration: "once" }); expect(client.browserCommand).not.toHaveBeenCalled(); expect(window.confirm).not.toHaveBeenCalled();
  });

  it("uses only verified image bytes and sends the selected observed ref at the exact revision", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(), bytes = Uint8Array.from([137, 80, 78, 71]), sha256 = `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
    client.getBrowserStatus = vi.fn(async () => browserStatus()); const observation: BrowserObservation = { tab: { ...browserStatus().tabs[0]!, revision: 11 }, elements: [{ ref: "element-one", role: "button", text: "Submit" }], evidence: { evidence_id: "evidence-one", sha256, mime_type: "image/png", byte_length: bytes.byteLength } };
    client.observeBrowser = vi.fn<NonNullable<WorkbenchClient["observeBrowser"]>>(async () => observation); client.getBrowserEvidence = vi.fn(async () => ({ evidenceId: "evidence-one", sha256, bytes })); client.browserCommand = vi.fn<NonNullable<WorkbenchClient["browserCommand"]>>(async (request) => ({ command_id: request.command_id, status: "succeeded" }));
    const create = vi.fn(() => "blob:verified-browser-image"); Object.defineProperty(URL, "createObjectURL", { configurable: true, value: create }); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: vi.fn() });
    await drawBrowser(client); await click("Observe browser"); await wait(() => Boolean(node.querySelector('img[alt="Verified browser observation"]'))); expect(create).toHaveBeenCalledOnce(); await input("Browser element", "element-one"); await click("Click selected element");
    expect(client.browserCommand).toHaveBeenCalledExactlyOnceWith({ type: "click", command_id: expect.any(String), tab_id: "tab-one", expected_revision: 11, ref: "element-one" }); expect(client.observeBrowser).toHaveBeenCalledExactlyOnceWith("tab-one");
  });

  it("refuses mismatched evidence and does not expose action targets or create a preview URL", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.getBrowserStatus = vi.fn(async () => browserStatus()); client.observeBrowser = vi.fn<NonNullable<WorkbenchClient["observeBrowser"]>>(async () => ({ tab: browserStatus().tabs[0]!, elements: [{ ref: "element-one", role: "button", text: "Submit" }], evidence: { evidence_id: "evidence-one", sha256: `sha256:${"a".repeat(64)}`, mime_type: "image/png", byte_length: 4 } })); client.getBrowserEvidence = vi.fn(async () => ({ evidenceId: "evidence-other", sha256: `sha256:${"a".repeat(64)}`, bytes: Uint8Array.from([1, 2, 3, 4]) }));
    const create = vi.fn(); Object.defineProperty(URL, "createObjectURL", { configurable: true, value: create }); Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: vi.fn() }); await drawBrowser(client); await click("Observe browser"); expect(create).not.toHaveBeenCalled(); expect(node.querySelector('[aria-label="Browser element"]')).toBeNull(); expect(node.textContent).toContain("does not match the observed revision");
  });

  it("locks an unknown browser command, permits safety takeover, and reconciles only its original read receipt without rerunning it", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.getBrowserStatus = vi.fn(async () => browserStatus()); let original = ""; client.browserCommand = vi.fn<NonNullable<WorkbenchClient["browserCommand"]>>(async (request) => { if (request.type === "open") { original = request.command_id; throw new Error("Response lost after dispatch"); } return { command_id: request.command_id, status: "succeeded" }; }); client.getBrowserCommandReceipt = vi.fn<NonNullable<WorkbenchClient["getBrowserCommandReceipt"]>>(async (id) => ({ command_id: id, state: "completed", result: { command_id: id, status: "succeeded", tab: browserStatus().tabs[0]! } }));
    await drawBrowser(client); await input("Approved browser permission", "grant-one"); await input("Open browser address", "https://example.com/"); await click("Open browser tab"); expect(find("Open browser tab").disabled).toBe(true); expect(find("Take control").disabled).toBe(false); expect(client.browserCommand).toHaveBeenCalledOnce(); await click("Inspect original browser action"); expect(client.getBrowserCommandReceipt).toHaveBeenCalledExactlyOnceWith(original); expect(client.browserCommand).toHaveBeenCalledOnce(); expect(node.textContent).toContain("verified completion receipt"); expect(find("Open browser tab").disabled).toBe(false);
  });

  it("creates a finite Goal proposal without starting work, then approves the exact displayed revision only", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.listGoals = vi.fn(async () => ({ goals: [] })); client.createGoal = vi.fn(async () => goalSnapshot()); client.goalCommand = vi.fn(async () => goalSnapshot({ status: "approved", revision: 5, approved_proposal_revision: 2 })); await drawGoal(client, false, true);
    await input("Goal title", "Deliver login"); await input("Goal objective", "Implement and verify login"); await input("Goal completion conditions", "Login works\nTests pass"); await input("Goal token limit", "5000"); await act(async () => node.querySelector<HTMLFormElement>("form")!.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })));
    expect(client.createGoal).toHaveBeenCalledExactlyOnceWith({ command_id: expect.any(String), project_id: "project-one", session_id: "session-one", title: "Deliver login", objective: "Implement and verify login", done_conditions: ["Login works", "Tests pass"], budget: { max_tokens: 5000 } }); expect(client.goalCommand).not.toHaveBeenCalled(); await click("Approve Goal proposal"); expect(client.goalCommand).toHaveBeenCalledExactlyOnceWith("goal-one", { command_id: expect.any(String), expected_revision: 4, proposal_revision: 2, operation: "approve" }); expect(find("Start Goal").disabled).toBe(false); expect(client.goalCommand).toHaveBeenCalledOnce();
  });

  it("rejects unbounded proposals and requires explicit human confirmation of every final completion condition", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.listGoals = vi.fn(async () => ({ goals: [goalSnapshot({ status: "awaiting_final_acceptance" })] })); client.createGoal = vi.fn(async () => goalSnapshot()); client.goalCommand = vi.fn(async () => goalSnapshot({ status: "completed" })); await drawGoal(client); expect(find("Accept completed Goal").disabled).toBe(true); await act(async () => [...node.querySelectorAll<HTMLInputElement>('.goal-conditions input')].forEach((checkbox) => checkbox.click())); await click("Accept completed Goal"); expect(client.goalCommand).toHaveBeenCalledExactlyOnceWith("goal-one", { command_id: expect.any(String), expected_revision: 4, operation: "accept", confirmed: true, accepted_conditions: ["Login works", "Tests pass"] });
    await click("New Goal"); await input("Goal title", "Unbounded"); await input("Goal objective", "Do everything"); await input("Goal completion conditions", "Everything works"); await act(async () => node.querySelector<HTMLFormElement>("form")!.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }))); expect(client.createGoal).not.toHaveBeenCalled(); expect(node.textContent).toContain("at least one finite token or time limit");
  });

  it("does not repeat an unknown Goal write and unlocks only after the original exact command receipt is verified", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.listGoals = vi.fn(async () => ({ goals: [goalSnapshot()] })); client.createGoal = vi.fn(async () => goalSnapshot()); let original = ""; client.goalCommand = vi.fn(async (_id, request) => { original = request.command_id; throw new Error("Response lost"); }); client.getGoalCommandReceipt = vi.fn<NonNullable<WorkbenchClient["getGoalCommandReceipt"]>>(async (id, commandId) => ({ goal_id: id, command_id: commandId, state: "completed", result: goalSnapshot({ status: "approved", revision: 5 }) })); await drawGoal(client); await click("Approve Goal proposal"); expect(find("Approve Goal proposal").disabled).toBe(true); await click("Refresh"); expect(find("Approve Goal proposal").disabled).toBe(true); expect(client.goalCommand).toHaveBeenCalledOnce(); await click("Inspect original Goal command"); expect(client.getGoalCommandReceipt).toHaveBeenCalledExactlyOnceWith("goal-one", original); expect(client.goalCommand).toHaveBeenCalledOnce(); expect(node.textContent).toContain("verified completion receipt"); expect(find("Start Goal").disabled).toBe(false);
  });

  it("reconciles an unknown Goal creation by its original command without guessing an ID or creating it again", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.listGoals = vi.fn(async () => ({ goals: [] })); let original = ""; client.createGoal = vi.fn(async (request) => { original = request.command_id; throw new Error("Creation response lost"); }); client.goalCommand = vi.fn(async () => goalSnapshot()); client.getGoalCreationReceipt = vi.fn<NonNullable<WorkbenchClient["getGoalCreationReceipt"]>>(async (id) => ({ command_id: id, state: "completed", goal_id: "goal-one", result: goalSnapshot() })); await drawGoal(client, false, true); await input("Goal title", "Deliver login"); await input("Goal objective", "Implement login"); await input("Goal completion conditions", "Login works"); await input("Goal token limit", "5000"); await act(async () => node.querySelector<HTMLFormElement>("form")!.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }))); expect(find("Save Goal proposal").disabled).toBe(true); await click("Inspect original Goal command"); expect(client.getGoalCreationReceipt).toHaveBeenCalledExactlyOnceWith(original); expect(client.createGoal).toHaveBeenCalledOnce(); expect(client.goalCommand).not.toHaveBeenCalled(); expect(find("Approve Goal proposal").disabled).toBe(false);
  });

  it("does not unlock an unknown browser operation using a receipt from another command", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.getBrowserStatus = vi.fn(async () => browserStatus()); client.browserCommand = vi.fn(async () => { throw new Error("Response lost"); }); client.getBrowserCommandReceipt = vi.fn<NonNullable<WorkbenchClient["getBrowserCommandReceipt"]>>(async () => ({ command_id: "different-command", state: "completed", result: { command_id: "different-command", status: "succeeded" } })); await drawBrowser(client); await input("Approved browser permission", "grant-one"); await input("Open browser address", "https://example.com/"); await click("Open browser tab"); await click("Inspect original browser action"); expect(find("Open browser tab").disabled).toBe(true); expect(node.textContent).toContain("does not match the original command"); expect(client.browserCommand).toHaveBeenCalledOnce();
  });

  it("keeps Replay controller views read-only even when the transport advertises live operations", async () => {
    const client: WorkbenchClient = new DemoTraceGraphClient(); client.getBrowserStatus = vi.fn(async () => browserStatus()); client.browserCommand = vi.fn<NonNullable<WorkbenchClient["browserCommand"]>>(async (request) => ({ command_id: request.command_id, status: "succeeded" })); await drawBrowser(client, true); expect(find("Take control").disabled).toBe(true); expect(find("Observe browser").disabled).toBe(true); expect(find("Request browser permission").disabled).toBe(true); expect(client.browserCommand).not.toHaveBeenCalled(); client.listGoals = vi.fn(async () => ({ goals: [goalSnapshot()] })); client.goalCommand = vi.fn(async () => goalSnapshot()); await drawGoal(client, true); expect(find("Approve Goal proposal").disabled).toBe(true); expect(find("New Goal").disabled).toBe(true); expect(client.goalCommand).not.toHaveBeenCalled();
  });
});
