// @vitest-environment jsdom
import {act} from "react";
import {createRoot,type Root} from "react-dom/client";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {HostCapabilitiesSchema,type ManagedSkillCommand,type ManagedSkillsSnapshot,WorkbenchSettingsSnapshotSchema} from "@tracegraph/contracts";
import {DemoTraceGraphClient,type WorkbenchClient} from "./client";
import {LanguageProvider} from "./i18n";
import {translate} from "@tracegraph/sdk/client";
import {SkillsManager} from "./components/SkillsManager";
import {UnifiedSettings} from "./components/UnifiedSettings";
const sha="sha256:"+"a".repeat(64),stateSha="sha256:"+"b".repeat(64);
const caps=HostCapabilitiesSchema.parse({profile_id:"profile:local",protocol_version:"test",capabilities:["skills.manage.read","skills.manage.write","skills.manage.validate","skills.manage.reconcile","settings.read","settings.write"].map(operation=>({operation,state:"available",scope:"profile"}))});
let node:HTMLDivElement,root:Root;
const find=(label:string)=>[...node.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent?.trim()===label)!;
const click=async(label:string)=>{expect(find(label)).toBeDefined();await act(async()=>find(label).click());};
const change=async(label:string,value:string)=>{const field=node.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;await act(async()=>{Object.getOwnPropertyDescriptor(field instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,"value")!.set!.call(field,value);field.dispatchEvent(new Event("input",{bubbles:true}));});};
function fixture(){const client:WorkbenchClient=new DemoTraceGraphClient();vi.spyOn(client,"getSnapshot").mockReturnValue({...client.getSnapshot(),availableProjects:[],connection:{...client.getSnapshot().connection,state:"live"}});client.listManagedSkills=vi.fn<NonNullable<WorkbenchClient["listManagedSkills"]>>(async scope=>({scope,state_sha256:stateSha,state_revision:0,entries:[],conflicts:[],diagnostics:[],effective:"new-run",legacy_disabled_names:[]} satisfies ManagedSkillsSnapshot));client.managedSkillCommand=vi.fn<NonNullable<WorkbenchClient["managedSkillCommand"]>>(async input=>({command_id:input.command_id,scope:input.scope,name:input.name,status:"succeeded",code:"skill_updated",sha256:sha,effective:"new-run",receipt_event_id:"event:receipt"}));return client;}
const draw=(client:WorkbenchClient,available=caps)=><LanguageProvider><SkillsManager client={client} capabilities={available}/></LanguageProvider>;
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});window.localStorage.setItem("tracegraph.language","en");node=document.createElement("div");document.body.append(node);root=createRoot(node);});
afterEach(async()=>{await act(async()=>root.unmount());node.remove();vi.restoreAllMocks();});
describe("real scoped Skill management UI",()=>{
 it("retains each completed create/save receipt after updating the selected document, then clears it only for a new draft",async()=>{
  const client=fixture();await act(async()=>root.render(draw(client)));await click("Save Skill");
  const status=()=>[...node.querySelectorAll('[role="status"]')].map(value=>value.textContent).join(" ");
  expect(status()).toContain("Skill change completed.");expect(node.querySelector(".skill-result-diagnostics code")?.textContent).toBe("skill_updated");expect(client.managedSkillCommand).toHaveBeenCalledOnce();
  await change("SKILL.md content","Updated literal content");expect(node.querySelector(".skill-result-diagnostics")).toBeNull();await click("Save Skill");
  expect(client.managedSkillCommand).toHaveBeenCalledTimes(2);expect(client.managedSkillCommand).toHaveBeenLastCalledWith(expect.objectContaining({type:"save",expected_sha256:sha,content:"Updated literal content"}));
  expect(status()).toContain("Skill change completed.");expect(node.querySelector(".skill-result-diagnostics code")?.textContent).toBe("skill_updated");
  await click("New Skill");expect(status()).not.toContain("Skill change completed.");expect(node.querySelector(".skill-result-diagnostics")).toBeNull();expect(client.managedSkillCommand).toHaveBeenCalledTimes(2);
 });

 it("localizes only fresh Skill templates and preserves an edited draft across locale changes",async()=>{
  const client=fixture();window.localStorage.setItem("tracegraph.language","zh-CN");await act(async()=>root.render(draw(client)));
  const content=()=>node.querySelector<HTMLTextAreaElement>(`[aria-label="${translate("zh-CN","SKILL.md content")}"]`)!;
  expect(content().value).toContain("description: 说明何时使用此技能");expect(content().value).toContain("在这里编写本地技能的使用说明。");expect(content().value).toContain("allowed_tools: [read_file]");
  await change(translate("zh-CN","SKILL.md content"),"User supplied literal English instructions");await click(translate("zh-CN","Refresh Skills"));expect(content().value).toBe("User supplied literal English instructions");
  await act(async()=>root.render(null));window.localStorage.setItem("tracegraph.language","en");await act(async()=>root.render(draw(client)));
  const field=node.querySelector<HTMLTextAreaElement>('[aria-label="SKILL.md content"]')!;expect(field.value).toBe("User supplied literal English instructions");
  await click("New Skill");expect(field.value).toContain("description: Describe when to use this Skill");expect(field.value).toContain("Write the local Skill instructions here.");expect(client.managedSkillCommand).not.toHaveBeenCalled();
 });
 it("shows a friendly canonical Skill result while retaining its exact code only in collapsed diagnostics",async()=>{
  const client=fixture();client.listManagedSkills=vi.fn<NonNullable<WorkbenchClient["listManagedSkills"]>>(async scope=>({scope,state_sha256:stateSha,state_revision:3,entries:[{name:"review",sha256:sha,byte_length:10,enabled:true,removed:false,diagnostics:[]}],conflicts:[],diagnostics:[],effective:"new-run",legacy_disabled_names:[]}));
  await act(async()=>root.render(draw(client)));await click("Disable Skill");
  const status=[...node.querySelectorAll('[role="status"]')].map(value=>value.textContent).join(" ");expect(status).toContain("Skill change completed.");expect(status).not.toContain("skill_updated");expect(status).toContain("Applies to new tasks");
  const details=node.querySelector<HTMLDetailsElement>(".skill-result-diagnostics")!;expect(details.open).toBe(false);expect(details.querySelector("code")!.textContent).toBe("skill_updated");expect(client.managedSkillCommand).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({type:"set-enabled",name:"review",enabled:false,expected_sha256:sha,expected_state_sha256:stateSha}));
 });

 it("keeps invalid names and byte-bounded imports local until an explicit valid save",async()=>{const client=fixture();await act(async()=>root.render(draw(client)));await change("Skill name","../private");await click("Save Skill");expect(client.managedSkillCommand).not.toHaveBeenCalled();expect(find("Save Skill").disabled).toBe(false);expect(node.textContent).not.toContain("unknown result");await change("Skill name","review");const field=node.querySelector<HTMLInputElement>('[aria-label="Import local SKILL.md"]')!;const file={size:19,arrayBuffer:async()=>new TextEncoder().encode("Explicit imported text").buffer} as File;await act(async()=>{Object.defineProperty(field,"files",{value:[file],configurable:true});field.dispatchEvent(new Event("change",{bubbles:true}));});expect(client.managedSkillCommand).not.toHaveBeenCalled();expect((node.querySelector('[aria-label="SKILL.md content"]') as HTMLTextAreaElement).value).toBe("Explicit imported text");await click("Save Skill");expect(client.managedSkillCommand).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({scope:{kind:"global"},content:"Explicit imported text"}));});
 it("creates in global scope without a project and sends only explicitly entered content",async()=>{const client=fixture(),run=vi.spyOn(client,"startRun");await act(async()=>root.render(draw(client)));await change("Skill name","review");await change("SKILL.md content","Explicit selected local content");await click("Save Skill");expect(client.managedSkillCommand).toHaveBeenCalledExactlyOnceWith({command_id:expect.any(String),type:"create",scope:{kind:"global"},name:"review",expected_sha256:null,content:"Explicit selected local content"});expect(run).not.toHaveBeenCalled();expect(node.textContent).toContain("Applies to new tasks");});
 it("approves only the same displayed intent and never auto-approves a declared tool",async()=>{const client=fixture();client.managedSkillCommand=vi.fn<NonNullable<WorkbenchClient["managedSkillCommand"]>>(async input=>({command_id:input.command_id,scope:input.scope,name:input.name,status:input.approval?"succeeded":"awaiting_approval",code:input.approval?"skill_updated":"skill_approval_required",sha256:input.approval?sha:null,approval_id:"approval:skill",effective:"new-run"}));await act(async()=>root.render(draw(client)));await click("Save Skill");expect(client.managedSkillCommand).toHaveBeenCalledOnce();expect(find("Save Skill").disabled).toBe(true);await click("Approve Skill change");const [first,next]=vi.mocked(client.managedSkillCommand!).mock.calls;expect(next![0]).toEqual({...first![0],approval:{approval_id:"approval:skill",decision:"approve"}});});
 it("retains unknown intent and draft after closing, and only inspects its original command",async()=>{const client=fixture();client.managedSkillCommand=vi.fn(async()=>{throw new TypeError("Synthetic lost response");});client.getManagedSkillCommandReceipt=vi.fn<NonNullable<WorkbenchClient["getManagedSkillCommandReceipt"]>>(async id=>({command_id:id,state:"unknown",observed_sha256:sha}));await act(async()=>root.render(draw(client)));await change("SKILL.md content","Keep private draft");await click("Save Skill");const original=vi.mocked(client.managedSkillCommand!).mock.calls[0]![0];await act(async()=>root.render(null));await act(async()=>root.render(draw(client)));expect((node.querySelector('[aria-label="SKILL.md content"]') as HTMLTextAreaElement).value).toBe("Keep private draft");expect(find("Save Skill").disabled).toBe(true);await click("Inspect Skill command result");expect(client.getManagedSkillCommandReceipt).toHaveBeenCalledExactlyOnceWith(original.command_id);expect(node.textContent).toContain("Observed file hashes do not prove");expect(client.managedSkillCommand).toHaveBeenCalledOnce();});
 it("keeps file CAS conflict drafts explicit and sends original file plus state hashes for toggles",async()=>{const client=fixture();client.listManagedSkills=vi.fn<NonNullable<WorkbenchClient["listManagedSkills"]>>(async scope=>({scope,state_sha256:stateSha,state_revision:3,entries:[{name:"review",sha256:sha,byte_length:10,enabled:true,removed:false,diagnostics:[]}],conflicts:[],diagnostics:[],effective:"new-run",legacy_disabled_names:[]}));client.readManagedSkill=vi.fn<NonNullable<WorkbenchClient["readManagedSkill"]>>(async input=>({...input,sha256:sha,byte_length:10,enabled:true,removed:false,diagnostics:[],content:"old content"}));await act(async()=>root.render(draw(client)));await click("Disable Skill");expect(client.managedSkillCommand).toHaveBeenLastCalledWith({type:"set-enabled",command_id:expect.any(String),scope:{kind:"global"},name:"review",expected_sha256:sha,expected_state_sha256:stateSha,enabled:false});await click("review");await change("SKILL.md content","Changed draft");client.managedSkillCommand=vi.fn<NonNullable<WorkbenchClient["managedSkillCommand"]>>(async input=>({command_id:input.command_id,scope:input.scope,name:input.name,status:"conflict",code:"skill_revision_conflict",sha256:stateSha,effective:"new-run"}));await click("Save Skill");expect((node.querySelector('[aria-label="SKILL.md content"]') as HTMLTextAreaElement).value).toBe("Changed draft");expect(client.managedSkillCommand).toHaveBeenCalledOnce();expect(find("Save Skill").disabled).toBe(false);});
 it("does not turn old read-only installations or disconnected clients into writable managers",async()=>{const client=fixture(),old={...caps,capabilities:caps.capabilities.filter(cap=>!cap.operation.startsWith("skills.manage"))};await act(async()=>root.render(draw(client,old)));expect(find("Save Skill").disabled).toBe(true);expect(client.listManagedSkills).not.toHaveBeenCalled();expect(node.textContent).toContain("unavailable on this installation");vi.mocked(client.getSnapshot).mockReturnValue({...client.getSnapshot(),connection:{...client.getSnapshot().connection,state:"offline"}});await act(async()=>root.render(draw(client)));expect(find("Save Skill").disabled).toBe(true);expect(node.textContent).toContain("Reconnect to manage Skills");expect(client.managedSkillCommand).not.toHaveBeenCalled();});
 it("uses the controller-backed global manager inside Skills settings without project fallback",async()=>{const client=fixture();client.getCapabilities=vi.fn(async()=>caps);client.getWorkbenchSettings=vi.fn(async()=>WorkbenchSettingsSnapshotSchema.parse({config_version:"outlive.workbench.v1",profile_id:"profile:local",revision:0,settings:{},fields:[],pending_restart:[]}));const legacy=vi.spyOn(client,"listSkills");await act(async()=>root.render(<LanguageProvider><UnifiedSettings client={client} open initialCategory="skills" onApplied={vi.fn()} onClose={vi.fn()} onMemory={vi.fn()}/></LanguageProvider>));expect(node.querySelector(".skills-manager")).not.toBeNull();expect(node.textContent).not.toContain("No registered projects expose Skills.");expect(legacy).not.toHaveBeenCalled();});
});
