// @vitest-environment jsdom
import {act} from "react";
import {createRoot,type Root} from "react-dom/client";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {HostCapabilitiesSchema,VisualRetentionSettingsSchema,type VisualEvidenceEntry} from "@tracegraph/contracts";
import {DemoTraceGraphClient,type WorkbenchClient} from "./client";
import {LanguageProvider} from "./i18n";
import {VisualRetentionSettingsPanel} from "./components/VisualRetentionSettings";
const sha="sha256:"+"a".repeat(64),caps=HostCapabilitiesSchema.parse({profile_id:"profile:local",protocol_version:"test",capabilities:["visual.retention.read","visual.retention.write","visual.evidence.read","visual.evidence.pin","visual.evidence.cleanup","visual.evidence.reconcile"].map(operation=>({operation,state:"available",scope:"profile"}))});
const settings=()=>VisualRetentionSettingsSchema.parse({schema_version:"outlive.visual-retention.v1",profile_id:"profile:local",revision:3,updated_at:null,last_command_id:null,values:{retention_days:30,automatic_cleanup:true},legacy_policy:"retain-unregistered"});
const entry=(id:string,age=40,pinned=false):VisualEvidenceEntry=>({evidence_id:id,source:"browser",project_id:"project:one",captured_at:new Date(Date.now()-age*86400000).toISOString(),sha256:sha,byte_length:1024,mime_type:"image/png",revision:4,pinned,state:"retained",run_artifacts:[]});
let node:HTMLDivElement,root:Root;
const find=(label:string)=>[...node.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent?.trim()===label)!;
const click=async(label:string)=>{expect(find(label)).toBeDefined();await act(async()=>find(label).click());};
const change=async(label:string,value:string)=>{const field=node.querySelector<HTMLInputElement|HTMLSelectElement>(`[aria-label="${label}"]`)!;expect(field).not.toBeNull();await act(async()=>{Object.getOwnPropertyDescriptor(field instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype,"value")!.set!.call(field,value);field.dispatchEvent(new Event(field instanceof HTMLSelectElement?"change":"input",{bubbles:true}));});};
function fixture(entries:VisualEvidenceEntry[]=[]){const client:WorkbenchClient=new DemoTraceGraphClient();vi.spyOn(client,"getSnapshot").mockReturnValue({...client.getSnapshot(),connection:{...client.getSnapshot().connection,state:"live"},availableProjects:[{id:"project:one",name:"Selected project",workspaceKind:"managed_local",pathLabel:"Managed project"}]});client.getVisualRetentionSettings=vi.fn(async()=>settings());client.listVisualEvidence=vi.fn<NonNullable<WorkbenchClient["listVisualEvidence"]>>(async()=>({source:"registered-provenance",entries,total:entries.length,legacy_policy:"retain-unregistered"}));client.cleanupVisualEvidence=vi.fn<NonNullable<WorkbenchClient["cleanupVisualEvidence"]>>(async input=>({command_id:input.command_id,status:"completed",deleted:[],unknown:[],deleted_bytes:0,checked_at:new Date().toISOString(),more_expired:false}));return client;}
const draw=(client:WorkbenchClient,capabilities=caps)=><LanguageProvider><VisualRetentionSettingsPanel client={client} capabilities={capabilities}/></LanguageProvider>;
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});window.localStorage.setItem("tracegraph.language","en");node=document.createElement("div");document.body.append(node);root=createRoot(node);});
afterEach(async()=>{await act(async()=>root.unmount());node.remove();vi.restoreAllMocks();});
describe("visual evidence controls use real scoped commands",()=>{
 it("only reads on page open and saves confirmed retention values against their loaded revision",async()=>{const client=fixture();client.updateVisualRetentionSettings=vi.fn<NonNullable<WorkbenchClient["updateVisualRetentionSettings"]>>(async input=>({...settings(),revision:4,last_command_id:input.command_id,values:input.values}));await act(async()=>root.render(draw(client)));expect((node.querySelector('[aria-label="Screenshot retention days"]') as HTMLInputElement).value).toBe("30");expect(client.cleanupVisualEvidence).not.toHaveBeenCalled();await change("Screenshot retention days","45");await click("Save screenshot retention");expect(client.updateVisualRetentionSettings).toHaveBeenCalledExactlyOnceWith({command_id:expect.any(String),expected_revision:3,values:{retention_days:45,automatic_cleanup:true}});expect(node.textContent).toContain("Screenshot retention settings saved.");expect(client.cleanupVisualEvidence).not.toHaveBeenCalled();});
 it("keeps a refused settings draft while refreshing its new revision for an explicit retry",async()=>{const client=fixture();client.updateVisualRetentionSettings=vi.fn<NonNullable<WorkbenchClient["updateVisualRetentionSettings"]>>(async()=>{throw Object.assign(new Error("CAS"),{code:"visual_revision_conflict"});});await act(async()=>root.render(draw(client)));await change("Screenshot retention days","90");await click("Save screenshot retention");client.getVisualRetentionSettings=vi.fn(async()=>({...settings(),revision:5}));await click("Refresh screenshots");expect((node.querySelector('[aria-label="Screenshot retention days"]') as HTMLInputElement).value).toBe("90");expect(client.updateVisualRetentionSettings).toHaveBeenCalledOnce();expect(find("Save screenshot retention").disabled).toBe(false);client.updateVisualRetentionSettings=vi.fn<NonNullable<WorkbenchClient["updateVisualRetentionSettings"]>>(async input=>({...settings(),revision:6,last_command_id:input.command_id,values:input.values}));await click("Save screenshot retention");expect(client.updateVisualRetentionSettings).toHaveBeenCalledExactlyOnceWith({command_id:expect.any(String),expected_revision:5,values:{retention_days:90,automatic_cleanup:true}});});
 it("pins exact evidence and revision without treating metadata as an image preview",async()=>{const original=entry("browser:pin"),client=fixture([original]);client.pinVisualEvidence=vi.fn<NonNullable<WorkbenchClient["pinVisualEvidence"]>>(async(id,input)=>({...original,evidence_id:id,revision:5,pinned:input.pinned,last_command_id:input.command_id}));const run=vi.spyOn(client,"startRun");await act(async()=>root.render(draw(client)));await click("Pin screenshot");expect(client.pinVisualEvidence).toHaveBeenCalledExactlyOnceWith(original.evidence_id,{command_id:expect.any(String),expected_revision:4,pinned:true});expect(node.querySelector("img")).toBeNull();expect(run).not.toHaveBeenCalled();expect(node.textContent).toContain("excluded from expiry cleanup");});
 it("previews eligible loaded records and confirms only the selected project/task and bounded batch",async()=>{const client=fixture([entry("browser:expired"),entry("browser:recent",2),entry("browser:pinned",50,true)]);await act(async()=>root.render(draw(client)));await change("Screenshot project scope","project:one");await change("Screenshot task scope","run:one");await click("Review expired screenshots");const review=node.querySelector(".visual-cleanup-review")!;expect(review.textContent).toContain("Selected project · run:one");expect(review.querySelectorAll("li")).toHaveLength(1);expect(review.textContent).toContain("browser:expired");expect(review.textContent).not.toContain("browser:pinned");expect(client.cleanupVisualEvidence).not.toHaveBeenCalled();await click("Confirm screenshot cleanup");expect(client.cleanupVisualEvidence).toHaveBeenCalledExactlyOnceWith({command_id:expect.any(String),project_id:"project:one",run_id:"run:one",limit:50});expect(node.textContent).toContain("reports no screenshots deleted");expect(node.textContent).not.toContain("confirms these screenshots were deleted");});
 it("preserves an unknown cleanup on reopening and reads its original receipt without repeating deletion",async()=>{const client=fixture([entry("browser:expired")]);client.cleanupVisualEvidence=vi.fn<NonNullable<WorkbenchClient["cleanupVisualEvidence"]>>(async()=>{throw new TypeError("Dropped effect response");});client.getVisualEvidenceCommandReceipt=vi.fn<NonNullable<WorkbenchClient["getVisualEvidenceCommandReceipt"]>>(async id=>({command_id:id,operation:"visual.evidence.cleanup",state:"unknown",observed_bytes:[{evidence_id:"browser:expired",all_registered_bytes_absent:true,present_copies:0,unverifiable_copies:0}]}));await act(async()=>root.render(draw(client)));await click("Review expired screenshots");await click("Confirm screenshot cleanup");const id=vi.mocked(client.cleanupVisualEvidence!).mock.calls[0]![0].command_id;await act(async()=>root.render(null));await act(async()=>root.render(draw(client)));expect(find("Review expired screenshots").disabled).toBe(true);await click("Inspect original screenshot command");expect(client.getVisualEvidenceCommandReceipt).toHaveBeenCalledExactlyOnceWith(id);expect(node.textContent).toContain("Observed bytes do not prove cleanup completed");expect(client.cleanupVisualEvidence).toHaveBeenCalledOnce();expect(find("Save screenshot retention").disabled).toBe(true);});
 it("retains failed load as failure and an empty inventory as empty, without a cleanup success claim",async()=>{const client=fixture();await act(async()=>root.render(draw(client)));expect(node.textContent).toContain("No registered screenshots were found");expect(find("Review expired screenshots").disabled).toBe(true);expect(node.querySelector('[aria-label="Screenshot cleanup receipt"]')).toBeNull();client.listVisualEvidence=vi.fn<NonNullable<WorkbenchClient["listVisualEvidence"]>>(async()=>{throw new Error("Synthetic invalid provenance");});await click("Refresh screenshots");expect(node.querySelector('[role="alert"]')?.textContent).toContain("could not be loaded");expect(client.cleanupVisualEvidence).not.toHaveBeenCalled();});
 it("distinguishes policy denial and offline state from unsupported and never dispatches stale controls",async()=>{const client=fixture([entry("browser:one")]),denied={...caps,capabilities:caps.capabilities.map(cap=>cap.operation==="visual.retention.read"?{...cap,state:"policy-denied" as const}:cap)};await act(async()=>root.render(draw(client,denied)));expect(node.textContent).toContain("current permissions");expect(client.getVisualRetentionSettings).not.toHaveBeenCalled();vi.mocked(client.getSnapshot).mockReturnValue({...client.getSnapshot(),connection:{...client.getSnapshot().connection,state:"offline"}});await act(async()=>root.render(draw(client)));expect(node.textContent).toContain("Reconnect to manage screenshots");expect(find("Review expired screenshots").disabled).toBe(true);expect(client.cleanupVisualEvidence).not.toHaveBeenCalled();});
});
