import Foundation
import AppKit
import ApplicationServices
import ScreenCaptureKit
import CryptoKit

// Private bounded protocol. This executable never evaluates source, shell or AppleScript.
let inputTag: Int64 = 0x4f55544c495645
struct HelperFailure: Error { let code: String; let message: String }
func fail(_ code: String, _ message: String) throws -> Never { throw HelperFailure(code: code, message: message) }
func output(_ value: [String: Any]) { if let bytes = try? JSONSerialization.data(withJSONObject: value, options: [.sortedKeys]), bytes.count <= 24 * 1024 * 1024 { FileHandle.standardOutput.write(bytes); FileHandle.standardOutput.write(Data([10])) } }
func result(_ value: Any) { output(["ok": true, "result": value]) }
func attribute(_ element: AXUIElement, _ name: CFString) -> CFTypeRef? { var value: CFTypeRef?; return AXUIElementCopyAttributeValue(element, name, &value) == .success ? value : nil }
func text(_ element: AXUIElement, _ name: CFString, _ maximum: Int) -> String? { guard let value = attribute(element, name) as? String else { return nil }; return String(value.prefix(maximum)) }
func axBounds(_ element: AXUIElement) -> CGRect? { guard let position = attribute(element, kAXPositionAttribute as CFString), let size = attribute(element, kAXSizeAttribute as CFString), CFGetTypeID(position) == AXValueGetTypeID(), CFGetTypeID(size) == AXValueGetTypeID() else { return nil }; var point = CGPoint.zero; var dimensions = CGSize.zero; guard AXValueGetValue(unsafeBitCast(position, to: AXValue.self), .cgPoint, &point), AXValueGetValue(unsafeBitCast(size, to: AXValue.self), .cgSize, &dimensions) else { return nil }; return CGRect(origin: point, size: dimensions) }
func locked() -> Bool { guard let session = CGSessionCopyCurrentDictionary() as? [String: Any] else { return true }; return (session["CGSSessionScreenIsLocked"] as? Bool ?? false) || !(session[kCGSessionOnConsoleKey as String] as? Bool ?? true) }
func status() -> [String: Any] { ["platform": "darwin", "backend_available": true, "accessibility": AXIsProcessTrusted(), "screen_capture": CGPreflightScreenCaptureAccess(), "input_monitoring": CGPreflightListenEventAccess(), "locked": locked()] }
var identityCache: [String: (String, String)] = [:]
func identity(_ app: NSRunningApplication) throws -> String { guard let url = app.executableURL else { try fail("computer_target_changed", "Target executable is unavailable") }; let metadata = try FileManager.default.attributesOfItem(atPath: url.path); guard let size = metadata[.size] as? UInt64, size > 0, size <= 256 * 1024 * 1024 else { try fail("computer_target_changed", "Target executable identity is unavailable") }; let stamp = "\(size):\(metadata[.modificationDate] ?? ""):\(metadata[.systemFileNumber] ?? "")"; if let cached = identityCache[url.path], cached.0 == stamp { return cached.1 }; let digest = "sha256:" + SHA256.hash(data: try Data(contentsOf: url, options: [.mappedIfSafe])).map { String(format: "%02x", $0) }.joined(); identityCache[url.path] = (stamp, digest); return digest }
func windows() -> [[String: Any]] { (CGWindowListCopyWindowInfo([.optionOnScreenOnly, .excludeDesktopElements], kCGNullWindowID) as? [[String: Any]]) ?? [] }
func windowBounds(_ info: [String: Any]) -> CGRect? { guard let value = info[kCGWindowBounds as String] as? [String: Any] else { return nil }; return CGRect(dictionaryRepresentation: value as CFDictionary) }
func protectedApplication(_ id: String) -> Bool { id.hasPrefix("com.outlive.agent") || id == "com.apple.systempreferences" || id == "com.apple.ScriptEditor2" }
func listTargets() throws -> [[String: Any]] { var targets: [[String: Any]] = []; var identities: [pid_t: String] = [:]; for window in windows() { guard targets.count < 128, let pid = window[kCGWindowOwnerPID as String] as? Int32, let id = window[kCGWindowNumber as String] as? UInt32, let layer = window[kCGWindowLayer as String] as? Int, layer == 0, let bounds = windowBounds(window), bounds.width > 1, bounds.height > 1, let app = NSRunningApplication(processIdentifier: pid), let bundle = app.bundleIdentifier, !protectedApplication(bundle), app.executableURL?.lastPathComponent.lowercased() != "osascript", !(window[kCGWindowName as String] as? String ?? "").lowercased().hasPrefix("outlive agent") else { continue }; let hash: String; if let cached = identities[pid] { hash = cached } else { guard let computed = try? identity(app) else { continue }; hash = computed; identities[pid] = hash }; targets.append(["application_id": bundle, "pid": Int(pid), "title": String((app.localizedName ?? bundle).prefix(300)), "identity": hash, "window_id": String(id)]) }; return targets }
struct Target { let app: NSRunningApplication; let pid: pid_t; let id: UInt32; let bounds: CGRect; let value: [String: Any] }
func target(_ value: Any?, foreground: Bool = false) throws -> Target { guard let item = value as? [String: Any], let pid = item["pid"] as? Int32, let idText = item["window_id"] as? String, let id = UInt32(idText), let appID = item["application_id"] as? String, let expectedHash = item["identity"] as? String, let app = NSRunningApplication(processIdentifier: pid), app.bundleIdentifier == appID, !protectedApplication(appID), try identity(app) == expectedHash, let window = windows().first(where: { ($0[kCGWindowNumber as String] as? UInt32) == id && ($0[kCGWindowOwnerPID as String] as? Int32) == pid && ($0[kCGWindowLayer as String] as? Int) == 0 }), let bounds = windowBounds(window), app.executableURL?.lastPathComponent.lowercased() != "osascript", !(window[kCGWindowName as String] as? String ?? "").lowercased().hasPrefix("outlive agent") else { try fail("computer_target_changed", "The granted application or window changed") }; if locked() { try fail("computer_locked", "The computer is locked") }; if foreground { guard NSWorkspace.shared.frontmostApplication?.processIdentifier == pid else { try fail("computer_target_changed", "The granted application is not in the foreground") }; let focused = attribute(AXUIElementCreateApplication(pid), kAXFocusedWindowAttribute as CFString); guard let focused, CFGetTypeID(focused) == AXUIElementGetTypeID(), let focusedBounds = axBounds(unsafeBitCast(focused, to: AXUIElement.self)), abs(focusedBounds.minX - bounds.minX) < 3, abs(focusedBounds.minY - bounds.minY) < 3, abs(focusedBounds.width - bounds.width) < 3, abs(focusedBounds.height - bounds.height) < 3 else { try fail("computer_target_changed", "Another window has input focus") }; let exactWindow = try axWindow(Target(app: app, pid: pid, id: id, bounds: bounds, value: item)); guard CFEqual(exactWindow, focused) else { try fail("computer_target_changed", "The selected AX window does not own input focus") } }; return Target(app: app, pid: pid, id: id, bounds: bounds, value: item) }
func accessibility() throws { guard AXIsProcessTrusted() else { try fail("computer_accessibility_required", "Accessibility permission is required") } }
func axWindow(_ value: Target) throws -> AXUIElement { let application = AXUIElementCreateApplication(value.pid); guard let windows = attribute(application, kAXWindowsAttribute as CFString) as? [AXUIElement] else { try fail("computer_ax_unavailable", "The application exposes no accessible windows") }; let matches = windows.filter { element in guard let rect = axBounds(element) else { return false }; return abs(rect.minX - value.bounds.minX) < 3 && abs(rect.minY - value.bounds.minY) < 3 && abs(rect.width - value.bounds.width) < 3 && abs(rect.height - value.bounds.height) < 3 }; guard matches.count == 1, let first = matches.first else { try fail("computer_ax_unavailable", "The selected window could not be identified uniquely") }; return first }
func focus(_ value: Target) throws -> [String: Any] { try accessibility(); let window = try axWindow(value); guard value.app.activate(options: []), AXUIElementPerformAction(window, kAXRaiseAction as CFString) == .success else { try fail("computer_target_changed", "The selected window could not be brought to the foreground") }; let deadline = Date().addingTimeInterval(1); while Date() < deadline { if (try? target(value.value, foreground: true)) != nil { return ["focused": true] }; RunLoop.current.run(until: Date().addingTimeInterval(0.02)) }; try fail("computer_target_changed", "The selected window did not receive input focus") }
func inspect(_ value: Target) throws -> [String: Any] { try accessibility(); let root = try axWindow(value); var elements: [[String: Any]] = []; var truncated = false; func visit(_ element: AXUIElement, _ depth: Int) { if elements.count >= 256 || depth > 5 { truncated = true; return }; let role = text(element, kAXRoleAttribute as CFString, 100) ?? "unknown"; var row: [String: Any] = ["element_id": "ax:\(elements.count)", "role": role]; if let title = text(element, kAXTitleAttribute as CFString, 512) { row["title"] = title }; let subrole = text(element, kAXSubroleAttribute as CFString, 100) ?? ""; // Never read password/secure input values.
 if !role.localizedCaseInsensitiveContains("secure") && !subrole.localizedCaseInsensitiveContains("secure") { if let value = text(element, kAXValueAttribute as CFString, 1024) { row["value"] = value } }; if let bounds = axBounds(element) { row["bounds"] = ["x": bounds.minX, "y": bounds.minY, "width": bounds.width, "height": bounds.height] }; if let enabled = attribute(element, kAXEnabledAttribute as CFString) as? Bool { row["enabled"] = enabled }; elements.append(row); if let children = attribute(element, kAXChildrenAttribute as CFString) as? [AXUIElement] { for child in children { visit(child, depth + 1); if elements.count >= 256 { truncated = true; break } } } }; visit(root, 0); return ["elements": elements, "truncated": truncated] }
func capture(_ value: Target) throws -> [String: Any] { guard CGPreflightScreenCaptureAccess() else { try fail("computer_capture_required", "Screen Capture permission is required") }; let semaphore = DispatchSemaphore(value: 0); var shareable: SCShareableContent?; var error: Error?; SCShareableContent.getExcludingDesktopWindows(true, onScreenWindowsOnly: true) { content, failure in shareable = content; error = failure; semaphore.signal() }; guard semaphore.wait(timeout: .now() + 5) == .success, error == nil, let window = shareable?.windows.first(where: { $0.windowID == value.id && $0.owningApplication?.processID == value.pid }) else { try fail("computer_capture_unavailable", "The selected window is unavailable for capture") }; let configuration = SCStreamConfiguration(); configuration.width = min(4096, max(1, Int(window.frame.width))); configuration.height = min(4096, max(1, Int(window.frame.height))); configuration.showsCursor = false; var image: CGImage?; SCScreenshotManager.captureImage(contentFilter: SCContentFilter(desktopIndependentWindow: window), configuration: configuration) { pixels, failure in image = pixels; error = failure; semaphore.signal() }; guard semaphore.wait(timeout: .now() + 5) == .success, error == nil, let image, let png = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:]), png.count <= 16 * 1024 * 1024 else { try fail("computer_capture_unavailable", "Window capture did not produce bounded PNG pixels") }; _ = try target(value.value); return ["png_base64": png.base64EncodedString()] }
func post(_ event: CGEvent?) throws { guard let event else { try fail("computer_input_unavailable", "The native input event could not be created") }; event.setIntegerValueField(.eventSourceUserData, value: inputTag); event.post(tap: .cghidEventTap) }
func act(_ request: [String: Any]) throws -> [String: Any] { try accessibility(); guard CGPreflightPostEventAccess(), CGPreflightListenEventAccess() else { try fail("computer_monitor_required", "Native input and observation permissions are required") }; let selected = try target(request["target"], foreground: true); guard let action = request["action"] as? [String: Any], let kind = action["kind"] as? String else { try fail("computer_input_invalid", "Invalid native input") }; switch kind {
 case "click": guard let x = action["x"] as? Double, let y = action["y"] as? Double, x.isFinite, y.isFinite, x >= 0, y >= 0, x < selected.bounds.width, y < selected.bounds.height else { try fail("computer_input_scope", "Click coordinates must be inside the selected window") }; let right = (action["button"] as? String) == "right"; let point = CGPoint(x: selected.bounds.minX + x, y: selected.bounds.minY + y); try post(CGEvent(mouseEventSource: nil, mouseType: right ? .rightMouseDown : .leftMouseDown, mouseCursorPosition: point, mouseButton: right ? .right : .left)); try post(CGEvent(mouseEventSource: nil, mouseType: right ? .rightMouseUp : .leftMouseUp, mouseCursorPosition: point, mouseButton: right ? .right : .left));
 case "type": guard let value = action["text"] as? String, !value.isEmpty, value.count <= 4000 else { try fail("computer_input_invalid", "Invalid input text") }; var chunks: [[UInt16]] = []; var chunk: [UInt16] = []; for scalar in value.unicodeScalars { let encoded = Array(String(scalar).utf16); if chunk.count + encoded.count > 32 { chunks.append(chunk); chunk = [] }; chunk.append(contentsOf: encoded) }; if !chunk.isEmpty { chunks.append(chunk) }; for slice in chunks { _ = try target(selected.value, foreground: true); guard let down = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: true), let up = CGEvent(keyboardEventSource: nil, virtualKey: 0, keyDown: false) else { try fail("computer_input_unavailable", "Could not create text event") }; slice.withUnsafeBufferPointer { pointer in down.keyboardSetUnicodeString(stringLength: slice.count, unicodeString: pointer.baseAddress); up.keyboardSetUnicodeString(stringLength: slice.count, unicodeString: pointer.baseAddress) }; try post(down); try post(up) }
 case "key": let keys: [String: CGKeyCode] = ["Enter": 36, "Escape": 53, "Tab": 48, "Backspace": 51, "ArrowUp": 126, "ArrowDown": 125, "ArrowLeft": 123, "ArrowRight": 124, "Space": 49]; guard let name = action["key"] as? String, let code = keys[name] else { try fail("computer_input_invalid", "Unsupported key") }; var flags: CGEventFlags = []; for name in (action["modifiers"] as? [String] ?? []) { switch name { case "shift": flags.insert(.maskShift); case "control": flags.insert(.maskControl); case "alt": flags.insert(.maskAlternate); case "meta": flags.insert(.maskCommand); default: try fail("computer_input_invalid", "Unsupported key modifier") } }; let down = CGEvent(keyboardEventSource: nil, virtualKey: code, keyDown: true); let up = CGEvent(keyboardEventSource: nil, virtualKey: code, keyDown: false); down?.flags = flags; up?.flags = flags; try post(down); try post(up);
 case "scroll": guard let x = action["delta_x"] as? Int32, let y = action["delta_y"] as? Int32, abs(Int(x)) <= 2000, abs(Int(y)) <= 2000 else { try fail("computer_input_invalid", "Invalid scroll distance") }; // Target focus is rechecked; cursor is positioned inside this window before scrolling.
 guard let move = CGEvent(mouseEventSource: nil, mouseType: .mouseMoved, mouseCursorPosition: CGPoint(x: selected.bounds.midX, y: selected.bounds.midY), mouseButton: .left) else { try fail("computer_input_unavailable", "Could not create scroll target") }; try post(move); try post(CGEvent(scrollWheelEvent2Source: nil, units: .pixel, wheelCount: 2, wheel1: y, wheel2: x, wheel3: 0));
 default: try fail("computer_input_invalid", "Unsupported native input operation") }; return ["posted": true] }
func watch(_ value: Target) throws { try accessibility(); guard CGPreflightListenEventAccess() else { try fail("computer_monitor_required", "Input Monitoring permission is required") }; _ = try target(value.value, foreground: true); let events: [CGEventType] = [.keyDown, .keyUp, .flagsChanged, .leftMouseDown, .rightMouseDown, .otherMouseDown, .mouseMoved, .leftMouseDragged, .rightMouseDragged, .scrollWheel]; let mask = events.reduce(CGEventMask(0)) { $0 | (1 << $1.rawValue) }; guard let tap = CGEvent.tapCreate(tap: .cgSessionEventTap, place: .headInsertEventTap, options: .listenOnly, eventsOfInterest: mask, callback: { _, type, event, _ in if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput { output(["event": "monitor-unavailable"]) } else if event.getIntegerValueField(.eventSourceUserData) != inputTag { output(["event": "user-input"]) }; return Unmanaged.passUnretained(event) }, userInfo: nil), let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0) else { try fail("computer_monitor_required", "Native input observation is unavailable") }; CFRunLoopAddSource(CFRunLoopGetCurrent(), source, .commonModes); CGEvent.tapEnable(tap: tap, enable: true); output(["ready": true]); let monitor = Timer.scheduledTimer(withTimeInterval: 0.1, repeats: true) { _ in if locked() { output(["event": "locked"]) } else if (try? target(value.value, foreground: true)) == nil { output(["event": "target-changed"]) } else if !CGEvent.tapIsEnabled(tap: tap) { output(["event": "monitor-unavailable"]) } }; let runLoop = CFRunLoopGetCurrent(); DispatchQueue.global().async { while readLine() != nil {} ; CFRunLoopStop(runLoop) }; CFRunLoopRun(); monitor.invalidate(); CGEvent.tapEnable(tap: tap, enable: false); CFRunLoopRemoveSource(CFRunLoopGetCurrent(), source, .commonModes) }

do { guard let line = readLine(), line.utf8.count <= 64 * 1024, let data = line.data(using: .utf8), let request = try JSONSerialization.jsonObject(with: data) as? [String: Any], let operation = request["operation"] as? String else { try fail("computer_protocol_invalid", "Invalid helper request") }; switch operation { case "status": result(status()); case "targets": result(try listTargets()); case "validate": _ = try target(request["target"], foreground: request["foreground"] as? Bool ?? false); result(["valid": true]); case "focus": result(try focus(target(request["target"]))); case "inspect": result(try inspect(target(request["target"]))); case "capture": result(try capture(target(request["target"]))); case "act": result(try act(request)); case "watch": try watch(target(request["target"], foreground: true)); default: try fail("computer_protocol_invalid", "Unsupported helper operation") } } catch let failure as HelperFailure { output(["ok": false, "code": failure.code, "message": failure.message]) } catch { output(["ok": false, "code": "computer_native_failed", "message": "Native computer operation failed"]) }
