using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text.Json.Nodes;
using System.Windows.Automation;
using System.Windows.Forms;

// Private closed protocol. Source is built on Windows; native acceptance is separate.
static class Program {
 const long Tag=0x4f55544c495645;
 static void Output(object value) { var json=System.Text.Json.JsonSerializer.Serialize(value);if(json.Length>24*1024*1024)throw new InvalidOperationException("computer_output_limit");Console.WriteLine(json);Console.Out.Flush(); }
 static string S(JsonObject value,string name)=>value[name]?.GetValue<string>()??throw new InvalidOperationException("computer_protocol_invalid");
 static int I(JsonObject value,string name)=>value[name]?.GetValue<int>()??throw new InvalidOperationException("computer_protocol_invalid");
 static bool Locked() {var desktop=N.OpenInputDesktop(0,false,0x0100);if(desktop==IntPtr.Zero)return true;try{var name=new System.Text.StringBuilder(256);return !N.GetUserObjectInformation(desktop,2,name,512,out _)||name.ToString()!="Default";}finally{N.CloseDesktop(desktop);} }
 static object Status()=>new{platform="win32",backend_available=true,accessibility=Environment.UserInteractive,screen_capture=Environment.UserInteractive,input_monitoring=Environment.UserInteractive&&!Locked(),locked=Locked()};
 static string Identity(Process process) {if(process.SessionId!=Process.GetCurrentProcess().SessionId)throw new InvalidOperationException("computer_target_changed");var path=process.MainModule?.FileName??throw new InvalidOperationException("computer_target_changed");var info=new FileInfo(path);if(info.Length<1||info.Length>256*1024*1024)throw new InvalidOperationException("computer_target_changed");using var stream=File.OpenRead(path);return "sha256:"+Convert.ToHexString(SHA256.HashData(stream)).ToLowerInvariant();}
 static string Application(Process process)=>"win:"+Path.GetFileName(process.MainModule!.FileName).ToLowerInvariant();
 static string Title(IntPtr window) {var text=new System.Text.StringBuilder(301);N.GetWindowText(window,text,301);return text.ToString();}
 static bool Protected(string id)=>new[]{"win:outlive agent.exe","win:systemsettings.exe","win:consent.exe","win:wscript.exe","win:cscript.exe"}.Contains(id);
 static List<object> Targets() {var result=new List<object>();N.EnumWindows((window,_)=>{if(result.Count>=128)return false;try{if(!N.IsWindowVisible(window)||N.GetWindowTextLength(window)==0||Title(window).StartsWith("Outlive Agent",StringComparison.OrdinalIgnoreCase))return true;N.GetWindowThreadProcessId(window,out var pid);using var process=Process.GetProcessById((int)pid);if(Protected(Application(process)))return true;result.Add(new{application_id=Application(process),pid=process.Id,title=Title(window),identity=Identity(process),window_id=window.ToInt64().ToString()});}catch{}return true;},IntPtr.Zero);return result;}
 static IntPtr Target(JsonObject value,bool foreground=false){var window=new IntPtr(long.Parse(S(value,"window_id")));N.GetWindowThreadProcessId(window,out var pid);using var process=Process.GetProcessById(I(value,"pid"));if(!N.IsWindow(window)||!N.IsWindowVisible(window)||Title(window).StartsWith("Outlive Agent",StringComparison.OrdinalIgnoreCase)||pid!=process.Id||Protected(Application(process))||Application(process)!=S(value,"application_id")||Identity(process)!=S(value,"identity"))throw new InvalidOperationException("computer_target_changed");if(Locked())throw new InvalidOperationException("computer_locked");if(foreground&&N.GetForegroundWindow()!=window)throw new InvalidOperationException("computer_target_changed");return window;}
 static object Focus(JsonObject value){var window=Target(value);if(!N.SetForegroundWindow(window))throw new InvalidOperationException("computer_target_changed");Target(value,true);return new{focused=true};}
 static object Inspect(JsonObject value){var root=AutomationElement.FromHandle(Target(value));var result=new List<object>();bool truncated=false;void Visit(AutomationElement element,int depth){if(result.Count>=256||depth>5){truncated=true;return;}var current=element.Current;var row=new Dictionary<string,object>{{"element_id","uia:"+result.Count},{"role",current.ControlType.ProgrammaticName},{"enabled",current.IsEnabled}};if(current.Name.Length>0)row["title"]=current.Name[..Math.Min(512,current.Name.Length)];if(!current.IsPassword&&element.TryGetCurrentPattern(ValuePattern.Pattern,out var pattern)){var text=((ValuePattern)pattern).Current.Value;row["value"]=text[..Math.Min(1024,text.Length)];}var rect=current.BoundingRectangle;if(!rect.IsEmpty)row["bounds"]=new{x=rect.X,y=rect.Y,width=rect.Width,height=rect.Height};result.Add(row);var child=TreeWalker.ControlViewWalker.GetFirstChild(element);while(child!=null){Visit(child,depth+1);if(result.Count>=256){truncated=true;break;}child=TreeWalker.ControlViewWalker.GetNextSibling(child);}}Visit(root,0);return new{elements=result,truncated};}
 static object Capture(JsonObject value){var window=Target(value);if(!N.GetWindowRect(window,out var rect)||rect.Right-rect.Left<=0||rect.Bottom-rect.Top<=0||rect.Right-rect.Left>4096||rect.Bottom-rect.Top>4096)throw new InvalidOperationException("computer_capture_unavailable");using var bitmap=new Bitmap(rect.Right-rect.Left,rect.Bottom-rect.Top);using(var graphics=Graphics.FromImage(bitmap)){var context=graphics.GetHdc();try{if(!N.PrintWindow(window,context,2))throw new InvalidOperationException("computer_capture_unavailable");}finally{graphics.ReleaseHdc(context);}}using var stream=new MemoryStream();bitmap.Save(stream,ImageFormat.Png);if(stream.Length>16*1024*1024)throw new InvalidOperationException("computer_capture_unavailable");Target(value);return new{png_base64=Convert.ToBase64String(stream.ToArray())};}
 static void Send(N.INPUT input){if(N.SendInput(1,new[]{input},Marshal.SizeOf<N.INPUT>())!=1)throw new InvalidOperationException("computer_input_unavailable");}
 static void Mouse(uint flags,int x=0,int y=0,uint data=0){Send(new N.INPUT{type=0,U=new N.UNION{mouse=new N.MOUSE{dx=x,dy=y,data=data,flags=flags,extra=new UIntPtr((ulong)Tag)}}});}
 static N.INPUT KeyInput(ushort code,uint flags,ushort scan=0)=>new N.INPUT{type=1,U=new N.UNION{key=new N.KEY{vk=code,scan=scan,flags=flags,extra=new UIntPtr((ulong)Tag)}}};
 static void Key(ushort code,uint flags,ushort scan=0){Send(KeyInput(code,flags,scan));}
 static void SendBatch(List<N.INPUT> input){if(N.SendInput((uint)input.Count,input.ToArray(),Marshal.SizeOf<N.INPUT>())!=input.Count)throw new InvalidOperationException("computer_input_unavailable");}
 static object Act(JsonObject request){var target=request["target"]!.AsObject();var window=Target(target,true);var action=request["action"]!.AsObject();switch(S(action,"kind")){case"click":N.GetWindowRect(window,out var r);var x=action["x"]!.GetValue<double>();var y=action["y"]!.GetValue<double>();if(!double.IsFinite(x)||!double.IsFinite(y)||x<0||y<0||x>=r.Right-r.Left||y>=r.Bottom-r.Top)throw new InvalidOperationException("computer_input_scope");var vx=N.GetSystemMetrics(76);var vy=N.GetSystemMetrics(77);var vw=N.GetSystemMetrics(78);var vh=N.GetSystemMetrics(79);Mouse(0x8001|0x4000,(int)((r.Left+x-vx)*65535/(vw-1)),(int)((r.Top+y-vy)*65535/(vh-1)));var right=S(action,"button")=="right";Mouse(right?8u:2u);Mouse(right?16u:4u);break;
 case"type":var text=S(action,"text");if(text.Length<1||text.Length>8000)throw new InvalidOperationException("computer_input_invalid");foreach(var character in text){Target(target,true);Key(0,4,character);Key(0,6,character);}break;
 case"key":var keys=new Dictionary<string,ushort>{{"Enter",13},{"Escape",27},{"Tab",9},{"Backspace",8},{"ArrowUp",38},{"ArrowDown",40},{"ArrowLeft",37},{"ArrowRight",39},{"Space",32}};if(!keys.TryGetValue(S(action,"key"),out var key))throw new InvalidOperationException("computer_input_invalid");var modifiers=new Dictionary<string,ushort>{{"shift",16},{"control",17},{"alt",18},{"meta",91}};var held=new List<ushort>();var batch=new List<N.INPUT>();foreach(var item in action["modifiers"]!.AsArray()){if(!modifiers.TryGetValue(item!.GetValue<string>(),out var modifier))throw new InvalidOperationException("computer_input_invalid");held.Add(modifier);batch.Add(KeyInput(modifier,0));}batch.Add(KeyInput(key,0));batch.Add(KeyInput(key,2));foreach(var modifier in held.AsEnumerable().Reverse())batch.Add(KeyInput(modifier,2));SendBatch(batch);break;
 case"scroll":var dx=I(action,"delta_x");var dy=I(action,"delta_y");if(Math.Abs(dx)>2000||Math.Abs(dy)>2000)throw new InvalidOperationException("computer_input_invalid");N.GetWindowRect(window,out var sr);var sx=N.GetSystemMetrics(76);var sy=N.GetSystemMetrics(77);Mouse(0x8001|0x4000,(int)(((sr.Left+sr.Right)/2-sx)*65535L/(N.GetSystemMetrics(78)-1)),(int)(((sr.Top+sr.Bottom)/2-sy)*65535L/(N.GetSystemMetrics(79)-1)));if(dy!=0)Mouse(0x800,data:unchecked((uint)dy));if(dx!=0)Mouse(0x1000,data:unchecked((uint)dx));break;default:throw new InvalidOperationException("computer_input_invalid");}return new{posted=true};}
 static N.HOOK? keyboard,mouse;
 static void Watch(JsonObject target){Target(target,true);keyboard=(code,w,l)=>{if(code>=0&&Marshal.PtrToStructure<N.KBD>(l).extra.ToUInt64()!=(ulong)Tag)Output(new{@event="user-input"});return N.CallNextHookEx(IntPtr.Zero,code,w,l);};mouse=(code,w,l)=>{if(code>=0&&Marshal.PtrToStructure<N.MS>(l).extra.ToUInt64()!=(ulong)Tag)Output(new{@event="user-input"});return N.CallNextHookEx(IntPtr.Zero,code,w,l);};var kh=N.SetWindowsHookEx(13,keyboard,IntPtr.Zero,0);var mh=N.SetWindowsHookEx(14,mouse,IntPtr.Zero,0);if(kh==IntPtr.Zero||mh==IntPtr.Zero){if(kh!=IntPtr.Zero)N.UnhookWindowsHookEx(kh);if(mh!=IntPtr.Zero)N.UnhookWindowsHookEx(mh);throw new InvalidOperationException("computer_monitor_required");}var thread=N.GetCurrentThreadId();using var timer=new System.Windows.Forms.Timer{Interval=100};timer.Tick+=(_,_)=>{if(Locked())Output(new{@event="locked"});else try{Target(target,true);}catch{Output(new{@event="target-changed"});}};timer.Start();Task.Run(()=>{while(Console.ReadLine()!=null){}N.PostThreadMessage(thread,0x12,UIntPtr.Zero,IntPtr.Zero);});Output(new{ready=true});try{System.Windows.Forms.Application.Run();}finally{N.UnhookWindowsHookEx(kh);N.UnhookWindowsHookEx(mh);}}
 [STAThread]static void Main(){try{var line=Console.ReadLine();if(line==null||line.Length>64*1024)throw new InvalidOperationException("computer_protocol_invalid");var request=JsonNode.Parse(line)!.AsObject();var operation=S(request,"operation");if(operation=="watch"){Watch(request["target"]!.AsObject());return;}object value=operation switch{"status"=>Status(),"targets"=>Targets(),"validate"=>Validate(request),"focus"=>Focus(request["target"]!.AsObject()),"inspect"=>Inspect(request["target"]!.AsObject()),"capture"=>Capture(request["target"]!.AsObject()),"act"=>Act(request),_=>throw new InvalidOperationException("computer_protocol_invalid")};Output(new{ok=true,result=value});}catch(Exception error){var code=error.Message.StartsWith("computer_")?error.Message:"computer_native_failed";Output(new{ok=false,code,message="Native computer operation could not be completed"});}}
 static object Validate(JsonObject request){Target(request["target"]!.AsObject(),request["foreground"]?.GetValue<bool>()??false);return new{valid=true};}
 static class N{
 [StructLayout(LayoutKind.Sequential)]public struct RECT{public int Left,Top,Right,Bottom;}
 [StructLayout(LayoutKind.Sequential)]public struct POINT{public int X,Y;}
 [StructLayout(LayoutKind.Sequential)]public struct MOUSE{public int dx,dy;public uint data,flags,time;public UIntPtr extra;}
 [StructLayout(LayoutKind.Sequential)]public struct KEY{public ushort vk,scan;public uint flags,time;public UIntPtr extra;}
 [StructLayout(LayoutKind.Explicit)]public struct UNION{[FieldOffset(0)]public MOUSE mouse;[FieldOffset(0)]public KEY key;}
 [StructLayout(LayoutKind.Sequential)]public struct INPUT{public uint type;public UNION U;}
 [StructLayout(LayoutKind.Sequential)]public struct KBD{public uint vk,scan,flags,time;public UIntPtr extra;}
 [StructLayout(LayoutKind.Sequential)]public struct MS{public POINT point;public uint data,flags,time;public UIntPtr extra;}
 public delegate bool ENUM(IntPtr h,IntPtr l);public delegate IntPtr HOOK(int code,IntPtr w,IntPtr l);
 [DllImport("user32.dll")]public static extern bool EnumWindows(ENUM f,IntPtr l);[DllImport("user32.dll")]public static extern bool IsWindow(IntPtr h);[DllImport("user32.dll")]public static extern bool IsWindowVisible(IntPtr h);
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]public static extern int GetWindowText(IntPtr h,System.Text.StringBuilder b,int n);[DllImport("user32.dll")]public static extern int GetWindowTextLength(IntPtr h);[DllImport("user32.dll")]public static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);[DllImport("user32.dll")]public static extern IntPtr GetForegroundWindow();[DllImport("user32.dll")]public static extern bool SetForegroundWindow(IntPtr window);[DllImport("user32.dll")]public static extern bool GetWindowRect(IntPtr h,out RECT r);[DllImport("user32.dll")]public static extern bool PrintWindow(IntPtr h,IntPtr dc,uint flags);[DllImport("user32.dll")]public static extern uint SendInput(uint count,INPUT[] input,int size);[DllImport("user32.dll")]public static extern int GetSystemMetrics(int index);
 [DllImport("user32.dll")]public static extern IntPtr OpenInputDesktop(uint flags,bool inherit,uint access);[DllImport("user32.dll",CharSet=CharSet.Unicode)]public static extern bool GetUserObjectInformation(IntPtr d,int index,System.Text.StringBuilder name,uint length,out uint needed);[DllImport("user32.dll")]public static extern bool CloseDesktop(IntPtr d);
 [DllImport("user32.dll")]public static extern IntPtr SetWindowsHookEx(int id,HOOK proc,IntPtr module,uint thread);[DllImport("user32.dll")]public static extern bool UnhookWindowsHookEx(IntPtr h);[DllImport("user32.dll")]public static extern IntPtr CallNextHookEx(IntPtr h,int code,IntPtr w,IntPtr l);[DllImport("kernel32.dll")]public static extern uint GetCurrentThreadId();[DllImport("user32.dll")]public static extern bool PostThreadMessage(uint thread,uint message,UIntPtr w,IntPtr l);
 }
}
