import {describe,expect,it,vi} from "vitest";
import {readFile} from "node:fs/promises";
import {createHash} from "node:crypto";
import {TraceGraphClient} from "./index.js";
const hash=(bytes:string|Uint8Array)=>"sha256:"+createHash("sha256").update(bytes).digest("hex");
const response=(value:unknown)=>new Response(JSON.stringify(value),{headers:{"content-type":"application/json"}});
describe("typed file/feedback SDK scope and byte integrity",()=>{
 it("validates actual UTF8 and base64 PNG bytes rather than trusting response metadata",async()=>{const png=await readFile(new URL("../../../apps/desktop/build/Outlive.iconset/icon_128x128.png",import.meta.url));let value:unknown={project_id:"project:one",path:"image.png",kind:"binary",sha256:hash(png),byte_length:png.length,image:{media_type:"image/png",data_base64:png.toString("base64"),width:128,height:128}};const client=new TraceGraphClient({token:"fixture",fetch:vi.fn(async()=>response(value))});expect((await client.readProjectFile("project:one",{path:"image.png"})).image?.data_base64).toBe(png.toString("base64"));for(const bad of [{...value as object,sha256:hash("false hash")},{...value as object,byte_length:1},{...value as object,project_id:"project:foreign"},{...value as object,path:"another.png"}]){value=bad;await expect(client.readProjectFile("project:one",{path:"image.png"})).rejects.toThrow();}value={project_id:"project:one",path:"file.txt",kind:"text",sha256:hash("with BOM\ufeff"),byte_length:12,content:"different text"};await expect(client.readProjectFile("project:one",{path:"file.txt"})).rejects.toThrow(/integrity/);});
 it("checks save and feedback receipts and never retries a failed mutation",async()=>{const input={command_id:"command:save",path:"file.txt",expected_sha256:hash("before"),content:"after"};let value:unknown={project_id:"project",command_id:input.command_id,path:input.path,expected_sha256:input.expected_sha256,content_sha256:hash("after"),actual_sha256:hash("after"),status:"succeeded",code:"file_saved",receipt_event_id:"event:receipt"};const transport=vi.fn(async()=>response(value));const client=new TraceGraphClient({token:"fixture",fetch:transport});expect(await client.saveProjectFile("project",input)).toMatchObject({status:"succeeded"});value={...value as object,content_sha256:hash("another intent"),actual_sha256:hash("another intent")};await expect(client.saveProjectFile("project",input)).rejects.toThrow(/bound intent/);value={run_id:"run:foreign",answer_event_id:"answer",value:"like",receipt_event_id:"receipt"};await expect(client.setAnswerFeedback("run:one",{command_id:"feedback",answer_event_id:"answer",value:"like"})).rejects.toThrow();const unavailable=vi.fn(async()=>{throw new TypeError("fixture connection dropped");});const offline=new TraceGraphClient({token:"fixture",fetch:unavailable});await expect(offline.saveProjectFile("project",input)).rejects.toThrow();expect(unavailable).toHaveBeenCalledTimes(1);});
});
