import {createHash} from "node:crypto";
import {describe,expect,it,vi} from "vitest";
import {TraceGraphClient} from "./index.js";
const body="Local private instruction",sha="sha256:"+createHash("sha256").update(body).digest("hex"),scope={kind:"global" as const};
const response=(value:unknown)=>new Response(JSON.stringify(value),{headers:{"content-type":"application/json"}});
describe("scoped local Skill SDK",()=>{
 it("checks returned scope, UTF-8 byte length and SHA rather than trusting a document response",async()=>{let value:unknown={scope,name:"review",sha256:sha,byte_length:Buffer.byteLength(body),enabled:true,removed:false,diagnostics:[],content:body};const fetch=vi.fn(async()=>response(value)),client=new TraceGraphClient({token:"fixture",fetch});expect((await client.readManagedSkill({scope,name:"review"})).content).toBe(body);for(const change of [{name:"other"},{scope:{kind:"project",project_id:"project:other"}},{content:body+" changed"},{byte_length:1}]){value={scope,name:"review",sha256:sha,byte_length:Buffer.byteLength(body),enabled:true,removed:false,diagnostics:[],content:body,...change};await expect(client.readManagedSkill({scope,name:"review"})).rejects.toThrow();}});
 it("uses exact command and receipt identity, with no second write after an uncertain response",async()=>{let value:unknown={command_id:"skill:one",scope,name:"review",status:"succeeded",code:"skill_updated",sha256:sha,effective:"new-run"};const fetch=vi.fn(async()=>response(value)),client=new TraceGraphClient({token:"fixture",fetch}),input={type:"create" as const,command_id:"skill:one",scope,name:"review",expected_sha256:null,content:body};expect(await client.managedSkillCommand(input)).toMatchObject({command_id:"skill:one"});expect(String(fetch.mock.calls[0]![0])).toContain("/api/workbench/skills/commands");value={...value as object,command_id:"skill:other"};await expect(client.managedSkillCommand(input)).rejects.toThrow(/intent/);value={command_id:"skill:other",state:"unknown",observed_sha256:sha};await expect(client.getManagedSkillCommandReceipt(input.command_id)).rejects.toThrow(/different command/);const dropped=vi.fn(async()=>{throw new TypeError("Dropped mutation response");}),uncertain=new TraceGraphClient({token:"fixture",fetch:dropped});await expect(uncertain.managedSkillCommand(input)).rejects.toThrow();expect(dropped).toHaveBeenCalledOnce();});
});
