import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {GoalBudgetSnapshotSchema,ObservationSchema,type ArtifactRef,type SessionEvent} from "@tracegraph/contracts";
import {JsonlEventLedger} from "../evidence/event-ledger.js";
import {DeterministicContextBuilder as ContextBuilder} from "../context/runtime-service.js";
import {DeliveryReviewOptionsSchema,deliveryRequirementPacket,recoveredDeliveryBudget,validateRequirementPacketReads,validateRequirementPacketWindow} from "./delivery-review.js";
import {SharedRunBudget} from "./shared-run-budget.js";
import {sha256} from "../../kernel/crypto.js";
const roots:string[]=[];afterEach(async()=>{for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
const now=new Date("2026-10-05T00:00:00Z"),config=DeliveryReviewOptionsSchema.parse({ordinaryBudget:{max_tokens:1000,max_time_ms:10000}});
async function fixture(){const root=await mkdtemp(join(tmpdir(),"outlive-continuation-safety-"));roots.push(root);const ledger=new JsonlEventLedger(root,{now:()=>now});await ledger.initialize();return{ledger,append:(data:Record<string,unknown>,type:SessionEvent["type"]="workbench.command_completed")=>ledger.append({project_id:"project:guard",run_id:"run:guard",type,summary:"Controlled canonical fixture fact",attempt:0,artifact_refs:[],data})};}
function budget(extra:Record<string,unknown>={}){return GoalBudgetSnapshotSchema.parse({limits:config.ordinaryBudget,charged_tokens:30,held_tokens:0,held_request_count:0,reported_input_tokens:20,reported_output_tokens:10,elapsed_ms:100,request_count:1,unknown_request_count:0,stop_reason:null,...extra});}
describe("canonical software recovery fences",()=>{
 it("conserves every canonical charge and accounts for downtime, never creates another ceiling",async()=>{const f=await fixture();await f.append({operation:"delivery.budget_admitted",budget_id:"delivery:run:guard",budget_snapshot:budget()});await f.append({operation:"delivery.budget_settled",budget_id:"delivery:run:guard",budget_checkpoint:{snapshot:budget({charged_tokens:80,request_count:2,elapsed_ms:400})}});expect(recoveredDeliveryBudget(await f.ledger.list("run:guard"),"delivery:run:guard",config,new Date(now.getTime()+1500))).toMatchObject({charged_tokens:80,elapsed_ms:1900,request_count:2,limits:config.ordinaryBudget});});
 it.each([{held_tokens:20,held_request_count:1},{unknown_request_count:1,stop_reason:"usage_unknown"},{stop_reason:"persistence_failed"}])("blocks unresolved reservations/outcomes %j",async extra=>{const f=await fixture();await f.append({operation:"delivery.budget_admitted",budget_id:"delivery:run:guard",budget_snapshot:budget(extra)});const events=await f.ledger.list("run:guard");expect(()=>recoveredDeliveryBudget(events,"delivery:run:guard",config,now)).toThrow(expect.objectContaining({code:"delivery_budget_reconciliation_required"}));});
 it.each([{charged_tokens:1000},{elapsed_ms:10000},{stop_reason:"paused"}])("cannot renew a stopped or exhausted allowance %j",async extra=>{const f=await fixture();await f.append({operation:"delivery.budget_admitted",budget_id:"delivery:run:guard",budget_snapshot:budget(extra)});const events=await f.ledger.list("run:guard");expect(()=>recoveredDeliveryBudget(events,"delivery:run:guard",config,now)).toThrow(expect.objectContaining({code:"delivery_budget_exhausted"}));});
 it("rejects a charge rollback or altered limit in later canonical facts",async()=>{const f=await fixture();await f.append({operation:"delivery.budget_admitted",budget_id:"delivery:run:guard",budget_snapshot:budget({charged_tokens:50})});await f.append({operation:"delivery.budget_restored",budget_id:"delivery:run:guard",budget_snapshot:budget({charged_tokens:20})});const events=await f.ledger.list("run:guard");expect(()=>recoveredDeliveryBudget(events,"delivery:run:guard",config,now)).toThrow(expect.objectContaining({code:"delivery_budget_recovery_corrupt"}));expect(()=>recoveredDeliveryBudget(events,"delivery:run:guard",DeliveryReviewOptionsSchema.parse({ordinaryBudget:{max_tokens:2000,max_time_ms:10000}}),now)).toThrow(expect.objectContaining({code:"delivery_budget_recovery_corrupt"}));});
 it("includes the complete task, consumed public guidance, approved Goal conditions and more than ten verification references",async()=>{const f=await fixture();await f.append({task:"original"},"run.created");const queued=await f.append({input:{input_id:"input:guidance",body:"PUBLIC_REQUIRED_GUIDANCE"}},"user.input_queued");await f.append({kind:"steer",queued_event_id:queued.event_id},"user.input_consumed");for(let i=0;i<12;i++)await f.append({receipt:{tool_name:"run_project_command",code:"project_command_passed"},observation:{facts:{path:"outlive.commands.json",command:`verify${i}`}}},"tool.completed");const packet=JSON.parse(deliveryRequirementPacket({projectId:"project:guard",runId:"run:guard",task:"x".repeat(4200)+"MANDATORY_TAIL",history:[{role:"user",content:"PUBLIC_CONTEXT"}],events:await f.ledger.list("run:guard"),goal:{goal_id:"goal:guard",approved_proposal_revision:7,objective:"Approved objective",done_conditions:["ACTUAL_DONE_CONDITION"]}}));expect(packet.initial_task).toContain("MANDATORY_TAIL");expect(packet.consumed_guidance[0].body).toBe("PUBLIC_REQUIRED_GUIDANCE");expect(packet.verification_receipts).toHaveLength(12);expect(packet.approved_goal).toMatchObject({approved_proposal_revision:7,done_conditions:["ACTUAL_DONE_CONDITION"]});expect(JSON.stringify(packet)).not.toContain("private_reasoning");});
 it("fails an oversized complete packet instead of truncating its last requirements",async()=>{const f=await fixture();await f.append({},"run.created");const events=await f.ledger.list("run:guard");expect(()=>deliveryRequirementPacket({projectId:"project:guard",runId:"run:guard",task:"Scope",history:Array.from({length:10},()=>({role:"user" as const,content:"x".repeat(4000)})),events})).toThrow(expect.objectContaining({code:"delivery_requirements_limit"}));});
 it("requires every packet byte both read and retained in the exact final model window",async()=>{const f=await fixture(),content="Complete approved public requirement.";const ref:ArtifactRef={artifact_id:"artifact:requirements",kind:"context_source_archive",project_id:"project:guard",run_id:"run:guard",content_hash:sha256(content),byte_length:Buffer.byteLength(content),mime_type:"application/json",created_at:now.toISOString()};const observation=ObservationSchema.parse({observation_id:"observation:packet",action_id:"action:read",receipt_id:"receipt:packet",status:"success",summary:"Actual scoped packet read",facts:{artifact_id:ref.artifact_id,content_hash:ref.content_hash,total_bytes:ref.byte_length,offset:0,bytes_read:ref.byte_length,content_excerpt:content},artifact_refs:[ref],created_at:now.toISOString()});await f.append({receipt:{tool_name:"read_artifact"},observation},"tool.completed");const events=await f.ledger.list("run:guard"),built=new ContextBuilder().build({projectId:ref.project_id,runId:ref.run_id,turnId:"turn:review",modelCallId:"model:review",task:"Readonly review",workspaceKind:"managed_local",observations:[observation],tokenLimit:12000,reservedOutputTokens:1000});expect(()=>validateRequirementPacketReads(events,ref)).not.toThrow();expect(()=>validateRequirementPacketWindow(events,ref,built.manifest)).not.toThrow();for(const action of ["externalized","truncated","masked"] as const){const manifest={...built.manifest,items:built.manifest.items.map(item=>item.source.source_id===observation.receipt_id?{...item,action}:item)};expect(()=>validateRequirementPacketWindow(events,ref,manifest)).toThrow(expect.objectContaining({code:"delivery_requirements_window"}));}const zeroTokenManifest={...built.manifest,items:built.manifest.items.map(item=>item.source.source_id===observation.receipt_id?{...item,included_tokens:0,original_tokens:0}:item)};expect(()=>validateRequirementPacketWindow(events,ref,zeroTokenManifest)).toThrow(expect.objectContaining({code:"delivery_requirements_window"}));expect(()=>validateRequirementPacketReads(events,{...ref,byte_length:ref.byte_length+1})).toThrow(expect.objectContaining({code:"delivery_requirements_unread"}));});
 it("freezes trusted Goal conditions before the first model dispatch",()=>{const budget=new SharedRunBudget({identity:"goal:requirements",limits:{max_tokens:1000},deliveryRequirements:{goal_id:"goal:requirements",approved_proposal_revision:1,objective:"Approved",done_conditions:["Immutable condition"]},checkpoint:async()=>undefined});try{expect(()=>budget.deliveryRequirements!.done_conditions.push("UNAUTHORIZED_MUTATION")).toThrow();expect(budget.deliveryRequirements?.done_conditions).toEqual(["Immutable condition"]);}finally{budget.dispose();}});
});
