import {cp,mkdir,mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {BUILTIN_PERMISSION_PRESETS,type EffectivePermissionPolicy,type ToolName} from "@tracegraph/contracts";
import {createManagedWorkspaceHandle} from "../../kernel/workspace.js";
import type {ModelAdapter,ModelInput} from "../../kernel/types.js";
import {createEffectivePermissionPolicy} from "../tools/policy-engine.js";
import {SubagentRegistry} from "../subagent/subagent.js";
import type {SubagentWorkspaceResolver} from "../subagent/workspace.js";
import {JsonlSessionStore} from "../session/session-store.js";
import {createAgentRuntime,type AgentRuntime} from "./runtime.js";
const roots:string[]=[],runtimes:AgentRuntime[]=[];
afterEach(async()=>{for(const runtime of runtimes.splice(0)){await runtime.shutdownRuns?.();await runtime.shutdownBackgroundWork?.();}for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
const finish={decision_id:"finish",kind:"finish",public_reason:"Scoped result prepared",evidence_refs:[],risk:"none",final_answer:"Scoped result"};
const spawn={decision_id:"spawn",kind:"tool_call",public_reason:"Delegate a bounded child",evidence_refs:[],risk:"low",tool_call:{action_id:"spawn:write",tool_name:"spawn_subagent",arguments:{profile_name:"writer",task_packet:{task:"Scoped edit"},context_scope:"isolated"}}};
async function fixture(){const root=await mkdtemp(join(tmpdir(),"outlive-core-child-workspace-"));roots.push(root);const source=join(root,"source"),child=join(root,"child");await mkdir(source);await mkdir(child);for(const path of [source,child])await writeFile(join(path,"value.txt"),"BEFORE\n");return {root,workspace:await createManagedWorkspaceHandle({projectId:"p",root:source}),child:await createManagedWorkspaceHandle({projectId:"p",root:child})};}
const full=createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"]});
const binding={binding_id:"child:core-fixture",baseline_digest:`sha256:${"0".repeat(64)}`,source_head:"0".repeat(40),source_index_hash:`sha256:${"1".repeat(64)}`,source_tree_hash:`sha256:${"2".repeat(64)}`};
function registry(model:ModelAdapter,tools:ToolName[]=["read_file","preview_patch","commit_patch","discover_project_commands","run_project_command"]){return new SubagentRegistry([{name:"writer",providerKey:"parent",model,rolePromptVersion:"fixture.v1",rolePrompt:"Trusted writer",toolAllowlist:tools,defaultBudget:{max_steps:4,max_tokens:16_000},budgetCeiling:{max_steps:4,max_tokens:16_000}}]);}
async function wait(runtime:AgentRuntime,id:string,status="terminal"){const deadline=Date.now()+5_000;while(Date.now()<deadline){const projection=await runtime.getProjection(id).catch(error=>{if(error.code==="run_not_found")return undefined;throw error;});if(projection&&(projection.status===status||status==="terminal"&&["completed","failed","cancelled"].includes(projection.status)))return projection;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error("Controlled Run did not reach "+status);}
describe("Core trusted write-child boundary",()=>{
 it("keeps an empty trusted catalog safe and denies unknown roles without child creation",async()=>{const f=await fixture();const inputs:ModelInput[]=[];let calls=0;const model:ModelAdapter={name:"empty-catalog",async decide(input){inputs.push(input);return calls++===0?spawn:finish;}};const runtime=await createAgentRuntime({dataDir:join(f.root,"data"),model,permissionPolicy:full,subagentRegistry:new SubagentRegistry([])});runtimes.push(runtime);const started=await runtime.startRun({command_id:"empty:catalog",project_id:"p",workspace:f.workspace,mode:"execute",task:"No compiled roles"});const completed=await wait(runtime,started.run_id);expect(completed.subagents.items).toEqual([]);const descriptor=inputs[0]!.toolSchemas.find(tool=>tool.name==="spawn_subagent")!;expect(descriptor.description).toContain("none (spawning is unavailable)");expect((descriptor.input_schema.properties as Record<string,unknown>).profile_name).toEqual({type:"string"});expect(JSON.stringify(completed.timeline)).toContain("Unknown subagent profile");});

 it.each(["patch","execute"])("requires a resolver for an actual %s-capable trusted role before any child exists",async kind=>{const f=await fixture();let children=0,calls=0;const child:ModelAdapter={name:"child",async decide(){children++;return finish;}};const parent:ModelAdapter={name:"parent",async decide(){return calls++===0?spawn:finish;}};const runtime=await createAgentRuntime({dataDir:join(f.root,"data"),model:parent,permissionPolicy:full,subagentRegistry:registry(child,kind==="execute"?["run_project_command"]:["commit_patch"])});runtimes.push(runtime);const created=await runtime.startRun({command_id:"write:no-resolver",project_id:"p",workspace:f.workspace,mode:"execute",task:"Require isolation"});const completed=await wait(runtime,created.run_id);expect(children).toBe(0);expect(completed.subagents.items).toEqual([]);expect(JSON.stringify(completed.timeline)).toContain("trusted isolated workspace");expect(await readFile(join(f.workspace.real_root,"value.txt"),"utf8")).toBe("BEFORE\n");});
 it("rejects widened resolver authority and releases its lease before recording any child start",async()=>{const f=await fixture();let released=0,calls=0;const parent:ModelAdapter={name:"parent",decide:async()=>calls++===0?spawn:finish};const resolver:SubagentWorkspaceResolver=async()=>({workspace:f.child,permissionPolicy:full,binding,release(){released++;}});const runtime=await createAgentRuntime({dataDir:join(f.root,"data"),model:parent,permissionPolicy:full,subagentRegistry:registry({name:"unused",decide:async()=>finish}),subagentWorkspaceResolver:resolver});runtimes.push(runtime);const created=await runtime.startRun({command_id:"write:widen",project_id:"p",workspace:f.workspace,mode:"execute",task:"Do not widen"});const completed=await wait(runtime,created.run_id);expect(released).toBe(1);expect(completed.subagents.items).toEqual([]);expect(JSON.stringify(completed.timeline)).toContain("exceeds or escapes");});
 it("keeps parent command-tool exclusions in child model schemas and rejects a forged command without dispatch",async()=>{const f=await fixture();const inputs:ModelInput[]=[];let calls=0,released=0;const policy=createEffectivePermissionPolicy({preset:{...BUILTIN_PERMISSION_PRESETS["full-write"],key:"custom",allowed_tools:BUILTIN_PERMISSION_PRESETS["full-write"].allowed_tools.filter(name=>name!=="run_project_command"&&name!=="discover_project_commands")}});const narrow=createEffectivePermissionPolicy({preset:{...policy.preset,sandbox_mode:"workspace-write"}});const child:ModelAdapter={name:"forged-execution",async decide(input){inputs.push(input);return {decision_id:"forged",kind:"tool_call",public_reason:"Try an unavailable command",evidence_refs:[],risk:"low",tool_call:{action_id:"forged:command",tool_name:"run_project_command",arguments:{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:`sha256:${"0".repeat(64)}`}}};}};const parent:ModelAdapter={name:"parent",decide:async()=>calls++===0?spawn:finish};const runtime=await createAgentRuntime({dataDir:join(f.root,"data"),model:parent,permissionPolicy:policy,subagentRegistry:registry(child),subagentWorkspaceResolver:async()=>({workspace:f.child,permissionPolicy:narrow,binding,release(){released++;}})});runtimes.push(runtime);const created=await runtime.startRun({command_id:"write:excluded-command",project_id:"p",workspace:f.workspace,mode:"execute",task:"Keep parent scope"});const completed=await wait(runtime,created.run_id);expect(inputs).toHaveLength(1);expect(inputs[0]!.toolSchemas.map(tool=>tool.name)).not.toContain("run_project_command");expect(inputs[0]!.toolSchemas.map(tool=>tool.name)).not.toContain("discover_project_commands");const childRun=await runtime.getProjection(completed.subagents.items[0]!.link.child_run_id);expect(childRun.status).toBe("failed");expect(childRun.timeline.some(event=>event.type==="tool.started"&&event.data.tool_name==="run_project_command")).toBe(false);expect(await readFile(join(f.child.real_root,"value.txt"),"utf8")).toBe("BEFORE\n");expect(released).toBe(1);});
 it("does not restore a retained writable child into the parent root or redispatch its pending patch",async()=>{const f=await fixture();let parentCalls=0,childCalls=0;const parent:ModelAdapter={name:"parent",decide:async()=>parentCalls++===0?spawn:finish};const child:ModelAdapter={name:"pending-child",async decide(){childCalls++;return {decision_id:"preview",kind:"tool_call",public_reason:"Preview a scoped edit",evidence_refs:[],risk:"low",tool_call:{action_id:"preview",tool_name:"preview_patch",arguments:{path:"value.txt",expected:"BEFORE",replacement:"AFTER"}}};}};const parentPolicy=createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["workspace-write"]});const resolver:SubagentWorkspaceResolver=async()=>({workspace:f.child,permissionPolicy:parentPolicy,binding,release(){}});const sessionDir=join(f.root,"sessions");const first=await createAgentRuntime({dataDir:join(f.root,"data"),model:parent,sessionStore:new JsonlSessionStore(sessionDir,{pid:2147483646}),permissionPolicy:parentPolicy,subagentRegistry:registry(child),subagentWorkspaceResolver:resolver});runtimes.push(first);const created=await first.startRun({command_id:"write:recovery",project_id:"p",workspace:f.workspace,mode:"execute",task:"Retain pending work"});let childId:string|undefined;while(!childId){childId=(await first.getProjection(created.run_id)).subagents.items[0]?.link.child_run_id;await new Promise(resolve=>setTimeout(resolve,5));}const waiting=await wait(first,childId,"awaiting_approval");const recoveredData=join(f.root,"recovered-data"),recoveredSessions=join(f.root,"recovered-sessions");await cp(join(f.root,"data"),recoveredData,{recursive:true});await cp(sessionDir,recoveredSessions,{recursive:true});const recovered=await createAgentRuntime({dataDir:recoveredData,model:parent,sessionStore:new JsonlSessionStore(recoveredSessions),permissionPolicy:parentPolicy});runtimes.push(recovered);const locator={runId:childId,sessionId:waiting.session_id!,projectId:"p"};await recovered.markRunInterrupted(locator);await expect(recovered.resumeRun({...locator,commandId:"write:resume-denied",workspace:f.workspace})).rejects.toMatchObject({code:"subagent_workspace_review_required"});expect(childCalls).toBe(1);expect(await readFile(join(f.workspace.real_root,"value.txt"),"utf8")).toBe("BEFORE\n");expect(await readFile(join(f.child.real_root,"value.txt"),"utf8")).toBe("BEFORE\n");});
});
