import {createServer,type Server} from "node:http";
import {mkdtemp,mkdir,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {createAgentRuntime,type AgentRuntime} from "./runtime.js";
import {SharedRunBudget,type BudgetCheckpoint} from "./shared-run-budget.js";
import {ConfigurableModelAdapter} from "../model/model-provider.js";
import {SubagentRegistry} from "../subagent/subagent.js";
import {createManagedWorkspaceHandle} from "../../kernel/workspace.js";
import {createEffectivePermissionPolicy} from "../tools/policy-engine.js";
import {BUILTIN_PERMISSION_PRESETS,type RunProjection} from "@tracegraph/contracts";
const roots:string[]=[],runtimes:AgentRuntime[]=[],servers:Server[]=[],budgets:SharedRunBudget[]=[];
afterEach(async()=>{for(const runtime of runtimes.splice(0)){await runtime.shutdownRuns?.();await runtime.shutdownBackgroundWork?.();}for(const budget of budgets.splice(0))budget.dispose();for(const server of servers.splice(0)){server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
const answer={decision_id:"decision:budget-answer",kind:"finish",finish_intent:"answer",public_reason:"Recorded actual result",evidence_refs:[],risk:"none",final_answer:"Controlled actual result"};
async function fixture(){const root=await mkdtemp(join(tmpdir(),"outlive-budget-tree-"));roots.push(root);const dir=join(root,"project");await mkdir(dir);return {root,workspace:await createManagedWorkspaceHandle({projectId:"project:budget-tree",root:dir})};}
async function wait(runtime:AgentRuntime,id:string,status:RunProjection["status"]){const deadline=Date.now()+5_000;while(Date.now()<deadline){const value=await runtime.getProjection(id);if(value.status===status)return value;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error(`Run did not become ${status}: ${(await runtime.getProjection(id)).status}`);}
describe("trusted aggregate budget through real Run and child boundaries",()=>{
 it("shares one lease with an actual child provider and all scoped canonical Run facts",async()=>{const f=await fixture();let parentCalls=0,childCalls=0;const server=createServer(async(req,res)=>{const chunks:Buffer[]=[];for await(const part of req)chunks.push(Buffer.from(part));const input=JSON.parse(Buffer.concat(chunks).toString()) as {messages:Array<{content:string}>};const child=input.messages.some(message=>typeof message.content==="string"&&message.content.includes("BUDGET_WORKER_ROLE"));if(child)childCalls++;else parentCalls++;
  const decision=!child&&parentCalls===1?{decision_id:"decision:spawn-budget",kind:"tool_call",public_reason:"Delegate scoped read-only review",evidence_refs:[],risk:"low",tool_call:{action_id:"action:spawn-budget",tool_name:"spawn_subagent",arguments:{profile_name:"worker",task_packet:{task:"Review a bounded fact"},context_scope:"isolated"}}}:answer;
  res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(decision)}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));});servers.push(server);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error();const model=new ConfigurableModelAdapter({resolveCredential:async()=>"isolated-budget-tree-key"});model.configure({provider:"custom",protocol:"openai-chat-completions",baseUrl:`http://127.0.0.1:${address.port}/v1`,model:"fixture-tree",credentialRef:"${secret:ISOLATED_TREE_KEY}"});
  const runtime=await createAgentRuntime({dataDir:join(f.root,"data"),model,permissionPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"]}),subagentRegistry:new SubagentRegistry([{name:"worker",providerKey:"fixture",rolePromptVersion:"fixture.v1",rolePrompt:"BUDGET_WORKER_ROLE",toolAllowlist:["read_file"],defaultBudget:{max_steps:3,max_tokens:20_000},budgetCeiling:{max_steps:3,max_tokens:20_000},model}])});runtimes.push(runtime);const events:BudgetCheckpoint[]=[];const budget=new SharedRunBudget({identity:"goal:aggregate-tree:1",limits:{max_tokens:100_000,max_time_ms:10_000},checkpoint:async value=>{events.push(value);}});budgets.push(budget);
  const started=await runtime.startRun({command_id:"command:budget-tree",project_id:f.workspace.project_id,workspace:f.workspace,mode:"execute",task:"Delegate this scoped review"},{model,requestBudget:budget,backgroundModelDerivation:false});const completed=await wait(runtime,started.run_id,"completed");expect(parentCalls).toBe(2);expect(childCalls).toBe(1);expect(budget.snapshot()).toMatchObject({charged_tokens:45,held_tokens:0,request_count:3});const child=completed.subagents.items[0]!;const childProjection=await runtime.getProjection(child.link.child_run_id);expect(childProjection.status).toBe("completed");for(const projection of [completed,childProjection])expect(projection.timeline.find(event=>event.type==="run.created")?.data).toMatchObject({goal_budget:budget.identity,background_model_derivation:false});expect(new Set(events.filter(event=>event.phase==="reserved").map(event=>event.run_id))).toEqual(new Set([completed.run_id,child.link.child_run_id]));expect(childProjection.timeline.some(event=>event.type==="model.usage_reported")).toBe(true);await new Promise(resolve=>setTimeout(resolve,100));expect(parentCalls+childCalls).toBe(3);
 });
 it("rejects adapters without a real request boundary before their first invocation",async()=>{const f=await fixture();let calls=0;const model={name:"unsupported-model",async decide(){calls++;return answer;}};const runtime=await createAgentRuntime({dataDir:join(f.root,"data"),model});runtimes.push(runtime);const budget=new SharedRunBudget({identity:"goal:unsupported:1",limits:{max_tokens:100},checkpoint:async()=>undefined});budgets.push(budget);await expect(runtime.startRun({command_id:"command:unsupported",project_id:f.workspace.project_id,workspace:f.workspace,mode:"execute",task:"Do not dispatch"},{model,requestBudget:budget})).rejects.toMatchObject({code:"goal_budget_adapter_unsupported"});expect(calls).toBe(0);expect(budget.snapshot().request_count).toBe(0);});
});
