import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {createServer,type Server} from "node:http";
import {mkdir,mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {BUILTIN_PERMISSION_PRESETS,type RunProjection} from "@tracegraph/contracts";
import {createAgentRuntime,type AgentRuntime} from "./runtime.js";
import {ConfigurableModelAdapter} from "../model/model-provider.js";
import {createEffectivePermissionPolicy} from "../tools/policy-engine.js";
import {createManagedWorkspaceHandle} from "../../kernel/workspace.js";
import {sha256} from "../../kernel/crypto.js";
import {JsonlEventLedger} from "../evidence/event-ledger.js";
import {SharedRunBudget} from "./shared-run-budget.js";
import {NativeSandboxRunner} from "../../seams/sandbox/runner.js";
const roots:string[]=[],runtimes:AgentRuntime[]=[],servers:Server[]=[],budgets:SharedRunBudget[]=[];
afterEach(async()=>{for(const runtime of runtimes.splice(0)){await runtime.shutdownRuns?.();await runtime.shutdownBackgroundWork?.();}for(const budget of budgets.splice(0))budget.dispose();for(const server of servers.splice(0)){server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
const before="export function clamp(value, min, max) { return value; }\n";
const buggy="export function clamp(value, min, max) { if (![value,min,max].every(Number.isFinite)) throw new TypeError('finite required'); return Math.max(min, Math.min(max, value)); }\n";
const fixed="export function clamp(value, min, max) { if (![value,min,max].every(Number.isFinite)) throw new TypeError('finite required'); if (min > max) throw new RangeError('reversed range'); return Math.max(min, Math.min(max, value)); }\n";
const tests="import assert from 'node:assert/strict'; import {clamp} from '../dist/clamp.mjs'; assert.equal(clamp(12,0,10),10); assert.equal(clamp(-1,0,10),0); assert.equal(clamp(4,0,10),4); assert.throws(()=>clamp(NaN,0,10),TypeError); console.log('ACTUAL_CLAMP_TESTS_PASS');\n";
const repairedTests=tests+"assert.throws(()=>clamp(4,10,0),RangeError); console.log('ACTUAL_REVERSED_RANGE_REGRESSION_PASS');\n";
function answer(review_result?:unknown){return{decision_id:"decision:finish",kind:"finish",finish_intent:"answer",public_reason:"Recorded software result",evidence_refs:[],risk:"none",final_answer:"Controlled implementation and real verification recorded; final user acceptance remains separate",...(review_result===undefined?{}:{review_result})};}
let operation=0;
function call(name:string,args:Record<string,unknown>){return{decision_id:`decision:${name}`,kind:"tool_call",public_reason:"Perform the scoped software check",evidence_refs:[],risk:"low",tool_call:{action_id:`action:${name}:${++operation}`,tool_name:name,arguments:args}};}
async function fixture(){const root=await mkdtemp(join(tmpdir(),"outlive-delivery-review-"));roots.push(root);const project=join(root,"project");for(const dir of ["src","test"])await mkdir(join(project,dir),{recursive:true});await writeFile(join(project,"src/clamp.mjs"),before);await writeFile(join(project,"test/clamp.test.mjs"),tests);await writeFile(join(project,"build.mjs"),"import {mkdirSync,copyFileSync} from 'node:fs';mkdirSync('dist',{recursive:true});copyFileSync('src/clamp.mjs','dist/clamp.mjs');console.log('ACTUAL_BUILD_OUTPUT');\n");const manifest=JSON.stringify({version:1,commands:{verify:{executable:"node",args:["verify.mjs"]}}});await writeFile(join(project,"outlive.commands.json"),manifest);await writeFile(join(project,"verify.mjs"),"import {spawnSync} from 'node:child_process';for(const file of ['build.mjs','test/clamp.test.mjs']){const result=spawnSync(process.execPath,[file],{stdio:'inherit'});if(result.status!==0)process.exit(result.status??1);}\n");return{root,project,manifestHash:sha256(manifest),workspace:await createManagedWorkspaceHandle({projectId:"project:delivery",root:project})};}
async function modelFixture(respond:(input:{body:Record<string,unknown>;serialized:string;child:boolean})=>unknown,usage={prompt_tokens:10,completion_tokens:5,total_tokens:15}){let calls=0,childCalls=0;const requests:Array<{child:boolean;body:Record<string,unknown>}>=[];const server=createServer(async(req,res)=>{const chunks:Buffer[]=[];for await(const part of req)chunks.push(Buffer.from(part));const body=JSON.parse(Buffer.concat(chunks).toString()) as Record<string,unknown>,serialized=JSON.stringify(body),child=serialized.includes("You are the independent readonly delivery reviewer");calls++;if(child)childCalls++;requests.push({child,body});let decision;try{decision=await respond({body,serialized,child});}catch(error){res.writeHead(500,{"content-type":"application/json"});res.end(JSON.stringify({error:String(error)}));return;}res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(decision)}}],usage}));});servers.push(server);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error("Fixture address missing");const model=new ConfigurableModelAdapter({resolveCredential:async()=>"controlled-review-key-not-live"});model.configure({provider:"custom",protocol:"openai-chat-completions",baseUrl:`http://127.0.0.1:${address.port}/v1`,model:"delivery-protocol-fixture",credentialRef:"${secret:CONTROLLED_REVIEW_KEY}"});return{model,requests,calls:()=>calls,childCalls:()=>childCalls};}
async function wait(runtime:AgentRuntime,id:string){const deadline=Date.now()+15_000;while(Date.now()<deadline){const value=await runtime.getProjection(id);if(["completed","failed","cancelled"].includes(value.status))return value;await new Promise(resolve=>setTimeout(resolve,10));}throw new Error(`No terminal: ${JSON.stringify((await runtime.getProjection(id)).timeline.slice(-2))}`);}
async function runtimeFixture(f:Awaited<ReturnType<typeof fixture>>,model:NonNullable<Parameters<typeof createAgentRuntime>[0]["model"]>,options:Partial<Parameters<typeof createAgentRuntime>[0]>={}){const runtime=await createAgentRuntime({dataDir:join(f.root,"data"),model,permissionPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"]}),deliveryReview:options.deliveryReview??{maxRounds:2,ordinaryBudget:{max_tokens:200_000,max_time_ms:900_000}},...options});runtimes.push(runtime);return runtime;}
const input=(f:Awaited<ReturnType<typeof fixture>>)=>({command_id:"command:delivery",project_id:f.workspace.project_id,workspace:f.workspace,mode:"execute" as const,task:"Implement a finite-number clamp library. Bounds must be ordered; reversed bounds must throw RangeError. Build the delivered module and test normal, non-finite and reversed-range behavior."});
function reviewReads(body:Record<string,unknown>){
 const strings:string[]=[];const collect=(value:unknown):void=>{if(typeof value==="string"){strings.push(value);try{collect(JSON.parse(value));}catch{}}else if(Array.isArray(value))value.forEach(collect);else if(value&&typeof value==="object")Object.values(value).forEach(collect);};collect(body);const text=strings.join("\n");
 const match=/"kind"\s*:\s*"delivery_requirements"[\s\S]*?"locator"\s*:\s*"([^"]+)"/.exec(text);
 if(!match)throw new Error("Actual scoped delivery packet observation missing");
 return{decision_id:"decision:review-reads",kind:"tool_call",public_reason:"Read complete public requirements and source independently",evidence_refs:[],risk:"none",tool_calls:[{action_id:"review:requirements",tool_name:"read_artifact",arguments:{locator:match[1],offset:0,limit:4000}},...["src/clamp.mjs","outlive.commands.json","test/clamp.test.mjs"].map((path,index)=>({action_id:`review:read:${index}`,tool_name:"read_file",arguments:{path}}))]};
}
const passed={verdict:"passed",reviewed_paths:["src/clamp.mjs","outlive.commands.json","test/clamp.test.mjs"],findings:[]};
async function saveProof(f:Awaited<ReturnType<typeof fixture>>,runtime:AgentRuntime,run:RunProjection,requests:number,edgeStderr:string){
 const directory=process.env.OUTLIVE_DELIVERY_EVIDENCE_ROOT;if(!directory)return;
 await mkdir(directory,{recursive:true});
 const ledger=new JsonlEventLedger(join(f.root,"data/events"));await ledger.initialize();
 const runIds=[run.run_id,...run.subagents.items.map(child=>child.link.child_run_id)];
 const events=Object.fromEntries(await Promise.all(runIds.map(async id=>[id,await ledger.list(id)] as const)));
 const files:Record<string,string>={};
 for(const path of ["src/clamp.mjs","dist/clamp.mjs","test/clamp.test.mjs","outlive.commands.json","build.mjs","verify.mjs"]){const bytes=await readFile(join(f.project,path));await mkdir(join(directory,"delivered",path,".."),{recursive:true});await writeFile(join(directory,"delivered",path),bytes);files[path]=sha256(bytes);}
 const commands=run.timeline.filter(event=>["tool.completed","tool.failed"].includes(event.type)&&(event.data.receipt as {tool_name?:unknown})?.tool_name==="run_project_command");
 const outputs=[];for(const [index,event] of commands.entries()){const ref=event.artifact_refs[0]!,artifact=await runtime.getArtifact({artifactId:ref.artifact_id,projectId:run.project_id,runId:run.run_id});if(artifact.status!=="available")throw new Error("Actual command output missing");const path=`command-${index+1}.json`;await writeFile(join(directory,path),artifact.content);outputs.push({path,sha256:sha256(artifact.content),artifact_ref:ref,event_id:event.event_id,event_type:event.type,business_status:(event.data.receipt as {business_status:string}).business_status});}
 await writeFile(join(directory,"edge-before-repair.stderr.txt"),edgeStderr);
 await writeFile(join(directory,"canonical-events.json"),JSON.stringify(events,null,2)+"\n");
 await writeFile(join(directory,"proof.json"),JSON.stringify({status:"passed",scope:"controlled-real-disk-runtime-protocol",provider:"local deterministic HTTP fixture, not a paid model",project_id:run.project_id,run_id:run.run_id,child_run_ids:runIds.slice(1),request_count:requests,original_internal_phase_limit:3,phase_checkpoints:run.timeline.filter(event=>event.data.operation==="delivery.turn_checkpoint").map(event=>event.data.turns_completed),review_verdicts:run.timeline.filter(event=>event.data.operation==="delivery.review_completed").map(event=>(event.data.review_result as {verdict:string}).verdict),independent_external_edge_regression_before_repair:{exit_code:1,expected_error:"Missing expected exception (RangeError)",stderr_path:"edge-before-repair.stderr.txt",stderr_sha256:sha256(edgeStderr),outside_agent_authority:true},files,outputs,budget:run.timeline.at(-1)?.data.delivery_budget,no_default_profile:true,no_paid_requests:true,no_git_commit_merge_or_push:true,full_software_quality_claim:false},null,2)+"\n");
}
describe("independent finite-budget software delivery",()=>{
 it("implements actual files, builds/tests, finds a real omitted requirement, repairs and independently reviews again",async()=>{
  const f=await fixture();let rootStep=0,reviewStep=0;let actualEdgeFailure=false,actualEdgeStderr="";const provider=await modelFixture(async({child,serialized,body})=>{
   if(child){if(++reviewStep%2===1)return reviewReads(body);const correct=serialized.includes("if (min > max)");if(!correct){try{await promisify(execFile)(process.execPath,["--input-type=module","-e","import assert from 'node:assert/strict'; import {clamp} from './dist/clamp.mjs'; assert.throws(()=>clamp(4,10,0),RangeError);"],{cwd:f.project});}catch(error){actualEdgeStderr=String((error as {stderr?:unknown}).stderr??"");actualEdgeFailure=(error as {code?:unknown}).code===1&&actualEdgeStderr.includes("Missing expected exception (RangeError)");}}return answer(correct?passed:{...passed,verdict:"blocked",findings:[{severity:"blocking",path:"src/clamp.mjs",line:1,summary:"Reversed bounds do not throw RangeError; add the bound-order guard and a regression test."}]});}
   switch(++rootStep){case 1:return call("read_file",{path:"src/clamp.mjs"});case 2:return call("preview_patch",{path:"src/clamp.mjs",expected:before,replacement:buggy});case 3:return call("discover_project_commands",{path:"."});case 4:return call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash,timeout_ms:5_000});case 5:return answer();case 6:expect(serialized).toContain("delivery_review");return call("preview_patch",{path:"test/clamp.test.mjs",expected:tests,replacement:repairedTests});case 7:return call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash,timeout_ms:5_000});case 8:expect(serialized).toContain("project_command_failed");return call("read_file",{path:"src/clamp.mjs"});case 9:return call("preview_patch",{path:"src/clamp.mjs",expected:buggy,replacement:fixed});case 10:return call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash,timeout_ms:5_000});default:return answer();}
  });const runtime=await runtimeFixture(f,provider.model,{maxTurns:3}),started=await runtime.startRun(input(f)),completed=await wait(runtime,started.run_id);
  expect(completed.status,JSON.stringify(completed.timeline.slice(-3))).toBe("completed");expect(completed.subagents.items).toHaveLength(2);expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(fixed);expect(await readFile(join(f.project,"dist/clamp.mjs"),"utf8")).toBe(fixed);expect(await readFile(join(f.project,"test/clamp.test.mjs"),"utf8")).toBe(repairedTests);
  const reviews=completed.timeline.filter(event=>event.data.operation==="delivery.review_completed");expect(reviews.map(event=>(event.data.review_result as {verdict:string}).verdict)).toEqual(["blocked","passed"]);
  expect(completed.timeline.filter(event=>event.data.operation==="delivery.turn_checkpoint").map(event=>event.data.turns_completed)).toEqual([3,6]);
  const actualFailed=completed.timeline.filter(event=>event.type==="tool.failed"&&(event.data.receipt as {tool_name?:string})?.tool_name==="run_project_command");expect(actualFailed).toHaveLength(1);expect(actualFailed[0]?.data.receipt).toMatchObject({business_status:"failure",transport_status:"success",code:"project_command_failed"});expect(completed.timeline.filter(event=>event.data.operation==="delivery.verification_failure_checkpoint")).toHaveLength(1);expect(completed.timeline.find(event=>event.data.operation==="delivery.verification_failure_resolved")?.data.failed_event_id).toBe(actualFailed[0]?.event_id);
  const commands=completed.timeline.filter(event=>event.type==="tool.completed"&&(event.data.receipt as {tool_name?:string})?.tool_name==="run_project_command");expect(commands).toHaveLength(2);for(const event of commands){expect(event.data.receipt).toMatchObject({business_status:"success",code:"project_command_passed"});const result=await runtime.getArtifact({artifactId:event.artifact_refs[0]!.artifact_id,projectId:completed.project_id,runId:completed.run_id});expect(result).toMatchObject({status:"available",content:expect.stringContaining("ACTUAL_BUILD_OUTPUT")});}const output=await runtime.getArtifact({artifactId:commands[1]!.artifact_refs[0]!.artifact_id,projectId:completed.project_id,runId:completed.run_id});expect(output).toMatchObject({status:"available",content:expect.stringContaining("ACTUAL_REVERSED_RANGE_REGRESSION_PASS")});
  for(const child of completed.subagents.items){const value=await runtime.getProjection(child.link.child_run_id);expect(value.mode).toBe("plan");expect(value.timeline.filter(event=>event.type==="tool.started").every(event=>["read_file","read_artifact"].includes(String(event.data.tool_name)))).toBe(true);expect(value.timeline.find(event=>event.type==="permission.configured")?.data.permission).toMatchObject({sandbox_mode:"read-only"});const ledger=new JsonlEventLedger(join(f.root,"data/events"));await ledger.initialize();const terminal=(await ledger.list(value.run_id)).find(event=>event.type==="run.completed")!;expect(completed.timeline.find(event=>event.type==="subagent.completed"&&(event.data.link as {child_run_id?:string})?.child_run_id===value.run_id)?.data).toMatchObject({child_terminal_event_id:terminal.event_id,child_terminal_event_hash:terminal.event_hash});}
  const checkpoints=completed.timeline.filter(event=>String(event.data.operation).startsWith("delivery.budget_"));expect(new Set(checkpoints.filter(event=>event.data.operation==="delivery.budget_reserved").map(event=>(event.data.budget_checkpoint as {run_id:string}).run_id)).size).toBe(3);expect(completed.timeline.at(-1)?.data.delivery_budget).toMatchObject({charged_tokens:provider.calls()*15,held_tokens:0,request_count:provider.calls()});expect(provider.childCalls()).toBe(4);expect(actualEdgeFailure).toBe(true);await saveProof(f,runtime,completed,provider.calls(),actualEdgeStderr);const beforeReplay=provider.calls();await runtime.replay(completed.run_id);expect(provider.calls()).toBe(beforeReplay);
 });
 it("rejects enabled unsupported adapters before any provider or file operation",async()=>{const f=await fixture();let calls=0;const runtime=await runtimeFixture(f,{name:"unsupported",async decide(){calls++;return answer();}});await expect(runtime.startRun(input(f))).rejects.toMatchObject({code:"delivery_budget_adapter_unsupported"});expect(calls).toBe(0);expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(before);});
 it("checks the bound adapter rather than trusting the outer budget claim",async()=>{const f=await fixture();let calls=0,released=0;const model={name:"outer-budget-claim",supportsRequestBudget:true as const,forRun:()=>({name:"bound-without-budget",decide:async()=>{calls++;return answer();},releaseRun:()=>{released++;}}),decide:async()=>answer()};const runtime=await runtimeFixture(f,model);await expect(runtime.startRun(input(f))).rejects.toMatchObject({code:"delivery_budget_adapter_unsupported"});expect(calls).toBe(0);expect(released).toBe(1);});
 it("requires fresh verification after an actual patch and stops after two missing attempts",async()=>{const f=await fixture();let root=0;const provider=await modelFixture(()=>++root===1?call("preview_patch",{path:"src/clamp.mjs",expected:before,replacement:fixed}):answer()),runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);expect(result.status).toBe("failed");expect(result.failure_code).toBe("delivery_verification_missing");expect(result.timeline.filter(event=>event.data.operation==="delivery.verification_required")).toHaveLength(2);expect(result.subagents.items).toEqual([]);expect(provider.childCalls()).toBe(0);expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(fixed);expect(result.timeline.some(event=>event.type==="tool.started"&&event.data.tool_name==="run_project_command")).toBe(false);});
 it("respects an admitted readonly denial before launching review",async()=>{const f=await fixture();await writeFile(join(f.project,"src/clamp.mjs"),buggy);let root=0;const provider=await modelFixture(()=>++root===1?call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}):answer()),runtime=await runtimeFixture(f,provider.model,{permissionPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"],rules:[{rule_id:"rule:review-read-denied",priority:100,when:{tool:"read_file"},then:"deny",explanation:"Required review files are outside this admitted reading authority"}]})}),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);expect(result.failure_code).toBe("delivery_review_read_denied");expect(result.subagents.items).toEqual([]);expect(provider.childCalls()).toBe(0);});
 it("retains an unknown command disk effect without reviewer, repeat dispatch or replay write",async()=>{const f=await fixture(),native=new NativeSandboxRunner();let dispatches=0;const provider=await modelFixture(()=>call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash})),runtime=await runtimeFixture(f,provider.model,{sandboxRunner:{probe:request=>native.probe(request),async run(){dispatches++;await writeFile(join(f.project,"unknown-effect.txt"),"ONE_UNKNOWN_DISK_EFFECT");throw new Error("controlled result lost");}}}),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);expect(result.failure_code).toBe("unknown_side_effect");expect(result.subagents.items).toEqual([]);expect(provider.calls()).toBe(1);expect(dispatches).toBe(1);expect(await readFile(join(f.project,"unknown-effect.txt"),"utf8")).toBe("ONE_UNKNOWN_DISK_EFFECT");await runtime.replay(result.run_id);expect(dispatches).toBe(1);expect(provider.calls()).toBe(1);});
 it("rejects repeating a settled failed command without a new actual observation or patch",async()=>{
  const f=await fixture();await writeFile(join(f.project,"verify.mjs"),"console.error('ACTUAL_FAILED_COMMAND');process.exit(7);\n");
  const provider=await modelFixture(()=>call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}));
  const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);
  expect(result.failure_code).toBe("verification_retry_requires_evidence");expect(provider.calls()).toBe(2);
  expect(result.timeline.filter(event=>event.type==="tool.started"&&event.data.tool_name==="run_project_command")).toHaveLength(1);
  expect(result.timeline.filter(event=>event.data.operation==="delivery.verification_failure_checkpoint")).toHaveLength(1);
  expect(result.subagents.items).toEqual([]);
 });
 it("limits separately proposed known failed verifications to three actual settled commands",async()=>{
  const f=await fixture();await writeFile(join(f.project,"verify.mjs"),"console.error('ACTUAL_FAILED_COMMAND');process.exit(7);\n");let step=0;
  const provider=await modelFixture(()=>{switch(++step){case 2:return call("read_file",{path:"src/clamp.mjs"});case 4:return call("read_file",{path:"test/clamp.test.mjs"});default:return call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash});}});
  const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);
  expect(result.failure_code).toBe("project_command_failed");expect(provider.calls()).toBe(5);
  expect(result.timeline.filter(event=>event.type==="tool.started"&&event.data.tool_name==="run_project_command")).toHaveLength(3);
  expect(result.timeline.filter(event=>event.data.operation==="delivery.verification_failure_checkpoint").map(event=>event.data.failure_count)).toEqual([1,2,3]);expect(result.subagents.items).toEqual([]);
 });
 it("cannot finish after an unresolved known failure even when no patch paths exist",async()=>{
  const f=await fixture();await writeFile(join(f.project,"verify.mjs"),"process.exit(7);\n");let step=0;
  const provider=await modelFixture(()=>++step===1?call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}):answer());
  const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);
  expect(result.failure_code).toBe("delivery_verification_unresolved");expect(provider.calls()).toBe(2);expect(result.timeline.some(event=>event.type==="run.completed")).toBe(false);expect(result.subagents.items).toEqual([]);
 });
 it("does not continue a real timed-out process or dispatch it twice",async()=>{
  const f=await fixture();await writeFile(join(f.project,"verify.mjs"),"setInterval(()=>{},1000);\n");
  const provider=await modelFixture(()=>call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash,timeout_ms:100}));
  const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);
  expect(result.failure_code).toBe("timeout");expect(provider.calls()).toBe(1);expect(result.timeline.some(event=>event.data.operation==="delivery.verification_failure_checkpoint")).toBe(false);expect(result.subagents.items).toEqual([]);
 });
 it("keeps legacy embeddings fail-closed for the same actual nonzero command",async()=>{
  const f=await fixture();await writeFile(join(f.project,"verify.mjs"),"process.exit(7);\n");
  const provider=await modelFixture(()=>call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}));
  const runtime=await runtimeFixture(f,provider.model,{deliveryReview:false}),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);
  expect(result.failure_code).toBe("project_command_failed");expect(provider.calls()).toBe(1);expect(result.timeline.some(event=>String(event.data.operation).startsWith("delivery."))).toBe(false);
 });
 it("fences an external source change during actual independent inspection",async()=>{const f=await fixture();let root=0,review=0;const provider=await modelFixture(async({child,body})=>{if(child){if(++review===1)return reviewReads(body);await writeFile(join(f.project,"src/clamp.mjs"),fixed);return answer(passed);}return ++root===1?call("preview_patch",{path:"src/clamp.mjs",expected:before,replacement:buggy}):root===2?call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}):answer();}),runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);expect(result.failure_code).toBe("delivery_review_source_changed");expect(result.timeline.some(event=>event.type==="run.completed")).toBe(false);expect(result.subagents.items[0]?.status).toBe("completed");expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(fixed);});
 it("settles a cancellation during review without completing or another parent request",async()=>{const f=await fixture();await writeFile(join(f.project,"src/clamp.mjs"),buggy);let root=0,review=0;let release!:()=>void;const hold=new Promise<void>(resolve=>{release=resolve;});const provider=await modelFixture(async({child,body})=>{if(child){if(++review===1)return reviewReads(body);await hold;return answer(passed);}return ++root===1?call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}):answer();}),runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f));const deadline=Date.now()+5_000;while(review<2&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,10));expect(review).toBe(2);await runtime.submitUserInput({type:"submit_user_input",command_id:"command:review-cancel",input_id:"input:review-cancel",project_id:started.project_id,run_id:started.run_id,kind:"cancel",body:"Cancel this software delivery",actor:"user"});release();const result=await wait(runtime,started.run_id);expect(result.status).toBe("cancelled");expect(result.subagents.active_count).toBe(0);expect(result.timeline.filter(event=>["run.completed","run.failed","run.cancelled"].includes(event.type))).toHaveLength(1);expect(root).toBe(2);expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(buggy);});
 it("does not reset the no-progress guard when internal phases continue",async()=>{const f=await fixture();const provider=await modelFixture(()=>call("read_file",{path:"src/clamp.mjs"})),runtime=await runtimeFixture(f,provider.model,{maxTurns:1}),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);expect(result.failure_code).toBe("no_progress_detected");expect(result.timeline.some(event=>event.data.operation==="delivery.turn_checkpoint")).toBe(true);expect(provider.calls()).toBeLessThan(10);expect(result.subagents.items).toEqual([]);});
 it("refuses resume while the original finite Run still awaits human approval",async()=>{const f=await fixture();const provider=await modelFixture(()=>call("preview_patch",{path:"src/clamp.mjs",expected:before,replacement:fixed})),runtime=await runtimeFixture(f,provider.model,{permissionPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["workspace-write"]})}),started=await runtime.startRun(input(f));let current=await runtime.getProjection(started.run_id);const deadline=Date.now()+5_000;while(current.status!=="awaiting_approval"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,10));current=await runtime.getProjection(started.run_id);}expect(current.status).toBe("awaiting_approval");await expect(runtime.resumeRun({commandId:"resume:delivery",runId:current.run_id,sessionId:current.session_id!,projectId:current.project_id,workspace:f.workspace})).rejects.toMatchObject({code:"run_not_interrupted"});expect(provider.calls()).toBe(1);expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(before);});
 it.each(["prose","forged-read","write"])("never accepts reviewer %s as delivery success",async kind=>{const f=await fixture();let root=0;const provider=await modelFixture(({child,body})=>child?kind==="write"?call("preview_patch",{path:"src/clamp.mjs",expected:before,replacement:fixed}):kind==="prose"?answer():answer(passed):++root===1?call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}):answer());await writeFile(join(f.project,"src/clamp.mjs"),buggy);const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);expect(result.status).toBe("failed");expect(result.failure_code).toBe("delivery_review_child_failed");expect(result.timeline.some(event=>event.type==="run.completed")).toBe(false);expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(buggy);const child=await runtime.getProjection(result.subagents.items[0]!.link.child_run_id);expect(child.timeline.some(event=>event.type==="tool.started"&&event.data.tool_name==="preview_patch")).toBe(false);});
 it("keeps Plan direct answers free of review and ordinary delivery budget",async()=>{const f=await fixture();const provider=await modelFixture(()=>answer()),runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun({...input(f),mode:"plan",task:"What is clamping?"}),result=await wait(runtime,started.run_id);expect(result.status).toBe("completed");expect(result.subagents.items).toEqual([]);expect(result.timeline.some(event=>String(event.data.operation).startsWith("delivery."))).toBe(false);expect(provider.calls()).toBe(1);});
 it("lets an ordinary project run complete after provider usage passes the former aggregate ceiling",async()=>{const f=await fixture(),provider=await modelFixture(()=>answer(),{prompt_tokens:205_000,completion_tokens:1,total_tokens:205_001}),runtime=await runtimeFixture(f,provider.model,{deliveryReview:{maxRounds:2}}),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);expect(result.status).toBe("completed");expect(result.timeline.find(event=>event.type==="model.usage_reported")?.data).toMatchObject({input_tokens:205_000,output_tokens:1,total_tokens:205_001});expect(result.timeline.find(event=>event.type==="run.created")?.data).not.toHaveProperty("delivery_budget");expect(result.timeline.some(event=>String(event.data.operation).startsWith("delivery.budget_"))).toBe(false);expect(result.timeline.at(-1)?.data).not.toHaveProperty("delivery_budget");});
 it("admits the same finite lease only after explicit execution-plan approval and bills no hidden derivation",async()=>{
  const f=await fixture();await writeFile(join(f.project,"src/clamp.mjs"),fixed);let step=0,review=0;
  const provider=await modelFixture(({child,body})=>{if(child)return ++review===1?reviewReads(body):answer(passed);switch(++step){case 1:return call("todo_write",{operation:"create",todo_id:"todo:delivery",title:"Verify the existing implementation"});case 2:return {...answer(),finish_intent:"submit_plan"};case 3:return call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash});default:return answer();}});
  const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun({...input(f),mode:"plan"});let pending=await runtime.getProjection(started.run_id);const deadline=Date.now()+5_000;while(!pending.pending_plan&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,10));pending=await runtime.getProjection(started.run_id);}
  expect(pending.status).toBe("awaiting_plan_approval");expect(provider.calls()).toBe(2);expect(pending.timeline.some(event=>String(event.data.operation).startsWith("delivery.budget_"))).toBe(false);
  await runtime.approvePlan({type:"approve_plan",command_id:"command:approve-delivery",run_id:pending.run_id,project_id:pending.project_id,plan_event_id:pending.pending_plan!.plan_event_id});
  const completed=await wait(runtime,started.run_id);expect(completed.status).toBe("completed");expect(completed.timeline.find(event=>event.data.operation==="delivery.budget_configured")?.data.background_model_derivation).toBe(false);expect(completed.timeline.at(-1)?.data.delivery_budget).toMatchObject({request_count:4,charged_tokens:60});expect(provider.calls()).toBe(6);
 });
 it("a finite ordinary token lease rejects preflight before any provider request",async()=>{
  const f=await fixture(),provider=await modelFixture(()=>answer()),runtime=await runtimeFixture(f,provider.model,{deliveryReview:{ordinaryBudget:{max_tokens:100,max_time_ms:30_000}}}),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);
  expect(result.status).toBe("cancelled");expect(provider.calls()).toBe(0);expect(result.timeline.some(event=>event.data.operation==="delivery.budget_stopped")).toBe(true);const terminal=result.timeline.find(event=>event.type==="run.cancelled")!;expect(terminal.summary).toBe("Run token budget cannot fit the next model request");expect(terminal.data).toMatchObject({code:"delivery_token_limit",budget_kind:"delivery",delivery_budget:`delivery:${started.run_id}`});expect(terminal.data).not.toHaveProperty("goal_budget");expect(await readFile(join(f.project,"src/clamp.mjs"),"utf8")).toBe(before);
 });
 it("keeps Goal-owned cancellation metadata distinct from delivery budgets",async()=>{
  const f=await fixture(),provider=await modelFixture(()=>answer()),runtime=await runtimeFixture(f,provider.model,{deliveryReview:false}),budget=new SharedRunBudget({identity:"goal:owner-check:1",limits:{max_tokens:100},checkpoint:async()=>undefined});budgets.push(budget);const started=await runtime.startRun(input(f),{model:provider.model,requestBudget:budget,backgroundModelDerivation:false}),result=await wait(runtime,started.run_id),terminal=result.timeline.find(event=>event.type==="run.cancelled")!;
  expect(result.status).toBe("cancelled");expect(provider.calls()).toBe(0);expect(terminal.summary).toBe("Goal request does not fit the remaining token budget");expect(terminal.data).toMatchObject({code:"goal_token_limit",budget_kind:"goal",goal_budget:budget.identity});expect(terminal.data).not.toHaveProperty("delivery_budget");
 });
 it("one fresh successful command resolves every prior known failure of that same scoped command",async()=>{
  const f=await fixture();await writeFile(join(f.project,"src/clamp.mjs"),buggy);await writeFile(join(f.project,"test/clamp.test.mjs"),repairedTests);let step=0,review=0;
  const provider=await modelFixture(({child,body})=>{if(child)return ++review===1?reviewReads(body):answer(passed);switch(++step){case 2:return call("read_file",{path:"src/clamp.mjs"});case 4:return call("preview_patch",{path:"src/clamp.mjs",expected:buggy,replacement:fixed});case 6:return answer();default:return call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash});}});
  const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f)),result=await wait(runtime,started.run_id);
  expect(result.status).toBe("completed");const failed=result.timeline.filter(event=>event.type==="tool.failed");expect(failed).toHaveLength(2);expect(result.timeline.filter(event=>event.data.operation==="delivery.verification_failure_resolved").map(event=>event.data.failed_event_id)).toEqual(failed.map(event=>event.event_id));expect(result.subagents.items).toHaveLength(1);
 });
 it("reuses the admitted Goal lease instead of allocating a second ordinary budget",async()=>{const f=await fixture();await writeFile(join(f.project,"src/clamp.mjs"),fixed);let root=0,review=0;const provider=await modelFixture(({child,body})=>child?++review===1?reviewReads(body):answer(passed):++root===1?call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}):answer());const checkpoints:unknown[]=[];const budget=new SharedRunBudget({identity:"goal:delivery:shared",limits:{max_tokens:200_000,max_time_ms:20_000},checkpoint:async value=>{checkpoints.push(value);}});budgets.push(budget);const runtime=await runtimeFixture(f,provider.model),started=await runtime.startRun(input(f),{model:provider.model,requestBudget:budget,backgroundModelDerivation:false}),result=await wait(runtime,started.run_id);expect(result.status).toBe("completed");expect(result.timeline.some(event=>String(event.data.operation).startsWith("delivery.budget_"))).toBe(false);expect(result.timeline.find(event=>event.type==="run.created")?.data.goal_budget).toBe(budget.identity);expect(budget.snapshot()).toMatchObject({charged_tokens:60,request_count:4});expect(checkpoints).toHaveLength(8);});
});
