import {afterEach,describe,expect,it} from "vitest";
import {SharedRunBudget,type BudgetCheckpoint} from "./shared-run-budget.js";
const leases:SharedRunBudget[]=[];afterEach(()=>leases.splice(0).forEach(value=>value.dispose()));
function fixture(max_tokens=1_000,max_time_ms?:number){const events:BudgetCheckpoint[]=[];const budget=new SharedRunBudget({identity:"goal:budget:revision:1",limits:{max_tokens,...(max_time_ms?{max_time_ms}:{})},checkpoint:async value=>{events.push(value);}});leases.push(budget);return {budget,events};}
const usage=(input_tokens:number,output_tokens:number)=>({provider:"openai",model:"fixture",input_tokens,output_tokens,total_tokens:input_tokens+output_tokens,request_kind:"initial" as const,request_sequence:1});
describe("aggregate pre-dispatch budget reservations",()=>{
 it("persists reservation before returning transport authority and caps output to remaining tokens",async()=>{const f=fixture(500);const reservation=await f.budget.reserve({runId:"run:parent",requestKind:"initial",inputTokens:400,maxOutputTokens:200});expect(reservation.maxOutputTokens).toBe(100);expect(f.events[0]).toMatchObject({phase:"reserved",run_id:"run:parent",reserved_tokens:500,snapshot:{held_tokens:500,request_count:1}});await reservation.settle(usage(100,20));expect(f.budget.snapshot()).toMatchObject({charged_tokens:120,held_tokens:0,reported_input_tokens:100});await reservation.settle(usage(400,100));expect(f.budget.snapshot().charged_tokens).toBe(120);});
 it("serializes concurrent parent and child admission without overspending",async()=>{const f=fixture(500);const results=await Promise.allSettled([f.budget.reserve({runId:"run:parent",requestKind:"initial",inputTokens:350,maxOutputTokens:150}),f.budget.reserve({runId:"run:child",requestKind:"initial",inputTokens:200,maxOutputTokens:150})]);expect(results[0].status).toBe("fulfilled");expect(results[1].status).toBe("rejected");expect(f.events.filter(e=>e.phase==="reserved")).toHaveLength(1);expect(f.budget.snapshot().held_tokens).toBe(500);if(results[0].status==="fulfilled")await results[0].value.settle(usage(350,100));});
 it("conservatively consumes uncertain or malformed usage and fences another provider request",async()=>{const f=fixture();const reservation=await f.budget.reserve({runId:"run:parent",requestKind:"initial",inputTokens:300,maxOutputTokens:200});await reservation.settle();expect(f.budget.snapshot()).toMatchObject({charged_tokens:500,held_tokens:0,unknown_request_count:1,stop_reason:"usage_unknown"});await expect(f.budget.reserve({runId:"run:child",requestKind:"repair",inputTokens:1,maxOutputTokens:1})).rejects.toMatchObject({code:"goal_budget_stopped"});});
 it("records a provider overrun honestly and stops further dispatch",async()=>{const f=fixture();const reservation=await f.budget.reserve({runId:"run:parent",requestKind:"initial",inputTokens:20,maxOutputTokens:30});await reservation.settle(usage(100,100));expect(f.budget.snapshot()).toMatchObject({charged_tokens:200,stop_reason:"usage_overrun"});expect(f.budget.signal.aborted).toBe(true);});
 it("a trusted proven pre-dispatch cancellation releases its reservation without inventing provider usage",async()=>{const f=fixture();const reservation=await f.budget.reserve({runId:"run:parent",requestKind:"initial",inputTokens:20,maxOutputTokens:30});await reservation.cancelBeforeDispatch();await reservation.settle();expect(f.budget.snapshot()).toMatchObject({charged_tokens:0,held_tokens:0,held_request_count:0,unknown_request_count:0,reported_input_tokens:0});expect(f.events.at(-1)).toMatchObject({outcome:"not_dispatched",actual_tokens:0});});
 it("does not grant request authority when durable checkpoint fails",async()=>{const budget=new SharedRunBudget({identity:"goal:disk-fail",limits:{max_tokens:100},checkpoint:async()=>{throw new Error("disk unavailable");}});leases.push(budget);await expect(budget.reserve({runId:"run:one",requestKind:"initial",inputTokens:10,maxOutputTokens:10})).rejects.toMatchObject({code:"goal_budget_persistence_failed"});expect(budget.signal.aborted).toBe(true);});
 it("a real finite deadline aborts the shared lease and prevents late admission",async()=>{const f=fixture(1_000,100);await new Promise(resolve=>setTimeout(resolve,140));expect(f.budget.signal.aborted).toBe(true);await expect(f.budget.reserve({runId:"run:one",requestKind:"initial",inputTokens:1,maxOutputTokens:1})).rejects.toMatchObject({code:"goal_budget_stopped"});expect(f.events.some(event=>event.phase==="stopped"&&event.snapshot.stop_reason==="time_limit")).toBe(true);});
 it("resume retains spent tokens/time and refuses outstanding reservation refund",async()=>{const f=fixture(1_000);const reservation=await f.budget.reserve({runId:"run:parent",requestKind:"initial",inputTokens:50,maxOutputTokens:50});expect(()=>new SharedRunBudget({identity:"goal:restore",limits:{max_tokens:1_000},previous:f.budget.snapshot(),checkpoint:async()=>undefined})).toThrow("Outstanding reservations");await reservation.settle(usage(50,30));await f.budget.stop();const snapshot=f.budget.snapshot();const restored=new SharedRunBudget({identity:"goal:restore",limits:snapshot.limits,previous:snapshot,checkpoint:async()=>undefined});leases.push(restored);expect(restored.snapshot().charged_tokens).toBe(80);expect(restored.snapshot().elapsed_ms).toBeGreaterThanOrEqual(snapshot.elapsed_ms);});
});
