import {z} from "zod";
import {IdentifierSchema} from "./common.js";
import {ModelConfigUpdateRequestSchema, PublicModelConfigResponseSchema} from "./credentials.js";
import {ModelConnectionTestResultSchema} from "./local-workbench.js";
export const SessionRunOptionsSchema=z.object({connection_id:IdentifierSchema.optional(),model:z.string().trim().min(1).max(200).optional(),reasoning_effort:z.enum(["default","low","medium","high","xhigh","max"]).default("default"),mode:z.enum(["plan","execute"]).default("execute"),permission_preset:z.enum(["read-only","workspace-write","full-write"]).default("workspace-write")}).strict();
export type SessionRunOptions=z.infer<typeof SessionRunOptionsSchema>;
export const SessionRunOptionsSnapshotSchema=z.object({session_id:IdentifierSchema,revision:z.number().int().nonnegative(),options:SessionRunOptionsSchema}).strict();
export type SessionRunOptionsSnapshot=z.infer<typeof SessionRunOptionsSnapshotSchema>;
export const SessionRunOptionsUpdateRequestSchema=z.object({command_id:IdentifierSchema,expected_revision:z.number().int().nonnegative(),options:SessionRunOptionsSchema}).strict();
export type SessionRunOptionsUpdateRequest=z.infer<typeof SessionRunOptionsUpdateRequestSchema>;
export const ModelConnectionSchema=z.object({connection_id:IdentifierSchema,label:z.string().trim().min(1).max(200),revision:z.number().int().nonnegative(),provider:PublicModelConfigResponseSchema.shape.provider,protocol:PublicModelConfigResponseSchema.shape.protocol,base_url:z.url().max(500),model:z.string().min(1).max(200),models:z.array(z.string().trim().min(1).max(200)).min(1).max(100),image_input_models:z.array(z.string().trim().min(1).max(200)).max(100).optional(),reasoning_by_model:z.record(z.string(),z.array(z.enum(["default","low","medium","high","xhigh","max"]))).optional(),has_key:z.boolean(),credential:PublicModelConfigResponseSchema.shape.credential,source:z.enum(["profile","environment"]),writable:z.boolean(),test:ModelConnectionTestResultSchema.optional()}).strict();
export type ModelConnection=z.infer<typeof ModelConnectionSchema>;
export const ModelConnectionsSnapshotSchema=z.object({connections:z.array(ModelConnectionSchema).max(100),default_connection_id:IdentifierSchema.nullable()}).strict();
export type ModelConnectionsSnapshot=z.infer<typeof ModelConnectionsSnapshotSchema>;
export const ModelConnectionSaveRequestSchema=ModelConfigUpdateRequestSchema.extend({command_id:IdentifierSchema,connection_id:IdentifierSchema.optional(),expected_revision:z.number().int().nonnegative().optional(),label:z.string().trim().min(1).max(200),clear_key:z.boolean().optional(),image_input_models:z.array(z.string().trim().min(1).max(200)).max(100).optional(),models:z.array(z.string().trim().min(1).max(200)).min(1).max(100).optional()}).strict();
export type ModelConnectionSaveRequest=z.infer<typeof ModelConnectionSaveRequestSchema>;
export const ModelConnectionRemoveRequestSchema=z.object({command_id:IdentifierSchema,expected_revision:z.number().int().nonnegative()}).strict();
export type ModelConnectionRemoveRequest=z.infer<typeof ModelConnectionRemoveRequestSchema>;
export const PermissionGrantSchema=z.object({enabled:z.boolean(),can_grant:z.boolean(),ceiling:z.enum(["read-only","workspace-write","full-write"]),source:z.string().max(100),pending_restart:z.boolean()}).strict();
export type PermissionGrant=z.infer<typeof PermissionGrantSchema>;
export const PermissionGrantUpdateRequestSchema=z.object({command_id:IdentifierSchema,enabled:z.boolean(),confirmed:z.literal(true)}).strict();
export type PermissionGrantUpdateRequest=z.infer<typeof PermissionGrantUpdateRequestSchema>;
