import { z } from "zod";
import {
  ArtifactRefSchema,
  IdentifierSchema,
  IsoDateTimeSchema,
  NonEmptyStringSchema,
  SCHEMA_VERSION,
  Sha256Schema,
} from "./common.js";

export const terminalEventTypes = ["run.completed", "run.failed", "run.cancelled"] as const;

export const EventTypeSchema = z.enum([
  "run.created",
  "run.started",
  "run.completed",
  "run.failed",
  "run.cancelled",
  "context.built",
  "context.budget_warning",
  "context.compaction_started",
  "context.compaction_completed",
  "context.tool_output_spilled",
  "context.summary_created",
  "context.summary_failed",
  "context.spill_refetched",
  "model.request_started",
  "model.usage_reported",
  "model.usage_anomaly",
  "model.decision",
  "model.request_failed",
  "model.output_invalid",
  "action.rejected",
  "action.stale",
  "action.late_ignored",
  "action.verified",
  "action.reconciled",
  "action.diverged",
  "action.rollback_refused",
  "permission.configured",
  "policy.evaluated",
  "policy.denied",
  "plan.ready",
  "plan.approved",
  "todo.created",
  "todo.updated",
  "todo.completed",
  "todo.blocked",
  "user.input_queued",
  "user.input_consumed",
  "approval.requested",
  "approval.granted",
  "approval.denied",
  "approval.expired",
  "tool.started",
  "tool.batch_started",
  "tool.batch_completed",
  "tool.completed",
  "tool.failed",
  "tool.unknown",
  "sandbox.configured",
  "sandbox.enforced",
  "sandbox.disabled",
  "patch.preview_created",
  "patch.applied",
  "patch.rolled_back",
  "test.completed",
  "graph.snapshot_created",
  "graph.delta_created",
  "memory.candidate_evaluated",
  "memory.written",
  "memory.recalled",
  "retrieval.index_updated",
  "subagent.started",
  "subagent.message_sent",
  "subagent.completed",
  "subagent.failed",
  "subagent.interrupted",
  "attachment.added",
  "attachment.rejected",
  "attachment.offloaded",
  "extension.error",
  "artifact.stored",
  "credentials.migrated",
  "session.opened",
  "session.closed",
  "session.title_changed",
  "session.tail_truncated",
  "run.interrupted",
  "run.resumed",
  "team.created",
  "team.member_joined",
  "team.heartbeat",
  "team.member_lost",
  "team.mailbox_delivered",
  "team.mailbox_claimed",
  "team.task_created",
  "team.task_claimed",
  "team.task_completed",
  "team.task_blocked",
  "team.task_cancelled",
  "team.task_reopened",
  "team.sweep_completed",
  "skill.registry_loaded",
  "skill.conflict",
  "skill.load_failed",
  "mcp.server_started",
  "mcp.server_failed",
  "mcp.server_stopped",
  "mcp.tools_changed",
  "mcp.tool_called",
  "lsp.diagnostics_received",
  "lsp.server_unavailable",
]);
export type EventType = z.infer<typeof EventTypeSchema>;

export function isTerminalEventType(type: EventType): type is (typeof terminalEventTypes)[number] {
  return terminalEventTypes.includes(type as (typeof terminalEventTypes)[number]);
}

const EventBaseShape = {
  schema_version: z.literal(SCHEMA_VERSION),
  event_id: IdentifierSchema,
  project_id: IdentifierSchema,
  run_id: IdentifierSchema,
  session_id: IdentifierSchema.optional(),
  sequence: z.number().int().positive(),
  occurred_at: IsoDateTimeSchema,
  attempt: z.number().int().nonnegative(),
  summary: NonEmptyStringSchema.max(2_000),
  artifact_refs: z.array(ArtifactRefSchema).default([]),
  idempotency_key: IdentifierSchema.optional(),
  turn_id: IdentifierSchema.optional(),
  operation_id: IdentifierSchema.optional(),
  parent_event_id: IdentifierSchema.optional(),
  caused_by_event_id: IdentifierSchema.optional(),
  context_manifest_ref: IdentifierSchema.optional(),
  model_call_id: IdentifierSchema.optional(),
  action_id: IdentifierSchema.optional(),
  patch_event_id: IdentifierSchema.optional(),
  graph_delta_id: IdentifierSchema.optional(),
  test_receipt_id: IdentifierSchema.optional(),
  previous_event_hash: Sha256Schema.optional(),
  event_hash: Sha256Schema,
  data: z.record(z.string(), z.unknown()).default({}),
};

const EventBaseSchema = z.object(EventBaseShape);
const eventVariants = EventTypeSchema.options.map((type) => EventBaseSchema.extend({ type: z.literal(type) }));

// The runtime discriminant is `type`; payload-specific contracts are linked by
// explicit IDs/artifact refs instead of placing large objects in the ledger.
export const SessionEventSchema = z.discriminatedUnion("type", eventVariants as [
  (typeof eventVariants)[number],
  (typeof eventVariants)[number],
  ...(typeof eventVariants)[number][],
]);
export type SessionEvent = z.infer<typeof SessionEventSchema>;

export const SessionEventProposalSchema = z.object({
  type: EventTypeSchema,
  project_id: IdentifierSchema,
  run_id: IdentifierSchema,
  session_id: IdentifierSchema.optional(),
  attempt: z.number().int().nonnegative().default(0),
  summary: NonEmptyStringSchema.max(2_000),
  artifact_refs: z.array(ArtifactRefSchema).default([]),
  idempotency_key: IdentifierSchema.optional(),
  turn_id: IdentifierSchema.optional(),
  operation_id: IdentifierSchema.optional(),
  parent_event_id: IdentifierSchema.optional(),
  caused_by_event_id: IdentifierSchema.optional(),
  context_manifest_ref: IdentifierSchema.optional(),
  model_call_id: IdentifierSchema.optional(),
  action_id: IdentifierSchema.optional(),
  patch_event_id: IdentifierSchema.optional(),
  graph_delta_id: IdentifierSchema.optional(),
  test_receipt_id: IdentifierSchema.optional(),
  data: z.record(z.string(), z.unknown()).default({}),
});
export type SessionEventProposal = z.infer<typeof SessionEventProposalSchema>;

export const WireSessionEventSchema = z.object({
  schema_version: z.literal(SCHEMA_VERSION),
  event_id: IdentifierSchema,
  project_id: IdentifierSchema,
  run_id: IdentifierSchema,
  session_id: IdentifierSchema.optional(),
  sequence: z.number().int().positive(),
  occurred_at: IsoDateTimeSchema,
  type: EventTypeSchema,
  summary: NonEmptyStringSchema.max(2_000),
  artifact_refs: z.array(ArtifactRefSchema),
  turn_id: IdentifierSchema.optional(),
  operation_id: IdentifierSchema.optional(),
  parent_event_id: IdentifierSchema.optional(),
  caused_by_event_id: IdentifierSchema.optional(),
  context_manifest_ref: IdentifierSchema.optional(),
  model_call_id: IdentifierSchema.optional(),
  action_id: IdentifierSchema.optional(),
  patch_event_id: IdentifierSchema.optional(),
  graph_delta_id: IdentifierSchema.optional(),
  test_receipt_id: IdentifierSchema.optional(),
  data: z.record(z.string(), z.unknown()),
});
export type WireSessionEvent = z.infer<typeof WireSessionEventSchema>;
