import {describe,expect,it} from "vitest";
import {GoalCreateRequestSchema,GoalCommandRequestSchema,GoalBudgetLimitsSchema,GoalCreationReceiptSchema} from "./goal.js";
const proposal={command_id:"command:goal",project_id:"project:one",title:"Build software",objective:"Implement the approved feature",done_conditions:["Tests pass","User reviews behavior"],budget:{max_tokens:20_000,max_time_ms:60_000}};
describe("versioned finite Goal contracts",()=>{
 it("requires explicit done conditions and at least one finite ceiling",()=>{expect(GoalCreateRequestSchema.parse(proposal)).toEqual(proposal);expect(GoalBudgetLimitsSchema.safeParse({}).success).toBe(false);for(const budget of [{max_tokens:Infinity},{max_time_ms:0},{max_tokens:1.5}])expect(GoalBudgetLimitsSchema.safeParse(budget).success).toBe(false);expect(GoalCreateRequestSchema.safeParse({...proposal,done_conditions:[]}).success).toBe(false);expect(GoalCreateRequestSchema.safeParse({...proposal,done_conditions:["duplicate","duplicate"]}).success).toBe(false);});
 it("does not accept client runtime/budget authority, automatic acceptance or shell payloads",()=>{for(const extra of [{credentials:"secret"},{permission_policy:{}},{workspace:"/arbitrary"},{trustedBudget:{}}])expect(GoalCreateRequestSchema.safeParse({...proposal,...extra}).success).toBe(false);expect(GoalCommandRequestSchema.safeParse({command_id:"command:accept",expected_revision:1,operation:"accept",accepted_conditions:proposal.done_conditions,confirmed:false}).success).toBe(false);expect(GoalCommandRequestSchema.safeParse({command_id:"command:start",expected_revision:1,operation:"start",shell:"arbitrary"}).success).toBe(false);});
 it("binds approval and mutation to explicit revisions",()=>{expect(GoalCommandRequestSchema.parse({command_id:"command:approve",expected_revision:1,operation:"approve",proposal_revision:1})).toMatchObject({proposal_revision:1});expect(GoalCommandRequestSchema.safeParse({command_id:"command:approve",operation:"approve",proposal_revision:1}).success).toBe(false);});
 it("never asserts a Goal locator for missing, failed or unknown creation receipts",()=>{for(const state of ["not_found","failed","unknown"]){expect(GoalCreationReceiptSchema.safeParse({command_id:"command:create",state,goal_id:"goal-unverified"}).success).toBe(false);expect(GoalCreationReceiptSchema.safeParse({command_id:"command:create",state,result:{goal_id:"goal-unverified"}}).success).toBe(false);}expect(GoalCreationReceiptSchema.safeParse({command_id:"command:create",state:"completed",goal_id:"goal-unverified"}).success).toBe(false);});
});
