import {randomUUID} from "node:crypto";
import {readFile,rm} from "node:fs/promises";
import {z} from "zod";
import {ImageProviderConfigUpdateSchema,ImageProviderConfigSnapshotSchema,SecretReferenceSchema,type ImageProviderConfigUpdate,type ImageProviderConfigSnapshot} from "@tracegraph/contracts";
import {ConfigurableImageProvider,createSecretReference,credentialNameFromReference,resolveSecretReference,registerSecretForRedaction,type CredentialStore} from "@tracegraph/core";
import {atomicPrivateJson} from "../local-profile.js";
const PersistedImageConfigSchema=ImageProviderConfigUpdateSchema.omit({api_key:true}).extend({credential_ref:SecretReferenceSchema}).strict();
function configError(code:string,message:string,statusCode=400){return Object.assign(new Error(message),{code,statusCode});}
/** Dedicated provider config is reference-only; it never borrows the chat credential implicitly. */
export class ImageConfigController {
  readonly provider:ConfigurableImageProvider;
  #saved:z.infer<typeof PersistedImageConfigSchema>|undefined;
  #queue:Promise<void>=Promise.resolve();
  constructor(readonly file:string,readonly store:CredentialStore){this.provider=new ConfigurableImageProvider({resolveCredential:async ref=>(await resolveSecretReference(ref,store)).value});}
  static async open(file:string,store:CredentialStore){const controller=new ImageConfigController(file,store);let source:string;try{source=await readFile(file,"utf8");}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return controller;throw configError("image_configuration_invalid","Image provider configuration could not be read",503);}try{controller.#saved=PersistedImageConfigSchema.parse(JSON.parse(source));}catch{throw configError("image_configuration_invalid","Image provider configuration is invalid",503);}const {credential_ref,...config}=controller.#saved;controller.provider.configure({...config,credentialRef:credential_ref});return controller;}
  async get():Promise<ImageProviderConfigSnapshot>{const saved=this.#saved;if(!saved)return ImageProviderConfigSnapshotSchema.parse(this.provider.publicConfig());let hasKey=false;try{hasKey=await this.store.get(credentialNameFromReference(saved.credential_ref))!==null;}catch{/* Availability is public; backend diagnostics and secrets stay private. */}const {credential_ref:_reference,...config}=saved;return ImageProviderConfigSnapshotSchema.parse({...config,configured:true,has_key:hasKey});}
  configure(value:ImageProviderConfigUpdate):Promise<ImageProviderConfigSnapshot>{const input=ImageProviderConfigUpdateSchema.parse(value);if(input.api_key)registerSecretForRedaction(input.api_key);return this.#serialize(async()=>{const previous=this.#saved;const sameEndpoint=previous&&previous.base_url.replace(/\/+$/u,"")===input.base_url.replace(/\/+$/u,"")&&previous.protocol===input.protocol;if(!input.api_key&&(!previous||!sameEndpoint))throw configError("image_credential_required","Provide a dedicated image key when configuring a new endpoint or protocol");const name=input.api_key?"OUTLIVE_IMAGE_"+randomUUID().replaceAll("-","_").toUpperCase():credentialNameFromReference(previous!.credential_ref);const reference=createSecretReference(name);const {api_key:key,...publicConfig}=input;try{if(key){await this.store.set(name,key);if(await this.store.get(name)!==key)throw new Error();}else if(await this.store.get(name)===null)throw configError("image_credential_required","The saved image key is unavailable; provide it again");const saved=PersistedImageConfigSchema.parse({...publicConfig,credential_ref:reference});await atomicPrivateJson(this.file,saved);this.#saved=saved;this.provider.configure({...publicConfig,credentialRef:reference});}catch(error){if(key)await this.store.delete(name).catch(()=>undefined);if((error as {code?:string}).code==="image_credential_required")throw error;throw configError("image_configuration_save_failed","Image settings or credential could not be saved",503);}if(previous&&previous.credential_ref!==reference)this.provider.retireCredential(previous.credential_ref,()=>this.store.delete(credentialNameFromReference(previous.credential_ref)));return this.get();});}
  clear():Promise<ImageProviderConfigSnapshot>{return this.#serialize(async()=>{await rm(this.file,{force:true});const previous=this.#saved;this.#saved=undefined;this.provider.clear();if(previous)this.provider.retireCredential(previous.credential_ref,()=>this.store.delete(credentialNameFromReference(previous.credential_ref)));return this.get();});}
  #serialize<T>(action:()=>Promise<T>):Promise<T>{const result=this.#queue.then(action,action);this.#queue=result.then(()=>undefined,()=>undefined);return result;}
}
