import {createServer,type Server} from "node:http";
import {afterEach,describe,expect,it} from "vitest";
import {ConfigurableModelAdapter} from "./model-provider.js";
import {SharedRunBudget,type BudgetCheckpoint} from "../runtime/shared-run-budget.js";
import type {ModelInput} from "../../kernel/types.js";
const servers:Server[]=[],budgets:SharedRunBudget[]=[];afterEach(async()=>{for(const value of budgets.splice(0))value.dispose();for(const value of servers.splice(0)){value.closeAllConnections();await new Promise<void>((resolve)=>value.close(()=>resolve()));}});
const answer=JSON.stringify({decision_id:"decision:budget",kind:"finish",public_reason:"Public answer ready",evidence_refs:[],risk:"none",final_answer:"ACTUAL_RESPONSE"});
async function fixture(responses:Array<{content:string;usage?:object;delay?:number;status?:number}>,limits={max_tokens:100_000}){const requests:Array<Record<string,unknown>>=[],events:BudgetCheckpoint[]=[];const server=createServer(async(req,res)=>{const chunks:Buffer[]=[];for await(const part of req)chunks.push(Buffer.from(part));requests.push(JSON.parse(Buffer.concat(chunks).toString()) as Record<string,unknown>);const response=responses[Math.min(requests.length-1,responses.length-1)]!;if(response.delay)await new Promise(resolve=>setTimeout(resolve,response.delay));res.writeHead(response.status??200,{"content-type":"application/json"});res.end(JSON.stringify({choices:[{message:{content:response.content}}],content:[{type:"text",text:response.content}],...(response.usage?{usage:response.usage}:{})}));});servers.push(server);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error("no fixture address");const model=new ConfigurableModelAdapter({resolveCredential:async()=>"isolated-not-live-key"});model.configure({provider:"custom",protocol:"openai-chat-completions",baseUrl:`http://127.0.0.1:${address.port}/v1`,model:"fixture",credentialRef:"${secret:ISOLATED_BUDGET_KEY}"});const budget=new SharedRunBudget({identity:"goal:provider:1",limits,checkpoint:async event=>{events.push(event);}});budgets.push(budget);const input:ModelInput={projectId:"project:budget",runId:"run:provider",task:"answer",mode:"execute",reasoningEffort:"default",turn:1,context:"bounded actual text",contextManifest:{manifest_id:"manifest:one",project_id:"project:budget",run_id:"run:provider",turn_id:"turn:one",model_call_id:"call:one",token_limit:12_000,reserved_output_tokens:2_000,input_tokens:1,fixed_constraints_preserved:true,items:[],created_at:new Date().toISOString()},observations:[],toolSchemas:[],requestBudget:budget};return {model,budget,input,requests,events};}
const usage={prompt_tokens:10,completion_tokens:5,total_tokens:15,input_tokens:10,output_tokens:5};
describe("real HTTP provider request budget boundary",()=>{
 it("rejects insufficient input budget before sending any HTTP request",async()=>{const f=await fixture([{content:answer,usage}],{max_tokens:100});await expect(f.model.decide(f.input)).rejects.toMatchObject({code:"goal_token_limit"});expect(f.requests).toHaveLength(0);});
 it("counts a real bounded repair as a separate reservation and settles both exact usage reports",async()=>{const f=await fixture([{content:'{"kind":"tool_call","tool_call":{"unsafe":true}}',usage},{content:answer,usage}]);expect(await f.model.decide(f.input)).toMatchObject({kind:"finish",final_answer:"ACTUAL_RESPONSE"});expect(f.requests).toHaveLength(2);expect(f.events.filter(event=>event.phase==="reserved").map(event=>event.request_kind)).toEqual(["initial","repair"]);expect(f.budget.snapshot()).toMatchObject({charged_tokens:30,held_tokens:0,request_count:2});for(const request of f.requests)expect(request.max_tokens).toBe(2048);});
 it("charges absent usage conservatively and prevents a second real HTTP request",async()=>{const f=await fixture([{content:answer}]);await f.model.decide(f.input);expect(f.requests).toHaveLength(1);expect(f.budget.snapshot()).toMatchObject({unknown_request_count:1,held_tokens:0,stop_reason:"usage_unknown"});await expect(f.model.decide(f.input)).rejects.toMatchObject({code:"goal_budget_stopped"});expect(f.requests).toHaveLength(1);});
 it("uses the actual OpenAI completion-token field for its enforced output reservation",async()=>{const f=await fixture([{content:answer,usage}]);f.model.configure({provider:"openai",protocol:"openai-chat-completions",baseUrl:f.model.publicConfig().base_url,model:"fixture",credentialRef:"${secret:ISOLATED_BUDGET_KEY}"});await f.model.decide(f.input);expect(f.requests[0]).toMatchObject({max_completion_tokens:2048});expect(f.requests[0]).not.toHaveProperty("max_tokens");});
 it("accounts for an actual Anthropic messages request with its independent output field",async()=>{const f=await fixture([{content:answer,usage}]);f.model.configure({provider:"anthropic",protocol:"anthropic-messages",baseUrl:f.model.publicConfig().base_url,model:"claude-test",credentialRef:"${secret:ISOLATED_BUDGET_KEY}"});expect(await f.model.decide(f.input)).toMatchObject({kind:"finish"});expect(f.requests[0]).toMatchObject({max_tokens:4096});expect(f.requests[0]).not.toHaveProperty("max_completion_tokens");expect(f.budget.snapshot()).toMatchObject({charged_tokens:15,request_count:1,held_tokens:0});});
 it("accounts for a dedicated real context summary in the same total lease",async()=>{const f=await fixture([{content:JSON.stringify({facts:["One source-grounded fact"],open_questions:[],refs:[]}),usage}]);await f.model.summarizeContext({projectId:f.input.projectId,runId:f.input.runId,modelCallId:"call:summary",promptVersion:"summary.v1",targetTokens:100,sourceText:"One source-grounded fact",requestBudget:f.budget});expect(f.events.filter(event=>event.phase==="reserved").map(event=>event.request_kind)).toEqual(["summary"]);expect(f.budget.snapshot()).toMatchObject({charged_tokens:15,request_count:1});});
 it("an actual time deadline aborts the outstanding HTTP request without admitting another",async()=>{const f=await fixture([{content:answer,usage,delay:400}],{max_tokens:100_000,max_time_ms:100} as {max_tokens:number});await expect(f.model.decide(f.input)).rejects.toMatchObject({code:"model_aborted"});expect(f.requests).toHaveLength(1);expect(f.budget.signal.aborted).toBe(true);expect(f.budget.snapshot().unknown_request_count).toBe(1);});
 it("fences unsupported image accounting before real HTTP even when image input is enabled",async()=>{const f=await fixture([{content:answer,usage}]);await expect(f.model.decide({...f.input,images:[{attachment:{attachment_id:"attachment:one",media_type:"image/png",bytes:8,sha256:`sha256:${"a".repeat(64)}`,source:"user_upload"},data_base64:"iVBORw0KGgo="}]})).rejects.toMatchObject({code:"model_image_unsupported"});expect(f.requests).toHaveLength(0);});
});
