/** Closed IPC vocabulary shared with preload; no generic channel or Electron API escapes. */
export const DESKTOP_IPC = {
  listManagedSkills: "tracegraph:listManagedSkills",
  readManagedSkill: "tracegraph:readManagedSkill",
  validateManagedSkill: "tracegraph:validateManagedSkill",
  managedSkillCommand: "tracegraph:managedSkillCommand",
  getManagedSkillCommandReceipt: "tracegraph:getManagedSkillCommandReceipt",
  getVisualRetentionSettings: "tracegraph:getVisualRetentionSettings",
  updateVisualRetentionSettings: "tracegraph:updateVisualRetentionSettings",
  listVisualEvidence: "tracegraph:listVisualEvidence",
  pinVisualEvidence: "tracegraph:pinVisualEvidence",
  cleanupVisualEvidence: "tracegraph:cleanupVisualEvidence",
  getVisualEvidenceCommandReceipt: "tracegraph:getVisualEvidenceCommandReceipt",

  nativeRunRequested:"tracegraph:native-run-requested",
  listProjectFiles:"tracegraph:listProjectFiles",
  readProjectFile:"tracegraph:readProjectFile",
  saveProjectFile:"tracegraph:saveProjectFile",
  reconcileProjectFileSave:"tracegraph:reconcileProjectFileSave",
  getAnswerFeedback:"tracegraph:getAnswerFeedback",
  setAnswerFeedback:"tracegraph:setAnswerFeedback",
  getModelConnections:"tracegraph:getModelConnections",
  saveModelConnection:"tracegraph:saveModelConnection",
  removeModelConnection:"tracegraph:removeModelConnection",
  testModelConnection:"tracegraph:testModelConnection",
  testModelCapabilities:"tracegraph:testModelCapabilities",
  getModelCapabilityTestReceipt:"tracegraph:getModelCapabilityTestReceipt",
  getSessionRunOptions:"tracegraph:getSessionRunOptions",
  updateSessionRunOptions:"tracegraph:updateSessionRunOptions",
  getPermissionGrant:"tracegraph:getPermissionGrant",
  setPermissionGrant:"tracegraph:setPermissionGrant",

  getConnectionStatus:"tracegraph:connection-status",
  copyText:"tracegraph:clipboard-copy",
  getImageConfig: "tracegraph:image-config-get",
  configureImageProvider: "tracegraph:image-config-set",
  clearImageProvider: "tracegraph:image-config-clear",
  startMediaRun: "tracegraph:media-run-start",
  getArtifactContent: "tracegraph:artifact-content-get",
  startHost: "tracegraph:host-start",
  getMigrationResult: "tracegraph:migration-result",
  previewMigration: "tracegraph:migration-preview",
  commitMigration: "tracegraph:migration-commit",
  openPreview: "tracegraph:preview-open",
  closePreview: "tracegraph:preview-close",
  hostStatus: "tracegraph:host-status",
  listSessions: "tracegraph:sessions-list",
  getSession: "tracegraph:session-get",
  getRun: "tracegraph:run-get",
  startRun: "tracegraph:run-start",
  startChat: "tracegraph:chat-start",
  approve: "tracegraph:run-approve",
  reject: "tracegraph:run-reject",
  stop: "tracegraph:run-stop",
  approvePlan: "tracegraph:run-plan-approve",
  getTodos: "tracegraph:todos-get",
  writeTodo: "tracegraph:todo-write",
  submitUserInput: "tracegraph:run-input",
  getArtifact: "tracegraph:artifact-get",
  resumeSession: "tracegraph:session-resume",
  renameSession: "tracegraph:session-rename",
  deleteSession: "tracegraph:session-delete",
  listProjects: "tracegraph:projects-list",
  openLocalProject: "tracegraph:project-open-local",
  revealProject: "tracegraph:project-reveal",
  removeProject: "tracegraph:project-remove",
  openProjectFile: "tracegraph:project-open-file",
  getModelConfig: "tracegraph:model-config-get",
  configureModel: "tracegraph:model-config-set",
  listMemoryControl: "tracegraph:memory-list",
  createMemoryCandidate: "tracegraph:memory-create",
  reviewMemory: "tracegraph:memory-review",
  correctMemory: "tracegraph:memory-correct",
  revokeMemory: "tracegraph:memory-revoke",
  deleteMemory: "tracegraph:memory-delete",
  listExperienceCases: "tracegraph:experience-list",
  reviewExperienceCase: "tracegraph:experience-review",
  createProject: "tracegraph:createProject",
  getPermissionConfig: "tracegraph:getPermissionConfig",
  configurePermissionPreset: "tracegraph:configurePermissionPreset",
  getTelemetryStatus: "tracegraph:getTelemetryStatus",
  getUsage: "tracegraph:getUsage",
  listExtensions: "tracegraph:listExtensions",
  listSkills: "tracegraph:listSkills",
  getMcpStatus: "tracegraph:getMcpStatus",
  getLspStatus: "tracegraph:getLspStatus",
  restartMcpServer: "tracegraph:restartMcpServer",
  reloadExtension: "tracegraph:reloadExtension",
  runExtensionCommand: "tracegraph:runExtensionCommand",
  createReplay: "tracegraph:createReplay",
  getReplayDiff: "tracegraph:getReplayDiff",
  exitReplay: "tracegraph:exitReplay",
  uploadAttachment: "tracegraph:uploadAttachment",
  getAttachmentContent: "tracegraph:getAttachmentContent",
  getSubagent: "tracegraph:getSubagent",
  getTeam: "tracegraph:getTeam",
  createTeam: "tracegraph:createTeam",
  sendTeamMailbox: "tracegraph:sendTeamMailbox",
  claimTeamMailbox: "tracegraph:claimTeamMailbox",
  writeTeamTask: "tracegraph:writeTeamTask",
  heartbeatTeam: "tracegraph:heartbeatTeam",
  sweepLostTeamMembers: "tracegraph:sweepLostTeamMembers",
  rollbackAction: "tracegraph:rollbackAction",
  getBrowserCommandReceipt: "tracegraph:getBrowserCommandReceipt",
  getComputerStatus: "tracegraph:getComputerStatus",
  listComputerTargets: "tracegraph:listComputerTargets",
  requestComputerGrant: "tracegraph:requestComputerGrant",
  revokeComputerGrant: "tracegraph:revokeComputerGrant",
  acquireComputerLease: "tracegraph:acquireComputerLease",
  resumeComputerLease: "tracegraph:resumeComputerLease",
  releaseComputerLease: "tracegraph:releaseComputerLease",
  observeComputer: "tracegraph:observeComputer",
  computerAction: "tracegraph:computerAction",
  getComputerCommandReceipt: "tracegraph:getComputerCommandReceipt",
  getComputerCapture: "tracegraph:getComputerCapture",
  getPersonalProfile: "tracegraph:getPersonalProfile",
  updatePersonalProfile: "tracegraph:updatePersonalProfile",
  getPersonalProfileCommandReceipt: "tracegraph:getPersonalProfileCommandReceipt",
  queryPersonalUsage: "tracegraph:queryPersonalUsage",
  searchPublicSessions: "tracegraph:searchPublicSessions",
  getBrowserStatus: "tracegraph:getBrowserStatus",
  requestBrowserGrant: "tracegraph:requestBrowserGrant",
  browserCommand: "tracegraph:browserCommand",
  observeBrowser: "tracegraph:observeBrowser",
  getBrowserEvidence: "tracegraph:getBrowserEvidence",
  listGoals: "tracegraph:listGoals",
  createGoal: "tracegraph:createGoal",
  getGoal: "tracegraph:getGoal",
  goalCommand: "tracegraph:goalCommand",
  getGoalCreationReceipt: "tracegraph:getGoalCreationReceipt",
  getGoalCommandReceipt: "tracegraph:getGoalCommandReceipt",
  getGoalBudget: "tracegraph:getGoalBudget",
  getWorkbenchSettingsHistory: "tracegraph:getWorkbenchSettingsHistory",
  restoreWorkbenchSettings: "tracegraph:restoreWorkbenchSettings",
  getProjectRunDefaults: "tracegraph:getProjectRunDefaults",
  updateProjectRunDefaults: "tracegraph:updateProjectRunDefaults",
  resetSessionRunOptions: "tracegraph:resetSessionRunOptions",
  getWorkbenchSettings: "tracegraph:getWorkbenchSettings",
  updateWorkbenchSettings: "tracegraph:updateWorkbenchSettings",
  getCapabilities: "tracegraph:getCapabilities",
  testModel: "tracegraph:testModel",
  getWorkbenchResources: "tracegraph:getWorkbenchResources",
  workbenchCommand: "tracegraph:workbenchCommand",
  openStream: "tracegraph:openStream",
  readStream: "tracegraph:readStream",
  closeStream: "tracegraph:closeStream",
} as const;
