import {afterEach,beforeEach,describe,it,expect,vi} from "vitest";
import {WorkbenchSettingsSnapshotSchema,type WorkbenchResources} from "@tracegraph/contracts";
import type {NativeBackgroundController,BackgroundMenuItem} from "./native-background.js";
const d=vi.hoisted(()=>({controller:undefined as NativeBackgroundController|undefined,menu:[] as BackgroundMenuItem[],notices:[] as Array<{click:()=>void}>,events:new Map<string,Function>(),windowEvents:new Map<string,Function>(),handlers:new Map<string,Function>(),bounds:[] as Array<unknown>,pins:[] as boolean[],send:vi.fn(),hide:vi.fn(),load:vi.fn(async():Promise<void>=>undefined),quit:vi.fn(),close:vi.fn(),workbenchCommand:vi.fn(),getRun:vi.fn(),dialog:vi.fn(),effect:undefined as any,owner:undefined as any,settings:undefined as any,resources:undefined as WorkbenchResources|undefined}));
vi.mock("./native-background.js",async original=>{const actual=await original<typeof import("./native-background.js")>();return {...actual,NativeBackgroundController:class extends actual.NativeBackgroundController{constructor(context:any){super(context);d.controller=this;}}};});
vi.mock("./native-background-electron.js",()=>({createNativeBackgroundEffects:()=>{d.effect={setMenu:(items:BackgroundMenuItem[])=>{d.menu=items;},setTooltip:vi.fn(),destroyTray:vi.fn(),notify:vi.fn(input=>{d.notices.push(input);return true;}),startPowerBlocker:vi.fn(()=>91),stopPowerBlocker:vi.fn()};return d.effect;}}));
vi.mock("electron",()=>({app:{isPackaged:false,whenReady:async()=>undefined,on:(name:string,callback:Function)=>d.events.set(name,callback),quit:d.quit},BrowserWindow:class{static getAllWindows(){return [];}webContents={id:7,setWindowOpenHandler:vi.fn(),on:vi.fn(),send:d.send};show=vi.fn();hide=d.hide;focus=vi.fn();isDestroyed=()=>false;getBounds=()=>({x:10,y:20,width:1440,height:900});setBounds=(next:unknown)=>d.bounds.push(next);setMinimumSize=vi.fn();setAlwaysOnTop=(enabled:boolean)=>d.pins.push(enabled);loadFile=d.load;once=vi.fn();on(name:string,cb:Function){d.windowEvents.set(name,cb);}},ipcMain:{handle:(name:string,callback:Function)=>d.handlers.set(name,callback)},dialog:{showMessageBox:d.dialog},screen:{getDisplayMatching:()=>({workArea:{x:0,y:0,width:1440,height:900}})},session:{defaultSession:{setPermissionRequestHandler:vi.fn()}},shell:{},clipboard:{}}));
vi.mock("@tracegraph/desktop-host",()=>({DESKTOP_HOST_PACKAGE_VERSION:"0.1.0-alpha.0",connectLocalHost:vi.fn(),LocalHostConnectionSupervisor:class{constructor(private options:any){}getSnapshot(){return {state:"connected",generation:4};}async initialize(){await this.options.onRebind(d.owner,4);}async read(fn:Function){return fn(d.owner);}async mutate(fn:Function){return fn(d.owner);}async refresh(){}async close(){await this.options.onDisconnect();await d.owner.close();}}}));
beforeEach(()=>{vi.resetModules();vi.clearAllMocks();d.controller=undefined;d.menu=[];d.notices=[];d.bounds=[];d.pins=[];d.events.clear();d.windowEvents.clear();d.handlers.clear();vi.stubEnv("OUTLIVE_PROFILE_ROOT","/synthetic-app105-only");d.settings=WorkbenchSettingsSnapshotSchema.parse({config_version:"outlive.workbench.v1",profile_id:"profile:real",revision:5,settings:{general:{prevent_sleep_during_tasks:true}},fields:[],pending_restart:[]});d.resources={runs:[{run_id:"run:active",project_id:"project:real",task:"Task",status:"running"}],terminals:[],previews:[],schedules:[],archived_session_ids:[],notifications:[]};d.dialog.mockResolvedValue({response:0});d.getRun.mockResolvedValue({run_id:"run:done",project_id:"project:real",session_id:"session:real"});d.owner={status:{profile_id:"profile:real",profile_root:"/synthetic-app105-only",protocol_version:"outlive.local-host.v1",boot_nonce:"owner:real",http_address:"http://127.0.0.1:54321"},client:{bootstrap:async()=>({}),getWorkbenchSettings:async()=>d.settings,getWorkbenchResources:async()=>d.resources,getRun:d.getRun,workbenchCommand:d.workbenchCommand,updateWorkbenchSettings:vi.fn(async()=>d.settings)},close:d.close};});
afterEach(async()=>{await d.controller?.close();vi.unstubAllEnvs();});
async function start(){await import("./main.js");await vi.waitFor(()=>expect(d.controller).toBeDefined());await d.controller!.refresh();}
function emit(){d.resources!.notifications!.push({notification_id:"event:actual",event_id:"event:actual",run_id:"run:done",project_id:"project:real",session_id:"session:real",task:"Private task title",status:"completed",occurred_at:"2026-10-05T00:00:00Z"});}
describe("Main native notification authority and application lifetime",()=>{
 it("shows only a current scoped Run with fixed read-only identifiers after the renderer finishes loading",async()=>{await start();emit();await d.controller!.refresh();d.windowEvents.get("closed")?.();let ready!:()=>void;d.load.mockImplementationOnce(()=>new Promise<void>(resolve=>{ready=resolve;}));d.notices[0]!.click();await vi.waitFor(()=>expect(d.load).toHaveBeenCalledTimes(2));expect(d.send).not.toHaveBeenCalled();ready();await vi.waitFor(()=>expect(d.send).toHaveBeenCalledWith("tracegraph:native-run-requested",{event_id:"event:actual",run_id:"run:done",project_id:"project:real",session_id:"session:real",connection_generation:4}));expect(d.workbenchCommand).not.toHaveBeenCalled();});
 it("rejects a changed Run project/session and does not turn a notification click into execution",async()=>{await start();emit();await d.controller!.refresh();d.getRun.mockResolvedValue({run_id:"run:done",project_id:"project:foreign",session_id:"session:real"});d.notices[0]!.click();await vi.waitFor(()=>expect(d.getRun).toHaveBeenCalledOnce());await new Promise(resolve=>setImmediate(resolve));expect(d.send).not.toHaveBeenCalled();expect(d.workbenchCommand).not.toHaveBeenCalled();});
 it("does not read or notify from replay and immediately releases the power blocker",async()=>{await start();expect(d.effect.startPowerBlocker).toHaveBeenCalledOnce();d.owner.client.replayActive=true;emit();await d.controller!.refresh();expect(d.notices).toHaveLength(0);expect(d.effect.stopPowerBlocker).toHaveBeenCalledWith(91);});
 it("keeps the Tray on window close, detaches on explicit quit, and never stops the owner implicitly",async()=>{await start();d.events.get("window-all-closed")?.();expect(d.quit).not.toHaveBeenCalled();d.menu.find(item=>item.label?.includes("退出应用"))!.click!();expect(d.quit).toHaveBeenCalledOnce();const preventDefault=vi.fn();d.events.get("before-quit")?.({preventDefault});expect(d.close).not.toHaveBeenCalled();expect(preventDefault).not.toHaveBeenCalled();d.events.get("will-quit")?.({preventDefault});await vi.waitFor(()=>expect(d.close).toHaveBeenCalledOnce());expect(preventDefault).toHaveBeenCalledOnce();expect(d.effect.stopPowerBlocker).toHaveBeenCalledWith(91);expect(d.effect.destroyTray).toHaveBeenCalledOnce();expect(d.workbenchCommand).not.toHaveBeenCalled();});
 it("hides ordinary window close without destroying the renderer or detaching background reads",async()=>{await start();const preventDefault=vi.fn();d.windowEvents.get("close")?.({preventDefault});expect(preventDefault).toHaveBeenCalledOnce();expect(d.hide).toHaveBeenCalledOnce();expect(d.load).toHaveBeenCalledOnce();expect(d.close).not.toHaveBeenCalled();expect(d.workbenchCommand).not.toHaveBeenCalled();await d.controller!.refresh();expect(d.effect.setTooltip).toHaveBeenCalled();});
 it("changes only the same trusted window for floating and pin actions",async()=>{await start();expect(d.pins).toEqual([false]);d.menu.find(item=>item.label==="浮动聊天窗口")!.click!();await vi.waitFor(()=>expect(d.bounds).toEqual([{x:10,y:20,width:880,height:700}]));await vi.waitFor(()=>expect(d.menu.find(item=>item.label==="浮动聊天窗口")?.checked).toBe(true));d.menu.find(item=>item.label==="窗口置顶")!.click!();await vi.waitFor(()=>expect(d.pins).toEqual([false,true]));await vi.waitFor(()=>expect(d.menu.find(item=>item.label==="窗口置顶")?.checked).toBe(true));d.menu.find(item=>item.label==="浮动聊天窗口")!.click!();await vi.waitFor(()=>expect(d.bounds).toHaveLength(2));expect(d.load).toHaveBeenCalledOnce();expect(d.workbenchCommand).not.toHaveBeenCalled();expect(d.close).not.toHaveBeenCalled();});
 it("requires concrete native confirmation before dispatching canonical host.stop",async()=>{await start();d.menu.find(item=>item.label?.includes("停止后台并退出"))!.click!();await vi.waitFor(()=>expect(d.dialog).toHaveBeenCalledOnce());expect(d.workbenchCommand).not.toHaveBeenCalled();await vi.waitFor(()=>expect(d.menu.find(item=>item.label?.includes("停止后台并退出"))?.enabled).toBe(true));d.dialog.mockResolvedValue({response:1});d.menu.find(item=>item.label?.includes("停止后台并退出"))!.click!();await vi.waitFor(()=>expect(d.workbenchCommand).toHaveBeenCalledWith({type:"host.stop",command_id:expect.any(String)}));expect(d.quit).toHaveBeenCalledOnce();});
});
