import { describe, expect, it, vi } from "vitest";
import { readFile } from "node:fs/promises";
import type { TraceGraphClient } from "@tracegraph/sdk";
import { invokeDirectDesktopRoute } from "./direct-routes.js";
const input={command_id:"probe:one",expected_revision:2,model:"fixture",features:["tools"],confirmed:true};
const result={command_id:input.command_id,connection_id:"fixture-service",connection_revision:2,model:"fixture",provider:"custom",protocol:"openai-chat-completions",checked_at:"2026-10-05T00:00:00Z",duration_ms:2,results:[{feature:"tools",status:"unknown",code:"model_timeout",duration_ms:2,dispatched:true,usage_status:"unknown"}]};
describe("fixed Desktop model capability bridge",()=>{
 it("validates closed input before invoking provider test and preserves unknown inside completed receipts",async()=>{const testModelCapabilities=vi.fn(async()=>result),getModelCapabilityTestReceipt=vi.fn(async()=>({command_id:input.command_id,state:"completed",result}));const client={testModelCapabilities,getModelCapabilityTestReceipt} as unknown as TraceGraphClient;expect(await invokeDirectDesktopRoute(client,"testModelCapabilities",["fixture-service",input])).toEqual(result);await expect(invokeDirectDesktopRoute(client,"testModelCapabilities",["fixture-service",{...input,confirmed:false}])).rejects.toThrow();await expect(invokeDirectDesktopRoute(client,"testModelCapabilities",["fixture-service",{...input,path:"/private"}])).rejects.toThrow();expect(testModelCapabilities).toHaveBeenCalledOnce();expect(await invokeDirectDesktopRoute(client,"getModelCapabilityTestReceipt",[input.command_id])).toMatchObject({state:"completed",result:{results:[{status:"unknown"}]}});});
 it("keeps receipt lookup on fixed read channel and rejects secret-bearing response fields",async()=>{const main=await readFile(new URL("./main.ts",import.meta.url),"utf8");expect(main.match(/const readChannels[^;]+/u)?.[0]).toContain("DESKTOP_IPC.getModelCapabilityTestReceipt,");const testModelCapabilities=vi.fn(async()=>({...result,api_key:"must-never-cross"}));await expect(invokeDirectDesktopRoute({testModelCapabilities} as unknown as TraceGraphClient,"testModelCapabilities",["fixture-service",input])).rejects.toThrow();});
});
