import {describe,it,expect,vi} from "vitest";
import {WorkbenchSettingsSnapshotSchema,type WorkbenchNotification,type NativeRunNavigation} from "@tracegraph/contracts";
import {NativeBackgroundController,type NativeBackgroundRead,type BackgroundMenuItem} from "./native-background.js";
import {NativeRunNavigationSchema} from "@tracegraph/contracts";
const notification=(id:string,status:WorkbenchNotification["status"]="completed"):WorkbenchNotification=>({notification_id:id,event_id:id,run_id:"run:real",project_id:"project:real",session_id:"session:real",task:"DO_NOT_SHOW_TASK_IN_OS_NOTIFICATION",status,occurred_at:"2026-10-05T00:00:00Z"});
function fixture(){
 let current:NativeBackgroundRead|undefined={profileId:"profile:real",ownerNonce:"owner:1",generation:1,settings:WorkbenchSettingsSnapshotSchema.parse({config_version:"outlive.workbench.v1",profile_id:"profile:real",revision:0,settings:{},fields:[],pending_restart:[]}),resources:{runs:[],terminals:[],previews:[],schedules:[],archived_session_ids:[],notifications:[notification("event:historic")]}};
 let menu:BackgroundMenuItem[]=[];const notices:Array<{title:string;body:string;click:()=>void;failed:()=>void}>=[];
 const effects={setMenu:vi.fn((value:BackgroundMenuItem[])=>{menu=value;}),setTooltip:vi.fn(),destroyTray:vi.fn(),notify:vi.fn(input=>{notices.push(input);return true;}),startPowerBlocker:vi.fn(()=>23),stopPowerBlocker:vi.fn()};
 const context={read:vi.fn(async()=>current),showWindow:vi.fn(async()=>undefined),navigate:vi.fn(async()=>undefined),setPreventSleep:vi.fn(async()=>undefined),stopBackgroundAndQuit:vi.fn(async()=>undefined),quit:vi.fn(),effects};
 const controller=new NativeBackgroundController(context);
 return {controller,context,effects,notices,get current():NativeBackgroundRead{return current!;},set current(value:NativeBackgroundRead|undefined){current=value;},get menu(){return menu;}};
}
describe("native background entry projections",()=>{
 it("baselines existing canonical events, deduplicates by event ID across owner replacement and never copies task content",async()=>{const f=fixture();try{await f.controller.refresh();expect(f.notices).toHaveLength(0);f.current.resources.notifications!.push(notification("event:done"));await f.controller.refresh();expect(f.notices).toHaveLength(1);expect(JSON.stringify(f.notices)).not.toContain("DO_NOT_SHOW_TASK");f.current.ownerNonce="owner:2";f.current.generation=2;await f.controller.refresh();expect(f.notices).toHaveLength(1);f.notices[0]!.click();await vi.waitFor(()=>expect(f.context.navigate).toHaveBeenCalledWith(notification("event:done"),1,"profile:real"));expect(f.context.stopBackgroundAndQuit).not.toHaveBeenCalled();expect(f.context.quit).not.toHaveBeenCalled();}finally{await f.controller.close();}});
 it("respects completion/failure/approval switches and starts a separate historical baseline after changing profiles",async()=>{const f=fixture();try{await f.controller.refresh();f.current.settings.settings.general.notify_completed=false;f.current.settings.settings.general.notify_failed=false;f.current.settings.settings.general.notify_approval=false;f.current.resources.notifications!.push(notification("event:done"),notification("event:failed","failed"),notification("event:ask","awaiting_approval"));await f.controller.refresh();expect(f.notices).toHaveLength(0);f.current.settings.settings.general.notify_approval=true;f.current.resources.notifications!.push(notification("event:plan","awaiting_plan_approval"));await f.controller.refresh();expect(f.notices).toHaveLength(1);f.current.profileId="profile:another";f.current.resources.notifications=[notification("event:other")];await f.controller.refresh();expect(f.notices).toHaveLength(1);}finally{await f.controller.close();}});
 it("holds power only for opted-in executing Runs and releases while awaiting approval, queued, replay/offline or closed",async()=>{const f=fixture();try{f.current.resources.runs=[{run_id:"run:active",project_id:"project:real",task:"work",status:"running"}];await f.controller.refresh();expect(f.effects.startPowerBlocker).not.toHaveBeenCalled();f.current.settings.settings.general.prevent_sleep_during_tasks=true;await f.controller.refresh();await f.controller.refresh();expect(f.effects.startPowerBlocker).toHaveBeenCalledOnce();f.current.resources.runs[0]!.status="awaiting_approval";await f.controller.refresh();expect(f.effects.stopPowerBlocker).toHaveBeenCalledWith(23);f.current.resources.runs[0]!.status="queued";await f.controller.refresh();expect(f.effects.startPowerBlocker).toHaveBeenCalledOnce();f.current.resources.runs[0]!.status="indexing";await f.controller.refresh();expect(f.effects.startPowerBlocker).toHaveBeenCalledTimes(2);f.current=undefined;await f.controller.refresh();expect(f.effects.stopPowerBlocker).toHaveBeenCalledTimes(2);}finally{await f.controller.close();expect(f.effects.destroyTray).toHaveBeenCalledOnce();}});
 it("uses distinct human menu actions for quit, stop background and persisted opt-in",async()=>{const f=fixture();try{await f.controller.refresh();f.menu.find(item=>item.type==="checkbox")!.click!();await vi.waitFor(()=>expect(f.context.setPreventSleep).toHaveBeenCalledWith(true));await vi.waitFor(()=>expect(f.menu.find(item=>item.type==="checkbox")?.enabled).toBe(true));f.menu.find(item=>item.label?.includes("退出应用"))!.click!();expect(f.context.quit).toHaveBeenCalledOnce();expect(f.context.stopBackgroundAndQuit).not.toHaveBeenCalled();f.menu.find(item=>item.label?.includes("停止后台并退出"))!.click!();await vi.waitFor(()=>expect(f.context.stopBackgroundAndQuit).toHaveBeenCalledWith(f.current));}finally{await f.controller.close();}});
 it("marks unavailable notification delivery and handles navigation failure with only a window show",async()=>{const f=fixture();try{await f.controller.refresh();f.effects.notify.mockImplementation(input=>{f.notices.push(input);return false;});f.context.navigate.mockRejectedValue(new Error("scope changed"));f.current.resources.notifications!.push(notification("event:new"));await f.controller.refresh();expect(f.effects.setTooltip).toHaveBeenLastCalledWith(expect.stringContaining("通知不可用"));f.notices[0]!.click();await vi.waitFor(()=>expect(f.context.showWindow).toHaveBeenCalledOnce());expect(f.context.stopBackgroundAndQuit).not.toHaveBeenCalled();await f.controller.close();f.notices[0]!.click();expect(f.context.showWindow).toHaveBeenCalledOnce();}finally{await f.controller.close();}});
 it("coalesces overlapping polls and releases a blocker when the live read fails",async()=>{const f=fixture();try{f.current.settings.settings.general.prevent_sleep_during_tasks=true;f.current.resources.runs=[{run_id:"run:active",project_id:"project:real",task:"work",status:"running"}];await f.controller.refresh();let release!:()=>void;f.context.read.mockImplementation(async()=>{await new Promise<void>(resolve=>{release=resolve;});throw new Error("replay authority");});const one=f.controller.refresh(),two=f.controller.refresh();expect(f.context.read).toHaveBeenCalledTimes(2);release();await Promise.all([one,two]);expect(f.effects.stopPowerBlocker).toHaveBeenCalledWith(23);}finally{await f.controller.close();}});
 it("keeps native navigation a closed read-only identifier schema",()=>{const good:NativeRunNavigation={event_id:"event:canonical",run_id:"run:real",project_id:"project:real",connection_generation:2};expect(NativeRunNavigationSchema.parse(good)).toEqual(good);for(const extra of [{resume:true},{path:"/private"},{token:"secret"},{type:"approve"}])expect(()=>NativeRunNavigationSchema.parse({...good,...extra})).toThrow();expect(()=>NativeRunNavigationSchema.parse({...good,connection_generation:-1})).toThrow();});
});
