import { contextBridge, ipcRenderer } from "electron";
import type { DesktopBridgeApi, DesktopHostStatus } from "./bridge-contract.js";
import type {
  HostConnectionSnapshot,
  NativeRunNavigation,
  ModelConfigUpdateRequest,
  ProjectSummary,
  PublicModelConfigResponse,
  SessionListQuery,
  SessionListResponse,
  SessionReadResult,
  RunProjection,
  StartRunRequest,
  MemoryCandidateCreateRequest,
  MemoryControlItem,
  MemoryControlListResponse,
  MemoryCorrectionRequest,
  MemoryDeleteRequest,
  MemoryDeleteResponse,
  MemoryReviewRequest,
  MemoryRevokeRequest,
  ExperienceControlListResponse,
  ExperienceLifecycleReviewRequest,
  ExperienceLifecycleReviewResponse,
} from "@tracegraph/contracts";

// Keep the sandboxed preload self-contained: its only runtime import is Electron.
const DESKTOP_IPC = {
  listManagedSkills: "tracegraph:listManagedSkills",
  readManagedSkill: "tracegraph:readManagedSkill",
  validateManagedSkill: "tracegraph:validateManagedSkill",
  managedSkillCommand: "tracegraph:managedSkillCommand",
  getManagedSkillCommandReceipt: "tracegraph:getManagedSkillCommandReceipt",
  getVisualRetentionSettings: "tracegraph:getVisualRetentionSettings",
  updateVisualRetentionSettings: "tracegraph:updateVisualRetentionSettings",
  listVisualEvidence: "tracegraph:listVisualEvidence",
  pinVisualEvidence: "tracegraph:pinVisualEvidence",
  cleanupVisualEvidence: "tracegraph:cleanupVisualEvidence",
  getVisualEvidenceCommandReceipt: "tracegraph:getVisualEvidenceCommandReceipt",

  listProjectFiles:"tracegraph:listProjectFiles",
  readProjectFile:"tracegraph:readProjectFile",
  saveProjectFile:"tracegraph:saveProjectFile",
  reconcileProjectFileSave:"tracegraph:reconcileProjectFileSave",
  getAnswerFeedback:"tracegraph:getAnswerFeedback",
  setAnswerFeedback:"tracegraph:setAnswerFeedback",
  getModelConnections:"tracegraph:getModelConnections",
  saveModelConnection:"tracegraph:saveModelConnection",
  removeModelConnection:"tracegraph:removeModelConnection",
  testModelConnection:"tracegraph:testModelConnection",
  testModelCapabilities:"tracegraph:testModelCapabilities",
  getModelCapabilityTestReceipt:"tracegraph:getModelCapabilityTestReceipt",
  getSessionRunOptions:"tracegraph:getSessionRunOptions",
  updateSessionRunOptions:"tracegraph:updateSessionRunOptions",
  getPermissionGrant:"tracegraph:getPermissionGrant",
  setPermissionGrant:"tracegraph:setPermissionGrant",

  getConnectionStatus:"tracegraph:connection-status",
  copyText:"tracegraph:clipboard-copy",
  getImageConfig: "tracegraph:image-config-get",
  configureImageProvider: "tracegraph:image-config-set",
  clearImageProvider: "tracegraph:image-config-clear",
  startMediaRun: "tracegraph:media-run-start",
  getArtifactContent: "tracegraph:artifact-content-get",
  startHost: "tracegraph:host-start",
  getMigrationResult: "tracegraph:migration-result",
  previewMigration: "tracegraph:migration-preview",
  commitMigration: "tracegraph:migration-commit",
  openPreview: "tracegraph:preview-open",
  closePreview: "tracegraph:preview-close",
  hostStatus: "tracegraph:host-status",
  listSessions: "tracegraph:sessions-list",
  getSession: "tracegraph:session-get",
  getRun: "tracegraph:run-get",
  startRun: "tracegraph:run-start",
  startChat: "tracegraph:chat-start",
  approve: "tracegraph:run-approve",
  reject: "tracegraph:run-reject",
  stop: "tracegraph:run-stop",
  approvePlan: "tracegraph:run-plan-approve",
  getTodos: "tracegraph:todos-get",
  writeTodo: "tracegraph:todo-write",
  submitUserInput: "tracegraph:run-input",
  getArtifact: "tracegraph:artifact-get",
  resumeSession: "tracegraph:session-resume",
  renameSession: "tracegraph:session-rename",
  deleteSession: "tracegraph:session-delete",
  listProjects: "tracegraph:projects-list",
  openLocalProject: "tracegraph:project-open-local",
  revealProject: "tracegraph:project-reveal",
  removeProject: "tracegraph:project-remove",
  openProjectFile: "tracegraph:project-open-file",
  getModelConfig: "tracegraph:model-config-get",
  configureModel: "tracegraph:model-config-set",
  listMemoryControl: "tracegraph:memory-list",
  createMemoryCandidate: "tracegraph:memory-create",
  reviewMemory: "tracegraph:memory-review",
  correctMemory: "tracegraph:memory-correct",
  revokeMemory: "tracegraph:memory-revoke",
  deleteMemory: "tracegraph:memory-delete",
  listExperienceCases: "tracegraph:experience-list",
  reviewExperienceCase: "tracegraph:experience-review",
  createProject: "tracegraph:createProject",
  getPermissionConfig: "tracegraph:getPermissionConfig",
  configurePermissionPreset: "tracegraph:configurePermissionPreset",
  getTelemetryStatus: "tracegraph:getTelemetryStatus",
  getUsage: "tracegraph:getUsage",
  listExtensions: "tracegraph:listExtensions",
  listSkills: "tracegraph:listSkills",
  getMcpStatus: "tracegraph:getMcpStatus",
  getLspStatus: "tracegraph:getLspStatus",
  restartMcpServer: "tracegraph:restartMcpServer",
  reloadExtension: "tracegraph:reloadExtension",
  runExtensionCommand: "tracegraph:runExtensionCommand",
  createReplay: "tracegraph:createReplay",
  getReplayDiff: "tracegraph:getReplayDiff",
  exitReplay: "tracegraph:exitReplay",
  uploadAttachment: "tracegraph:uploadAttachment",
  getAttachmentContent: "tracegraph:getAttachmentContent",
  getSubagent: "tracegraph:getSubagent",
  getTeam: "tracegraph:getTeam",
  createTeam: "tracegraph:createTeam",
  sendTeamMailbox: "tracegraph:sendTeamMailbox",
  claimTeamMailbox: "tracegraph:claimTeamMailbox",
  writeTeamTask: "tracegraph:writeTeamTask",
  heartbeatTeam: "tracegraph:heartbeatTeam",
  sweepLostTeamMembers: "tracegraph:sweepLostTeamMembers",
  rollbackAction: "tracegraph:rollbackAction",
  getBrowserCommandReceipt: "tracegraph:getBrowserCommandReceipt",
  getComputerStatus: "tracegraph:getComputerStatus",
  listComputerTargets: "tracegraph:listComputerTargets",
  requestComputerGrant: "tracegraph:requestComputerGrant",
  revokeComputerGrant: "tracegraph:revokeComputerGrant",
  acquireComputerLease: "tracegraph:acquireComputerLease",
  resumeComputerLease: "tracegraph:resumeComputerLease",
  releaseComputerLease: "tracegraph:releaseComputerLease",
  observeComputer: "tracegraph:observeComputer",
  computerAction: "tracegraph:computerAction",
  getComputerCommandReceipt: "tracegraph:getComputerCommandReceipt",
  getComputerCapture: "tracegraph:getComputerCapture",
  getPersonalProfile: "tracegraph:getPersonalProfile",
  updatePersonalProfile: "tracegraph:updatePersonalProfile",
  getPersonalProfileCommandReceipt: "tracegraph:getPersonalProfileCommandReceipt",
  queryPersonalUsage: "tracegraph:queryPersonalUsage",
  searchPublicSessions: "tracegraph:searchPublicSessions",
  getBrowserStatus: "tracegraph:getBrowserStatus",
  requestBrowserGrant: "tracegraph:requestBrowserGrant",
  browserCommand: "tracegraph:browserCommand",
  observeBrowser: "tracegraph:observeBrowser",
  getBrowserEvidence: "tracegraph:getBrowserEvidence",
  listGoals: "tracegraph:listGoals",
  createGoal: "tracegraph:createGoal",
  getGoal: "tracegraph:getGoal",
  goalCommand: "tracegraph:goalCommand",
  getGoalCreationReceipt: "tracegraph:getGoalCreationReceipt",
  getGoalCommandReceipt: "tracegraph:getGoalCommandReceipt",
  getGoalBudget: "tracegraph:getGoalBudget",
  getWorkbenchSettingsHistory: "tracegraph:getWorkbenchSettingsHistory",
  restoreWorkbenchSettings: "tracegraph:restoreWorkbenchSettings",
  getProjectRunDefaults: "tracegraph:getProjectRunDefaults",
  updateProjectRunDefaults: "tracegraph:updateProjectRunDefaults",
  resetSessionRunOptions: "tracegraph:resetSessionRunOptions",
  getWorkbenchSettings: "tracegraph:getWorkbenchSettings",
  updateWorkbenchSettings: "tracegraph:updateWorkbenchSettings",
  getCapabilities: "tracegraph:getCapabilities",
  testModel: "tracegraph:testModel",
  getWorkbenchResources: "tracegraph:getWorkbenchResources",
  workbenchCommand: "tracegraph:workbenchCommand",
  openStream: "tracegraph:openStream",
  readStream: "tracegraph:readStream",
  closeStream: "tracegraph:closeStream",
} as const;

// Only Main's closed connection failure envelope crosses IPC; no generic renderer invocation.
const connectionCodes=new Set(["host_offline","host_stopped","host_reconnecting","host_recovering","host_upgrade_required","host_profile_invalid","host_startup_failed","host_read_stale","host_replay_stale","host_recovery_exhausted","host_write_outcome_unknown"]);
async function invoke(channel:(typeof DESKTOP_IPC)[keyof typeof DESKTOP_IPC],...args:unknown[]):Promise<unknown>{
  const value:unknown=await ipcRenderer.invoke(channel,...args);
  if(typeof value==="object"&&value!==null&&"__outlive_connection_error" in value){
    const envelope=value.__outlive_connection_error as {code?:unknown;connection?:HostConnectionSnapshot};
    if(typeof envelope.code!=="string"||!connectionCodes.has(envelope.code)||!envelope.connection||!Number.isSafeInteger(envelope.connection.generation))throw new Error("Invalid Host connection failure");
    throw Object.assign(new Error(envelope.connection.message??"The local Host connection is unavailable"),{name:"HostConnectionError",code:envelope.code,connection:envelope.connection});
  }
  if(typeof value==="object"&&value!==null&&"__outlive_command_rejected" in value){
    const envelope=value.__outlive_command_rejected as {code?:unknown;admission?:unknown;status?:unknown;commandDispatched?:unknown};
    const auth=typeof envelope.code==="string"&&["capability_required","capability_invalid","capability_expired"].includes(envelope.code);
    if(envelope.admission!=="rejected"||!(auth?envelope.status===401:envelope.code==="mutation_preflight_failed"&&envelope.commandDispatched===false))throw new Error("Invalid Host admission rejection");
    throw Object.assign(new Error(auth?"Your connection expired. Repair the connection before retrying.":"The connection could not be verified. No command was sent. Repair the connection before retrying."),{code:envelope.code,admission:"rejected",...(auth?{status:401,body:{error:envelope.code}}:{commandDispatched:false})});
  }
  return value;
}

// This is the only pushed native event: validated, read-only identifiers.
const nativeRunListeners = new Set<(navigation: NativeRunNavigation) => void>();
let bufferedNativeRun: NativeRunNavigation | undefined;
function parseNativeRunNavigation(value: unknown): NativeRunNavigation | undefined {
  if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;
  const record = value as Record<string, unknown>;
  if (Object.keys(record).some(key => !["event_id", "run_id", "project_id", "session_id", "connection_generation"].includes(key))) return undefined;
  const identifier = (input: unknown) => typeof input === "string" && input.trim().length > 0 && input.length <= 160;
  if (![record.event_id, record.run_id, record.project_id].every(identifier) || (record.session_id !== undefined && !identifier(record.session_id)) || !Number.isSafeInteger(record.connection_generation) || Number(record.connection_generation) < 0) return undefined;
  return {event_id: record.event_id as string, run_id: record.run_id as string, project_id: record.project_id as string, ...(record.session_id === undefined ? {} : {session_id: record.session_id as string}), connection_generation: record.connection_generation as number};
}
ipcRenderer.on("tracegraph:native-run-requested", (_event, value: unknown) => {
  const navigation = parseNativeRunNavigation(value); if (!navigation) return;
  if (nativeRunListeners.size === 0) bufferedNativeRun = navigation;
  for (const listener of nativeRunListeners) { try { listener(navigation); } catch { /* One consumer cannot broaden or stop the fixed event. */ } }
});

const bridge: DesktopBridgeApi = Object.freeze({
  listManagedSkills: (...args: Parameters<DesktopBridgeApi["listManagedSkills"]>) => invoke(DESKTOP_IPC.listManagedSkills, ...args) as ReturnType<DesktopBridgeApi["listManagedSkills"]>,
  readManagedSkill: (...args: Parameters<DesktopBridgeApi["readManagedSkill"]>) => invoke(DESKTOP_IPC.readManagedSkill, ...args) as ReturnType<DesktopBridgeApi["readManagedSkill"]>,
  validateManagedSkill: (...args: Parameters<DesktopBridgeApi["validateManagedSkill"]>) => invoke(DESKTOP_IPC.validateManagedSkill, ...args) as ReturnType<DesktopBridgeApi["validateManagedSkill"]>,
  managedSkillCommand: (...args: Parameters<DesktopBridgeApi["managedSkillCommand"]>) => invoke(DESKTOP_IPC.managedSkillCommand, ...args) as ReturnType<DesktopBridgeApi["managedSkillCommand"]>,
  getManagedSkillCommandReceipt: (...args: Parameters<DesktopBridgeApi["getManagedSkillCommandReceipt"]>) => invoke(DESKTOP_IPC.getManagedSkillCommandReceipt, ...args) as ReturnType<DesktopBridgeApi["getManagedSkillCommandReceipt"]>,
  getVisualRetentionSettings: (...args: Parameters<DesktopBridgeApi["getVisualRetentionSettings"]>) => invoke(DESKTOP_IPC.getVisualRetentionSettings, ...args) as ReturnType<DesktopBridgeApi["getVisualRetentionSettings"]>,
  updateVisualRetentionSettings: (...args: Parameters<DesktopBridgeApi["updateVisualRetentionSettings"]>) => invoke(DESKTOP_IPC.updateVisualRetentionSettings, ...args) as ReturnType<DesktopBridgeApi["updateVisualRetentionSettings"]>,
  listVisualEvidence: (...args: Parameters<DesktopBridgeApi["listVisualEvidence"]>) => invoke(DESKTOP_IPC.listVisualEvidence, ...args) as ReturnType<DesktopBridgeApi["listVisualEvidence"]>,
  pinVisualEvidence: (...args: Parameters<DesktopBridgeApi["pinVisualEvidence"]>) => invoke(DESKTOP_IPC.pinVisualEvidence, ...args) as ReturnType<DesktopBridgeApi["pinVisualEvidence"]>,
  cleanupVisualEvidence: (...args: Parameters<DesktopBridgeApi["cleanupVisualEvidence"]>) => invoke(DESKTOP_IPC.cleanupVisualEvidence, ...args) as ReturnType<DesktopBridgeApi["cleanupVisualEvidence"]>,
  getVisualEvidenceCommandReceipt: (...args: Parameters<DesktopBridgeApi["getVisualEvidenceCommandReceipt"]>) => invoke(DESKTOP_IPC.getVisualEvidenceCommandReceipt, ...args) as ReturnType<DesktopBridgeApi["getVisualEvidenceCommandReceipt"]>,

  onNativeRunRequested: (listener: (navigation: NativeRunNavigation) => void) => {
    if (typeof listener !== "function") throw new Error("A navigation listener is required");
    nativeRunListeners.add(listener);
    if (bufferedNativeRun) {const navigation = bufferedNativeRun; bufferedNativeRun = undefined; queueMicrotask(() => {if (nativeRunListeners.has(listener)) {try {listener(navigation);} catch { /* A consumer exception conveys no native authority. */ }}});}
    return () => {nativeRunListeners.delete(listener);};
  },
  listProjectFiles: (...args: Parameters<DesktopBridgeApi["listProjectFiles"]>)=>invoke(DESKTOP_IPC.listProjectFiles,...args) as ReturnType<DesktopBridgeApi["listProjectFiles"]>,
  readProjectFile: (...args: Parameters<DesktopBridgeApi["readProjectFile"]>)=>invoke(DESKTOP_IPC.readProjectFile,...args) as ReturnType<DesktopBridgeApi["readProjectFile"]>,
  saveProjectFile: (...args: Parameters<DesktopBridgeApi["saveProjectFile"]>)=>invoke(DESKTOP_IPC.saveProjectFile,...args) as ReturnType<DesktopBridgeApi["saveProjectFile"]>,
  reconcileProjectFileSave: (...args: Parameters<DesktopBridgeApi["reconcileProjectFileSave"]>)=>invoke(DESKTOP_IPC.reconcileProjectFileSave,...args) as ReturnType<DesktopBridgeApi["reconcileProjectFileSave"]>,
  getAnswerFeedback: (...args: Parameters<DesktopBridgeApi["getAnswerFeedback"]>)=>invoke(DESKTOP_IPC.getAnswerFeedback,...args) as ReturnType<DesktopBridgeApi["getAnswerFeedback"]>,
  setAnswerFeedback: (...args: Parameters<DesktopBridgeApi["setAnswerFeedback"]>)=>invoke(DESKTOP_IPC.setAnswerFeedback,...args) as ReturnType<DesktopBridgeApi["setAnswerFeedback"]>,
  getModelConnections: (...args: Parameters<DesktopBridgeApi["getModelConnections"]>)=>invoke(DESKTOP_IPC.getModelConnections,...args) as ReturnType<DesktopBridgeApi["getModelConnections"]>,
  saveModelConnection: (...args: Parameters<DesktopBridgeApi["saveModelConnection"]>)=>invoke(DESKTOP_IPC.saveModelConnection,...args) as ReturnType<DesktopBridgeApi["saveModelConnection"]>,
  removeModelConnection: (...args: Parameters<DesktopBridgeApi["removeModelConnection"]>)=>invoke(DESKTOP_IPC.removeModelConnection,...args) as ReturnType<DesktopBridgeApi["removeModelConnection"]>,
  testModelConnection: (...args: Parameters<DesktopBridgeApi["testModelConnection"]>)=>invoke(DESKTOP_IPC.testModelConnection,...args) as ReturnType<DesktopBridgeApi["testModelConnection"]>,
  testModelCapabilities: (...args: Parameters<DesktopBridgeApi["testModelCapabilities"]>) => invoke(DESKTOP_IPC.testModelCapabilities, ...args) as ReturnType<DesktopBridgeApi["testModelCapabilities"]>,
  getModelCapabilityTestReceipt: (...args: Parameters<DesktopBridgeApi["getModelCapabilityTestReceipt"]>) => invoke(DESKTOP_IPC.getModelCapabilityTestReceipt, ...args) as ReturnType<DesktopBridgeApi["getModelCapabilityTestReceipt"]>,
  getSessionRunOptions: (...args: Parameters<DesktopBridgeApi["getSessionRunOptions"]>)=>invoke(DESKTOP_IPC.getSessionRunOptions,...args) as ReturnType<DesktopBridgeApi["getSessionRunOptions"]>,
  updateSessionRunOptions: (...args: Parameters<DesktopBridgeApi["updateSessionRunOptions"]>)=>invoke(DESKTOP_IPC.updateSessionRunOptions,...args) as ReturnType<DesktopBridgeApi["updateSessionRunOptions"]>,
  getPermissionGrant: (...args: Parameters<DesktopBridgeApi["getPermissionGrant"]>)=>invoke(DESKTOP_IPC.getPermissionGrant,...args) as ReturnType<DesktopBridgeApi["getPermissionGrant"]>,
  setPermissionGrant: (...args: Parameters<DesktopBridgeApi["setPermissionGrant"]>)=>invoke(DESKTOP_IPC.setPermissionGrant,...args) as ReturnType<DesktopBridgeApi["setPermissionGrant"]>,

  getConnectionStatus:()=>invoke(DESKTOP_IPC.getConnectionStatus) as Promise<HostConnectionSnapshot>,
  copyText:(text:string)=>invoke(DESKTOP_IPC.copyText,text) as Promise<void>,
  getImageConfig: (...args: Parameters<DesktopBridgeApi["getImageConfig"]>) => invoke(DESKTOP_IPC.getImageConfig, ...args) as ReturnType<DesktopBridgeApi["getImageConfig"]>,
  configureImageProvider: (...args: Parameters<DesktopBridgeApi["configureImageProvider"]>) => invoke(DESKTOP_IPC.configureImageProvider, ...args) as ReturnType<DesktopBridgeApi["configureImageProvider"]>,
  clearImageProvider: (...args: Parameters<DesktopBridgeApi["clearImageProvider"]>) => invoke(DESKTOP_IPC.clearImageProvider, ...args) as ReturnType<DesktopBridgeApi["clearImageProvider"]>,
  startMediaRun: (...args: Parameters<DesktopBridgeApi["startMediaRun"]>) => invoke(DESKTOP_IPC.startMediaRun, ...args) as ReturnType<DesktopBridgeApi["startMediaRun"]>,
  getArtifactContent: (...args: Parameters<DesktopBridgeApi["getArtifactContent"]>) => invoke(DESKTOP_IPC.getArtifactContent, ...args) as ReturnType<DesktopBridgeApi["getArtifactContent"]>,
  startHost: () => invoke(DESKTOP_IPC.startHost) as Promise<void>,
  getMigrationResult: () => invoke(DESKTOP_IPC.getMigrationResult) as ReturnType<DesktopBridgeApi["getMigrationResult"]>,
  previewMigration: () => invoke(DESKTOP_IPC.previewMigration) as ReturnType<DesktopBridgeApi["previewMigration"]>,
  commitMigration: (...args: Parameters<DesktopBridgeApi["commitMigration"]>) => invoke(DESKTOP_IPC.commitMigration, ...args) as ReturnType<DesktopBridgeApi["commitMigration"]>,
  openPreview: (...args: Parameters<DesktopBridgeApi["openPreview"]>) => invoke(DESKTOP_IPC.openPreview, ...args) as ReturnType<DesktopBridgeApi["openPreview"]>,
  closePreview: () => invoke(DESKTOP_IPC.closePreview) as Promise<void>,
  getHostStatus: () => invoke(DESKTOP_IPC.hostStatus) as Promise<DesktopHostStatus>,
  listSessions: (input: SessionListQuery) => invoke(DESKTOP_IPC.listSessions, input) as Promise<SessionListResponse>,
  getSession: (sessionId: string) => invoke(DESKTOP_IPC.getSession, sessionId) as Promise<SessionReadResult>,
  getRun: (runId: string) => invoke(DESKTOP_IPC.getRun, runId) as Promise<RunProjection>,
  startRun: (input: StartRunRequest) => invoke(DESKTOP_IPC.startRun, input) as Promise<RunProjection>,
  startChat: (...args: Parameters<DesktopBridgeApi["startChat"]>) => invoke(DESKTOP_IPC.startChat, ...args) as ReturnType<DesktopBridgeApi["startChat"]>,
  approve: (...args: Parameters<DesktopBridgeApi["approve"]>) => invoke(DESKTOP_IPC.approve, ...args) as ReturnType<DesktopBridgeApi["approve"]>,
  reject: (...args: Parameters<DesktopBridgeApi["reject"]>) => invoke(DESKTOP_IPC.reject, ...args) as ReturnType<DesktopBridgeApi["reject"]>,
  stop: (...args: Parameters<DesktopBridgeApi["stop"]>) => invoke(DESKTOP_IPC.stop, ...args) as ReturnType<DesktopBridgeApi["stop"]>,
  approvePlan: (...args: Parameters<DesktopBridgeApi["approvePlan"]>) => invoke(DESKTOP_IPC.approvePlan, ...args) as ReturnType<DesktopBridgeApi["approvePlan"]>,
  getTodos: (...args: Parameters<DesktopBridgeApi["getTodos"]>) => invoke(DESKTOP_IPC.getTodos, ...args) as ReturnType<DesktopBridgeApi["getTodos"]>,
  writeTodo: (...args: Parameters<DesktopBridgeApi["writeTodo"]>) => invoke(DESKTOP_IPC.writeTodo, ...args) as ReturnType<DesktopBridgeApi["writeTodo"]>,
  submitUserInput: (...args: Parameters<DesktopBridgeApi["submitUserInput"]>) => invoke(DESKTOP_IPC.submitUserInput, ...args) as ReturnType<DesktopBridgeApi["submitUserInput"]>,
  getArtifact: (...args: Parameters<DesktopBridgeApi["getArtifact"]>) => invoke(DESKTOP_IPC.getArtifact, ...args) as ReturnType<DesktopBridgeApi["getArtifact"]>,
  resumeSession: (...args: Parameters<DesktopBridgeApi["resumeSession"]>) => invoke(DESKTOP_IPC.resumeSession, ...args) as ReturnType<DesktopBridgeApi["resumeSession"]>,
  renameSession: (...args: Parameters<DesktopBridgeApi["renameSession"]>) => invoke(DESKTOP_IPC.renameSession, ...args) as ReturnType<DesktopBridgeApi["renameSession"]>,
  deleteSession: (...args: Parameters<DesktopBridgeApi["deleteSession"]>) => invoke(DESKTOP_IPC.deleteSession, ...args) as ReturnType<DesktopBridgeApi["deleteSession"]>,
  listProjects: () => invoke(DESKTOP_IPC.listProjects) as Promise<ProjectSummary[]>,
  openLocalProject: (input: { access: "read_write" | "read_only" }) => invoke(DESKTOP_IPC.openLocalProject, input) as Promise<ProjectSummary | undefined>,
  revealProject: (projectId: string) => invoke(DESKTOP_IPC.revealProject, projectId) as Promise<void>,
  removeProject: (projectId: string) => invoke(DESKTOP_IPC.removeProject, projectId) as Promise<void>,
  openProjectFile: (projectId: string) => invoke(DESKTOP_IPC.openProjectFile, projectId) as Promise<void>,
  getModelConfig: () => invoke(DESKTOP_IPC.getModelConfig) as Promise<PublicModelConfigResponse>,
  configureModel: (input: ModelConfigUpdateRequest) => invoke(DESKTOP_IPC.configureModel, input) as Promise<PublicModelConfigResponse>,
  listMemoryControl: () => invoke(DESKTOP_IPC.listMemoryControl) as Promise<MemoryControlListResponse>,
  createMemoryCandidate: (input: MemoryCandidateCreateRequest) => invoke(DESKTOP_IPC.createMemoryCandidate, input) as Promise<MemoryControlItem>,
  reviewMemory: (memoryId: string, input: MemoryReviewRequest) => invoke(DESKTOP_IPC.reviewMemory, { memory_id: memoryId, input }) as Promise<MemoryControlItem>,
  correctMemory: (memoryId: string, input: MemoryCorrectionRequest) => invoke(DESKTOP_IPC.correctMemory, { memory_id: memoryId, input }) as Promise<MemoryControlItem>,
  revokeMemory: (memoryId: string, input: MemoryRevokeRequest) => invoke(DESKTOP_IPC.revokeMemory, { memory_id: memoryId, input }) as Promise<MemoryControlItem>,
  deleteMemory: (memoryId: string, input: MemoryDeleteRequest) => invoke(DESKTOP_IPC.deleteMemory, { memory_id: memoryId, input }) as Promise<MemoryDeleteResponse>,
  listExperienceCases: () => invoke(DESKTOP_IPC.listExperienceCases) as Promise<ExperienceControlListResponse>,
  reviewExperienceCase: (caseId: string, input: ExperienceLifecycleReviewRequest) => invoke(DESKTOP_IPC.reviewExperienceCase, { case_id: caseId, input }) as Promise<ExperienceLifecycleReviewResponse>,
  createProject: (...args: Parameters<DesktopBridgeApi["createProject"]>) => invoke(DESKTOP_IPC.createProject, ...args) as ReturnType<DesktopBridgeApi["createProject"]>,
  getPermissionConfig: (...args: Parameters<DesktopBridgeApi["getPermissionConfig"]>) => invoke(DESKTOP_IPC.getPermissionConfig, ...args) as ReturnType<DesktopBridgeApi["getPermissionConfig"]>,
  configurePermissionPreset: (...args: Parameters<DesktopBridgeApi["configurePermissionPreset"]>) => invoke(DESKTOP_IPC.configurePermissionPreset, ...args) as ReturnType<DesktopBridgeApi["configurePermissionPreset"]>,
  getTelemetryStatus: (...args: Parameters<DesktopBridgeApi["getTelemetryStatus"]>) => invoke(DESKTOP_IPC.getTelemetryStatus, ...args) as ReturnType<DesktopBridgeApi["getTelemetryStatus"]>,
  getUsage: (...args: Parameters<DesktopBridgeApi["getUsage"]>) => invoke(DESKTOP_IPC.getUsage, ...args) as ReturnType<DesktopBridgeApi["getUsage"]>,
  listExtensions: (...args: Parameters<DesktopBridgeApi["listExtensions"]>) => invoke(DESKTOP_IPC.listExtensions, ...args) as ReturnType<DesktopBridgeApi["listExtensions"]>,
  listSkills: (...args: Parameters<DesktopBridgeApi["listSkills"]>) => invoke(DESKTOP_IPC.listSkills, ...args) as ReturnType<DesktopBridgeApi["listSkills"]>,
  getMcpStatus: (...args: Parameters<DesktopBridgeApi["getMcpStatus"]>) => invoke(DESKTOP_IPC.getMcpStatus, ...args) as ReturnType<DesktopBridgeApi["getMcpStatus"]>,
  getLspStatus: (...args: Parameters<DesktopBridgeApi["getLspStatus"]>) => invoke(DESKTOP_IPC.getLspStatus, ...args) as ReturnType<DesktopBridgeApi["getLspStatus"]>,
  restartMcpServer: (...args: Parameters<DesktopBridgeApi["restartMcpServer"]>) => invoke(DESKTOP_IPC.restartMcpServer, ...args) as ReturnType<DesktopBridgeApi["restartMcpServer"]>,
  reloadExtension: (...args: Parameters<DesktopBridgeApi["reloadExtension"]>) => invoke(DESKTOP_IPC.reloadExtension, ...args) as ReturnType<DesktopBridgeApi["reloadExtension"]>,
  runExtensionCommand: (...args: Parameters<DesktopBridgeApi["runExtensionCommand"]>) => invoke(DESKTOP_IPC.runExtensionCommand, ...args) as ReturnType<DesktopBridgeApi["runExtensionCommand"]>,
  createReplay: (...args: Parameters<DesktopBridgeApi["createReplay"]>) => invoke(DESKTOP_IPC.createReplay, ...args) as ReturnType<DesktopBridgeApi["createReplay"]>,
  getReplayDiff: (...args: Parameters<DesktopBridgeApi["getReplayDiff"]>) => invoke(DESKTOP_IPC.getReplayDiff, ...args) as ReturnType<DesktopBridgeApi["getReplayDiff"]>,
  exitReplay: (...args: Parameters<DesktopBridgeApi["exitReplay"]>) => invoke(DESKTOP_IPC.exitReplay, ...args) as ReturnType<DesktopBridgeApi["exitReplay"]>,
  uploadAttachment: (...args: Parameters<DesktopBridgeApi["uploadAttachment"]>) => invoke(DESKTOP_IPC.uploadAttachment, ...args) as ReturnType<DesktopBridgeApi["uploadAttachment"]>,
  getAttachmentContent: (...args: Parameters<DesktopBridgeApi["getAttachmentContent"]>) => invoke(DESKTOP_IPC.getAttachmentContent, ...args) as ReturnType<DesktopBridgeApi["getAttachmentContent"]>,
  getSubagent: (...args: Parameters<DesktopBridgeApi["getSubagent"]>) => invoke(DESKTOP_IPC.getSubagent, ...args) as ReturnType<DesktopBridgeApi["getSubagent"]>,
  getTeam: (...args: Parameters<DesktopBridgeApi["getTeam"]>) => invoke(DESKTOP_IPC.getTeam, ...args) as ReturnType<DesktopBridgeApi["getTeam"]>,
  createTeam: (...args: Parameters<DesktopBridgeApi["createTeam"]>) => invoke(DESKTOP_IPC.createTeam, ...args) as ReturnType<DesktopBridgeApi["createTeam"]>,
  sendTeamMailbox: (...args: Parameters<DesktopBridgeApi["sendTeamMailbox"]>) => invoke(DESKTOP_IPC.sendTeamMailbox, ...args) as ReturnType<DesktopBridgeApi["sendTeamMailbox"]>,
  claimTeamMailbox: (...args: Parameters<DesktopBridgeApi["claimTeamMailbox"]>) => invoke(DESKTOP_IPC.claimTeamMailbox, ...args) as ReturnType<DesktopBridgeApi["claimTeamMailbox"]>,
  writeTeamTask: (...args: Parameters<DesktopBridgeApi["writeTeamTask"]>) => invoke(DESKTOP_IPC.writeTeamTask, ...args) as ReturnType<DesktopBridgeApi["writeTeamTask"]>,
  heartbeatTeam: (...args: Parameters<DesktopBridgeApi["heartbeatTeam"]>) => invoke(DESKTOP_IPC.heartbeatTeam, ...args) as ReturnType<DesktopBridgeApi["heartbeatTeam"]>,
  sweepLostTeamMembers: (...args: Parameters<DesktopBridgeApi["sweepLostTeamMembers"]>) => invoke(DESKTOP_IPC.sweepLostTeamMembers, ...args) as ReturnType<DesktopBridgeApi["sweepLostTeamMembers"]>,
  rollbackAction: (...args: Parameters<DesktopBridgeApi["rollbackAction"]>) => invoke(DESKTOP_IPC.rollbackAction, ...args) as ReturnType<DesktopBridgeApi["rollbackAction"]>,
  getBrowserCommandReceipt: (...args: Parameters<DesktopBridgeApi["getBrowserCommandReceipt"]>) => invoke(DESKTOP_IPC.getBrowserCommandReceipt, ...args) as ReturnType<DesktopBridgeApi["getBrowserCommandReceipt"]>,
  getComputerStatus: (...args: Parameters<DesktopBridgeApi["getComputerStatus"]>) => invoke(DESKTOP_IPC.getComputerStatus, ...args) as ReturnType<DesktopBridgeApi["getComputerStatus"]>,
  listComputerTargets: (...args: Parameters<DesktopBridgeApi["listComputerTargets"]>) => invoke(DESKTOP_IPC.listComputerTargets, ...args) as ReturnType<DesktopBridgeApi["listComputerTargets"]>,
  requestComputerGrant: (...args: Parameters<DesktopBridgeApi["requestComputerGrant"]>) => invoke(DESKTOP_IPC.requestComputerGrant, ...args) as ReturnType<DesktopBridgeApi["requestComputerGrant"]>,
  revokeComputerGrant: (...args: Parameters<DesktopBridgeApi["revokeComputerGrant"]>) => invoke(DESKTOP_IPC.revokeComputerGrant, ...args) as ReturnType<DesktopBridgeApi["revokeComputerGrant"]>,
  acquireComputerLease: (...args: Parameters<DesktopBridgeApi["acquireComputerLease"]>) => invoke(DESKTOP_IPC.acquireComputerLease, ...args) as ReturnType<DesktopBridgeApi["acquireComputerLease"]>,
  resumeComputerLease: (...args: Parameters<DesktopBridgeApi["resumeComputerLease"]>) => invoke(DESKTOP_IPC.resumeComputerLease, ...args) as ReturnType<DesktopBridgeApi["resumeComputerLease"]>,
  releaseComputerLease: (...args: Parameters<DesktopBridgeApi["releaseComputerLease"]>) => invoke(DESKTOP_IPC.releaseComputerLease, ...args) as ReturnType<DesktopBridgeApi["releaseComputerLease"]>,
  observeComputer: (...args: Parameters<DesktopBridgeApi["observeComputer"]>) => invoke(DESKTOP_IPC.observeComputer, ...args) as ReturnType<DesktopBridgeApi["observeComputer"]>,
  computerAction: (...args: Parameters<DesktopBridgeApi["computerAction"]>) => invoke(DESKTOP_IPC.computerAction, ...args) as ReturnType<DesktopBridgeApi["computerAction"]>,
  getComputerCommandReceipt: (...args: Parameters<DesktopBridgeApi["getComputerCommandReceipt"]>) => invoke(DESKTOP_IPC.getComputerCommandReceipt, ...args) as ReturnType<DesktopBridgeApi["getComputerCommandReceipt"]>,
  getComputerCapture: (...args: Parameters<DesktopBridgeApi["getComputerCapture"]>) => invoke(DESKTOP_IPC.getComputerCapture, ...args) as ReturnType<DesktopBridgeApi["getComputerCapture"]>,
  getPersonalProfile: (...args: Parameters<DesktopBridgeApi["getPersonalProfile"]>) => invoke(DESKTOP_IPC.getPersonalProfile, ...args) as ReturnType<DesktopBridgeApi["getPersonalProfile"]>,
  updatePersonalProfile: (...args: Parameters<DesktopBridgeApi["updatePersonalProfile"]>) => invoke(DESKTOP_IPC.updatePersonalProfile, ...args) as ReturnType<DesktopBridgeApi["updatePersonalProfile"]>,
  getPersonalProfileCommandReceipt: (...args: Parameters<DesktopBridgeApi["getPersonalProfileCommandReceipt"]>) => invoke(DESKTOP_IPC.getPersonalProfileCommandReceipt, ...args) as ReturnType<DesktopBridgeApi["getPersonalProfileCommandReceipt"]>,
  queryPersonalUsage: (...args: Parameters<DesktopBridgeApi["queryPersonalUsage"]>) => invoke(DESKTOP_IPC.queryPersonalUsage, ...args) as ReturnType<DesktopBridgeApi["queryPersonalUsage"]>,
  searchPublicSessions: (...args: Parameters<DesktopBridgeApi["searchPublicSessions"]>) => invoke(DESKTOP_IPC.searchPublicSessions, ...args) as ReturnType<DesktopBridgeApi["searchPublicSessions"]>,
  getBrowserStatus: (...args: Parameters<DesktopBridgeApi["getBrowserStatus"]>) => invoke(DESKTOP_IPC.getBrowserStatus, ...args) as ReturnType<DesktopBridgeApi["getBrowserStatus"]>,
  requestBrowserGrant: (...args: Parameters<DesktopBridgeApi["requestBrowserGrant"]>) => invoke(DESKTOP_IPC.requestBrowserGrant, ...args) as ReturnType<DesktopBridgeApi["requestBrowserGrant"]>,
  browserCommand: (...args: Parameters<DesktopBridgeApi["browserCommand"]>) => invoke(DESKTOP_IPC.browserCommand, ...args) as ReturnType<DesktopBridgeApi["browserCommand"]>,
  observeBrowser: (...args: Parameters<DesktopBridgeApi["observeBrowser"]>) => invoke(DESKTOP_IPC.observeBrowser, ...args) as ReturnType<DesktopBridgeApi["observeBrowser"]>,
  getBrowserEvidence: (...args: Parameters<DesktopBridgeApi["getBrowserEvidence"]>) => invoke(DESKTOP_IPC.getBrowserEvidence, ...args) as ReturnType<DesktopBridgeApi["getBrowserEvidence"]>,
  listGoals: (...args: Parameters<DesktopBridgeApi["listGoals"]>) => invoke(DESKTOP_IPC.listGoals, ...args) as ReturnType<DesktopBridgeApi["listGoals"]>,
  createGoal: (...args: Parameters<DesktopBridgeApi["createGoal"]>) => invoke(DESKTOP_IPC.createGoal, ...args) as ReturnType<DesktopBridgeApi["createGoal"]>,
  getGoal: (...args: Parameters<DesktopBridgeApi["getGoal"]>) => invoke(DESKTOP_IPC.getGoal, ...args) as ReturnType<DesktopBridgeApi["getGoal"]>,
  goalCommand: (...args: Parameters<DesktopBridgeApi["goalCommand"]>) => invoke(DESKTOP_IPC.goalCommand, ...args) as ReturnType<DesktopBridgeApi["goalCommand"]>,
  getGoalCreationReceipt: (...args: Parameters<DesktopBridgeApi["getGoalCreationReceipt"]>) => invoke(DESKTOP_IPC.getGoalCreationReceipt, ...args) as ReturnType<DesktopBridgeApi["getGoalCreationReceipt"]>,
  getGoalCommandReceipt: (...args: Parameters<DesktopBridgeApi["getGoalCommandReceipt"]>) => invoke(DESKTOP_IPC.getGoalCommandReceipt, ...args) as ReturnType<DesktopBridgeApi["getGoalCommandReceipt"]>,
  getGoalBudget: (...args: Parameters<DesktopBridgeApi["getGoalBudget"]>) => invoke(DESKTOP_IPC.getGoalBudget, ...args) as ReturnType<DesktopBridgeApi["getGoalBudget"]>,
  getWorkbenchSettingsHistory: (...args: Parameters<DesktopBridgeApi["getWorkbenchSettingsHistory"]>) => invoke(DESKTOP_IPC.getWorkbenchSettingsHistory, ...args) as ReturnType<DesktopBridgeApi["getWorkbenchSettingsHistory"]>,
  restoreWorkbenchSettings: (...args: Parameters<DesktopBridgeApi["restoreWorkbenchSettings"]>) => invoke(DESKTOP_IPC.restoreWorkbenchSettings, ...args) as ReturnType<DesktopBridgeApi["restoreWorkbenchSettings"]>,
  getProjectRunDefaults: (...args: Parameters<DesktopBridgeApi["getProjectRunDefaults"]>) => invoke(DESKTOP_IPC.getProjectRunDefaults, ...args) as ReturnType<DesktopBridgeApi["getProjectRunDefaults"]>,
  updateProjectRunDefaults: (...args: Parameters<DesktopBridgeApi["updateProjectRunDefaults"]>) => invoke(DESKTOP_IPC.updateProjectRunDefaults, ...args) as ReturnType<DesktopBridgeApi["updateProjectRunDefaults"]>,
  resetSessionRunOptions: (...args: Parameters<DesktopBridgeApi["resetSessionRunOptions"]>) => invoke(DESKTOP_IPC.resetSessionRunOptions, ...args) as ReturnType<DesktopBridgeApi["resetSessionRunOptions"]>,
  getWorkbenchSettings: (...args: Parameters<DesktopBridgeApi["getWorkbenchSettings"]>) => invoke(DESKTOP_IPC.getWorkbenchSettings, ...args) as ReturnType<DesktopBridgeApi["getWorkbenchSettings"]>,
  updateWorkbenchSettings: (...args: Parameters<DesktopBridgeApi["updateWorkbenchSettings"]>) => invoke(DESKTOP_IPC.updateWorkbenchSettings, ...args) as ReturnType<DesktopBridgeApi["updateWorkbenchSettings"]>,
  getCapabilities: (...args: Parameters<DesktopBridgeApi["getCapabilities"]>) => invoke(DESKTOP_IPC.getCapabilities, ...args) as ReturnType<DesktopBridgeApi["getCapabilities"]>,
  testModel: (...args: Parameters<DesktopBridgeApi["testModel"]>) => invoke(DESKTOP_IPC.testModel, ...args) as ReturnType<DesktopBridgeApi["testModel"]>,
  getWorkbenchResources: (...args: Parameters<DesktopBridgeApi["getWorkbenchResources"]>) => invoke(DESKTOP_IPC.getWorkbenchResources, ...args) as ReturnType<DesktopBridgeApi["getWorkbenchResources"]>,
  workbenchCommand: (...args: Parameters<DesktopBridgeApi["workbenchCommand"]>) => invoke(DESKTOP_IPC.workbenchCommand, ...args) as ReturnType<DesktopBridgeApi["workbenchCommand"]>,
  openStream: (...args: Parameters<DesktopBridgeApi["openStream"]>) => invoke(DESKTOP_IPC.openStream, ...args) as ReturnType<DesktopBridgeApi["openStream"]>,
  readStream: (...args: Parameters<DesktopBridgeApi["readStream"]>) => invoke(DESKTOP_IPC.readStream, ...args) as ReturnType<DesktopBridgeApi["readStream"]>,
  closeStream: (...args: Parameters<DesktopBridgeApi["closeStream"]>) => invoke(DESKTOP_IPC.closeStream, ...args) as ReturnType<DesktopBridgeApi["closeStream"]>,
});

contextBridge.exposeInMainWorld("tracegraphDesktop", bridge);
