import { contextBridge, ipcRenderer } from "electron";
import type { DesktopBridgeApi, DesktopHostStatus } from "./bridge-contract.js";
import type {
  HostConnectionSnapshot,
  ModelConfigUpdateRequest,
  ProjectSummary,
  PublicModelConfigResponse,
  SessionListQuery,
  SessionListResponse,
  SessionReadResult,
  RunProjection,
  StartRunRequest,
  MemoryCandidateCreateRequest,
  MemoryControlItem,
  MemoryControlListResponse,
  MemoryCorrectionRequest,
  MemoryDeleteRequest,
  MemoryDeleteResponse,
  MemoryReviewRequest,
  MemoryRevokeRequest,
  ExperienceControlListResponse,
  ExperienceLifecycleReviewRequest,
  ExperienceLifecycleReviewResponse,
} from "@tracegraph/contracts";

// Keep the sandboxed preload self-contained: its only runtime import is Electron.
const DESKTOP_IPC = {
  listProjectFiles:"tracegraph:listProjectFiles",
  readProjectFile:"tracegraph:readProjectFile",
  saveProjectFile:"tracegraph:saveProjectFile",
  reconcileProjectFileSave:"tracegraph:reconcileProjectFileSave",
  getAnswerFeedback:"tracegraph:getAnswerFeedback",
  setAnswerFeedback:"tracegraph:setAnswerFeedback",
  getModelConnections:"tracegraph:getModelConnections",
  saveModelConnection:"tracegraph:saveModelConnection",
  removeModelConnection:"tracegraph:removeModelConnection",
  testModelConnection:"tracegraph:testModelConnection",
  getSessionRunOptions:"tracegraph:getSessionRunOptions",
  updateSessionRunOptions:"tracegraph:updateSessionRunOptions",
  getPermissionGrant:"tracegraph:getPermissionGrant",
  setPermissionGrant:"tracegraph:setPermissionGrant",

  getConnectionStatus:"tracegraph:connection-status",
  copyText:"tracegraph:clipboard-copy",
  getImageConfig: "tracegraph:image-config-get",
  configureImageProvider: "tracegraph:image-config-set",
  clearImageProvider: "tracegraph:image-config-clear",
  startMediaRun: "tracegraph:media-run-start",
  getArtifactContent: "tracegraph:artifact-content-get",
  startHost: "tracegraph:host-start",
  getMigrationResult: "tracegraph:migration-result",
  previewMigration: "tracegraph:migration-preview",
  commitMigration: "tracegraph:migration-commit",
  openPreview: "tracegraph:preview-open",
  closePreview: "tracegraph:preview-close",
  hostStatus: "tracegraph:host-status",
  listSessions: "tracegraph:sessions-list",
  getSession: "tracegraph:session-get",
  getRun: "tracegraph:run-get",
  startRun: "tracegraph:run-start",
  startChat: "tracegraph:chat-start",
  approve: "tracegraph:run-approve",
  reject: "tracegraph:run-reject",
  stop: "tracegraph:run-stop",
  approvePlan: "tracegraph:run-plan-approve",
  getTodos: "tracegraph:todos-get",
  writeTodo: "tracegraph:todo-write",
  submitUserInput: "tracegraph:run-input",
  getArtifact: "tracegraph:artifact-get",
  resumeSession: "tracegraph:session-resume",
  renameSession: "tracegraph:session-rename",
  deleteSession: "tracegraph:session-delete",
  listProjects: "tracegraph:projects-list",
  openLocalProject: "tracegraph:project-open-local",
  revealProject: "tracegraph:project-reveal",
  removeProject: "tracegraph:project-remove",
  openProjectFile: "tracegraph:project-open-file",
  getModelConfig: "tracegraph:model-config-get",
  configureModel: "tracegraph:model-config-set",
  listMemoryControl: "tracegraph:memory-list",
  createMemoryCandidate: "tracegraph:memory-create",
  reviewMemory: "tracegraph:memory-review",
  correctMemory: "tracegraph:memory-correct",
  revokeMemory: "tracegraph:memory-revoke",
  deleteMemory: "tracegraph:memory-delete",
  listExperienceCases: "tracegraph:experience-list",
  reviewExperienceCase: "tracegraph:experience-review",
  createProject: "tracegraph:createProject",
  getPermissionConfig: "tracegraph:getPermissionConfig",
  configurePermissionPreset: "tracegraph:configurePermissionPreset",
  getTelemetryStatus: "tracegraph:getTelemetryStatus",
  getUsage: "tracegraph:getUsage",
  listExtensions: "tracegraph:listExtensions",
  listSkills: "tracegraph:listSkills",
  getMcpStatus: "tracegraph:getMcpStatus",
  getLspStatus: "tracegraph:getLspStatus",
  restartMcpServer: "tracegraph:restartMcpServer",
  reloadExtension: "tracegraph:reloadExtension",
  runExtensionCommand: "tracegraph:runExtensionCommand",
  createReplay: "tracegraph:createReplay",
  getReplayDiff: "tracegraph:getReplayDiff",
  exitReplay: "tracegraph:exitReplay",
  uploadAttachment: "tracegraph:uploadAttachment",
  getAttachmentContent: "tracegraph:getAttachmentContent",
  getSubagent: "tracegraph:getSubagent",
  getTeam: "tracegraph:getTeam",
  createTeam: "tracegraph:createTeam",
  sendTeamMailbox: "tracegraph:sendTeamMailbox",
  claimTeamMailbox: "tracegraph:claimTeamMailbox",
  writeTeamTask: "tracegraph:writeTeamTask",
  heartbeatTeam: "tracegraph:heartbeatTeam",
  sweepLostTeamMembers: "tracegraph:sweepLostTeamMembers",
  rollbackAction: "tracegraph:rollbackAction",
  getWorkbenchSettings: "tracegraph:getWorkbenchSettings",
  updateWorkbenchSettings: "tracegraph:updateWorkbenchSettings",
  getCapabilities: "tracegraph:getCapabilities",
  testModel: "tracegraph:testModel",
  getWorkbenchResources: "tracegraph:getWorkbenchResources",
  workbenchCommand: "tracegraph:workbenchCommand",
  openStream: "tracegraph:openStream",
  readStream: "tracegraph:readStream",
  closeStream: "tracegraph:closeStream",
} as const;

// Only Main's closed connection failure envelope crosses IPC; no generic renderer invocation.
const connectionCodes=new Set(["host_offline","host_stopped","host_reconnecting","host_recovering","host_upgrade_required","host_profile_invalid","host_startup_failed","host_read_stale","host_replay_stale","host_recovery_exhausted","host_write_outcome_unknown"]);
async function invoke(channel:(typeof DESKTOP_IPC)[keyof typeof DESKTOP_IPC],...args:unknown[]):Promise<unknown>{
  const value:unknown=await ipcRenderer.invoke(channel,...args);
  if(typeof value==="object"&&value!==null&&"__outlive_connection_error" in value){
    const envelope=value.__outlive_connection_error as {code?:unknown;connection?:HostConnectionSnapshot};
    if(typeof envelope.code!=="string"||!connectionCodes.has(envelope.code)||!envelope.connection||!Number.isSafeInteger(envelope.connection.generation))throw new Error("Invalid Host connection failure");
    throw Object.assign(new Error(envelope.connection.message??"The local Host connection is unavailable"),{name:"HostConnectionError",code:envelope.code,connection:envelope.connection});
  }
  if(typeof value==="object"&&value!==null&&"__outlive_command_rejected" in value){
    const envelope=value.__outlive_command_rejected as {code?:unknown;admission?:unknown;status?:unknown;commandDispatched?:unknown};
    const auth=typeof envelope.code==="string"&&["capability_required","capability_invalid","capability_expired"].includes(envelope.code);
    if(envelope.admission!=="rejected"||!(auth?envelope.status===401:envelope.code==="mutation_preflight_failed"&&envelope.commandDispatched===false))throw new Error("Invalid Host admission rejection");
    throw Object.assign(new Error(auth?"Your connection expired. Repair the connection before retrying.":"The connection could not be verified. No command was sent. Repair the connection before retrying."),{code:envelope.code,admission:"rejected",...(auth?{status:401,body:{error:envelope.code}}:{commandDispatched:false})});
  }
  return value;
}

const bridge: DesktopBridgeApi = Object.freeze({
  listProjectFiles: (...args: Parameters<DesktopBridgeApi["listProjectFiles"]>)=>invoke(DESKTOP_IPC.listProjectFiles,...args) as ReturnType<DesktopBridgeApi["listProjectFiles"]>,
  readProjectFile: (...args: Parameters<DesktopBridgeApi["readProjectFile"]>)=>invoke(DESKTOP_IPC.readProjectFile,...args) as ReturnType<DesktopBridgeApi["readProjectFile"]>,
  saveProjectFile: (...args: Parameters<DesktopBridgeApi["saveProjectFile"]>)=>invoke(DESKTOP_IPC.saveProjectFile,...args) as ReturnType<DesktopBridgeApi["saveProjectFile"]>,
  reconcileProjectFileSave: (...args: Parameters<DesktopBridgeApi["reconcileProjectFileSave"]>)=>invoke(DESKTOP_IPC.reconcileProjectFileSave,...args) as ReturnType<DesktopBridgeApi["reconcileProjectFileSave"]>,
  getAnswerFeedback: (...args: Parameters<DesktopBridgeApi["getAnswerFeedback"]>)=>invoke(DESKTOP_IPC.getAnswerFeedback,...args) as ReturnType<DesktopBridgeApi["getAnswerFeedback"]>,
  setAnswerFeedback: (...args: Parameters<DesktopBridgeApi["setAnswerFeedback"]>)=>invoke(DESKTOP_IPC.setAnswerFeedback,...args) as ReturnType<DesktopBridgeApi["setAnswerFeedback"]>,
  getModelConnections: (...args: Parameters<DesktopBridgeApi["getModelConnections"]>)=>invoke(DESKTOP_IPC.getModelConnections,...args) as ReturnType<DesktopBridgeApi["getModelConnections"]>,
  saveModelConnection: (...args: Parameters<DesktopBridgeApi["saveModelConnection"]>)=>invoke(DESKTOP_IPC.saveModelConnection,...args) as ReturnType<DesktopBridgeApi["saveModelConnection"]>,
  removeModelConnection: (...args: Parameters<DesktopBridgeApi["removeModelConnection"]>)=>invoke(DESKTOP_IPC.removeModelConnection,...args) as ReturnType<DesktopBridgeApi["removeModelConnection"]>,
  testModelConnection: (...args: Parameters<DesktopBridgeApi["testModelConnection"]>)=>invoke(DESKTOP_IPC.testModelConnection,...args) as ReturnType<DesktopBridgeApi["testModelConnection"]>,
  getSessionRunOptions: (...args: Parameters<DesktopBridgeApi["getSessionRunOptions"]>)=>invoke(DESKTOP_IPC.getSessionRunOptions,...args) as ReturnType<DesktopBridgeApi["getSessionRunOptions"]>,
  updateSessionRunOptions: (...args: Parameters<DesktopBridgeApi["updateSessionRunOptions"]>)=>invoke(DESKTOP_IPC.updateSessionRunOptions,...args) as ReturnType<DesktopBridgeApi["updateSessionRunOptions"]>,
  getPermissionGrant: (...args: Parameters<DesktopBridgeApi["getPermissionGrant"]>)=>invoke(DESKTOP_IPC.getPermissionGrant,...args) as ReturnType<DesktopBridgeApi["getPermissionGrant"]>,
  setPermissionGrant: (...args: Parameters<DesktopBridgeApi["setPermissionGrant"]>)=>invoke(DESKTOP_IPC.setPermissionGrant,...args) as ReturnType<DesktopBridgeApi["setPermissionGrant"]>,

  getConnectionStatus:()=>invoke(DESKTOP_IPC.getConnectionStatus) as Promise<HostConnectionSnapshot>,
  copyText:(text:string)=>invoke(DESKTOP_IPC.copyText,text) as Promise<void>,
  getImageConfig: (...args: Parameters<DesktopBridgeApi["getImageConfig"]>) => invoke(DESKTOP_IPC.getImageConfig, ...args) as ReturnType<DesktopBridgeApi["getImageConfig"]>,
  configureImageProvider: (...args: Parameters<DesktopBridgeApi["configureImageProvider"]>) => invoke(DESKTOP_IPC.configureImageProvider, ...args) as ReturnType<DesktopBridgeApi["configureImageProvider"]>,
  clearImageProvider: (...args: Parameters<DesktopBridgeApi["clearImageProvider"]>) => invoke(DESKTOP_IPC.clearImageProvider, ...args) as ReturnType<DesktopBridgeApi["clearImageProvider"]>,
  startMediaRun: (...args: Parameters<DesktopBridgeApi["startMediaRun"]>) => invoke(DESKTOP_IPC.startMediaRun, ...args) as ReturnType<DesktopBridgeApi["startMediaRun"]>,
  getArtifactContent: (...args: Parameters<DesktopBridgeApi["getArtifactContent"]>) => invoke(DESKTOP_IPC.getArtifactContent, ...args) as ReturnType<DesktopBridgeApi["getArtifactContent"]>,
  startHost: () => invoke(DESKTOP_IPC.startHost) as Promise<void>,
  getMigrationResult: () => invoke(DESKTOP_IPC.getMigrationResult) as ReturnType<DesktopBridgeApi["getMigrationResult"]>,
  previewMigration: () => invoke(DESKTOP_IPC.previewMigration) as ReturnType<DesktopBridgeApi["previewMigration"]>,
  commitMigration: (...args: Parameters<DesktopBridgeApi["commitMigration"]>) => invoke(DESKTOP_IPC.commitMigration, ...args) as ReturnType<DesktopBridgeApi["commitMigration"]>,
  openPreview: (...args: Parameters<DesktopBridgeApi["openPreview"]>) => invoke(DESKTOP_IPC.openPreview, ...args) as ReturnType<DesktopBridgeApi["openPreview"]>,
  closePreview: () => invoke(DESKTOP_IPC.closePreview) as Promise<void>,
  getHostStatus: () => invoke(DESKTOP_IPC.hostStatus) as Promise<DesktopHostStatus>,
  listSessions: (input: SessionListQuery) => invoke(DESKTOP_IPC.listSessions, input) as Promise<SessionListResponse>,
  getSession: (sessionId: string) => invoke(DESKTOP_IPC.getSession, sessionId) as Promise<SessionReadResult>,
  getRun: (runId: string) => invoke(DESKTOP_IPC.getRun, runId) as Promise<RunProjection>,
  startRun: (input: StartRunRequest) => invoke(DESKTOP_IPC.startRun, input) as Promise<RunProjection>,
  startChat: (...args: Parameters<DesktopBridgeApi["startChat"]>) => invoke(DESKTOP_IPC.startChat, ...args) as ReturnType<DesktopBridgeApi["startChat"]>,
  approve: (...args: Parameters<DesktopBridgeApi["approve"]>) => invoke(DESKTOP_IPC.approve, ...args) as ReturnType<DesktopBridgeApi["approve"]>,
  reject: (...args: Parameters<DesktopBridgeApi["reject"]>) => invoke(DESKTOP_IPC.reject, ...args) as ReturnType<DesktopBridgeApi["reject"]>,
  stop: (...args: Parameters<DesktopBridgeApi["stop"]>) => invoke(DESKTOP_IPC.stop, ...args) as ReturnType<DesktopBridgeApi["stop"]>,
  approvePlan: (...args: Parameters<DesktopBridgeApi["approvePlan"]>) => invoke(DESKTOP_IPC.approvePlan, ...args) as ReturnType<DesktopBridgeApi["approvePlan"]>,
  getTodos: (...args: Parameters<DesktopBridgeApi["getTodos"]>) => invoke(DESKTOP_IPC.getTodos, ...args) as ReturnType<DesktopBridgeApi["getTodos"]>,
  writeTodo: (...args: Parameters<DesktopBridgeApi["writeTodo"]>) => invoke(DESKTOP_IPC.writeTodo, ...args) as ReturnType<DesktopBridgeApi["writeTodo"]>,
  submitUserInput: (...args: Parameters<DesktopBridgeApi["submitUserInput"]>) => invoke(DESKTOP_IPC.submitUserInput, ...args) as ReturnType<DesktopBridgeApi["submitUserInput"]>,
  getArtifact: (...args: Parameters<DesktopBridgeApi["getArtifact"]>) => invoke(DESKTOP_IPC.getArtifact, ...args) as ReturnType<DesktopBridgeApi["getArtifact"]>,
  resumeSession: (...args: Parameters<DesktopBridgeApi["resumeSession"]>) => invoke(DESKTOP_IPC.resumeSession, ...args) as ReturnType<DesktopBridgeApi["resumeSession"]>,
  renameSession: (...args: Parameters<DesktopBridgeApi["renameSession"]>) => invoke(DESKTOP_IPC.renameSession, ...args) as ReturnType<DesktopBridgeApi["renameSession"]>,
  deleteSession: (...args: Parameters<DesktopBridgeApi["deleteSession"]>) => invoke(DESKTOP_IPC.deleteSession, ...args) as ReturnType<DesktopBridgeApi["deleteSession"]>,
  listProjects: () => invoke(DESKTOP_IPC.listProjects) as Promise<ProjectSummary[]>,
  openLocalProject: (input: { access: "read_write" | "read_only" }) => invoke(DESKTOP_IPC.openLocalProject, input) as Promise<ProjectSummary | undefined>,
  revealProject: (projectId: string) => invoke(DESKTOP_IPC.revealProject, projectId) as Promise<void>,
  removeProject: (projectId: string) => invoke(DESKTOP_IPC.removeProject, projectId) as Promise<void>,
  openProjectFile: (projectId: string) => invoke(DESKTOP_IPC.openProjectFile, projectId) as Promise<void>,
  getModelConfig: () => invoke(DESKTOP_IPC.getModelConfig) as Promise<PublicModelConfigResponse>,
  configureModel: (input: ModelConfigUpdateRequest) => invoke(DESKTOP_IPC.configureModel, input) as Promise<PublicModelConfigResponse>,
  listMemoryControl: () => invoke(DESKTOP_IPC.listMemoryControl) as Promise<MemoryControlListResponse>,
  createMemoryCandidate: (input: MemoryCandidateCreateRequest) => invoke(DESKTOP_IPC.createMemoryCandidate, input) as Promise<MemoryControlItem>,
  reviewMemory: (memoryId: string, input: MemoryReviewRequest) => invoke(DESKTOP_IPC.reviewMemory, { memory_id: memoryId, input }) as Promise<MemoryControlItem>,
  correctMemory: (memoryId: string, input: MemoryCorrectionRequest) => invoke(DESKTOP_IPC.correctMemory, { memory_id: memoryId, input }) as Promise<MemoryControlItem>,
  revokeMemory: (memoryId: string, input: MemoryRevokeRequest) => invoke(DESKTOP_IPC.revokeMemory, { memory_id: memoryId, input }) as Promise<MemoryControlItem>,
  deleteMemory: (memoryId: string, input: MemoryDeleteRequest) => invoke(DESKTOP_IPC.deleteMemory, { memory_id: memoryId, input }) as Promise<MemoryDeleteResponse>,
  listExperienceCases: () => invoke(DESKTOP_IPC.listExperienceCases) as Promise<ExperienceControlListResponse>,
  reviewExperienceCase: (caseId: string, input: ExperienceLifecycleReviewRequest) => invoke(DESKTOP_IPC.reviewExperienceCase, { case_id: caseId, input }) as Promise<ExperienceLifecycleReviewResponse>,
  createProject: (...args: Parameters<DesktopBridgeApi["createProject"]>) => invoke(DESKTOP_IPC.createProject, ...args) as ReturnType<DesktopBridgeApi["createProject"]>,
  getPermissionConfig: (...args: Parameters<DesktopBridgeApi["getPermissionConfig"]>) => invoke(DESKTOP_IPC.getPermissionConfig, ...args) as ReturnType<DesktopBridgeApi["getPermissionConfig"]>,
  configurePermissionPreset: (...args: Parameters<DesktopBridgeApi["configurePermissionPreset"]>) => invoke(DESKTOP_IPC.configurePermissionPreset, ...args) as ReturnType<DesktopBridgeApi["configurePermissionPreset"]>,
  getTelemetryStatus: (...args: Parameters<DesktopBridgeApi["getTelemetryStatus"]>) => invoke(DESKTOP_IPC.getTelemetryStatus, ...args) as ReturnType<DesktopBridgeApi["getTelemetryStatus"]>,
  getUsage: (...args: Parameters<DesktopBridgeApi["getUsage"]>) => invoke(DESKTOP_IPC.getUsage, ...args) as ReturnType<DesktopBridgeApi["getUsage"]>,
  listExtensions: (...args: Parameters<DesktopBridgeApi["listExtensions"]>) => invoke(DESKTOP_IPC.listExtensions, ...args) as ReturnType<DesktopBridgeApi["listExtensions"]>,
  listSkills: (...args: Parameters<DesktopBridgeApi["listSkills"]>) => invoke(DESKTOP_IPC.listSkills, ...args) as ReturnType<DesktopBridgeApi["listSkills"]>,
  getMcpStatus: (...args: Parameters<DesktopBridgeApi["getMcpStatus"]>) => invoke(DESKTOP_IPC.getMcpStatus, ...args) as ReturnType<DesktopBridgeApi["getMcpStatus"]>,
  getLspStatus: (...args: Parameters<DesktopBridgeApi["getLspStatus"]>) => invoke(DESKTOP_IPC.getLspStatus, ...args) as ReturnType<DesktopBridgeApi["getLspStatus"]>,
  restartMcpServer: (...args: Parameters<DesktopBridgeApi["restartMcpServer"]>) => invoke(DESKTOP_IPC.restartMcpServer, ...args) as ReturnType<DesktopBridgeApi["restartMcpServer"]>,
  reloadExtension: (...args: Parameters<DesktopBridgeApi["reloadExtension"]>) => invoke(DESKTOP_IPC.reloadExtension, ...args) as ReturnType<DesktopBridgeApi["reloadExtension"]>,
  runExtensionCommand: (...args: Parameters<DesktopBridgeApi["runExtensionCommand"]>) => invoke(DESKTOP_IPC.runExtensionCommand, ...args) as ReturnType<DesktopBridgeApi["runExtensionCommand"]>,
  createReplay: (...args: Parameters<DesktopBridgeApi["createReplay"]>) => invoke(DESKTOP_IPC.createReplay, ...args) as ReturnType<DesktopBridgeApi["createReplay"]>,
  getReplayDiff: (...args: Parameters<DesktopBridgeApi["getReplayDiff"]>) => invoke(DESKTOP_IPC.getReplayDiff, ...args) as ReturnType<DesktopBridgeApi["getReplayDiff"]>,
  exitReplay: (...args: Parameters<DesktopBridgeApi["exitReplay"]>) => invoke(DESKTOP_IPC.exitReplay, ...args) as ReturnType<DesktopBridgeApi["exitReplay"]>,
  uploadAttachment: (...args: Parameters<DesktopBridgeApi["uploadAttachment"]>) => invoke(DESKTOP_IPC.uploadAttachment, ...args) as ReturnType<DesktopBridgeApi["uploadAttachment"]>,
  getAttachmentContent: (...args: Parameters<DesktopBridgeApi["getAttachmentContent"]>) => invoke(DESKTOP_IPC.getAttachmentContent, ...args) as ReturnType<DesktopBridgeApi["getAttachmentContent"]>,
  getSubagent: (...args: Parameters<DesktopBridgeApi["getSubagent"]>) => invoke(DESKTOP_IPC.getSubagent, ...args) as ReturnType<DesktopBridgeApi["getSubagent"]>,
  getTeam: (...args: Parameters<DesktopBridgeApi["getTeam"]>) => invoke(DESKTOP_IPC.getTeam, ...args) as ReturnType<DesktopBridgeApi["getTeam"]>,
  createTeam: (...args: Parameters<DesktopBridgeApi["createTeam"]>) => invoke(DESKTOP_IPC.createTeam, ...args) as ReturnType<DesktopBridgeApi["createTeam"]>,
  sendTeamMailbox: (...args: Parameters<DesktopBridgeApi["sendTeamMailbox"]>) => invoke(DESKTOP_IPC.sendTeamMailbox, ...args) as ReturnType<DesktopBridgeApi["sendTeamMailbox"]>,
  claimTeamMailbox: (...args: Parameters<DesktopBridgeApi["claimTeamMailbox"]>) => invoke(DESKTOP_IPC.claimTeamMailbox, ...args) as ReturnType<DesktopBridgeApi["claimTeamMailbox"]>,
  writeTeamTask: (...args: Parameters<DesktopBridgeApi["writeTeamTask"]>) => invoke(DESKTOP_IPC.writeTeamTask, ...args) as ReturnType<DesktopBridgeApi["writeTeamTask"]>,
  heartbeatTeam: (...args: Parameters<DesktopBridgeApi["heartbeatTeam"]>) => invoke(DESKTOP_IPC.heartbeatTeam, ...args) as ReturnType<DesktopBridgeApi["heartbeatTeam"]>,
  sweepLostTeamMembers: (...args: Parameters<DesktopBridgeApi["sweepLostTeamMembers"]>) => invoke(DESKTOP_IPC.sweepLostTeamMembers, ...args) as ReturnType<DesktopBridgeApi["sweepLostTeamMembers"]>,
  rollbackAction: (...args: Parameters<DesktopBridgeApi["rollbackAction"]>) => invoke(DESKTOP_IPC.rollbackAction, ...args) as ReturnType<DesktopBridgeApi["rollbackAction"]>,
  getWorkbenchSettings: (...args: Parameters<DesktopBridgeApi["getWorkbenchSettings"]>) => invoke(DESKTOP_IPC.getWorkbenchSettings, ...args) as ReturnType<DesktopBridgeApi["getWorkbenchSettings"]>,
  updateWorkbenchSettings: (...args: Parameters<DesktopBridgeApi["updateWorkbenchSettings"]>) => invoke(DESKTOP_IPC.updateWorkbenchSettings, ...args) as ReturnType<DesktopBridgeApi["updateWorkbenchSettings"]>,
  getCapabilities: (...args: Parameters<DesktopBridgeApi["getCapabilities"]>) => invoke(DESKTOP_IPC.getCapabilities, ...args) as ReturnType<DesktopBridgeApi["getCapabilities"]>,
  testModel: (...args: Parameters<DesktopBridgeApi["testModel"]>) => invoke(DESKTOP_IPC.testModel, ...args) as ReturnType<DesktopBridgeApi["testModel"]>,
  getWorkbenchResources: (...args: Parameters<DesktopBridgeApi["getWorkbenchResources"]>) => invoke(DESKTOP_IPC.getWorkbenchResources, ...args) as ReturnType<DesktopBridgeApi["getWorkbenchResources"]>,
  workbenchCommand: (...args: Parameters<DesktopBridgeApi["workbenchCommand"]>) => invoke(DESKTOP_IPC.workbenchCommand, ...args) as ReturnType<DesktopBridgeApi["workbenchCommand"]>,
  openStream: (...args: Parameters<DesktopBridgeApi["openStream"]>) => invoke(DESKTOP_IPC.openStream, ...args) as ReturnType<DesktopBridgeApi["openStream"]>,
  readStream: (...args: Parameters<DesktopBridgeApi["readStream"]>) => invoke(DESKTOP_IPC.readStream, ...args) as ReturnType<DesktopBridgeApi["readStream"]>,
  closeStream: (...args: Parameters<DesktopBridgeApi["closeStream"]>) => invoke(DESKTOP_IPC.closeStream, ...args) as ReturnType<DesktopBridgeApi["closeStream"]>,
});

contextBridge.exposeInMainWorld("tracegraphDesktop", bridge);
