import {readFile} from "node:fs/promises";
import {runInNewContext} from "node:vm";
import {describe,it,expect,vi} from "vitest";
import type {DesktopBridgeApi} from "./bridge-contract.js";
import {createDesktopSdkPort} from "./desktop-sdk.js";
async function fixture(){const source=await readFile(new URL("../dist/preload.cjs",import.meta.url),"utf8");const listeners=new Map<string,Function>();let bridge!:DesktopBridgeApi;const invoke=vi.fn();runInNewContext(source,{exports:{},require:(name:string)=>{expect(name).toBe("electron");return {contextBridge:{exposeInMainWorld:(name:string,value:DesktopBridgeApi)=>{expect(name).toBe("tracegraphDesktop");bridge=value;}},ipcRenderer:{invoke,on:(channel:string,listener:Function)=>listeners.set(channel,listener)}};},queueMicrotask});return {bridge,listeners,invoke};}
const navigation={event_id:"event:stored",run_id:"run:one",project_id:"project:one",session_id:"session:one",connection_generation:4};
describe("compiled sandbox preload read-only notification event",()=>{
 it("registers only the closed event, buffers before view mount, unsubscribes and never invokes commands",async()=>{const f=await fixture();expect([...f.listeners.keys()]).toEqual(["tracegraph:native-run-requested"]);const event=f.listeners.get("tracegraph:native-run-requested")!;event({},navigation);const seen=vi.fn();const unsubscribe=f.bridge.onNativeRunRequested!(seen);await new Promise(resolve=>queueMicrotask(()=>resolve(undefined)));expect(seen).toHaveBeenCalledWith(navigation);event({},navigation);expect(seen).toHaveBeenCalledTimes(2);unsubscribe();event({},navigation);expect(seen).toHaveBeenCalledTimes(2);expect(f.invoke).not.toHaveBeenCalled();});
 it("rejects payload execution authority, malformed identities and generations before notifying any consumer",async()=>{const f=await fixture();const seen=vi.fn();f.bridge.onNativeRunRequested!(seen);const event=f.listeners.get("tracegraph:native-run-requested")!;for(const value of [{...navigation,token:"private"},{...navigation,resume:true},{...navigation,path:"/arbitrary"},{...navigation,connection_generation:-1},{...navigation,run_id:""},{...navigation,run_id:"x".repeat(161)},null])event({},value);expect(seen).not.toHaveBeenCalled();expect(f.invoke).not.toHaveBeenCalled();expect(()=>f.bridge.onNativeRunRequested!(null as never)).toThrow();});
 it("forwards through DesktopSdkPort with a removable subscription and strict safe payload schema",()=>{let listener!:Function;const unsubscribe=vi.fn();const bridge={onNativeRunRequested:vi.fn((callback:Function)=>{listener=callback;return unsubscribe;})} as unknown as DesktopBridgeApi;const sdk=createDesktopSdkPort(bridge);const seen=vi.fn();const detach=sdk.onNativeRunRequested!(seen);listener(navigation);expect(seen).toHaveBeenCalledWith(navigation);expect(()=>listener({...navigation,resume:true})).toThrow();expect(seen).toHaveBeenCalledOnce();detach();expect(unsubscribe).toHaveBeenCalledOnce();});
});
