import {describe,expect,it} from 'vitest';
import {SharedRunBudget,type ModelInput} from '@tracegraph/core';
import {budgetedFixtureModel} from '../test-support/budgeted-fixture-model.js';

const input={projectId:'project:fixture',runId:'run:fixture',task:'Controlled test',mode:'execute',turn:1,reasoningEffort:'default',context:'Public fixture context',observations:[],toolSchemas:[]} as unknown as ModelInput;
describe('test-only fixture adapter enforces the real aggregate reservation seam',()=>{
 it('rejects insufficient budget before invoking the decision producer',async()=>{let calls=0;const budget=new SharedRunBudget({identity:'fixture:small',limits:{max_tokens:10},checkpoint:async()=>{}}),model=budgetedFixtureModel({name:'fixture:small',async decide(){calls++;return{};}});try{await expect(model.decide({...input,requestBudget:budget})).rejects.toMatchObject({code:'goal_token_limit'});expect(calls).toBe(0);expect(budget.snapshot()).toMatchObject({request_count:0,charged_tokens:0,held_tokens:0});}finally{budget.dispose();}});
 it('records actual reservations and bounded synthetic fixture response usage',async()=>{const checkpoints:string[]=[],budget=new SharedRunBudget({identity:'fixture:known',limits:{max_tokens:10_000},checkpoint:async value=>{checkpoints.push(value.phase);}}),model=budgetedFixtureModel({name:'fixture:known',async decide(){return{answer:'bounded'};}});try{expect(await model.decide({...input,requestBudget:budget})).toEqual({answer:'bounded'});expect(checkpoints).toEqual(['reserved','settled']);expect(budget.snapshot()).toMatchObject({request_count:1,held_tokens:0,unknown_request_count:0});expect(budget.snapshot().charged_tokens).toBeGreaterThan(1000);}finally{budget.dispose();}});
 it('retains a conservative unknown charge if the fixture producer cannot return a result',async()=>{const budget=new SharedRunBudget({identity:'fixture:unknown',limits:{max_tokens:10_000},checkpoint:async()=>{}}),model=budgetedFixtureModel({name:'fixture:unknown',async decide(){throw Error('Controlled lost result');}});try{await expect(model.decide({...input,requestBudget:budget})).rejects.toThrow('Controlled lost result');expect(budget.snapshot()).toMatchObject({request_count:1,held_tokens:0,unknown_request_count:1,stop_reason:'usage_unknown'});}finally{budget.dispose();}});
});
