import {mkdtemp,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {describe,expect,it} from "vitest";
import type {ComputerAction,ComputerTarget,ComputerNativeStatus} from "@tracegraph/contracts";
import {ComputerControl,type NativeComputerBackend} from "./computer-control.js";

const target:ComputerTarget={application_id:"test.owned-editor",pid:123,title:"Owned test app",identity:"sha256:"+"a".repeat(64),window_id:"44"};
const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlGAAAAAASUVORK5CYII=","base64");
class FixtureBackend implements NativeComputerBackend {
 native:ComputerNativeStatus={platform:"darwin",backend_available:true,accessibility:true,screen_capture:true,input_monitoring:true,locked:false};
 calls=0;observations=0;closed=false;changed=false;foreground=true;early:false|"user-input"=false;
 event:((event:"user-input"|"locked"|"target-changed"|"monitor-unavailable")=>void)|undefined;
 hold:((signal:AbortSignal)=>Promise<void>)|undefined;
 async status(){return this.native;}async targets(){return [target];}
 async validateTarget(value:ComputerTarget,_foreground:boolean){if(this.changed||_foreground&&!this.foreground||value.identity!==target.identity||value.pid!==target.pid||value.window_id!==target.window_id)throw Object.assign(new Error("changed"),{code:"computer_target_changed",statusCode:409});}
 async focusTarget(_target:ComputerTarget){this.foreground=true;}
 async inspect(_target:ComputerTarget){this.observations++;return {elements:[{element_id:"ax:1",role:"AXStaticText",value:"API_KEY=private-test-secret"}],truncated:false};}
 async capture(){return png;}
 async watch(_target:ComputerTarget,listener:NonNullable<FixtureBackend["event"]>){this.event=listener;if(this.early)listener(this.early);return {close:async()=>{this.event=undefined;}};}
 async act(_target:ComputerTarget,_action:ComputerAction,signal:AbortSignal){this.calls++;if(this.hold)await this.hold(signal);}
 async close(){this.closed=true;}
}
async function fixture(input:{human?:boolean;backend?:FixtureBackend;now?:()=>Date}={}){const root=await mkdtemp(join(tmpdir(),"outlive-computer-unit-"));const backend=input.backend??new FixtureBackend();const control=await ComputerControl.create({profileRoot:root,backend,...(input.human===false?{}:{answerGrant:async()=>"allow" as const,confirmInputLease:async()=>true}),...(input.now?{now:input.now}:{})});return {root,backend,control,close:async()=>{await control.close();await rm(root,{recursive:true,force:true});}};}
async function grantAndLease(control:ComputerControl,duration:"once"|"always"="always"){const grant=await control.requestGrant({command_id:"grant",target,duration});const lease=await control.acquireLease({command_id:"lease",grant_id:grant.grant_id,target,seconds:300});return {grant,lease};}

describe("computer app authority and exclusive human handback",()=>{
 it("cannot synthesize a human grant or bypass it using target identity",async()=>{const f=await fixture({human:false});try{await expect(f.control.requestGrant({command_id:"self-grant",target,duration:"always"})).rejects.toMatchObject({code:"computer_grant_ui_unavailable"});await expect(f.control.observe({command_id:"observe",grant_id:"forged",target,capture:false})).rejects.toMatchObject({code:"computer_grant_required"});expect(f.backend.observations).toBe(0);expect((await f.control.status()).human_grant_available).toBe(false);}finally{await f.close();}});
 it("never grants its own authorization UI or system-permission settings",async()=>{const f=await fixture();try{for(const id of ["com.outlive.agent","com.apple.systempreferences","win:outlive agent.exe","win:systemsettings.exe","win:consent.exe"]){await expect(f.control.requestGrant({command_id:"protected:"+id,target:{...target,application_id:id},duration:"always"})).rejects.toMatchObject({code:"computer_authority_target_denied"});}expect((await f.control.status()).grants).toHaveLength(0);expect(f.backend.calls).toBe(0);}finally{await f.close();}});
 it("rejects missing OS Accessibility and input-monitor permissions before dispatch",async()=>{const f=await fixture();try{f.backend.native.accessibility=false;await expect(f.control.requestGrant({command_id:"ax-denied",target,duration:"once"})).rejects.toMatchObject({code:"computer_accessibility_required"});f.backend.native.accessibility=true;const grant=await f.control.requestGrant({command_id:"grant",target,duration:"once"});f.backend.native.input_monitoring=false;await expect(f.control.acquireLease({command_id:"input-denied",grant_id:grant.grant_id,target,seconds:15})).rejects.toMatchObject({code:"computer_monitor_required"});expect(f.backend.calls).toBe(0);}finally{await f.close();}});
 it("admits only one lease, pauses immediately on external input and requires explicit human resume with CAS",async()=>{const f=await fixture();try{const {grant,lease}=await grantAndLease(f.control);await expect(f.control.acquireLease({command_id:"competing",grant_id:grant.grant_id,target,seconds:300})).rejects.toMatchObject({code:"computer_input_busy"});f.backend.event?.("user-input");const paused=(await f.control.status()).lease!;expect(paused).toMatchObject({state:"paused",pause_reason:"user-input",generation:1});await expect(f.control.act({command_id:"paused-write",lease_id:lease.lease_id,expected_generation:0,action:{kind:"key",key:"Enter",modifiers:[]}})).rejects.toMatchObject({code:"computer_lease_conflict"});await expect(f.control.resumeLease({command_id:"stale-resume",lease_id:lease.lease_id,expected_generation:0})).rejects.toMatchObject({code:"computer_lease_conflict"});const resumed=await f.control.resumeLease({command_id:"manual-resume",lease_id:lease.lease_id,expected_generation:1});expect(resumed.state).toBe("active");expect(resumed.generation).toBe(2);expect(f.backend.calls).toBe(0);}finally{await f.close();}});
 it("permits only trusted human composition to focus the selected window and still validates it after confirmation",async()=>{const root=await mkdtemp(join(tmpdir(),"outlive-computer-focus-"));const backend=new FixtureBackend();backend.foreground=false;let confirmations=0;let changeAfterConfirmation=false;const control=await ComputerControl.create({profileRoot:root,backend,answerGrant:async()=>"allow",confirmInputLease:async({target})=>{confirmations++;await backend.focusTarget(target);if(changeAfterConfirmation)backend.foreground=false;return true;}});try{const {lease}=await grantAndLease(control);expect(confirmations).toBe(1);expect(lease.state).toBe("active");backend.event?.("user-input");backend.foreground=false;changeAfterConfirmation=true;await expect(control.resumeLease({command_id:"foreign-focus",lease_id:lease.lease_id,expected_generation:1})).rejects.toMatchObject({code:"computer_target_changed"});expect((await control.status()).lease?.state).toBe("paused");expect(backend.calls).toBe(0);}finally{await control.close();await rm(root,{recursive:true,force:true});}});
 it("refuses Plan Mode input and exposes a durable receipt without repeating input",async()=>{const f=await fixture();try{const {lease}=await grantAndLease(f.control);const input={command_id:"plan-action",lease_id:lease.lease_id,expected_generation:0,action:{kind:"key" as const,key:"Enter" as const,modifiers:[]}};await expect(f.control.act(input,{mode:"plan"})).rejects.toMatchObject({code:"computer_plan_readonly"});expect(f.backend.calls).toBe(0);expect(await f.control.reconcile(input.command_id)).toMatchObject({state:"not_found"});const result=await f.control.act({...input,command_id:"real-action"});expect(await f.control.reconcile("real-action")).toMatchObject({state:"completed",result});expect(f.backend.calls).toBe(1);}finally{await f.close();}});
 it("does not miss user input occurring while the monitoring readiness handshake is settling",async()=>{const backend=new FixtureBackend();backend.early="user-input";const f=await fixture({backend});try{const {lease}=await grantAndLease(f.control);expect(lease).toMatchObject({state:"paused",pause_reason:"user-input"});expect((await f.control.status()).lease?.state).toBe("paused");}finally{await f.close();}});
 it("revokes authority during in-flight input, records unknown, and never retries the same command",async()=>{const f=await fixture();let started!:()=>void;const begun=new Promise<void>(resolve=>started=resolve);f.backend.hold=signal=>new Promise((_,reject)=>{started();signal.addEventListener("abort",()=>reject(new Error("aborted")),{once:true});});try{const {grant,lease}=await grantAndLease(f.control);const input={command_id:"write-once",lease_id:lease.lease_id,expected_generation:0,action:{kind:"type" as const,text:"Owned test value"}};const action=f.control.act(input);await begun;await f.control.revokeGrant({command_id:"revoke",grant_id:grant.grant_id});const receipt=await action;expect(receipt.status).toBe("unknown");expect(f.backend.calls).toBe(1);expect(await f.control.act(input)).toEqual(receipt);expect(f.backend.calls).toBe(1);await expect(f.control.observe({command_id:"after-revoke",grant_id:grant.grant_id,target,capture:false})).rejects.toMatchObject({code:"computer_grant_required"});}finally{await f.close();}});
 it("records only posted input, rechecks identity before every action, and refuses command-id reuse",async()=>{const f=await fixture();try{const {lease}=await grantAndLease(f.control);const input={command_id:"click-once",lease_id:lease.lease_id,expected_generation:0,action:{kind:"click" as const,x:2,y:3,button:"left" as const}};const result=await f.control.act(input);expect(result).toMatchObject({status:"posted",code:"native_input_posted_unverified"});expect(result.message).toContain("verify the business result");await f.control.act(input);expect(f.backend.calls).toBe(1);await expect(f.control.act({...input,action:{...input.action,x:4}})).rejects.toMatchObject({code:"command_id_conflict"});f.backend.changed=true;await expect(f.control.act({...input,command_id:"changed-target"})).rejects.toMatchObject({code:"computer_target_changed"});expect(f.backend.calls).toBe(1);}finally{await f.close();}});
 it("produces redacted AX and actual bounded PNG Artifacts linked to the exact granted target",async()=>{const f=await fixture();try{const grant=await f.control.requestGrant({command_id:"grant",target,duration:"always"});const observation=await f.control.observe({command_id:"window-observe",grant_id:grant.grant_id,target,capture:true});expect(JSON.stringify(observation)).not.toContain("private-test-secret");expect(observation.artifact.kind).toBe("tool_output");expect(observation.capture_artifact?.kind).toBe("image/png");const bytes=await f.control.captureContent({grant_id:grant.grant_id,target,artifact:observation.capture_artifact!});expect(Buffer.from(bytes)).toEqual(png);await expect(f.control.captureContent({grant_id:grant.grant_id,target:{...target,window_id:"45"},artifact:observation.capture_artifact!})).rejects.toMatchObject({code:"computer_capture_scope"});const files=await readFile(join(f.root,"computer-grants.json"),"utf8");expect(files).not.toContain("private-test-secret");expect(f.backend.observations).toBe(1);}finally{await f.close();}});
 it("expires input authority, blocks locked input, and persists grants without restoring leases or replaying input",async()=>{let now=new Date("2026-10-05T00:00:00Z");const f=await fixture({now:()=>now});try{const {grant,lease}=await grantAndLease(f.control);f.backend.event?.("locked");expect((await f.control.status()).lease?.pause_reason).toBe("locked");f.backend.native.locked=true;await expect(f.control.resumeLease({command_id:"locked-resume",lease_id:lease.lease_id,expected_generation:1})).rejects.toMatchObject({code:"computer_locked"});f.backend.native.locked=false;now=new Date("2026-10-05T00:10:00Z");expect((await f.control.status()).lease?.pause_reason).toBe("expired");await f.control.close();const restarted=await ComputerControl.create({profileRoot:f.root,backend:new FixtureBackend(),answerGrant:async()=>"allow",confirmInputLease:async()=>true});try{const status=await restarted.status();expect(status.lease).toBeNull();expect(status.grants).toContainEqual(expect.objectContaining({grant_id:grant.grant_id,state:"active"}));await expect(restarted.act({command_id:"new-after-restart",lease_id:lease.lease_id,expected_generation:0,action:{kind:"key",key:"Enter",modifiers:[]}})).rejects.toMatchObject({code:"computer_lease_missing"});}finally{await restarted.close();}}finally{await f.close();}});
 it("releases a once grant and cannot reuse it after handback",async()=>{const f=await fixture();try{const {grant,lease}=await grantAndLease(f.control,"once");await f.control.releaseLease({command_id:"handback",lease_id:lease.lease_id});expect((await f.control.status()).lease?.state).toBe("released");await expect(f.control.acquireLease({command_id:"reuse-once",grant_id:grant.grant_id,target,seconds:15})).rejects.toMatchObject({code:"computer_grant_required"});}finally{await f.close();}});
 it("cancels an outstanding human prompt when the owner closes and admits no late authority",async()=>{const root=await mkdtemp(join(tmpdir(),"outlive-computer-close-"));let entered!:()=>void;const begun=new Promise<void>(resolve=>entered=resolve);let answer!:(value:"allow")=>void;const control=await ComputerControl.create({profileRoot:root,backend:new FixtureBackend(),answerGrant:async()=>{entered();return new Promise(resolve=>answer=resolve);},confirmInputLease:async()=>true});try{const pending=control.requestGrant({command_id:"pending-human",target,duration:"always"});const rejected=expect(pending).rejects.toMatchObject({code:"computer_closed"});await begun;await control.close();answer("allow");await rejected;await expect(readFile(join(root,"computer-grants.json"))).rejects.toMatchObject({code:"ENOENT"});}finally{await control.close();await rm(root,{recursive:true,force:true});}});
});
