import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {createServer,type Server} from "node:http";
import {cp,mkdir,mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createHash} from "node:crypto";
import {afterEach,describe,expect,it} from "vitest";
import {ConfigurableModelAdapter,JsonlEventLedger,PrivateFileCredentialStore,type AgentRuntime} from "@tracegraph/core";
import {type RunProjection} from "@tracegraph/contracts";
import {createHostComposition} from "./composition/host-composition.js";
const roots:string[]=[],servers:Server[]=[],compositions:Array<Awaited<ReturnType<typeof createHostComposition>>>=[];
const sha256=(value:string|Uint8Array)=>`sha256:${createHash("sha256").update(value).digest("hex")}`;
afterEach(async()=>{for(const value of compositions.splice(0))await value.close();for(const server of servers.splice(0)){server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
const before="export function clamp(value, min, max) { return value; }\n";
const buggy="export function clamp(value, min, max) { if (![value,min,max].every(Number.isFinite)) throw new TypeError('finite required'); return Math.max(min, Math.min(max, value)); }\n";
const fixed="export function clamp(value, min, max) { if (![value,min,max].every(Number.isFinite)) throw new TypeError('finite required'); if (min > max) throw new RangeError('reversed range'); return Math.max(min, Math.min(max, value)); }\n";
const tests="import assert from 'node:assert/strict'; import {clamp} from '../dist/clamp.mjs'; assert.equal(clamp(12,0,10),10); assert.equal(clamp(-1,0,10),0); assert.equal(clamp(4,0,10),4); assert.throws(()=>clamp(NaN,0,10),TypeError); console.log('ACTUAL_CLAMP_TESTS_PASS');\n";
const repairedTests=tests+"assert.throws(()=>clamp(4,10,0),RangeError); console.log('ACTUAL_REVERSED_RANGE_REGRESSION_PASS');\n";
function answer(review_result?:unknown){return{decision_id:"decision:finish",kind:"finish",finish_intent:"answer",public_reason:"Recorded software result",evidence_refs:[],risk:"none",final_answer:"Controlled implementation and real verification recorded; final user acceptance remains separate",...(review_result===undefined?{}:{review_result})};}
let operation=0;
function call(name:string,args:Record<string,unknown>){return{decision_id:`decision:${name}`,kind:"tool_call",public_reason:"Perform the scoped software check",evidence_refs:[],risk:"low",tool_call:{action_id:`action:${name}:${++operation}`,tool_name:name,arguments:args}};}
async function fixture(){const root=await mkdtemp(join(tmpdir(),"outlive-delivery-review-"));roots.push(root);const project=join(root,"project");for(const dir of ["src","test"])await mkdir(join(project,dir),{recursive:true});await writeFile(join(project,"src/clamp.mjs"),before);await writeFile(join(project,"test/clamp.test.mjs"),tests);await writeFile(join(project,"build.mjs"),"import {mkdirSync,copyFileSync} from 'node:fs';mkdirSync('dist',{recursive:true});copyFileSync('src/clamp.mjs','dist/clamp.mjs');console.log('ACTUAL_BUILD_OUTPUT');\n");const manifest=JSON.stringify({version:1,commands:{verify:{executable:"node",args:["verify.mjs"]}}});await writeFile(join(project,"outlive.commands.json"),manifest);await writeFile(join(project,"verify.mjs"),"import {spawnSync} from 'node:child_process';for(const file of ['build.mjs','test/clamp.test.mjs']){const result=spawnSync(process.execPath,[file],{stdio:'inherit'});if(result.status!==0)process.exit(result.status??1);}\n");return{root,project,manifestHash:sha256(manifest)};}
async function modelFixture(respond:(input:{body:Record<string,unknown>;serialized:string;child:boolean})=>unknown){let calls=0,childCalls=0;const requests:Array<{child:boolean;body:Record<string,unknown>}>=[];const server=createServer(async(req,res)=>{const chunks:Buffer[]=[];for await(const part of req)chunks.push(Buffer.from(part));const body=JSON.parse(Buffer.concat(chunks).toString()) as Record<string,unknown>,serialized=JSON.stringify(body),child=serialized.includes("You are the independent readonly delivery reviewer");calls++;if(child)childCalls++;requests.push({child,body});let decision;try{decision=await respond({body,serialized,child});}catch(error){res.writeHead(500,{"content-type":"application/json"});res.end(JSON.stringify({error:String(error)}));return;}res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(decision)}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));});servers.push(server);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error("Fixture address missing");const model=new ConfigurableModelAdapter({resolveCredential:async()=>"controlled-review-key-not-live"});model.configure({provider:"custom",protocol:"openai-chat-completions",baseUrl:`http://127.0.0.1:${address.port}/v1`,model:"delivery-protocol-fixture",credentialRef:"${secret:CONTROLLED_REVIEW_KEY}"});return{model,baseUrl:`http://127.0.0.1:${address.port}/v1`,requests,calls:()=>calls,childCalls:()=>childCalls};}
async function wait(runtime:AgentRuntime,id:string){const deadline=Date.now()+15_000;while(Date.now()<deadline){const value=await runtime.getProjection(id);if(["completed","failed","cancelled"].includes(value.status))return value;await new Promise(resolve=>setTimeout(resolve,10));}throw new Error(`No terminal: ${JSON.stringify((await runtime.getProjection(id)).timeline.slice(-2))}`);}
function reviewReads(body:Record<string,unknown>){
 const strings:string[]=[];const collect=(value:unknown):void=>{if(typeof value==="string"){strings.push(value);try{collect(JSON.parse(value));}catch{}}else if(Array.isArray(value))value.forEach(collect);else if(value&&typeof value==="object")Object.values(value).forEach(collect);};collect(body);const text=strings.join("\n");
 const match=/"kind"\s*:\s*"delivery_requirements"[\s\S]*?"locator"\s*:\s*"([^"]+)"/.exec(text);
 if(!match)throw new Error("Actual scoped delivery packet observation missing");
 return{decision_id:"decision:review-reads",kind:"tool_call",public_reason:"Read complete public requirements and source independently",evidence_refs:[],risk:"none",tool_calls:[{action_id:"review:requirements",tool_name:"read_artifact",arguments:{locator:match[1],offset:0,limit:4000}},...["src/clamp.mjs","outlive.commands.json","test/clamp.test.mjs"].map((path,index)=>({action_id:`review:read:${index}`,tool_name:"read_file",arguments:{path}}))]};
}
const passed={verdict:"passed",reviewed_paths:["src/clamp.mjs","outlive.commands.json","test/clamp.test.mjs"],findings:[]};

async function compose(root:string,model:ConfigurableModelAdapter){const value=await createHostComposition({profileRoot:root,deliveryBudget:{max_tokens:200_000,max_time_ms:900_000},dataDir:join(root,"data"),sessionDir:join(root,"sessions"),permissionConfigPath:join(root,"permission.json"),credentialStore:new PrivateFileCredentialStore(join(root,"credentials.json")),environment:{TRACEGRAPH_PERMISSION_PRESET:"full-write"},runtimeModel:model,useEnvironmentModel:false,nativePicker:false,nativePermissionPrompts:false,admission:"workspace"});compositions.push(value);return value;}
async function api(composition:Awaited<ReturnType<typeof compose>>){await composition.host.app.listen({port:0,host:"127.0.0.1"});const address=composition.host.app.server.address();if(!address||typeof address==="string")throw new Error("Controlled API address unavailable");const base=`http://127.0.0.1:${address.port}`,origin="http://127.0.0.1:4310";const bootstrap=await fetch(base+"/api/bootstrap",{headers:{origin}});if(!bootstrap.ok)throw new Error("Controlled bootstrap failed");const token=(await bootstrap.json() as {token:string}).token;return async(path:string,input:Record<string,unknown>)=>{const result=await fetch(base+path,{method:"POST",headers:{origin,authorization:`Bearer ${token}`,"content-type":"application/json","x-tracegraph-command-id":String(input.command_id)},body:JSON.stringify(input)});return{status:result.status,body:await result.json() as Record<string,unknown>};};}
async function waiting(runtime:AgentRuntime,id:string){const deadline=Date.now()+8000;while(Date.now()<deadline){const value=await runtime.getProjection(id);if(value.status==="awaiting_approval")return value;if(["failed","cancelled","completed"].includes(value.status))throw new Error(JSON.stringify(value.timeline.slice(-2)));await new Promise(resolve=>setTimeout(resolve,10));}throw new Error("Actual API approval not reached");}
async function recovered(named=false){const f=await fixture();await mkdir(join(f.project,".tracegraph"));await writeFile(join(f.project,".tracegraph/policy.json"),JSON.stringify({policy_version:1,rules:[{rule_id:"human:patch",priority:100,when:{tool:"commit_patch"},then:"ask",explanation:"Explicit human patch approval required"}]}));let root=0,review=0;const provider=await modelFixture(({child,body})=>child?++review===1?reviewReads(body):answer(passed):++root===1?call("preview_patch",{path:"src/clamp.mjs",expected:before,replacement:fixed}):root===2?call("run_project_command",{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:f.manifestHash}):answer());const source=join(f.root,"source"),snapshot=join(f.root,"snapshot"),first=await compose(source,provider.model),project=await first.registerProject(f.project,"read_write"),post=await api(first);let connection:Record<string,unknown>|undefined;if(named){const saved=await post("/api/workbench/models",{command_id:"api:save-controlled-connection",label:"Controlled saved provider",provider:"custom",protocol:"openai-chat-completions",base_url:provider.baseUrl,model:"delivery-protocol-fixture",api_key:"controlled-review-key-not-live"});expect(saved.status,JSON.stringify(saved.body)).toBe(200);connection=(saved.body.connections as Array<Record<string,unknown>>)[0];}const started=await post("/api/runs",{command_id:"api:start",project_id:project.workspace.project_id,task:"Implement the clamp library and actually build/test it",mode:"execute"});expect(started.status).toBe(200);const pending=await waiting(first.runtime,String(started.body.run_id));await cp(source,snapshot,{recursive:true,filter:path=>!path.endsWith(".lock")});await first.close();const fresh=await compose(snapshot,provider.model),request=await api(fresh);return{f,provider,pending,fresh,request,connection};}
describe("production API finite human continuation",{timeout:20000},()=>{
 it("uses the existing typed resume/approval routes with same-budget receipts and real project build/test bytes",async()=>{const f=await recovered();const resumed=await f.request(`/api/sessions/${f.pending.session_id}/resume`,{command_id:"api:resume"});expect(resumed.status,JSON.stringify(resumed.body)).toBe(200);const projection=await f.fresh.runtime.getProjection(f.pending.run_id);expect(projection.status).toBe("awaiting_approval");expect(f.provider.calls()).toBe(1);expect(await readFile(join(f.f.project,"src/clamp.mjs"),"utf8")).toBe(before);const approval=projection.pending_approval!,response=await f.request(`/api/runs/${projection.run_id}/approve`,{type:"approve",command_id:"api:approve",project_id:projection.project_id,run_id:projection.run_id,approval_id:approval.approval_id,action_id:approval.action_id});expect(response.status,JSON.stringify(response.body)).toBe(200);const terminal=await wait(f.fresh.runtime,projection.run_id);expect(terminal.status,JSON.stringify(terminal.timeline.slice(-3))).toBe("completed");expect(await readFile(join(f.f.project,"dist/clamp.mjs"),"utf8")).toBe(fixed);expect(terminal.timeline.filter(event=>event.data.operation==="delivery.budget_admitted")).toHaveLength(1);expect(terminal.timeline.find(event=>event.data.operation==="delivery.budget_restored")?.data).toMatchObject({new_budget:false,budget_snapshot:{charged_tokens:15,request_count:1}});const calls=f.provider.calls(),retry=await f.request(`/api/sessions/${f.pending.session_id}/resume`,{command_id:"api:resume"});expect(retry.status).toBe(200);expect(f.provider.calls()).toBe(calls);const output=process.env.OUTLIVE_CONTINUATION_API_EVIDENCE_ROOT;if(output){await mkdir(output,{recursive:true});const ledger=new JsonlEventLedger(join(f.f.root,"snapshot/data/events"));await ledger.initialize();const events=Object.fromEntries(await Promise.all([terminal.run_id,...terminal.subagents.items.map(item=>item.link.child_run_id)].map(async id=>[id,await ledger.list(id)])));await writeFile(join(output,"events.json"),JSON.stringify(events,null,2));await writeFile(join(output,"report.json"),JSON.stringify({status:"passed",boundary:"actual HTTP API and local deterministic provider; durable pre-shutdown copy, not paid model quality",api_statuses:{start:200,resume:resumed.status,approval:response.status,retry:retry.status},provider_requests:calls,run_id:terminal.run_id,terminal:terminal.timeline.at(-1)?.data,source_sha256:sha256(await readFile(join(f.f.project,"src/clamp.mjs"))),built_sha256:sha256(await readFile(join(f.f.project,"dist/clamp.mjs")))},null,2));}});
 it.each(["model","policy"] as const)("rejects changed %s on the actual resume endpoint with zero additional provider requests",async kind=>{const f=await recovered();if(kind==="model")f.provider.model.clearConfiguration();else await f.fresh.permissionConfig.setUserPreset("read-only");const beforeCalls=f.provider.calls(),response=await f.request(`/api/sessions/${f.pending.session_id}/resume`,{command_id:`api:reject:${kind}`});expect(response.status,JSON.stringify(response.body)).toBe(409);expect(response.body.error).toBe(kind==="model"?"delivery_model_binding_changed":"resume_policy_changed");expect(f.provider.calls()).toBe(beforeCalls);expect(await readFile(join(f.f.project,"src/clamp.mjs"),"utf8")).toBe(before);});
 it("restores the exact saved model and credential revision, not the current arbitrary default",async()=>{const f=await recovered(true),binding=f.pending.timeline.find(event=>event.type==="run.created")?.data.model_binding;expect(binding).toMatchObject({connection_id:f.connection?.connection_id,revision:f.connection?.revision,model:"delivery-protocol-fixture"});const result=await f.request(`/api/sessions/${f.pending.session_id}/resume`,{command_id:"api:named-resume"});expect(result.status,JSON.stringify(result.body)).toBe(200);expect(f.provider.calls()).toBe(1);const projection=await f.fresh.runtime.getProjection(f.pending.run_id);expect(projection.status).toBe("awaiting_approval");const approval=projection.pending_approval!;const approved=await f.request(`/api/runs/${projection.run_id}/approve`,{type:"approve",command_id:"api:named-approve",project_id:projection.project_id,run_id:projection.run_id,approval_id:approval.approval_id,action_id:approval.action_id});expect(approved.status,JSON.stringify(approved.body)).toBe(200);const terminal=await wait(f.fresh.runtime,projection.run_id);expect(terminal.status,JSON.stringify(terminal.timeline.slice(-3))).toBe("completed");expect(await readFile(join(f.f.project,"dist/clamp.mjs"),"utf8")).toBe(fixed);});
 it("refuses credential/config rotation before admission and never charges a new request",async()=>{const f=await recovered(true),connection=f.connection!;const saved=await f.request("/api/workbench/models",{command_id:"api:rotate-controlled-credential",connection_id:connection.connection_id,expected_revision:connection.revision,label:connection.label,provider:"custom",protocol:"openai-chat-completions",base_url:f.provider.baseUrl,model:"delivery-protocol-fixture",api_key:"controlled-rotated-key-not-live"});expect(saved.status,JSON.stringify(saved.body)).toBe(200);const calls=f.provider.calls(),response=await f.request(`/api/sessions/${f.pending.session_id}/resume`,{command_id:"api:reject-rotated"});expect(response.status,JSON.stringify(response.body)).toBe(409);expect(response.body.error).toBe("delivery_model_binding_changed");expect(f.provider.calls()).toBe(calls);expect((await f.fresh.runtime.getProjection(f.pending.run_id)).timeline.filter(event=>event.data.operation==="delivery.budget_reserved")).toHaveLength(1);expect(await readFile(join(f.f.project,"src/clamp.mjs"),"utf8")).toBe(before);});

});
