import {createHash} from "node:crypto";
import {createServer} from "node:http";
import {mkdtemp,mkdir,link,readFile,readdir,rm,lstat,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join,resolve,dirname} from "node:path";
import {describe,it,expect} from "vitest";
import {ensureLocalHost,connectLocalHost,startLocalHost} from "../dist/local-host.js";
import {WorkbenchJournal} from "./workbench-journal.js";
import {resolveDesktopHostNodeExecutable,verifyStandaloneNodeExecutable} from "./composition/node-executable.js";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {readLocalOwnerStopIntent} from "./local-owner-intent.js";

const a="a".repeat(64),b="b".repeat(64);
async function until<T>(read:()=>Promise<T>,accept:(value:T)=>boolean){const deadline=Date.now()+10_000;while(Date.now()<deadline){const value=await read();if(accept(value))return value;await new Promise(resolve=>setTimeout(resolve,25));}throw new Error("Owned upgrade fixture did not settle");}
async function runtime(root:string,id:string){const dir=join(root,`runtime-${id.slice(0,1)}`);await mkdir(join(dir,"bin"),{recursive:true});const node=await resolveDesktopHostNodeExecutable({execPath:process.execPath,electron:true,platform:process.platform,environment:process.env}),version=(await promisify(execFile)(node,["--eval","process.stdout.write(process.versions.node)"])).stdout,name=process.platform==="win32"?"node.exe":"bin/node";await link(node,join(dir,name));
  // Some developer Node builds use a sibling libnode; fixture resources follow its real executable layout.
  // This is a protocol/process oracle, not proof of the packaged vendor Node graph.
  if(process.platform==="darwin"){const libraryRoot=join(dirname(node),"../lib");let libraries:string[]=[];try{libraries=(await readdir(libraryRoot)).filter(name=>/^libnode\.[0-9]+\.dylib$/u.test(name));}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}if(libraries.length){await mkdir(join(dir,"lib"));for(const library of libraries)await link(join(libraryRoot,library),join(dir,"lib",library));}}
  const hash=createHash("sha256").update(await readFile(node)).digest("hex");await writeFile(join(dir,"runtime-manifest.json"),JSON.stringify({schema_version:"outlive.bundled-runtime.v1",node_version:version,platform:process.platform,arch:process.arch,executable:name,sha256:hash,product_build_id:id}));await verifyStandaloneNodeExecutable(join(dir,name),process.env,version);return dir;}
async function stopOwned(root:string){try{const c=await connectLocalHost({profileRoot:root});await c.stop();await until(async()=>{try{await lstat(join(root,"owner.json"));return false;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return true;throw error;}},x=>x);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT"&&(error as NodeJS.ErrnoException).code!=="ECONNREFUSED")throw error;}}

describe("actual private owner build handoff",()=>{
 it("replaces an idle child PID atomically, deduplicates first-launch clients, and preserves model/settings/completed Run without resubmission",async()=>{
  const root=await mkdtemp(join(tmpdir(),"outlive-real-upgrade-")),profileRoot=join(root,"profile"),one=await runtime(root,a),two=await runtime(root,b),webAssetRoot=resolve("../../apps/web/dist");
  let calls=0;const providerRequests:Array<{startedAt:number;kind:"task"|"derivation"}>=[];const provider=createServer(async(request,response)=>{let raw="";for await(const chunk of request)raw+=String(chunk);const input=JSON.parse(raw) as {messages?:Array<{content?:string}>};calls++;const extraction=input.messages?.[0]?.content?.startsWith("You extract");providerRequests.push({startedAt:Date.now(),kind:extraction?"derivation":"task"});response.writeHead(200,{"content-type":"application/json"});response.end(JSON.stringify({choices:[{message:{content:JSON.stringify(extraction?{summary:"No reusable facts",candidates:[]}:{decision_id:"fixture:preserved-answer",kind:"finish",finish_intent:"answer",public_reason:"Completed before upgrade",evidence_refs:[],risk:"none",final_answer:"Preserved original answer"})}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}));});await new Promise<void>(done=>provider.listen(0,"127.0.0.1",done));const address=provider.address();if(!address||typeof address==="string")throw new Error("Provider missing");
  let old:Awaited<ReturnType<typeof ensureLocalHost>>|undefined,newOne:typeof old,newTwo:typeof old;
  try{old=await ensureLocalHost({profileRoot,runtimeDirectory:one,webAssetRoot,credentialBackend:"private-file",httpPort:0});expect(old.status.pid).not.toBe(process.pid);await old.client.configureModel({provider:"custom",protocol:"openai-chat-completions",base_url:`http://127.0.0.1:${address.port}/v1`,model:"preserved-upgrade-model",api_key:"isolated-upgrade-key"});const settings=await old.client.getWorkbenchSettings();await old.client.updateWorkbenchSettings({command_id:"upgrade:settings",expected_revision:settings.revision,patch:{model:{reasoning_effort:"high"}}});const modelBefore=await old.client.getModelConfig(),settingsBefore=await readFile(join(profileRoot,"workbench-settings.json")),credentialHashBefore=createHash("sha256").update(await readFile(join(profileRoot,"credentials.json"))).digest("hex");const run=await old.client.startChat({command_id:"upgrade:preserved-chat",task:"Complete this answer before the owner upgrade"});const completed=await until(()=>old!.client.getRun(run.run_id),value=>value.status==="completed");const timelineBefore=completed.timeline;
   const ensureAfterSettledProducer=()=>until(async()=>{try{return await ensureLocalHost({profileRoot,runtimeDirectory:two,webAssetRoot,credentialBackend:"private-file",recoveryMode:true});}catch(error){if((error as {code?:string}).code==="local_host_upgrade_required"&&(error as Error).message==="Background work or an owned resource is still settling. The old Host remains running; the application will wait for a safe idle point.")return undefined;throw error;}},value=>value!==undefined);[newOne,newTwo]=await Promise.all([ensureAfterSettledProducer(),ensureAfterSettledProducer()]);expect(newOne).toBeDefined();expect(newTwo).toBeDefined();
   expect(newOne.status.product_build_id).toBe(b);expect(newTwo.status.pid).toBe(newOne.status.pid);expect(newOne.status.pid).not.toBe(old.status.pid);expect(newOne.status.boot_nonce).not.toBe(old.status.boot_nonce);expect(newOne.status.profile_id).toBe(old.status.profile_id);expect(newOne.status.http_address).toBe(old.status.http_address);const modelAfter=await newOne.client.getModelConfig();const stableModel=(value:typeof modelBefore)=>({...value,credential:{...value.credential,last_updated_at:undefined}});expect(stableModel(modelAfter)).toEqual(stableModel(modelBefore));expect(createHash("sha256").update(await readFile(join(profileRoot,"credentials.json"))).digest("hex")).toBe(credentialHashBefore);expect(await readFile(join(profileRoot,"workbench-settings.json"))).toEqual(settingsBefore);const preserved=await newOne.client.getRun(run.run_id);expect(preserved.status).toBe("completed");expect(preserved.timeline).toEqual(timelineBefore);expect(providerRequests.filter(request=>request.kind==="task")).toHaveLength(1);
   const journal=new WorkbenchJournal(join(profileRoot,"owner-upgrade-events"));let prepared=0,retired=0,preparedAt=0;for await(const ids of journal.ledger.iterateRunIdBatches(32))for(const id of ids)for(const event of await journal.ledger.list(id)){if(event.type==="workbench.command_completed"&&event.data.operation==="host.upgrade.prepare"){prepared++;preparedAt=Date.parse(event.occurred_at);}if(event.type==="workbench.command_completed"&&event.data.operation==="host.upgrade.retired")retired++;}expect({prepared,retired}).toEqual({prepared:1,retired:1});expect(providerRequests.length).toBe(calls);expect(providerRequests.every(request=>request.startedAt<=preparedAt)).toBe(true);
   await expect(ensureLocalHost({profileRoot,runtimeDirectory:one,webAssetRoot,credentialBackend:"private-file",recoveryMode:true})).rejects.toMatchObject({code:"local_host_upgrade_required"});const current=await connectLocalHost({profileRoot});expect(current.status.boot_nonce).toBe(newOne.status.boot_nonce);await current.close();
  }finally{await old?.close();await newOne?.close();await newTwo?.close();await stopOwned(profileRoot);await new Promise<void>(resolve=>provider.close(()=>resolve()));await rm(root,{recursive:true,force:true});}
 },30_000);

 it("refuses real held Run work and unknown file commands, preserving the current owner and every original command",async()=>{
  const root=await mkdtemp(join(tmpdir(),"outlive-upgrade-busy-")),profileRoot=join(root,"profile");let release:(()=>void)|undefined,calls=0;
  const provider=createServer(async(request,response)=>{let raw="";for await(const chunk of request)raw+=String(chunk);const input=JSON.parse(raw) as {messages?:Array<{content?:string}>};if(input.messages?.[0]?.content?.startsWith("You extract")){response.writeHead(200,{"content-type":"application/json"});response.end(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:"No reusable facts",candidates:[]})}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}));return;}calls++;release=()=>{if(response.writableEnded)return;response.writeHead(200,{"content-type":"application/json"});response.end(JSON.stringify({choices:[{message:{content:JSON.stringify({decision_id:"fixture:answer",kind:"finish",finish_intent:"answer",public_reason:"Fixture done",evidence_refs:[],risk:"none",final_answer:"Fixture done"})}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}));};});await new Promise<void>(done=>provider.listen(0,"127.0.0.1",done));const address=provider.address();if(!address||typeof address==="string")throw new Error("Provider missing");
  const owner=await startLocalHost({profileRoot,httpPort:0,credentialBackend:"private-file",productBuildId:a}),client=await connectLocalHost({profileRoot});
  try{await client.client.configureModel({provider:"custom",protocol:"openai-chat-completions",base_url:`http://127.0.0.1:${address.port}/v1`,model:"held-upgrade-model",api_key:"isolated-upgrade-provider-key"});const run=await client.client.startChat({command_id:"upgrade:held-chat",task:"Wait for this controlled provider"});await until(async()=>calls,x=>x===1);const input={command_id:"upgrade:held",profile_id:owner.status.profile_id,owner_nonce:owner.status.boot_nonce,source_build_id:a,target_build_id:b};await expect(client.native.prepareUpgrade!(input)).rejects.toMatchObject({code:"host_upgrade_busy"});expect((await client.client.getRun(run.run_id)).status).toBe("running");expect((await client.native.upgradeStatus!()).state).toBe("open");expect((await client.native.upgradeReceipt!(input.command_id)).state).toBe("not_found");release!();await until(()=>client.client.getRun(run.run_id),x=>x.status==="completed");
   const journal=new WorkbenchJournal(join(profileRoot,"project-file-events"));await journal.initialize();await journal.ledger.append({type:"workbench.command_requested",project_id:"fixture:project",run_id:`workbench:${createHash("sha256").update("file:unknown-original").digest("hex")}`,operation_id:"file:unknown-original",attempt:0,artifact_refs:[],summary:"Fixture unknown original write",data:{operation:"file.save",digest:"fixture"}});await new Promise(resolve=>setTimeout(resolve,100));const refused=await until(async()=>{try{await client.native.prepareUpgrade!({...input,command_id:"upgrade:unknown"});return "prepared";}catch(error){return (error as {code?:string}).code??"unsettled";}},code=>code!=="host_upgrade_busy");expect(refused).toBe("host_upgrade_command_unsettled");expect((await client.native.upgradeStatus!()).state).toBe("open");expect((await journal.inspect("file:unknown-original")).state).toBe("unknown");expect(await journal.ledger.list(`workbench:${createHash("sha256").update("file:unknown-original").digest("hex")}`)).toHaveLength(1);expect(calls).toBe(1);const reconnected=await connectLocalHost({profileRoot});expect(reconnected.status.boot_nonce).toBe(owner.status.boot_nonce);await reconnected.close();
  }finally{release?.();await client.close();await owner.close();await new Promise<void>(resolve=>provider.close(()=>resolve()));await rm(root,{recursive:true,force:true});}
 },20_000);

 it("does not revive an explicitly stopped owner from a verified new bundle",async()=>{
  const root=await mkdtemp(join(tmpdir(),"outlive-upgrade-stop-")),profileRoot=join(root,"profile"),one=await runtime(root,a),two=await runtime(root,b),webAssetRoot=resolve("../../apps/web/dist");let old:Awaited<ReturnType<typeof ensureLocalHost>>|undefined;
  try{old=await ensureLocalHost({profileRoot,runtimeDirectory:one,webAssetRoot,credentialBackend:"private-file",httpPort:0});await old.stop();await until(async()=>{try{await lstat(join(profileRoot,"owner.json"));return false;}catch{return true;}},x=>x);const marker=await readFile(join(profileRoot,"owner-stop.json"));await expect(ensureLocalHost({profileRoot,runtimeDirectory:two,webAssetRoot,credentialBackend:"private-file",recoveryMode:true})).rejects.toMatchObject({code:"host_stopped"});expect(await readFile(join(profileRoot,"owner-stop.json"))).toEqual(marker);expect(await readLocalOwnerStopIntent({profileRoot})).toBe(true);}
  finally{await old?.close();await stopOwned(profileRoot);await rm(root,{recursive:true,force:true});}
 },20_000);
});
