import {createServer} from "node:http";
import {mkdtemp,rm,readFile,writeFile,readdir} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {deflateSync} from "node:zlib";
import {createHash} from "node:crypto";
import {describe,it,expect} from "vitest";
import {TraceGraphClient} from "@tracegraph/sdk";
import {ReceiptSchema,type RunProjection} from "@tracegraph/contracts";
import {startLocalHost,connectLocalHost} from "./local-host.js";
const key="isolated-media-fixture-key";
function crc(bytes:Uint8Array){let value=0xffffffff;for(const byte of bytes){value^=byte;for(let i=0;i<8;i++)value=(value>>>1)^((value&1)?0xedb88320:0);}return(value^0xffffffff)>>>0;}
function png(){const chunk=(type:string,data:Buffer)=>{const bytes=Buffer.alloc(data.length+12);bytes.writeUInt32BE(data.length);bytes.write(type,4);data.copy(bytes,8);bytes.writeUInt32BE(crc(bytes.subarray(4,-4)),bytes.length-4);return bytes;};const header=Buffer.alloc(13);header.writeUInt32BE(2,0);header.writeUInt32BE(2,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from("89504e470d0a1a0a","hex"),chunk("IHDR",header),chunk("IDAT",deflateSync(Buffer.from([0,255,0,0,255,0,255,0,255,0,0,0,255,255,255,255,255,255]))),chunk("IEND",Buffer.alloc(0))]);}
async function settle(client:TraceGraphClient,id:string){const deadline=Date.now()+10_000;while(Date.now()<deadline){const run=await client.getRun(id);if(!["created","queued","indexing","running","executing","planning"].includes(run.status))return run;await new Promise(done=>setTimeout(done,10));}throw new Error("Media fixture Run did not settle");}
function mediaReceipt(run:RunProjection){return ReceiptSchema.parse(run.timeline.find(event=>["tool.completed","tool.failed","tool.unknown"].includes(event.type))?.data.receipt);}
describe("MEDIA-094 real authenticated Host/provider/SDK integration",()=>{
 it("uses a dedicated image config without a chat provider; all protocols produce real scoped bytes and exact retries",async()=>{
  const root=await mkdtemp(join(tmpdir(),"outlive-media-host-")),bytes=png(),base64=bytes.toString("base64");const seen:Array<{path:string;body:Record<string,unknown>}> = [];
  const provider=createServer(async(request,response)=>{let text="";for await(const chunk of request)text+=String(chunk);if(request.headers.authorization!=="Bearer "+key){response.writeHead(401);response.end("denied");return;}const body=JSON.parse(text);seen.push({path:request.url!,body});const payload=request.url?.endsWith("/images/generations")?{data:[{b64_json:base64}]}:request.url?.endsWith("/responses")?{status:"completed",output:[{type:"image_generation_call",status:"completed",result:base64}]}:{choices:[{message:{content:"Do not persist this untrusted response body",images:[{image_url:{url:"data:image/png;base64,"+base64}}]}}]};response.writeHead(200,{"content-type":"application/json"});response.end(JSON.stringify(payload));});await new Promise<void>(done=>provider.listen(0,"127.0.0.1",done));const address=provider.address();if(!address||typeof address==="string")throw new Error();
  const owner=await startLocalHost({profileRoot:root,httpPort:0,credentialBackend:"private-file"}),connected=await connectLocalHost({profileRoot:root});const web=new TraceGraphClient({baseUrl:owner.status.http_address});await web.bootstrap();
  try{
   expect(await connected.client.getModelConfig()).toMatchObject({configured:false,has_key:false});expect(await connected.client.getImageConfig()).toMatchObject({configured:false,has_key:false});
   const initial=(await connected.client.getCapabilities()).capabilities;expect(initial.find(value=>value.operation==="media.generate")).toMatchObject({state:"unconfigured"});expect(initial.find(value=>value.operation==="media.chart")).toMatchObject({state:"available"});
   let first:RunProjection|undefined;
   for(const protocol of ["openai-images","openai-responses","openai-chat-images"] as const){const config=await connected.client.configureImageProvider({protocol,base_url:`http://127.0.0.1:${address.port}/v1`,model:"deterministic-image-fixture",api_key:key,...(protocol==="openai-responses"?{image_model:"deterministic-image-model"}:{})});expect(config).toMatchObject({configured:true,has_key:true,protocol});expect(JSON.stringify(config)).not.toContain(key);
    const request={command_id:"command:media-"+protocol,operation:{kind:"generate" as const,prompt:"Return the deterministic PNG fixture",format:"png" as const,size:"1024x1024" as const,quality:"auto" as const}};
    const run=await settle(connected.client,(await connected.client.startMediaRun(request)).run_id);first??=run;expect(run.status).toBe("completed");expect(run.task).toBe("Create image: Return the deterministic PNG fixture");expect(run.timeline.find(event=>event.type==="run.created")?.data.background_model_derivation).toBe(false);const receipt=mediaReceipt(run);expect(receipt).toMatchObject({business_status:"success",code:"media_artifact_created",tool_name:"generate_image"});const ref=receipt.artifact_refs.find(ref=>ref.mime_type==="image/png")!;expect(ref).toBeDefined();const content=await web.getArtifactContent(run.run_id,ref.artifact_id);expect(Buffer.from(content.bytes)).toEqual(bytes);expect(content.sha256).toBe("sha256:"+createHash("sha256").update(bytes).digest("hex"));expect((await connected.client.startMediaRun(request)).run_id).toBe(run.run_id);await expect(connected.client.startMediaRun({...request,operation:{...request.operation,quality:"high"}})).rejects.toMatchObject({status:409});
    expect(JSON.stringify(run)).not.toContain(base64);expect(JSON.stringify(run)).not.toContain(key);expect(JSON.stringify(run)).not.toContain("Do not persist");expect(await connected.client.getArtifact(run.run_id,ref.artifact_id)).toMatchObject({status:"unavailable",reason:"unsupported_mime"});
   }
   expect(seen).toHaveLength(3);expect(seen[0]?.body).toMatchObject({output_format:"png",n:1});expect(seen[1]?.body).toMatchObject({tools:[{type:"image_generation",model:"deterministic-image-model",output_format:"png"}]});expect(seen[2]?.body).toMatchObject({modalities:["image","text"],stream:false});
   const second=await settle(connected.client,(await connected.client.startMediaRun({command_id:"command:diagram",operation:{kind:"diagram",title:"Scoped diagram",nodes:[{id:"a",label:"Start"},{id:"b",label:"Artifact"}],edges:[{from:"a",to:"b"}]}})).run_id);const foreign=mediaReceipt(first!).artifact_refs.find(ref=>ref.mime_type==="image/png")!;
   await expect(web.getArtifactContent(second.run_id,foreign.artifact_id)).rejects.toMatchObject({status:404});
   const replay=await web.createReplay({session_id:first!.session_id,run_id:first!.run_id,until_sequence:first!.last_sequence});expect(replay.snapshot.projection.run_id).toBe(first!.run_id);await expect(web.getArtifactContent(first!.run_id,foreign.artifact_id)).rejects.toMatchObject({status:403});await expect(web.startMediaRun({command_id:"command:replay-denied",operation:{kind:"chart",title:"no",chart_type:"bar",labels:["x"],values:[1]}})).rejects.toMatchObject({status:403});expect(seen).toHaveLength(3);
   const saved=await readFile(join(root,"data","image-provider.json"),"utf8");expect(saved).toContain("credential_ref");expect(saved).not.toContain(key);expect((await connected.client.clearImageProvider()).configured).toBe(false);expect((await connected.client.getCapabilities()).capabilities.find(value=>value.operation==="media.generate")).toMatchObject({state:"unconfigured"});
  }finally{await connected.close();await owner.close();provider.closeAllConnections();await new Promise<void>(done=>provider.close(()=>done()));await rm(root,{recursive:true,force:true});}
 },30_000);
 it("does not turn malformed/base64/text-only HTTP200 into image success and returns safe 401 errors",async()=>{
  const root=await mkdtemp(join(tmpdir(),"outlive-media-negative-"));let status=200,payload:unknown={data:[{b64_json:Buffer.from("Here is JavaScript to make an image").toString("base64")}]},calls=0;
  const provider=createServer(async(request,response)=>{for await(const _chunk of request){}calls++;response.writeHead(status,{"content-type":"application/json"});response.end(JSON.stringify(payload));});await new Promise<void>(done=>provider.listen(0,"127.0.0.1",done));const address=provider.address();if(!address||typeof address==="string")throw new Error();const owner=await startLocalHost({profileRoot:root,httpPort:0,credentialBackend:"private-file"}),connection=await connectLocalHost({profileRoot:root});
  try{await connection.client.configureImageProvider({protocol:"openai-images",base_url:`http://127.0.0.1:${address.port}`,model:"fixture",api_key:key});for(const [id,nextStatus,nextPayload,code] of [["prose",200,payload,"image_output_invalid"],["base64",200,{data:[{b64_json:"@@@@"}]},"image_output_invalid"],["auth",401,{error:{message:key+" secret error response"}},"image_authentication_failed"]] as const){status=nextStatus;payload=nextPayload;const run=await settle(connection.client,(await connection.client.startMediaRun({command_id:"command:"+id,operation:{kind:"generate",prompt:"Negative fixture"}})).run_id);expect(mediaReceipt(run)).toMatchObject({business_status:"failure",code,artifact_refs:[]});expect(run.artifact_refs.some(ref=>ref.mime_type==="image/png")).toBe(false);expect(JSON.stringify(run)).not.toContain(key);}expect(calls).toBe(3);
  }finally{await connection.close();await owner.close();provider.closeAllConnections();await new Promise<void>(done=>provider.close(()=>done()));await rm(root,{recursive:true,force:true});}
 },30_000);
});
