import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it, expect, vi } from "vitest";
import { ModelCapabilityControl } from "./model-capability-control.js";
import type { ConfigurableModelAdapter, ModelAdapter } from "@tracegraph/core";
const input={command_id:"probe:projection",expected_revision:0,model:"fixture",features:["text"] as "text"[],confirmed:true as const};
describe("canonical probe receipt precedes its optional settings projection",()=>{
 it("records only after the completed canonical event and keeps unknown feature truth",async()=>{const root=await mkdtemp(join(tmpdir(),"outlive-probe-projection-"));const releaseRun=vi.fn();let control!:ModelCapabilityControl;const record=vi.fn(async()=>{const receipt=await control.receipt(input.command_id);expect(receipt).toMatchObject({state:"completed",result:{results:[{status:"unknown"}]}});expect(control.pending).toBe(1);});control=await ModelCapabilityControl.open({profileRoot:root,capture:()=>({provider:"custom",protocol:"openai-chat-completions",revision:0,adapter:{testCapability:async()=>({feature:"text",status:"unknown",code:"model_timeout",duration_ms:1,dispatched:true,usage_status:"unknown"}),releaseRun} as unknown as ConfigurableModelAdapter&ModelAdapter}),record});try{const result=await control.test("fixture",input);expect(record).toHaveBeenCalledExactlyOnceWith(result);expect(releaseRun).toHaveBeenCalledOnce();expect(control.pending).toBe(0);}finally{control.close();await rm(root,{recursive:true,force:true});}});
 it("a settings summary failure preserves a completed receipt and explicit retry never repeats provider work",async()=>{const root=await mkdtemp(join(tmpdir(),"outlive-probe-projection-fail-"));const testCapability=vi.fn(async()=>({feature:"text",status:"passed",code:"model_probe_passed",duration_ms:1,dispatched:true,usage_status:"unknown",evidence:"exact_text"})),record=vi.fn(async()=>{throw new Error("PRIVATE_PROFILE_PATH");});const control=await ModelCapabilityControl.open({profileRoot:root,capture:()=>({provider:"custom",protocol:"openai-chat-completions",revision:0,adapter:{testCapability} as unknown as ConfigurableModelAdapter&ModelAdapter}),record});try{await expect(control.test("fixture",input)).rejects.toMatchObject({code:"model_probe_projection_failed",statusCode:503});expect(await control.receipt(input.command_id)).toMatchObject({state:"completed",result:{results:[{status:"passed"}]}});await expect(control.test("fixture",input)).rejects.toMatchObject({code:"model_probe_projection_failed"});expect(testCapability).toHaveBeenCalledOnce();expect(control.pending).toBe(0);}finally{control.close();await rm(root,{recursive:true,force:true});}});
});
