import {createHash} from "node:crypto";
import {mkdtemp,writeFile,chmod,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {describe,expect,it,vi} from "vitest";
import type {ComputerTarget} from "@tracegraph/contracts";
import {ComputerControl} from "./computer-control.js";
import {NativeComputerHelperBackend,createNativeComputerBackend} from "./native-computer.js";
const target:ComputerTarget={application_id:"test.owned",pid:1,title:"fixture",window_id:"1",identity:"sha256:"+"a".repeat(64)};
async function helper(emitUserInput=true){const root=await mkdtemp(join(tmpdir(),"outlive-native-protocol-"));const executable=join(root,"helper"),marker=join(root,"calls.jsonl");const script=`#!${process.execPath}\nimport{appendFileSync}from'node:fs';import{createInterface}from'node:readline';const lines=createInterface({input:process.stdin});let first=true;lines.on('line',line=>{if(!first)return;first=false;const input=JSON.parse(line);appendFileSync(${JSON.stringify(marker)},JSON.stringify({operation:input.operation,pid:process.pid,env:Object.keys(process.env)})+'\\n');if(input.operation==='status'){console.log(JSON.stringify({ok:true,result:{platform:'darwin',backend_available:true,accessibility:true,screen_capture:true,input_monitoring:true,locked:false}}));process.exit(0);}else if(input.operation==='validate'||input.operation==='focus'){console.log(JSON.stringify({ok:true,result:{valid:true}}));process.exit(0);}else if(input.operation==='watch'){console.log(JSON.stringify({ready:true}));${emitUserInput?"setTimeout(()=>console.log(JSON.stringify({event:'user-input'})),15);":""}setInterval(()=>{},1000);}else if(input.operation==='act'){setInterval(()=>{},1000);}else{console.log(JSON.stringify({ok:false,code:'computer_protocol_invalid',message:'Denied'}));process.exit(0);}});`;
await writeFile(executable,script);await chmod(executable,0o700);return {root,marker,executable,sha256:createHash("sha256").update(script).digest("hex"),close:()=>rm(root,{recursive:true,force:true})};}
async function waitUntil(predicate:()=>Promise<boolean>){const end=Date.now()+2000;while(Date.now()<end){if(await predicate())return;await new Promise(resolve=>setTimeout(resolve,10));}throw new Error("Owned fixture did not settle");}
function alive(pid:number){try{process.kill(pid,0);return true;}catch{return false;}}
// The helper boundary itself only exists on darwin/win32, so every fixture backend pins its
// platform instead of inheriting the host OS. Otherwise these cases would pass on Linux for the
// wrong reason (they would exercise the unsupported-platform short-circuit) and assert nothing
// about the protocol they name. The unsupported-platform path stays covered by its own case.
describe("closed native computer helper boundary",()=>{
 it("does not execute a missing, relative, or hash-mismatched helper",async()=>{const f=await helper();try{for(const options of [{},{executable:"helper",sha256:f.sha256},{executable:f.executable,sha256:"0".repeat(64)}]){const backend=new NativeComputerHelperBackend({platform:"darwin",...options});expect((await backend.status()).backend_available).toBe(false);await backend.close();}await expect(readFile(f.marker)).rejects.toMatchObject({code:"ENOENT"});}finally{await f.close();}});
 it("uses the exact validated executable and keeps caller secrets and Node hooks out of its environment",async()=>{const f=await helper();vi.stubEnv("OUTLIVE_FAKE_SECRET","synthetic-never-forwarded");vi.stubEnv("NODE_OPTIONS","--require fake-evil-preload");const backend=new NativeComputerHelperBackend({platform:"darwin",executable:f.executable,sha256:f.sha256});try{expect((await backend.status()).accessibility).toBe(true);await backend.focusTarget(target);const calls=(await readFile(f.marker,"utf8")).trim().split("\n").map(line=>JSON.parse(line));expect(calls.map(c=>c.operation)).toEqual(["status","focus"]);expect(calls.every(c=>c.env.includes("PATH")&&!c.env.includes("OUTLIVE_FAKE_SECRET")&&!c.env.includes("NODE_OPTIONS"))).toBe(true);}finally{vi.unstubAllEnvs();await backend.close();await f.close();}});
 it("waits for actual monitor readiness, reports external input, and closes all owned monitor processes",async()=>{const f=await helper();const backend=new NativeComputerHelperBackend({platform:"darwin",executable:f.executable,sha256:f.sha256});let input!:()=>void;const observed=new Promise<void>(resolve=>input=resolve);try{const monitor=await backend.watch(target,event=>{expect(event).toBe("user-input");input();});await observed;const call=JSON.parse((await readFile(f.marker,"utf8")).trim());expect(alive(call.pid)).toBe(true);await monitor.close();await waitUntil(async()=>!alive(call.pid));}finally{await backend.close();await f.close();}});
 it("cancels an in-flight native input process without replaying its operation",async()=>{const f=await helper();const backend=new NativeComputerHelperBackend({platform:"darwin",executable:f.executable,sha256:f.sha256});const abort=new AbortController();try{const action=backend.act(target,{kind:"type",text:"fixture only"},abort.signal);const rejection=expect(action).rejects.toMatchObject({code:"computer_input_aborted"});await waitUntil(async()=>{try{return (await readFile(f.marker,"utf8")).includes('"act"');}catch{return false;}});const call=JSON.parse((await readFile(f.marker,"utf8")).trim());abort.abort();await rejection;await waitUntil(async()=>!alive(call.pid));expect((await readFile(f.marker,"utf8")).trim().split("\n")).toHaveLength(1);}finally{await backend.close();await f.close();}});
 it("settles real helper input as unknown when a trusted Runtime cancellation aborts it, with no command retry",async()=>{const f=await helper(false);const backend=new NativeComputerHelperBackend({platform:"darwin",executable:f.executable,sha256:f.sha256});const control=await ComputerControl.create({profileRoot:join(f.root,"profile"),backend,answerGrant:async()=>"allow",confirmInputLease:async()=>true});const cancel=new AbortController();try{const grant=await control.requestGrant({command_id:"grant",target,duration:"always"});const lease=await control.acquireLease({command_id:"lease",grant_id:grant.grant_id,target,seconds:15});const input={command_id:"runtime-input",lease_id:lease.lease_id,expected_generation:0,action:{kind:"type" as const,text:"isolated only"}};const action=control.act(input,{mode:"execute",signal:cancel.signal});await waitUntil(async()=>{try{return (await readFile(f.marker,"utf8")).includes('"act"');}catch{return false;}});const call=(await readFile(f.marker,"utf8")).trim().split("\n").map(line=>JSON.parse(line)).find(call=>call.operation==="act");cancel.abort();expect((await action).status).toBe("unknown");expect((await control.status()).lease?.pause_reason).toBe("run-cancelled");expect(await control.reconcile(input.command_id)).toMatchObject({state:"completed",result:{status:"unknown"}});await control.act(input,{mode:"execute"});await waitUntil(async()=>!alive(call.pid));const calls=(await readFile(f.marker,"utf8")).trim().split("\n").map(line=>JSON.parse(line));expect(calls.filter(call=>call.operation==="act")).toHaveLength(1);}finally{await control.close();await f.close();}});
 it("bounds an unresponsive helper and distinguishes unsupported platform status",async()=>{const f=await helper();const backend=new NativeComputerHelperBackend({platform:"darwin",executable:f.executable,sha256:f.sha256,timeoutMs:100});try{await expect(backend.act(target,{kind:"key",key:"Enter",modifiers:[]},new AbortController().signal)).rejects.toMatchObject({code:"computer_helper_timeout"});const unsupported=new NativeComputerHelperBackend({platform:"linux"});expect(await unsupported.status()).toMatchObject({platform:"unsupported",backend_available:false});await unsupported.close();}finally{await backend.close();await f.close();}});
 it.skipIf(process.platform!=="darwin")("reports truthful fixed source helper availability without granting or posting any OS input",async()=>{const backend=await createNativeComputerBackend();try{const status=await backend.status();expect(status.platform).toBe("darwin");if(!status.backend_available){expect(status.reason).toBeTruthy();return;}expect(typeof status.accessibility).toBe("boolean");expect(typeof status.input_monitoring).toBe("boolean");await expect(backend.validateTarget(target,false)).rejects.toMatchObject({code:"computer_target_changed"});}finally{await backend.close();}});
});
