import {createHash,randomUUID} from "node:crypto";
import {constants} from "node:fs";
import {lstat,open,readdir,realpath} from "node:fs/promises";
import {join,relative} from "node:path";
import {JsonlEventLedger,PolicyEngine,type AgentRuntime} from "@tracegraph/core";
import {MAX_PROJECT_FILE_BYTES,MAX_PROJECT_CONTEXT_FILE_BYTES,ProjectFileListRequestSchema,ProjectFileReadRequestSchema,ProjectFileSaveRequestSchema,AnswerFeedbackRequestSchema,type ProjectFileContextSnapshot,type EffectivePermissionPolicy,type WorkspaceHandle,type ProjectFileList,type ProjectFileListRequest,type ProjectFileReadRequest,type ProjectFileSnapshot,type ProjectFileSaveRequest,type ProjectFileSaveResult,type SessionEvent,type AnswerFeedbackRequest,type AnswerFeedbackSnapshot} from "@tracegraph/contracts";
import type {PermissionConfigController} from "./composition/permission-config.js";
import type {WorkspaceCoordinator,WorkspaceLease} from "./workspace-coordinator.js";
import {workbenchError} from "./workbench-journal.js";
import {projectFileImage} from "./project-file-image.js";

export interface ProjectFilesFeedbackContext {
 profileRoot:string;runtime:Pick<AgentRuntime,"getProjection">;permissionConfig:PermissionConfigController;workspaceCoordinator:WorkspaceCoordinator;
 resolveWorkspace(projectId:string):Promise<WorkspaceHandle>;
 /** Trusted resolver validates session ownership and its explicitly selected permission. */
 resolvePolicy?(projectId:string,sessionId?:string):Promise<EffectivePermissionPolicy>;
}
const hash=(bytes:string|Uint8Array)=>`sha256:${createHash("sha256").update(bytes).digest("hex")}` as const;
const saveRun=(id:string)=>`file-save:${createHash("sha256").update(id).digest("hex")}`;
const feedbackRun=(id:string)=>`answer-feedback:${createHash("sha256").update(id).digest("hex")}`;
const excluded=(name:string)=>name===".git"||name==="node_modules"||name===".tracegraph"||name===".outlive"||name===".env"||name.startsWith(".env.");
/** All durable records use the existing SessionEvent ledger. File content never enters it. */
export class ProjectFilesFeedbackController {
 readonly ledger:JsonlEventLedger;readonly #context:ProjectFilesFeedbackContext;readonly #pending=new Map<string,Promise<unknown>>();
 private constructor(context:ProjectFilesFeedbackContext){this.#context=context;this.ledger=new JsonlEventLedger(join(context.profileRoot,"project-file-events"));}
 static async create(context:ProjectFilesFeedbackContext){const controller=new ProjectFilesFeedbackController(context);await controller.ledger.initialize();return controller;}
 async #workspace(projectId:string){const workspace=await this.#context.resolveWorkspace(projectId);if(workspace.project_id!==projectId||!workspace.capabilities.read)throw workbenchError("project_scope_denied","Project file access is unavailable",403);return workspace;}
 async #assertRead(projectId:string,workspace:WorkspaceHandle,path?:string,toolName="read_file"){const policy=await this.#policy(projectId,workspace);const decision=PolicyEngine.fromEffective(policy).evaluate({toolName,sideEffect:"read",capabilityAllowed:workspace.capabilities.read,...(path?{path}:{})});if(decision.kind!=="allow")throw workbenchError(decision.kind==="ask"?"file_read_approval_required":"file_read_policy_denied","Project policy does not permit this file read",403);}
 async #path(workspace:WorkspaceHandle,path:string,directory=false){
  const root=await realpath(workspace.real_root);let current=root;
  for(const part of path?path.split("/"):[]){if(excluded(part))throw workbenchError("file_scope_denied","This private or dependency path is excluded from the file editor",403);current=join(current,part);const info=await lstat(current).catch(()=>{throw workbenchError("file_unavailable","Project path is unavailable",404);});if(info.isSymbolicLink())throw workbenchError("file_symlink_denied","Symbolic links cannot be opened or edited",403);}
  const canonical=await realpath(current);const rel=relative(root,canonical);if(rel.startsWith("..")||canonical!==current)throw workbenchError("file_scope_denied","Project path is outside the registered workspace",403);
  const info=await lstat(current);if(directory?!info.isDirectory():!info.isFile())throw workbenchError("file_kind_unsupported","Choose a regular project file or directory",400);
  if(!directory&&info.nlink!==1)throw workbenchError("file_hardlink_denied","Files with multiple hard links cannot be opened or edited",403);
  return {absolute:current,root,info};
 }
 async #bytes(workspace:WorkspaceHandle,path:string,maximum=MAX_PROJECT_FILE_BYTES){const target=await this.#path(workspace,path);const handle=await open(target.absolute,constants.O_RDONLY|(process.platform==="win32"?0:constants.O_NOFOLLOW));try{const stat=await handle.stat();if(!stat.isFile()||stat.nlink!==1||stat.ino!==target.info.ino||stat.dev!==target.info.dev)throw workbenchError("file_changed","File identity changed; reload before continuing");const sizeError=()=>workbenchError("file_too_large",maximum===MAX_PROJECT_FILE_BYTES?"File exceeds the one MiB editor limit":"Selected context file exceeds the 64 KiB limit",413);if(stat.size>maximum)throw sizeError();const bytes=Buffer.alloc(maximum+1);let length=0;while(length<bytes.length){const read=await handle.read(bytes,length,bytes.length-length,length);if(!read.bytesRead)break;length+=read.bytesRead;}if(length>maximum)throw sizeError();return {bytes:bytes.subarray(0,length),target};}finally{await handle.close();}}
 async list(projectId:string,input:ProjectFileListRequest={}):Promise<ProjectFileList>{const parsed=ProjectFileListRequestSchema.parse(input),workspace=await this.#workspace(projectId),path=parsed.path??"";await this.#assertRead(projectId,workspace,path||undefined,"list_dir");const target=await this.#path(workspace,path,true);const entries:ProjectFileList["entries"]=[];let truncated=false;for(const item of (await readdir(target.absolute,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){if(excluded(item.name)||item.isSymbolicLink()||(!item.isDirectory()&&!item.isFile()))continue;if(entries.length===2000){truncated=true;break;}const child=path?`${path}/${item.name}`:item.name;try{await this.#assertRead(projectId,workspace,child,item.isDirectory()?"list_dir":"read_file");const safe=await this.#path(workspace,child,item.isDirectory());entries.push({path:child,name:item.name,kind:item.isDirectory()?"directory":"file",...(item.isFile()?{byte_length:safe.info.size}:{})});}catch{/* Unsupported, denied or concurrently removed entry is omitted. */}}return {project_id:projectId,path,entries,truncated};}
 async read(projectId:string,input:ProjectFileReadRequest):Promise<ProjectFileSnapshot>{const parsed=ProjectFileReadRequestSchema.parse(input),workspace=await this.#workspace(projectId);await this.#assertRead(projectId,workspace,parsed.path);const {bytes}=await this.#bytes(workspace,parsed.path);const base={project_id:projectId,path:parsed.path,sha256:hash(bytes),byte_length:bytes.length},image=projectFileImage(bytes);if(image)return {...base,kind:"binary",image};try{if(bytes.includes(0))return {...base,kind:"binary"};return {...base,kind:"text",content:new TextDecoder("utf-8",{fatal:true,ignoreBOM:true}).decode(bytes)};}catch{return {...base,kind:"binary"};}}
 /** Trusted admission seam only: callers bind this policy to the same project's Run.
  * No route accepts a policy or client-supplied context content. */
 async readContext(projectId:string,path:string,admittedPolicy:EffectivePermissionPolicy):Promise<ProjectFileContextSnapshot>{
  const parsed=ProjectFileReadRequestSchema.parse({path}),workspace=await this.#workspace(projectId);
  const decision=PolicyEngine.fromEffective(admittedPolicy).evaluate({toolName:"read_file",sideEffect:"read",capabilityAllowed:workspace.capabilities.read,path:parsed.path});
  if(decision.kind!=="allow")throw workbenchError(decision.kind==="ask"?"file_read_approval_required":"file_read_policy_denied","Project policy does not permit this file read",403);
  const {bytes}=await this.#bytes(workspace,parsed.path,MAX_PROJECT_CONTEXT_FILE_BYTES);
  let content:string;try{if(bytes.includes(0))throw new Error();content=new TextDecoder("utf-8",{fatal:true,ignoreBOM:true}).decode(bytes);}catch{throw workbenchError("file_context_not_text","Select a UTF-8 text file without binary data",400);}
  return {project_id:projectId,path:parsed.path,sha256:hash(bytes),byte_length:bytes.length,content};
 }
 async #policy(projectId:string,workspace:WorkspaceHandle,sessionId?:string){if(this.#context.resolvePolicy)return this.#context.resolvePolicy(projectId,sessionId);if(sessionId)throw workbenchError("session_policy_unavailable","This Host cannot resolve the selected session permission",403);return this.#context.permissionConfig.resolveProject(workspace.real_root);}
 async #append(projectId:string,runId:string,commandId:string,type:SessionEvent["type"],phase:string,data:Record<string,unknown>){return this.ledger.append({type,project_id:projectId,run_id:runId,operation_id:commandId,attempt:0,artifact_refs:[],summary:`Project file operation ${phase}`,idempotency_key:hash(`${commandId}:${phase}`),data});}
 async #serialize<T>(key:string,execute:()=>Promise<T>):Promise<T>{const previous=this.#pending.get(key);const next=(previous??Promise.resolve()).catch(()=>undefined).then(execute);this.#pending.set(key,next);try{return await next;}finally{if(this.#pending.get(key)===next)this.#pending.delete(key);}}
 async save(projectId:string,input:ProjectFileSaveRequest):Promise<ProjectFileSaveResult>{const parsed=ProjectFileSaveRequestSchema.parse(input);return this.#serialize(parsed.command_id,()=>this.#save(projectId,parsed));}
 async #save(projectId:string,input:ProjectFileSaveRequest):Promise<ProjectFileSaveResult>{
  const bytes=Buffer.from(input.content,"utf8");if(bytes.length>MAX_PROJECT_FILE_BYTES||bytes.includes(0)||bytes.toString("utf8")!==input.content)throw workbenchError("file_content_unsupported","Save only UTF-8 text within the one MiB editor limit",400);
  const workspace=await this.#workspace(projectId),contentHash=hash(bytes),runId=saveRun(input.command_id),intent={project_id:projectId,path:input.path,expected_sha256:input.expected_sha256,content_sha256:contentHash,...(input.session_id?{session_id:input.session_id}:{})},digest=hash(JSON.stringify(intent));
  let events=await this.ledger.list(runId);if(events[0]&&(events[0].project_id!==projectId||events[0].data.digest!==digest))throw workbenchError("command_id_conflict","Command identifier was reused with another save intent");
  const receipt=events.find(event=>event.type==="workbench.command_completed");if(receipt)return {...receipt.data.result as ProjectFileSaveResult,receipt_event_id:receipt.event_id};
  if(events.some(event=>event.data.phase==="dispatch"))return this.reconcile(projectId,{command_id:input.command_id});
  const policy=await this.#policy(projectId,workspace,input.session_id);
  const decision=PolicyEngine.fromEffective(policy).evaluate({toolName:"commit_patch",sideEffect:"write",capabilityAllowed:workspace.capabilities.commit_patch,path:input.path,actionDigest:digest});
  if(!events.length){await this.#append(projectId,runId,input.command_id,"workbench.command_requested","requested",{...intent,digest,policy_digest:policy.policy_digest,decision_kind:decision.kind});events=await this.ledger.list(runId);}
  const finish=async(status:ProjectFileSaveResult["status"],code:string,actual?:string)=>{const result:ProjectFileSaveResult={command_id:input.command_id,project_id:projectId,path:input.path,expected_sha256:input.expected_sha256,content_sha256:contentHash,status,code,...(actual?{actual_sha256:actual}:{})};const event=await this.#append(projectId,runId,input.command_id,"workbench.command_completed","receipt",{result});return {...result,receipt_event_id:event.event_id};};
  if(events[0]!.data.policy_digest!==policy.policy_digest)return await finish("denied","save_policy_changed");
  if(decision.kind==="deny")return await finish("denied","save_policy_denied");
  let approval=events.find(event=>event.type==="approval.requested");
  if(decision.kind==="ask"){
   if(!approval){approval=await this.#append(projectId,runId,input.command_id,"approval.requested","approval-requested",{approval_id:`file-approval:${randomUUID()}`,policy_digest:policy.policy_digest,action_digest:digest,path:input.path,expected_sha256:input.expected_sha256,content_sha256:contentHash});}
   const approvalId=String(approval.data.approval_id);
   if(!input.approval)return {command_id:input.command_id,project_id:projectId,path:input.path,expected_sha256:input.expected_sha256,content_sha256:contentHash,status:"awaiting_approval",code:"save_approval_required",approval_id:approvalId};
   if(input.approval.approval_id!==approvalId)throw workbenchError("save_approval_invalid","Approval does not match this exact file save",403);
   await this.#append(projectId,runId,input.command_id,input.approval.decision==="approve"?"approval.granted":"approval.denied","approval-decision",{approval_id:approvalId,action_digest:digest,policy_digest:policy.policy_digest});
   if(input.approval.decision==="deny")return await finish("denied","save_approval_denied");
  }else if(input.approval)throw workbenchError("save_approval_invalid","This save has no pending approval",403);
  let lease:WorkspaceLease;try{lease=await this.#context.workspaceCoordinator.acquireWorkspace(workspace,{holderId:input.command_id,kind:"file"});}catch(error){const code=(error as {code?:unknown}).code;return await finish("failed",typeof code==="string"&&/^[a-z][a-z0-9_]{0,100}$/u.test(code)?code:"file_admission_failed");}
  try{
   if((await this.#policy(projectId,workspace,input.session_id)).policy_digest!==policy.policy_digest)return await finish("denied","save_policy_changed");
   const current=await this.#bytes(workspace,input.path);const currentHash=hash(current.bytes);if(currentHash!==input.expected_sha256)return await finish("conflict","file_revision_conflict",currentHash);
   try{new TextDecoder("utf8",{fatal:true}).decode(current.bytes);if(current.bytes.includes(0))throw new Error();}catch{return await finish("failed","file_content_unsupported");}
   // Write only the already authorized inode. A path/symlink swap cannot redirect
   // the write to a different file. Partial crash outcomes require reconciliation.
   const handle=await open(current.target.absolute,constants.O_RDWR|(process.platform==="win32"?0:constants.O_NOFOLLOW));let dispatched=false;
   try{const stat=await handle.stat();const latest=await this.#bytes(workspace,input.path);if(stat.ino!==current.target.info.ino||stat.dev!==current.target.info.dev||stat.nlink!==1||latest.target.info.ino!==stat.ino||latest.target.info.dev!==stat.dev||hash(latest.bytes)!==currentHash)return await finish("conflict","file_revision_conflict",hash(latest.bytes));
    await this.#append(projectId,runId,input.command_id,"workbench.command_requested","dispatch",{phase:"dispatch",action_digest:digest});dispatched=true;
    const target=await this.#path(workspace,input.path);if(target.info.ino!==stat.ino||target.info.dev!==stat.dev)return {command_id:input.command_id,project_id:projectId,path:input.path,expected_sha256:input.expected_sha256,content_sha256:contentHash,status:"unknown",code:"save_outcome_unknown"};
    const pinned=Buffer.alloc(MAX_PROJECT_FILE_BYTES+1);let length=0;while(length<pinned.length){const read=await handle.read(pinned,length,pinned.length-length,length);if(!read.bytesRead)break;length+=read.bytesRead;}const pinnedHash=hash(pinned.subarray(0,length));if(length>MAX_PROJECT_FILE_BYTES||pinnedHash!==currentHash)return await finish("conflict","file_revision_conflict",pinnedHash);
    let offset=0;while(offset<bytes.length){const written=await handle.write(bytes,offset,bytes.length-offset,offset);if(!written.bytesWritten)throw new Error("File write did not progress");offset+=written.bytesWritten;}await handle.truncate(bytes.length);await handle.sync();
    const observed=hash((await this.#bytes(workspace,input.path)).bytes);if(observed!==contentHash)return {command_id:input.command_id,project_id:projectId,path:input.path,expected_sha256:input.expected_sha256,content_sha256:contentHash,status:"unknown",code:"save_outcome_unknown",actual_sha256:observed};
    return await finish("succeeded","file_saved",observed);
   }catch(error){if(dispatched)return {command_id:input.command_id,project_id:projectId,path:input.path,expected_sha256:input.expected_sha256,content_sha256:contentHash,status:"unknown",code:"save_outcome_unknown"};throw error;}finally{await handle.close();}
  }catch(error){const code=(error as {code?:unknown}).code;return await finish("failed",typeof code==="string"&&/^[a-z][a-z0-9_]{0,100}$/u.test(code)?code:"file_save_failed");}finally{lease.release();}
 }
 async reconcile(projectId:string,input:{command_id:string}):Promise<ProjectFileSaveResult>{const events=await this.ledger.list(saveRun(input.command_id)),first=events[0];if(!first||first.project_id!==projectId)throw workbenchError("save_command_unavailable","This save command is unavailable in this project",404);await this.#workspace(projectId);const receipt=events.find(event=>event.type==="workbench.command_completed");if(receipt)return {...receipt.data.result as ProjectFileSaveResult,receipt_event_id:receipt.event_id};const base={command_id:input.command_id,project_id:projectId,path:String(first.data.path),expected_sha256:String(first.data.expected_sha256),content_sha256:String(first.data.content_sha256)};if(!events.some(event=>event.data.phase==="dispatch")){const approval=events.find(event=>event.type==="approval.requested");return {...base,status:approval?"awaiting_approval":"unknown",code:"save_not_dispatched",...(approval?{approval_id:String(approval.data.approval_id)}:{})};}const workspace=await this.#workspace(projectId);const lease=await this.#context.workspaceCoordinator.acquireWorkspace(workspace,{holderId:`reconcile:${input.command_id}`,kind:"file"});try{const observed=hash((await this.#bytes(workspace,base.path)).bytes);const result:ProjectFileSaveResult={...base,actual_sha256:observed,status:observed===base.content_sha256?"succeeded":observed===base.expected_sha256?"failed":"conflict",code:observed===base.content_sha256?"reconciled_content_matches":observed===base.expected_sha256?"reconciled_not_applied":"reconciled_external_change"};const event=await this.#append(projectId,saveRun(input.command_id),input.command_id,"workbench.command_completed","receipt",{result,reconciled:true});return {...result,receipt_event_id:event.event_id};}finally{lease.release();}}
 async #answer(runId:string){const run=await this.#context.runtime.getProjection(runId);const workspace=await this.#context.resolveWorkspace(run.project_id);if(workspace.project_id!==run.project_id)throw workbenchError("answer_scope_denied","Answer project is unavailable",403);const event=[...run.timeline].reverse().find(event=>event.type==="run.completed"&&event.run_id===runId&&event.project_id===run.project_id&&typeof event.data.outcome==="string"&&event.data.outcome.trim());if(run.status!=="completed"||!event)throw workbenchError("answer_unavailable","Feedback requires an actual completed public answer",409);return {run,event};}
 async feedback(runId:string):Promise<AnswerFeedbackSnapshot>{const {event}=await this.#answer(runId),events=await this.ledger.list(feedbackRun(runId));const latest=[...events].reverse().find(item=>item.type==="workbench.command_completed"&&item.data.answer_event_id===event.event_id);return latest?{run_id:runId,answer_event_id:event.event_id,value:latest.data.value as AnswerFeedbackSnapshot["value"],updated_at:latest.occurred_at,receipt_event_id:latest.event_id}:{run_id:runId,answer_event_id:event.event_id,value:"clear"};}
 async setFeedback(runId:string,input:AnswerFeedbackRequest):Promise<AnswerFeedbackSnapshot>{const parsed=AnswerFeedbackRequestSchema.parse(input);return this.#serialize(`feedback:${runId}`,async()=>{const {run,event}=await this.#answer(runId);if(event.event_id!==parsed.answer_event_id)throw workbenchError("answer_scope_denied","Feedback does not identify this Run's public answer",403);const stream=feedbackRun(runId),events=await this.ledger.list(stream),existing=events.find(item=>item.operation_id===parsed.command_id);const digest=hash(JSON.stringify({run_id:runId,...parsed}));if(existing&&existing.data.digest!==digest)throw workbenchError("command_id_conflict","Command identifier was reused for different feedback");const completed=events.find(item=>item.operation_id===parsed.command_id&&item.type==="workbench.command_completed");if(completed)return {run_id:runId,answer_event_id:parsed.answer_event_id,value:completed.data.value as AnswerFeedbackSnapshot["value"],updated_at:completed.occurred_at,receipt_event_id:completed.event_id};if(!existing)await this.ledger.append({type:"workbench.command_requested",project_id:run.project_id,run_id:stream,operation_id:parsed.command_id,parent_event_id:event.event_id,attempt:0,artifact_refs:[],summary:"Local public answer feedback requested",idempotency_key:hash(`${parsed.command_id}:requested`),data:{operation:"answer.feedback",digest,target_run_id:runId,answer_event_id:parsed.answer_event_id,value:parsed.value,local_only:true}});const receipt=await this.ledger.append({type:"workbench.command_completed",project_id:run.project_id,run_id:stream,operation_id:parsed.command_id,parent_event_id:event.event_id,attempt:0,artifact_refs:[],summary:"Local public answer feedback saved",idempotency_key:hash(parsed.command_id),data:{operation:"answer.feedback",digest,target_run_id:runId,answer_event_id:parsed.answer_event_id,value:parsed.value,local_only:true}});return {run_id:runId,answer_event_id:parsed.answer_event_id,value:parsed.value,updated_at:receipt.occurred_at,receipt_event_id:receipt.event_id};});}
}
