import {verifyRasterImage} from "@tracegraph/core";
import type {ProjectFileSnapshot} from "@tracegraph/contracts";
/** Bounded local preview metadata; browser decoding remains the final display oracle. */
export function projectFileImage(bytes:Buffer):ProjectFileSnapshot["image"] {
 const bounded=(width:number,height:number)=>Number.isInteger(width)&&Number.isInteger(height)&&width>0&&height>0&&width<=8192&&height<=8192&&width*height<=16_777_216;
 const result=(media_type:"image/png"|"image/jpeg"|"image/webp",width:number,height:number)=>bounded(width,height)?{media_type,width,height,data_base64:bytes.toString("base64")}:undefined;
 try{
  if(bytes.subarray(0,8).toString("hex")==="89504e470d0a1a0a"){const verified=verifyRasterImage(bytes,"image/png");return result("image/png",verified.width,verified.height);}
  if(bytes.length>20&&bytes[0]===255&&bytes[1]===216&&bytes.at(-2)===255&&bytes.at(-1)===217){let offset=2,width=0,height=0;while(offset+4<bytes.length){if(bytes[offset++]!==255)return;while(bytes[offset]===255)offset++;const marker=bytes[offset++]!;if(marker===0||marker===216||marker===217)return;const length=bytes.readUInt16BE(offset);if(length<2||offset+length>bytes.length)return;if([192,193,194].includes(marker)){if(length<11||bytes[offset+2]!==8)return;height=bytes.readUInt16BE(offset+3);width=bytes.readUInt16BE(offset+5);const components=bytes[offset+7]!;if(components<1||components>4||length!==8+3*components)return;}if(marker===218){if(!width||!height||length<6||offset+length>=bytes.length-2)return;return result("image/jpeg",width,height);}offset+=length;}return;}
  if(bytes.length>=30&&bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP"&&bytes.readUInt32LE(4)+8===bytes.length){let offset=12,canvas:{width:number;height:number}|undefined,frame:{width:number;height:number}|undefined;while(offset+8<=bytes.length){const type=bytes.toString("ascii",offset,offset+4),length=bytes.readUInt32LE(offset+4),start=offset+8;if(length<1||start+length>bytes.length)return;if(type==="ANIM"||type==="ANMF")return;if(type==="VP8X"){if(length!==10)return;canvas={width:bytes.readUIntLE(start+4,3)+1,height:bytes.readUIntLE(start+7,3)+1};if(!bounded(canvas.width,canvas.height))return;}if(type==="VP8 "&&length>10&&bytes.subarray(start+3,start+6).toString("hex")==="9d012a")frame={width:bytes.readUInt16LE(start+6)&0x3fff,height:bytes.readUInt16LE(start+8)&0x3fff};if(type==="VP8L"&&length>5&&bytes[start]===0x2f){const packed=bytes.readUInt32LE(start+1);frame={width:(packed&0x3fff)+1,height:((packed>>>14)&0x3fff)+1};}offset=start+length+(length%2);}if(offset!==bytes.length||!frame||canvas&&(canvas.width!==frame.width||canvas.height!==frame.height))return;return result("image/webp",frame.width,frame.height);}
 }catch{return;}
 return;
}
