import {describe,it,expect} from "vitest";
import {mkdtemp,mkdir,writeFile,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {TraceGraphClient} from "@tracegraph/sdk";
import {startLocalHost,connectLocalHost} from "./local-host.js";
describe("real private UDS and loopback file/feedback workflows",()=>{
 it("gates existing project saves with actual approval and blocks live file/feedback access through replay",async()=>{
  const root=await mkdtemp(join(tmpdir(),"outlive-files-transport-"));const directory=join(root,"repository");await mkdir(directory);await writeFile(join(directory,"file.txt"),"before\n");const owner=await startLocalHost({profileRoot:join(root,"profile"),httpPort:0,credentialBackend:"private-file"}),connected=await connectLocalHost({profileRoot:join(root,"profile")}),web=new TraceGraphClient({baseUrl:owner.status.http_address});await web.bootstrap();
  try{const project=await connected.native.registerProject({selectedPath:directory,access:"read_write"});expect((await web.listProjectFiles(project.project_id)).entries).toMatchObject([{name:"file.txt",kind:"file"}]);const snapshot=await web.readProjectFile(project.project_id,{path:"file.txt"});const request={command_id:"command:real-file-save",path:"file.txt",expected_sha256:snapshot.sha256,content:"after\n"};const pending=await connected.client.saveProjectFile(project.project_id,request);expect(pending.status).toBe("awaiting_approval");expect(await readFile(join(directory,"file.txt"),"utf8")).toBe("before\n");const saved=await web.saveProjectFile(project.project_id,{...request,approval:{approval_id:pending.approval_id!,decision:"approve"}});expect(saved).toMatchObject({status:"succeeded",receipt_event_id:expect.any(String)});expect(await readFile(join(directory,"file.txt"),"utf8")).toBe("after\n");expect(await connected.client.reconcileProjectFileSave(project.project_id,{command_id:request.command_id})).toEqual(saved);await expect(web.readProjectFile("project:foreign",{path:"file.txt"})).rejects.toMatchObject({status:404});
   // The trusted built-in local renderer creates a real completed plain-chat Run,
   // without granting that chat any filesystem authority or making model calls.
   const started=await connected.client.startMediaRun({command_id:"command:real-feedback-answer",operation:{kind:"diagram",title:"Local feedback test",nodes:[{id:"a",label:"Public answer"}]}});let run=started;for(let i=0;i<200&&run.status!=="completed";i++){await new Promise(resolve=>setTimeout(resolve,20));run=await connected.client.getRun(run.run_id);}expect(run.status).toBe("completed");const answer=run.timeline.find(event=>event.type==="run.completed")!;expect(answer).toBeDefined();expect((await web.getAnswerFeedback(run.run_id)).answer_event_id).toBe(answer.event_id);expect(await connected.client.setAnswerFeedback(run.run_id,{command_id:"command:real-like",answer_event_id:answer.event_id,value:"like"})).toMatchObject({value:"like",receipt_event_id:expect.any(String)});expect((await web.getAnswerFeedback(run.run_id)).value).toBe("like");await expect(web.setAnswerFeedback(run.run_id,{command_id:"command:foreign-answer",answer_event_id:"event:foreign",value:"dislike"})).rejects.toMatchObject({status:403});await expect(web.listProjectFiles("chat:local")).rejects.toMatchObject({status:403});
   await web.createReplay({session_id:run.session_id,run_id:run.run_id,until_sequence:run.last_sequence});for(const operation of [()=>web.listProjectFiles(project.project_id),()=>web.readProjectFile(project.project_id,{path:"file.txt"}),()=>web.saveProjectFile(project.project_id,{...request,command_id:"command:replay-save"}),()=>web.getAnswerFeedback(run.run_id),()=>web.setAnswerFeedback(run.run_id,{command_id:"command:replay-like",answer_event_id:answer.event_id,value:"clear"})])await expect(operation()).rejects.toMatchObject({status:403});expect(await readFile(join(directory,"file.txt"),"utf8")).toBe("after\n");expect((await connected.client.getAnswerFeedback(run.run_id)).value).toBe("like");
  }finally{await connected.close();await owner.close();await rm(root,{recursive:true,force:true});}
 },30_000);
});
