import {createServer} from "node:net";
import {mkdtemp,mkdir,readFile,realpath,rm,writeFile,symlink} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,expect,it,vi} from "vitest";
import {BUILTIN_PERMISSION_PRESETS,WorkbenchSettingsValuesSchema,type SandboxMode} from "@tracegraph/contracts";
import {createEffectivePermissionPolicy,createManagedWorkspaceHandle,probeNativeSandbox,type ModelAdapter} from "@tracegraph/core";
import type {PermissionConfigController} from "./composition/permission-config.js";
import type {WorkbenchControlContext} from "./workbench-control.js";
import {WorkspaceCoordinator} from "./workspace-coordinator.js";
import {DevWorkbench} from "../dist/dev-workbench.js";
import {createHostComposition} from "./composition/host-composition.js";
import {budgetedFixtureModel} from "../test-support/budgeted-fixture-model.js";

const roots:string[]=[];
afterEach(async()=>{vi.restoreAllMocks();for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
async function port(){const server=createServer();await new Promise<void>(done=>server.listen(0,"127.0.0.1",done));const value=(server.address() as {port:number}).port;await new Promise<void>(done=>server.close(()=>done()));return value;}
async function fixture(mode:SandboxMode="danger-full-access"){
 const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-readonly-preview-")));roots.push(root);const profileRoot=join(root,"profile"),source=join(root,"source");await mkdir(profileRoot);await mkdir(source);await writeFile(join(profileRoot,"private.txt"),"SYNTHETIC PRIVATE PROFILE");await writeFile(join(source,"marker.txt"),"SOURCE UNCHANGED");
 const script=join(source,"server.mjs");await writeFile(script,`import {writeFileSync,readFileSync} from 'node:fs';import {join} from 'node:path';import {createServer} from 'node:http';let sourceDenied=false,cacheWritten=false,profileDenied=false;try{writeFileSync('marker.txt','SOURCE MODIFIED')}catch{sourceDenied=true}const cache=process.env.XDG_CACHE_HOME??process.cwd();try{writeFileSync(join(cache,'cache-marker.txt'),'PRIVATE CACHE');cacheWritten=true}catch{}try{readFileSync(process.argv[2])}catch{profileDenied=true}createServer((request,response)=>{response.setHeader('content-type','application/json');response.end(JSON.stringify({sourceDenied,cacheWritten,profileDenied,pid:process.pid,ownerPID:process.ppid,cacheSeparate:cache!==process.cwd(),tempSeparate:process.env.TMPDIR===cache}))}).listen(Number(process.env.PORT),'127.0.0.1');`);
 const workspace=await createManagedWorkspaceHandle({projectId:"project:preview",root:source}),coordinator=new WorkspaceCoordinator();
 const policy=createEffectivePermissionPolicy({preset:mode==="read-only"?BUILTIN_PERMISSION_PRESETS["read-only"]:mode==="workspace-write"?BUILTIN_PERMISSION_PRESETS["workspace-write"]:BUILTIN_PERMISSION_PRESETS["full-write"]});
 const context={profileRoot,profileId:"profile:preview",resolveWorkspace:async()=>workspace,listProjects:()=>[{workspace}],workspaceCoordinator:coordinator,permissionConfig:{snapshot:()=>({selected_preset:{sandbox_mode:mode}}),resolveProject:async()=>policy} as unknown as PermissionConfigController} as WorkbenchControlContext;
 const dev=new DevWorkbench({...context,getSettings:()=>WorkbenchSettingsValuesSchema.parse({})});await dev.initialize();return {root,source,profileRoot,script,workspace,coordinator,context,dev};
}
async function start(f:Awaited<ReturnType<typeof fixture>>,id="preview:one"){
 const result=await f.dev.command({type:"preview.start",command_id:id,project_id:f.workspace.project_id,command:process.execPath,args:[f.script,join(f.profileRoot,"private.txt")],port:await port()});
 let body:any;await vi.waitFor(async()=>{body=await(await fetch(result.preview!.url,{signal:AbortSignal.timeout(500)})).json();},{timeout:6000,interval:25});return {result,body};
}
describe.skipIf(process.platform!=="darwin")("DEV-091 owned read-only preview actual processes",()=>{
 it("denies source writes under full access, permits private cache, and does not block the same workspace's later writer",async()=>{
  const f=await fixture();try{const {result,body}=await start(f);expect(body).toMatchObject({sourceDenied:true,cacheWritten:true,profileDenied:true,cacheSeparate:true,tempSeparate:true});expect(await readFile(join(f.source,"marker.txt"),"utf8")).toBe("SOURCE UNCHANGED");
   expect(result.preview).toMatchObject({source_access:"read-only",cache_writable:true});expect(JSON.stringify(result)).not.toContain(f.profileRoot);
   const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),1000);let writer;try{writer=await f.coordinator.acquireWorkspace(f.workspace,{holderId:"run:later-writer",kind:"run",signal:controller.signal});}finally{clearTimeout(timer);}expect(f.coordinator.list().filter(x=>x.kind==="run")).toMatchObject([{state:"active"}]);await writeFile(join(f.source,"run-result.txt"),"LATER RUN WRITE");writer.release();expect((await(await fetch(result.preview!.url)).json()).pid).toBe(body.pid);
   await f.dev.command({type:"preview.stop",command_id:"preview:stop",preview_id:result.preview!.preview_id});await expect(fetch(result.preview!.url)).rejects.toThrow();expect(f.coordinator.list()).toEqual([]);
  }finally{await f.dev.close();}
 });
 it("allows a read-only registration and read-only preset to host an enforced preview without a write capability",async()=>{const f=await fixture("read-only");f.workspace.capabilities.commit_patch=false;f.workspace.capabilities.run_command=false;try{const {body}=await start(f);expect(body).toMatchObject({sourceDenied:true,cacheWritten:true,profileDenied:true});expect(await readFile(join(f.source,"marker.txt"),"utf8")).toBe("SOURCE UNCHANGED");}finally{await f.dev.close();}});
 it("rejects project read denial, restricted per-file policy and foreign project scope before a process is started",async()=>{const f=await fixture();const input={type:"preview.start" as const,command_id:"preview:deny",project_id:f.workspace.project_id,command:process.execPath,args:[f.script],port:await port()};try{
  f.workspace.capabilities.read=false;await expect(f.dev.command(input)).rejects.toMatchObject({code:"project_scope_denied"});f.workspace.capabilities.read=true;
  f.context.permissionConfig.resolveProject=async()=>createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"],rules:[{rule_id:"read-deny",priority:1,when:{side_effect:"read"},then:"deny",explanation:"No source reads"}]});await expect(f.dev.command(input)).rejects.toMatchObject({code:"preview_read_policy_denied"});
  f.context.permissionConfig.resolveProject=async()=>createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"],rules:[{rule_id:"file-deny",priority:1,when:{tool:"read_file",path_glob:"private/**"},then:"deny",explanation:"No private file reads"}]});await expect(f.dev.command(input)).rejects.toMatchObject({code:"preview_read_policy_restricted"});
  await expect(f.dev.command({...input,project_id:"project:foreign"})).rejects.toMatchObject({code:"project_scope_denied"});expect(f.dev.previews()).toEqual([]);expect(f.coordinator.list()).toEqual([]);await expect(readFile(join(f.profileRoot,"preview-cache"))).rejects.toMatchObject({code:"ENOENT"});
 }finally{await f.dev.close();}});
 it("fails closed when native enforcement is unavailable even with a full-access Host",async()=>{const f=await fixture();await f.dev.close();f.dev=new DevWorkbench({...f.context,sandboxProbe:request=>probeNativeSandbox(request,{platform:"darwin",seatbeltExecutable:join(f.root,"missing-seatbelt")}),getSettings:()=>WorkbenchSettingsValuesSchema.parse({})});await f.dev.initialize();try{await expect(start(f)).rejects.toMatchObject({code:"sandbox_unavailable"});expect(f.dev.previews()).toEqual([]);expect(f.coordinator.list()).toEqual([]);expect(await readFile(join(f.source,"marker.txt"),"utf8")).toBe("SOURCE UNCHANGED");}finally{await f.dev.close();}});
 it("refuses a private cache alias that would grant source writes",async()=>{const f=await fixture();await symlink(f.source,join(f.profileRoot,"preview-cache"));try{await expect(start(f)).rejects.toMatchObject({code:"preview_cache_scope_denied"});expect(f.dev.previews()).toEqual([]);expect(await readFile(join(f.source,"marker.txt"),"utf8")).toBe("SOURCE UNCHANGED");}finally{await f.dev.close();}});
 it("rejects a cache within source even when its relative directory name starts with two dots",async()=>{const f=await fixture();await f.dev.close();const nested=join(f.source,"..private-profile");await mkdir(nested);f.dev=new DevWorkbench({...f.context,profileRoot:nested,getSettings:()=>WorkbenchSettingsValuesSchema.parse({})});await f.dev.initialize();try{await expect(start(f)).rejects.toMatchObject({code:"preview_cache_scope_denied"});expect(f.coordinator.list()).toEqual([]);expect(await readFile(join(f.source,"marker.txt"),"utf8")).toBe("SOURCE UNCHANGED");await expect(readFile(join(nested,"preview-cache"))).rejects.toMatchObject({code:"ENOENT"});}finally{await f.dev.close();}});
 it("redacts the actual private cache path from owned process stderr snapshots",async()=>{const f=await fixture();await writeFile(f.script,(await readFile(f.script,"utf8"))+"\nsetInterval(()=>console.error('CACHE '+process.env.XDG_CACHE_HOME),25);\n");try{await start(f);await vi.waitFor(()=>expect(f.dev.previews()[0]?.message).toMatch(/^CACHE \[(?:REDACTED_LOCAL_PATH|private preview cache)\]/u));expect(JSON.stringify(f.dev.previews())).not.toContain(f.profileRoot);}finally{await f.dev.close();}});
 it("attempts both real owned process groups when one cleanup cannot be verified and retains only its uncertain lease",async()=>{const f=await fixture();let first:Awaited<ReturnType<typeof start>>|undefined;try{
  first=await start(f,"preview:cleanup-one");const second=await start(f,"preview:cleanup-two"),kill=process.kill.bind(process),firstGroup=-first.body.ownerPID;
  vi.spyOn(process,"kill").mockImplementation(((pid:number,signal:any)=>{if(pid===firstGroup)throw Object.assign(new Error("Synthetic first owned group verification denied"),{code:"EPERM"});return kill(pid,signal);}) as typeof process.kill);
  await expect(f.dev.close()).rejects.toBeInstanceOf(AggregateError);vi.restoreAllMocks();await expect(fetch(second.result.preview!.url)).rejects.toThrow();expect(f.dev.previews().find(item=>item.preview_id===second.result.preview!.preview_id)?.state).toBe("stopped");expect(f.dev.previews().find(item=>item.preview_id===first!.result.preview!.preview_id)?.state).toBe("failed");expect(f.coordinator.list().map(item=>item.holder_id)).toEqual(["preview:cleanup-one"]);
 }finally{vi.restoreAllMocks();if(first)try{process.kill(-first.body.ownerPID,"SIGKILL");}catch(error){if((error as NodeJS.ErrnoException).code!=="ESRCH")throw error;}await f.dev.close().catch(()=>undefined);f.coordinator.close();}});
 it("lets a real admitted Run commit a scoped patch while the same workspace preview stays alive",async()=>{const f=await fixture();await f.dev.close();let calls=0;const model:ModelAdapter={name:"preview-writer-fixture",async decide(){calls++;return calls===1?{decision_id:"preview-writer:patch",kind:"tool_call",public_reason:"Preview a scoped source edit",evidence_refs:[],risk:"low",tool_call:{action_id:"preview-writer:patch",tool_name:"preview_patch",arguments:{path:"marker.txt",expected:"SOURCE UNCHANGED",replacement:"REAL RUN WRITE"}}}:{decision_id:"preview-writer:done",kind:"finish",public_reason:"Scoped edit completed",evidence_refs:[],risk:"none",final_answer:"Scoped edit completed"};}};
  const composition=await createHostComposition({profileRoot:f.profileRoot,dataDir:join(f.profileRoot,"data"),sessionDir:join(f.profileRoot,"sessions"),permissionConfigPath:join(f.profileRoot,"permission.json"),environment:{TRACEGRAPH_PERMISSION_PRESET:"full-write"},runtimeModel:budgetedFixtureModel(model),useEnvironmentModel:false,nativePicker:false,nativePermissionPrompts:false,admission:"workspace"});
  const project=await composition.registerProject(f.source,"read_write");project.workspace.capabilities.index=false;const dev=new DevWorkbench({...f.context,permissionConfig:composition.permissionConfig,resolveWorkspace:async()=>project.workspace,workspaceCoordinator:composition.workspaceCoordinator,getSettings:()=>WorkbenchSettingsValuesSchema.parse({})});await dev.initialize();
  try{const preview=await start({...f,dev,workspace:project.workspace,coordinator:composition.workspaceCoordinator});const started=await composition.host.runSessions.startRun({command_id:"preview-writer:start",project_id:project.workspace.project_id,task:"Make the scoped marker edit",mode:"execute"});
   await vi.waitFor(async()=>{const projection=await composition.runtime.getProjection(started.run_id);if(projection.pending_approval){const pending=projection.pending_approval;await composition.runtime.approve({type:"approve",command_id:`approve:${pending.approval_id}`,project_id:projection.project_id,run_id:projection.run_id,approval_id:pending.approval_id,action_id:pending.action_id});}const terminal=await composition.runtime.getProjection(started.run_id);expect(terminal.status).toBe("failed");expect(terminal.failure_code).toBe("delivery_verification_missing");},{timeout:8000,interval:20});
   expect(await readFile(join(f.source,"marker.txt"),"utf8")).toBe("REAL RUN WRITE");expect((await(await fetch(preview.result.preview!.url)).json()).pid).toBe(preview.body.pid);await vi.waitFor(()=>expect(composition.workspaceCoordinator.list().map(item=>item.kind)).toEqual(["preview"]));expect((await composition.runtime.getProjection(started.run_id)).timeline.some(event=>event.type==="patch.applied")).toBe(true);
  }finally{await dev.close();await composition.close();}
 },15_000);
});
