import {mkdtemp,mkdir,realpath,rm,readFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {describe,it,expect} from "vitest";
import {startLocalHost,connectLocalHost} from "../dist/local-host.js";
import {TraceGraphClient} from "@tracegraph/sdk";
const content="---\nname: review\ndescription: Local review\nversion: 1.0.0\nallowed_tools: [read_file]\n---\nPRIVATE_SKILL_HTTP_ONLY_BODY\n";
describe("authenticated built Host and SDK Skill integration",()=>{
 it("manages a real global Skill before project setup, persists tombstones and keeps private bodies off receipts",async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-skills-http-")));let owner=await startLocalHost({profileRoot:root,httpPort:0,credentialBackend:"private-file"}),native=await connectLocalHost({profileRoot:root});try{const web=new TraceGraphClient({baseUrl:owner.status.http_address});await web.bootstrap();const capabilities=await web.getCapabilities();expect(capabilities.capabilities.find(c=>c.operation==="skills.manage.write")).toMatchObject({state:"available"});expect(await web.listProjects()).toEqual([]);expect((await web.listManagedSkills({kind:"global"})).entries).toEqual([]);const input={command_id:"skill:http-create",type:"create" as const,scope:{kind:"global" as const},name:"review",expected_sha256:null,content};const pending=await web.managedSkillCommand(input);expect(pending).toMatchObject({status:"awaiting_approval"});expect((await web.listManagedSkills(input.scope)).entries).toEqual([]);const saved=await web.managedSkillCommand({...input,approval:{approval_id:pending.approval_id!,decision:"approve"}});expect(saved.status).toBe("succeeded");expect((await web.readManagedSkill({scope:input.scope,name:"review"})).content).toBe(content);expect(await readFile(join(root,"skills","review","SKILL.md"),"utf8")).toBe(content);expect(JSON.stringify(saved)).not.toContain("PRIVATE_SKILL_HTTP_ONLY_BODY");expect(JSON.stringify(await web.getManagedSkillCommandReceipt(input.command_id))).not.toContain(root);
 const unauthorized=await fetch(`${owner.status.http_address}/api/workbench/skills/list`,{method:"POST",headers:{"content-type":"application/json",origin:"http://127.0.0.1:4310"},body:JSON.stringify({kind:"global"})});expect(unauthorized.status).toBe(401);
 const wrong=await fetch(`${owner.status.http_address}/api/workbench/skills/commands`,{method:"POST",headers:{"content-type":"application/json",origin:"http://127.0.0.1:4310",authorization:`Bearer ${web.token}`},body:JSON.stringify({...input,command_id:"skill:path-denied",source_path:"/private/other"})});expect(wrong.status).toBe(400);expect(await web.getManagedSkillCommandReceipt("skill:path-denied")).toMatchObject({state:"not_found"});
 const list=await web.listManagedSkills(input.scope),remove={type:"remove" as const,command_id:"skill:http-remove",scope:input.scope,name:"review",expected_sha256:saved.sha256,expected_state_sha256:list.state_sha256};const ask=await web.managedSkillCommand(remove);const removed=await web.managedSkillCommand({...remove,approval:{approval_id:ask.approval_id!,decision:"approve"}});expect(removed.status).toBe("succeeded");expect(await readFile(join(root,"skills","review","SKILL.md"),"utf8")).toBe(content);await native.close();await owner.close();owner=await startLocalHost({profileRoot:root,httpPort:0,credentialBackend:"private-file"});native=await connectLocalHost({profileRoot:root});expect((await native.client.listManagedSkills(input.scope)).entries[0]).toMatchObject({removed:true,enabled:false});expect(await native.client.getManagedSkillCommandReceipt(input.command_id)).toMatchObject({state:"completed",result:{status:"succeeded"}});await mkdir(join(root,"project"));const registered=await native.native.registerProject({selectedPath:join(root,"project"),access:"read_write"});expect((await native.client.listManagedSkills({kind:"project",project_id:registered.project_id})).entries).toEqual([]);
 }finally{await native.close();await owner.close();await rm(root,{recursive:true,force:true});}},30_000);
});

it("freezes admitted Skill content while the next real Run resolves the edited registry",async()=>{
 const {createServer}=await import("node:http");const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-skills-run-")));let release:(()=>void)|undefined;const mainRequests:string[]=[];
 const finish={decision_id:"decision:finish",kind:"finish",public_reason:"Fixture completed",evidence_refs:[],risk:"none",final_answer:"Fixture result"};
 const provider=createServer(async(request,response)=>{let raw="";for await(const chunk of request)raw+=String(chunk);const payload=JSON.parse(raw);const send=(value:unknown)=>{if(response.writableEnded)return;response.writeHead(200,{"content-type":"application/json"});response.end(JSON.stringify({choices:[{message:{content:JSON.stringify(value)}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}}));};if(payload.messages?.[0]?.content.startsWith("You extract")){send({summary:"No memory candidates",candidates:[]});return;}mainRequests.push(raw);if(mainRequests.length===1)release=()=>send({decision_id:"decision:load",kind:"tool_call",public_reason:"Read the admitted Skill",evidence_refs:[],risk:"low",tool_call:{action_id:"action:skill",tool_name:"load_skill",arguments:{name:"review"}}});else send(finish);});await new Promise<void>(resolve=>provider.listen(0,"127.0.0.1",resolve));const address=provider.address();if(!address||typeof address==="string")throw new Error("Missing fixture address");const owner=await startLocalHost({profileRoot:root,httpPort:0,credentialBackend:"private-file",deliveryBudget:{max_tokens:200_000,max_time_ms:900_000}}),connected=await connectLocalHost({profileRoot:root}),client=connected.client;
 const wait=async<T>(read:()=>Promise<T>,check:(v:T)=>boolean)=>{const end=Date.now()+10_000;let last:T|undefined;while(Date.now()<end){const value=await read();last=value;if(check(value))return value;if(typeof value==="object"&&value!==null&&"status" in value&&["failed","cancelled","interrupted"].includes(String(value.status)))break;await new Promise(done=>setTimeout(done,20));}const run=last as {status?:string;timeline?:Array<{type:string;summary:string}>}|undefined;throw new Error(`Canonical fixture did not complete: ${JSON.stringify({status:run?.status,events:run?.timeline?.slice(-8).map(event=>({type:event.type,summary:event.summary}))})}`);};
 try{await client.configureModel({provider:"custom",protocol:"openai-chat-completions",base_url:`http://127.0.0.1:${address.port}/v1`,model:"isolated-skill-fixture",api_key:"fixture-only-key"});await mkdir(join(root,"workspace"));const project=await connected.native.registerProject({selectedPath:join(root,"workspace"),access:"read_write"});const old=content.replace("PRIVATE_SKILL_HTTP_ONLY_BODY","PRIVATE_ADMITTED_OLD_BODY"),create={type:"create" as const,command_id:"skill:frozen-create",scope:{kind:"global" as const},name:"review",expected_sha256:null,content:old};const pending=await client.managedSkillCommand(create),created=await client.managedSkillCommand({...create,approval:{approval_id:pending.approval_id!,decision:"approve"}});const first=await client.startRun({command_id:"run:old-skill",project_id:project.project_id,task:"Use the review Skill",mode:"execute"});await wait(async()=>mainRequests.length,x=>x===1);const edit={...create,type:"save" as const,command_id:"skill:frozen-edit",expected_sha256:created.sha256,content:old.replace("1.0.0","2.0.0").replace("PRIVATE_ADMITTED_OLD_BODY","PRIVATE_NEW_SKILL_BODY")};const ask=await client.managedSkillCommand(edit);expect((await client.managedSkillCommand({...edit,approval:{approval_id:ask.approval_id!,decision:"approve"}})).status).toBe("succeeded");release!();const firstDone=await wait(()=>client.getRun(first.run_id),run=>run.status==="completed");expect(firstDone.timeline.find(event=>event.type==="run.completed")?.data.delivery_budget).toMatchObject({request_count:2,unknown_request_count:0,reported_input_tokens:20,reported_output_tokens:10});expect(mainRequests[1]).toContain("PRIVATE_ADMITTED_OLD_BODY");expect(mainRequests[1]).not.toContain("PRIVATE_NEW_SKILL_BODY");const next=await client.startRun({command_id:"run:new-skill",project_id:project.project_id,task:"Use the updated review catalog",mode:"execute"});const nextDone=await wait(()=>client.getRun(next.run_id),run=>run.status==="completed");expect(mainRequests[2]).toContain("2.0.0");const oldEvents=(await client.getRun(first.run_id)).timeline,newEvents=nextDone.timeline;const oldDigest=oldEvents.find(e=>e.type==="skill.registry_loaded")!.data.registry_digest,newDigest=newEvents.find(e=>e.type==="skill.registry_loaded")!.data.registry_digest;expect(newDigest).not.toBe(oldDigest);expect(oldEvents.some(e=>e.type==="tool.completed")).toBe(true);
 }finally{release?.();await connected.close();await owner.close();await new Promise<void>(resolve=>provider.close(()=>resolve()));await rm(root,{recursive:true,force:true});}
},30_000);
