import {afterEach,describe,expect,it,vi} from "vitest";
import {mkdtemp,mkdir,readFile,writeFile,rm,symlink,link,realpath,rename} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {SkillRegistry,createManagedWorkspaceHandle} from "@tracegraph/core";
import {type ManagedSkillCommand,type ManagedSkillScope} from "@tracegraph/contracts";
import {PermissionConfigController} from "./composition/permission-config.js";
import {WorkspaceCoordinator} from "./workspace-coordinator.js";
import {SkillManagementController,type SkillManagementContext} from "./skill-management.js";
const roots:string[]=[],coordinators:WorkspaceCoordinator[]=[];
afterEach(async()=>{coordinators.splice(0).forEach(c=>c.close());for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
const globalScope:ManagedSkillScope={kind:"global"};
const document=(name="review",body="Read source before reviewing. PRIVATE_SKILL_MARKER",tools="read_file")=>`---\nname: ${name}\ndescription: Local review\nversion: 1.0.0\nallowed_tools: [${tools}]\n---\n${body}\n`;
async function fixture(){const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-skills-")));roots.push(root);const project=join(root,"project");await mkdir(project);const workspace=await createManagedWorkspaceHandle({projectId:"project:skills",root:project});const permission=await PermissionConfigController.open({userConfigPath:join(root,"permissions.json"),permissionPresetFlag:"full-write",environment:{}});const coordinator=new WorkspaceCoordinator();coordinators.push(coordinator);const context:SkillManagementContext={profileRoot:root,permissionConfig:permission,workspaceCoordinator:coordinator,legacyDisabledNames:()=>[],resolveWorkspace:async id=>{if(id!==workspace.project_id)throw new Error("Scope unavailable");return workspace;}};const control=await SkillManagementController.create(context);return {root,project,workspace,permission,coordinator,context,control};}
async function approved(control:SkillManagementController,input:ManagedSkillCommand){const first=await control.command(input);return first.status==="awaiting_approval"?control.command({...input,approval:{approval_id:first.approval_id!,decision:"approve"}}):first;}
const create=(id:string,scope:ManagedSkillScope=globalScope):ManagedSkillCommand=>({type:"create",command_id:id,scope,name:"review",expected_sha256:null,content:document()});

describe("local Skill lifecycle preserves scope, CAS and canonical evidence",()=>{
 it("refuses enablement overflow before changing the valid state or writing a dispatch event",async()=>{const f=await fixture(),created=await approved(f.control,create("skill:state-base")),state=JSON.stringify({revision:5,disabled:Array.from({length:256},(_,i)=>`disabled-${i}`),removed:[]}),path=join(f.root,"skills",".enablement.json");await writeFile(path,state);const current=await f.control.list(globalScope);const result=await approved(f.control,{type:"set-enabled",command_id:"skill:state-overflow",scope:globalScope,name:"review",expected_sha256:created.sha256,expected_state_sha256:current.state_sha256,enabled:false});expect(result).toMatchObject({status:"failed",code:"skill_state_limit"});expect(await readFile(path,"utf8")).toBe(state);expect((await f.control.list(globalScope)).state_sha256).toBe(current.state_sha256);const ids=await f.control.ledger.listRunIds();for(const id of ids){const events=await f.control.ledger.list(id);if(events[0]?.operation_id==="skill:state-overflow")expect(events.some(e=>e.data.phase==="dispatch")).toBe(false);}});
 it.runIf(process.platform==="darwin")("rejects an ancestor symlink swapped immediately before creation without touching its private target",async()=>{const f=await fixture(),privateDir=join(f.root,"private-target");await mkdir(privateDir);await writeFile(join(privateDir,"marker.txt"),"private untouched");const control=await SkillManagementController.create({...f.context,beforeWriteTargetOpen:async()=>{const directory=join(f.root,"skills","review");await rename(directory,directory+"-original");await symlink(privateDir,directory);}});expect(await control.command(create("skill:ancestor-race"))).toMatchObject({status:"unknown"});await expect(readFile(join(privateDir,"SKILL.md"))).rejects.toMatchObject({code:"ENOENT"});expect(await readFile(join(privateDir,"marker.txt"),"utf8")).toBe("private untouched");expect(await control.receipt("skill:ancestor-race")).toMatchObject({state:"unknown"});});
 it("binds concurrent reuse of one command ID to exactly one scope and content",async()=>{const f=await fixture(),project:ManagedSkillScope={kind:"project",project_id:f.workspace.project_id};const global=create("skill:concurrent"),other={...create(global.command_id,project),content:document("review","Different project intent")};const results=await Promise.allSettled([f.control.command(global),f.control.command(other)]);expect(results[0]).toMatchObject({status:"fulfilled",value:{status:"succeeded"}});expect(results[1]).toMatchObject({status:"rejected",reason:{code:"command_id_conflict"}});expect(await readFile(join(f.root,"skills","review","SKILL.md"),"utf8")).toBe(global.content);expect((await f.control.list(project)).entries).toEqual([]);const events=await f.control.ledger.list((await f.control.ledger.listRunIds())[0]!);expect(events.filter(event=>event.data.phase==="dispatch")).toHaveLength(1);expect(await f.control.receipt(global.command_id)).toMatchObject({state:"completed",result:{scope:globalScope}});});
 it("manages global Skills without projects, imports bounded text and never logs body or profile paths",async()=>{const f=await fixture();expect(await f.control.list(globalScope)).toMatchObject({entries:[],state_revision:0});const result=await approved(f.control,create("skill:create"));expect(result).toMatchObject({status:"succeeded",receipt_event_id:expect.any(String)});expect(await readFile(join(f.root,"skills","review","SKILL.md"),"utf8")).toBe(document());expect(await f.control.list(globalScope)).toMatchObject({entries:[{name:"review",enabled:true,removed:false,catalog:{source:"user",version:"1.0.0"}}]});const loaded=await f.control.read({scope:globalScope,name:"review"});expect(loaded.content).toBe(document());const events=JSON.stringify(await f.control.ledger.list((await f.control.ledger.listRunIds())[0]!));expect(events).not.toContain("PRIVATE_SKILL_MARKER");expect(events).not.toContain(f.root);expect(await f.control.command(create("skill:create"))).toEqual(result);expect(await f.control.receipt("skill:create")).toMatchObject({state:"completed",result:{status:"succeeded"}});const imported=await approved(f.control,{...create("skill:import"),type:"import",name:"imported",content:document("imported")});expect(imported.status).toBe("succeeded");});
 it("uses the original file hash for edits and preserves externally changed bytes on conflict",async()=>{const f=await fixture();const original=await approved(f.control,create("skill:first"));const next:ManagedSkillCommand={type:"save",command_id:"skill:edit",scope:globalScope,name:"review",expected_sha256:original.sha256,content:document("review","Changed local instruction")};await writeFile(join(f.root,"skills","review","SKILL.md"),document("review","External change"));const result=await approved(f.control,next);expect(result).toMatchObject({status:"conflict",code:"skill_revision_conflict"});expect((await f.control.read({scope:globalScope,name:"review"})).content).toContain("External change");await expect(f.control.command({...next,content:document("review","Different intent")})).rejects.toMatchObject({code:"command_id_conflict"});});
 it("requires exact approval and retains immutable policy limits independent of allowed_tools",async()=>{const f=await fixture();await f.permission.setUserPreset("workspace-write");const input={...create("skill:approval"),content:document("review","Tools are only restrictions","run_command, commit_patch")};const pending=await f.control.command(input);expect(pending.status).toBe("awaiting_approval");expect((await f.control.list(globalScope)).entries).toEqual([]);await expect(f.control.command({...input,approval:{approval_id:"approval:foreign",decision:"approve"}})).rejects.toMatchObject({code:"skill_approval_invalid"});expect(await f.control.command({...input,approval:{approval_id:pending.approval_id!,decision:"deny"}})).toMatchObject({status:"denied"});await f.permission.setUserPreset("read-only");expect(await f.control.command({...input,command_id:"skill:denied"})).toMatchObject({status:"denied",code:"skill_policy_denied"});expect(f.permission.snapshot().selected_preset_key).toBe("read-only");expect((await f.control.list(globalScope)).entries).toEqual([]);});
 it("persists scope removal, exposes global inheritance and requires explicit restore even after body changes",async()=>{const f=await fixture(),scope:ManagedSkillScope={kind:"project",project_id:f.workspace.project_id};await approved(f.control,create("skill:global"));const project=await approved(f.control,{...create("skill:project",scope),content:document("review","Project override")});const list=await f.control.list(scope);expect(list.conflicts).toMatchObject([{name:"review",winner:"project",loser:"user"}]);const registry=new SkillRegistry({userSkillsRoot:join(f.root,"skills")});const frozen=await registry.scan(f.project);const removed=await approved(f.control,{type:"remove",command_id:"skill:remove",scope,name:"review",expected_sha256:project.sha256,expected_state_sha256:list.state_sha256});expect(removed.status).toBe("succeeded");expect(await readFile(join(f.project,".tracegraph","skills","review","SKILL.md"),"utf8")).toContain("Project override");const reopened=await SkillManagementController.create(f.context),states=await reopened.enabledScopes(f.project);expect((await registry.scan(f.project,s=>!states[s.source].has(s.name))).skills[0]?.source).toBe("user");expect(frozen.skills[0]?.body).toContain("Project override");await writeFile(join(f.project,".tracegraph","skills","review","SKILL.md"),document("review","Externally changed removed Skill"));const current=await reopened.list(scope);expect(current.entries[0]).toMatchObject({removed:true,enabled:false});expect(current.conflicts).toEqual([]);const restored=await approved(reopened,{type:"restore",command_id:"skill:restore",scope,name:"review",expected_sha256:current.entries[0]!.sha256,expected_state_sha256:current.state_sha256});expect(restored.status).toBe("succeeded");expect((await reopened.list(scope)).entries[0]).toMatchObject({removed:false,enabled:true});});
 it("detects stale scope enablement CAS and keeps legacy disables restrictive",async()=>{const f=await fixture();const first=await approved(f.control,create("skill:base"));const before=await f.control.list(globalScope);const toggle:ManagedSkillCommand={type:"set-enabled",command_id:"skill:off",scope:globalScope,name:"review",expected_sha256:first.sha256,expected_state_sha256:before.state_sha256,enabled:false};expect(await approved(f.control,toggle)).toMatchObject({status:"succeeded"});expect(await approved(f.control,{...toggle,command_id:"skill:stale",enabled:true})).toMatchObject({status:"conflict",code:"skill_state_conflict"});const legacy=await SkillManagementController.create({...f.context,legacyDisabledNames:()=>["review"]});expect((await legacy.list(globalScope)).entries[0]?.enabled).toBe(false);});
 it("rejects symlink, hardlink, invalid and oversized content without changing private targets",async()=>{const f=await fixture();await mkdir(join(f.root,"skills"));const secret=join(f.root,"secret.txt");await writeFile(secret,"private-original");await symlink(f.project,join(f.root,"skills","escape"));await expect(f.control.read({scope:globalScope,name:"escape"})).rejects.toMatchObject({code:"skill_scope_unsafe"});await mkdir(join(f.root,"skills","linked"));await link(secret,join(f.root,"skills","linked","SKILL.md"));await expect(f.control.read({scope:globalScope,name:"linked"})).rejects.toMatchObject({code:"skill_file_unsafe"});expect(await approved(f.control,{...create("skill:invalid"),content:"name: no frontmatter"})).toMatchObject({status:"failed",code:"skill_document_invalid"});expect(f.control.validate({name:"review",content:"é".repeat(200000)}).valid).toBe(false);await expect(f.control.read({scope:globalScope,name:"../secret"})).rejects.toBeDefined();expect(await readFile(secret,"utf8")).toBe("private-original");});
 it("keeps a lost receipt unknown after actual disk change and never repeats the original effect",async()=>{const f=await fixture();const after=vi.fn(async()=>{throw new Error("Injected receipt interruption");});const control=await SkillManagementController.create({...f.context,afterEffect:after});const input=create("skill:unknown");expect(await approved(control,input)).toMatchObject({status:"unknown",code:"skill_effect_unknown"});expect(await readFile(join(f.root,"skills","review","SKILL.md"),"utf8")).toBe(document());const reopened=await SkillManagementController.create(f.context);const receipt=await reopened.receipt(input.command_id);expect(receipt).toMatchObject({state:"unknown",observed_sha256:expect.any(String)});expect(await reopened.command(input)).toMatchObject({status:"unknown"});expect(after).toHaveBeenCalledOnce();expect(await reopened.receipt("skill:absent")).toMatchObject({state:"not_found"});});
 it("respects project policy denial and never enlarges immutable host permission",async()=>{const f=await fixture();await mkdir(join(f.project,".tracegraph"));await writeFile(join(f.project,".tracegraph","policy.json"),JSON.stringify({policy_version:1,rules:[{rule_id:"deny:skills",priority:1,when:{path_glob:".tracegraph/skills/**"},then:"deny",explanation:"Project denies Skill writes"}]}));const scope:ManagedSkillScope={kind:"project",project_id:f.workspace.project_id};expect(await f.control.command(create("skill:project-deny",scope))).toMatchObject({status:"denied"});expect((await f.control.list(scope)).entries).toEqual([]);await expect(f.control.read({scope,name:"review"})).rejects.toMatchObject({code:"skill_read_policy_denied"});expect(f.permission.snapshot().ceiling_preset_key).toBe("full-write");});
});
