import {createHash,randomUUID} from "node:crypto";
import {constants} from "node:fs";
import {lstat,mkdir,open,readdir,realpath} from "node:fs/promises";
import {join} from "node:path";
import {JsonlEventLedger,PolicyEngine,SkillRegistry,validateSkillMarkdown} from "@tracegraph/core";
import {ManagedSkillCommandSchema,ManagedSkillScopeSchema,ManagedSkillSelectorSchema,ValidateManagedSkillRequestSchema,MAX_MANAGED_SKILL_BYTES,SkillNameSchema,type ManagedSkillCommand,type ManagedSkillCommandResult,type ManagedSkillCommandReceipt,type ManagedSkillScope,type ManagedSkillSelector,type ManagedSkillEntry,type ManagedSkillsSnapshot,type ManagedSkillDocument,type ManagedSkillValidation,type ValidateManagedSkillRequest,type WorkspaceHandle,type SessionEvent} from "@tracegraph/contracts";
import type {PermissionConfigController} from "./composition/permission-config.js";
import type {WorkspaceCoordinator} from "./workspace-coordinator.js";
import {workbenchError} from "./workbench-journal.js";

const hash=(value:string|Uint8Array)=>`sha256:${createHash("sha256").update(value).digest("hex")}` as const;
const runId=(id:string)=>`skill-command:${createHash("sha256").update(id).digest("hex")}`;
const scopeKey=(scope:ManagedSkillScope)=>scope.kind==="global"?"global":`project:${scope.project_id}`;
interface SkillState { revision:number; disabled:string[]; removed:string[]; sha256:`sha256:${string}`; }
const emptyState=():SkillState=>({revision:0,disabled:[],removed:[],sha256:hash(JSON.stringify({revision:0,disabled:[],removed:[]}))});
// Darwin SDK sys/fcntl.h: O_NOFOLLOW_ANY rejects symlinks in every path
// segment, including ancestors swapped after the parent identity check.
const noFollow=process.platform==="darwin"?0x20000000:process.platform==="win32"?0:constants.O_NOFOLLOW;
const privateError=(code:string,message:string,status=409)=>workbenchError(code,message,status);
export interface SkillManagementContext {
 profileRoot:string;permissionConfig:PermissionConfigController;workspaceCoordinator:WorkspaceCoordinator;
 resolveWorkspace(projectId:string):Promise<WorkspaceHandle>;legacyDisabledNames():readonly string[];
 /** Trusted fault-injection seam after external state changed; never a client setting. */
 afterEffect?():Promise<void>;
 /** Trusted adversarial test seam immediately before opening the write target. */
 beforeWriteTargetOpen?():Promise<void>;
}
/** Fixed scope files; raw bodies never enter canonical events or mutation receipts. */
export class SkillManagementController {
 readonly ledger:JsonlEventLedger;readonly #context:SkillManagementContext;readonly #registry:SkillRegistry;
 readonly #queues=new Map<string,Promise<unknown>>();
 #writeSupported=process.platform!=="win32";
 get writeSupported(){return this.#writeSupported;}
 private constructor(context:SkillManagementContext){this.#context=context;this.#registry=new SkillRegistry({userSkillsRoot:join(context.profileRoot,"skills")});this.ledger=new JsonlEventLedger(join(context.profileRoot,"skill-management-events"));}
 static async create(context:SkillManagementContext){const value=new SkillManagementController(context);await value.ledger.initialize();if(process.platform==="darwin"){try{const fd=await open(context.profileRoot,constants.O_RDONLY|constants.O_DIRECTORY|noFollow);await fd.close();}catch{value.#writeSupported=false;}}return value;}
 async #serialize<T>(key:string,execute:()=>Promise<T>):Promise<T>{const next=(this.#queues.get(key)??Promise.resolve()).catch(()=>undefined).then(execute);this.#queues.set(key,next);try{return await next;}finally{if(this.#queues.get(key)===next)this.#queues.delete(key);}}
 async #scope(scope:ManagedSkillScope,create=false){
  const parsed=ManagedSkillScopeSchema.parse(scope);let workspace:WorkspaceHandle|undefined;
  if(parsed.kind==="project"){workspace=await this.#context.resolveWorkspace(parsed.project_id);if(workspace.project_id!==parsed.project_id||!workspace.capabilities.read)throw privateError("skill_scope_denied","Project Skills are outside the available scope",403);}
  const base=workspace?.real_root??this.#context.profileRoot;const baseInfo=await lstat(base);if(baseInfo.isSymbolicLink()||!baseInfo.isDirectory()||await realpath(base)!==base)throw privateError("skill_scope_unsafe","Skill scope must be a registered real directory",403);
  let root=base;for(const part of parsed.kind==="global"?["skills"]:[".tracegraph","skills"]){root=join(root,part);if(create)await mkdir(root,{mode:0o700}).catch(error=>{if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;});const info=await lstat(root).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});if(!info){if(create)throw privateError("skill_scope_unsafe","Skill scope is unavailable",403);return {scope:parsed,root,workspace,exists:false};}if(!info.isDirectory()||info.isSymbolicLink()||await realpath(root)!==root)throw privateError("skill_scope_unsafe","Symbolic links cannot define a Skill scope",403);}
  return {scope:parsed,root,workspace,exists:true};
 }
 async #assertRead(scope:ManagedSkillScope,name?:string){const bound=await this.#scope(scope),policy=await this.#context.permissionConfig.resolveProject(bound.workspace?.real_root??this.#context.profileRoot);const path=scope.kind==="global"?`skills/${name?name+"/SKILL.md":""}`:`.tracegraph/skills/${name?name+"/SKILL.md":""}`;const decision=PolicyEngine.fromEffective(policy).evaluate({toolName:name?"read_file":"list_dir",sideEffect:"read",capabilityAllowed:bound.workspace?.capabilities.read??true,path});if(decision.kind!=="allow")throw privateError("skill_read_policy_denied","Current policy does not permit this Skill read",403);}
 async #directory(scope:ManagedSkillScope,name:string,create=false){const bound=await this.#scope(scope,create);const directory=join(bound.root,SkillNameSchema.parse(name));if(!bound.exists)return {...bound,directory,exists:false};if(create)await mkdir(directory,{mode:0o700}).catch(error=>{if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;});const info=await lstat(directory).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});if(!info)return {...bound,directory,exists:false};if(!info.isDirectory()||info.isSymbolicLink()||await realpath(directory)!==directory)throw privateError("skill_scope_unsafe","Skill directories must be real scoped directories",403);return {...bound,directory,exists:true};}
 async #read(scope:ManagedSkillScope,name:string){const target=await this.#directory(scope,name);if(!target.exists)return null;const file=join(target.directory,"SKILL.md");const info=await lstat(file).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});if(!info)return null;if(!info.isFile()||info.isSymbolicLink()||info.nlink!==1)throw privateError("skill_file_unsafe","Only regular single-link SKILL.md files are allowed",403);const handle=await open(file,constants.O_RDONLY|noFollow);try{const stat=await handle.stat();if(stat.ino!==info.ino||stat.dev!==info.dev||stat.nlink!==1||!stat.isFile())throw privateError("skill_revision_conflict","Skill identity changed; read it again");if(stat.size>MAX_MANAGED_SKILL_BYTES)throw privateError("skill_too_large","Skill exceeds the 256 KiB limit",413);const bytes=await boundedBytes(handle,MAX_MANAGED_SKILL_BYTES);if(bytes.length>MAX_MANAGED_SKILL_BYTES)throw privateError("skill_too_large","Skill exceeds the 256 KiB limit",413);const content=new TextDecoder("utf8",{fatal:true,ignoreBOM:true}).decode(bytes);if(content.includes("\0"))throw privateError("skill_not_text","Skills must be UTF-8 text",400);return {content,sha256:hash(bytes),bytes:bytes.length,target,info};}catch(error){if(error instanceof TypeError)throw privateError("skill_not_text","Skills must be UTF-8 text",400);throw error;}finally{await handle.close();}}
 async #stateAt(root:string):Promise<SkillState>{
  const file=join(root,".enablement.json"),info=await lstat(file).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});if(!info)return emptyState();
  if(!info.isFile()||info.isSymbolicLink()||info.nlink!==1||info.size>32*1024)throw privateError("skill_state_unsafe","Skill enablement state could not be verified",403);
  const handle=await open(file,constants.O_RDONLY|noFollow);try{const stat=await handle.stat();if(stat.ino!==info.ino||stat.dev!==info.dev||stat.nlink!==1)throw privateError("skill_state_conflict","Skill enablement changed; refresh it");const bytes=await boundedBytes(handle,32*1024);
   let value:unknown;try{value=JSON.parse(bytes.toString("utf8"));}catch{throw privateError("skill_state_unsafe","Skill enablement state is invalid",403);}if(!value||typeof value!=="object"||Array.isArray(value))throw privateError("skill_state_unsafe","Skill enablement state is invalid",403);const state=value as {revision:unknown;disabled:unknown;removed:unknown};const names=(list:unknown):list is string[]=>Array.isArray(list)&&list.length<=256&&new Set(list).size===list.length&&list.every(name=>SkillNameSchema.safeParse(name).success);
   if(!Number.isSafeInteger(state.revision)||Number(state.revision)<0||!names(state.disabled)||!names(state.removed)||Object.keys(value).some(key=>!["revision","disabled","removed"].includes(key)))throw privateError("skill_state_unsafe","Skill enablement state is invalid",403);
   return {revision:Number(state.revision),disabled:state.disabled,removed:state.removed,sha256:hash(bytes)};
  }finally{await handle.close();}
 }
 async #state(scope:ManagedSkillScope):Promise<SkillState>{const bound=await this.#scope(scope);return bound.exists?this.#stateAt(bound.root):emptyState();}
 async enabledScopes(projectRoot:string){const global=await this.#state({kind:"global"});let project=emptyState();const root=join(projectRoot,".tracegraph","skills");try{for(const path of [join(projectRoot,".tracegraph"),root]){const stat=await lstat(path);if(!stat.isDirectory()||stat.isSymbolicLink()||await realpath(path)!==path)throw privateError("skill_state_unsafe","Skill enablement could not be verified",403);}project=await this.#stateAt(root);}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;}return {user:new Set([...global.disabled,...global.removed]),project:new Set([...project.disabled,...project.removed])};}
 validate(input:ValidateManagedSkillRequest):ManagedSkillValidation {const parsed=ValidateManagedSkillRequestSchema.parse(input),bytes=Buffer.from(parsed.content,"utf8");if(bytes.length>MAX_MANAGED_SKILL_BYTES||bytes.toString("utf8")!==parsed.content||bytes.includes(0))return {valid:false,sha256:hash(bytes),diagnostics:["Use UTF-8 SKILL.md text of 256 KiB or less."]};try{return {valid:true,sha256:hash(bytes),catalog:validateSkillMarkdown(parsed.content,parsed.name),diagnostics:[]};}catch{return {valid:false,sha256:hash(bytes),diagnostics:["SKILL.md must have matching name, description, version, valid allowed_tools and a non-empty body."]};}}
 async #entry(scope:ManagedSkillScope,name:string,state:SkillState){const document=await this.#read(scope,name);if(!document)return null;const checked=this.validate({name,content:document.content});const legacy=new Set(this.#context.legacyDisabledNames());return {name,sha256:document.sha256,byte_length:document.bytes,enabled:!state.disabled.includes(name)&&!state.removed.includes(name)&&!legacy.has(name),removed:state.removed.includes(name),...(checked.catalog?{catalog:{...checked.catalog,source:scope.kind==="global"?"user" as const:"project" as const}}:{}),diagnostics:checked.diagnostics} satisfies ManagedSkillEntry;}
 async list(scope:ManagedSkillScope):Promise<ManagedSkillsSnapshot>{await this.#assertRead(scope);const bound=await this.#scope(scope),state=await this.#state(scope),entries:ManagedSkillEntry[]=[],diagnostics:string[]=[];if(bound.exists)for(const item of (await readdir(bound.root,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,256)){if(!SkillNameSchema.safeParse(item.name).success||!item.isDirectory()||item.isSymbolicLink())continue;try{await this.#assertRead(scope,item.name);const entry=await this.#entry(scope,item.name,state);if(entry)entries.push(entry);}catch{diagnostics.push(`${item.name}: Skill file could not be safely read.`);}}
 const stateBySource=scope.kind==="project"?await this.enabledScopes(bound.workspace!.real_root):undefined,legacy=new Set(this.#context.legacyDisabledNames());const registry=scope.kind==="global"?await this.#registry.scanGlobal():await this.#registry.scan(bound.workspace!.real_root,skill=>!stateBySource![skill.source].has(skill.name)&&!legacy.has(skill.name));return {scope:bound.scope,state_sha256:state.sha256,state_revision:state.revision,entries,conflicts:registry.conflicts.map(({name,winner,loser,reason})=>({name,winner,loser,reason})),diagnostics:[...diagnostics,...registry.diagnostics.map(d=>`${d.source}: ${d.code}`)],effective:"new-run",legacy_disabled_names:this.#context.legacyDisabledNames().filter(name=>SkillNameSchema.safeParse(name).success)};}
 async read(input:ManagedSkillSelector):Promise<ManagedSkillDocument>{const parsed=ManagedSkillSelectorSchema.parse(input);await this.#assertRead(parsed.scope,parsed.name);const state=await this.#state(parsed.scope),entry=await this.#entry(parsed.scope,parsed.name,state),document=await this.#read(parsed.scope,parsed.name);if(!entry||!document)throw privateError("skill_not_found","This Skill no longer exists",404);if(entry.sha256!==document.sha256)throw privateError("skill_revision_conflict","Skill changed while reading; refresh it");return {...entry,scope:parsed.scope,content:document.content};}
 async #append(scope:ManagedSkillScope,id:string,type:SessionEvent["type"],phase:string,data:Record<string,unknown>){return this.ledger.append({type,project_id:scope.kind==="project"?scope.project_id:"workbench:profile",run_id:runId(id),operation_id:id,attempt:0,artifact_refs:[],summary:`Skill management ${phase}`,idempotency_key:hash(`${id}:${phase}`),data});}
 async command(input:ManagedSkillCommand):Promise<ManagedSkillCommandResult>{const parsed=ManagedSkillCommandSchema.parse(input);return this.#serialize(`command:${parsed.command_id}`,()=>this.#serialize(`scope:${scopeKey(parsed.scope)}`,()=>this.#command(parsed)));}
 async #command(input:ManagedSkillCommand):Promise<ManagedSkillCommandResult>{
 const {approval,...intentInput}=input;const contentHash="content" in input?hash(input.content):undefined;const {content:ignored,...metadata}=intentInput as typeof intentInput&{content?:string};void ignored;const intent={...metadata,...(contentHash?{content_sha256:contentHash}:{})},digest=hash(JSON.stringify(intent));let events=await this.ledger.list(runId(input.command_id));if(events.length&&events[0]!.data.digest!==digest)throw privateError("command_id_conflict","Command identifier was reused with another Skill intent");const completed=events.find(event=>event.type==="workbench.command_completed");if(completed)return {...completed.data.result as ManagedSkillCommandResult,receipt_event_id:completed.event_id};if(events.some(event=>event.data.phase==="dispatch"))return {command_id:input.command_id,scope:input.scope,name:input.name,status:"unknown",code:"skill_effect_unknown",sha256:input.expected_sha256,effective:"new-run"};
 const bound=await this.#scope(input.scope),policy=await this.#context.permissionConfig.resolveProject(bound.workspace?.real_root??this.#context.profileRoot);const path=`${input.scope.kind==="global"?"skills":".tracegraph/skills"}/${input.name}/SKILL.md`;const decision=PolicyEngine.fromEffective(policy).evaluate({toolName:"commit_patch",sideEffect:"write",capabilityAllowed:bound.workspace?bound.workspace.capabilities.commit_patch:this.#context.permissionConfig.snapshot().selected_preset.sandbox_mode!=="read-only",path,actionDigest:digest});if(!events.length){await this.#append(input.scope,input.command_id,"workbench.command_requested","requested",{digest,intent,policy_digest:policy.policy_digest});events=await this.ledger.list(runId(input.command_id));}
 if(events[0]!.data.digest!==digest)throw privateError("command_id_conflict","Command identifier was reused with another Skill intent");
 const finish=async(status:ManagedSkillCommandResult["status"],code:string,sha256:ManagedSkillCommandResult["sha256"],state_sha256?:ManagedSkillCommandResult["state_sha256"])=>{const result:ManagedSkillCommandResult={command_id:input.command_id,scope:input.scope,name:input.name,status,code,sha256,...(state_sha256?{state_sha256}:{}),effective:"new-run"};const receipt=await this.#append(input.scope,input.command_id,"workbench.command_completed","receipt",{result});return {...result,receipt_event_id:receipt.event_id};};
 if(events[0]!.data.policy_digest!==policy.policy_digest)return finish("denied","skill_policy_changed",input.expected_sha256);if(decision.kind==="deny")return finish("denied","skill_policy_denied",input.expected_sha256);if(!this.#writeSupported)return finish("failed","skill_scoped_write_platform_unavailable",input.expected_sha256);
 if("content" in input&&!this.validate({name:input.name,content:input.content}).valid)return finish("failed","skill_document_invalid",input.expected_sha256);
 if(decision.kind==="ask"){let pending=events.find(event=>event.type==="approval.requested");if(!pending)pending=await this.#append(input.scope,input.command_id,"approval.requested","approval-requested",{approval_id:`skill-approval:${randomUUID()}`,action_digest:digest,policy_digest:policy.policy_digest});const approvalId=String(pending.data.approval_id);if(!approval)return {command_id:input.command_id,scope:input.scope,name:input.name,status:"awaiting_approval",code:"skill_approval_required",sha256:input.expected_sha256,approval_id:approvalId,effective:"new-run"};if(approval.approval_id!==approvalId)throw privateError("skill_approval_invalid","Approval does not match this exact Skill intent",403);await this.#append(input.scope,input.command_id,approval.decision==="approve"?"approval.granted":"approval.denied","approval-decision",{approval_id:approvalId,action_digest:digest});if(approval.decision==="deny")return finish("denied","skill_approval_denied",input.expected_sha256);}else if(approval)throw privateError("skill_approval_invalid","This Skill command has no pending approval",403);
 const lease=bound.workspace?await this.#context.workspaceCoordinator.acquireWorkspace(bound.workspace,{holderId:input.command_id,kind:"file"}):undefined;
 try{const latestPolicy=await this.#context.permissionConfig.resolveProject(bound.workspace?.real_root??this.#context.profileRoot);if(latestPolicy.policy_digest!==policy.policy_digest)return finish("denied","skill_policy_changed",input.expected_sha256);const current=await this.#read(input.scope,input.name);if((current?.sha256??null)!==input.expected_sha256)return finish("conflict","skill_revision_conflict",current?.sha256??null);if(input.type==="create"&&current)return finish("conflict","skill_exists",current.sha256);if(input.type!=="create"&&input.type!=="import"&&!current)return finish("failed","skill_not_found",null);const state=await this.#state(input.scope);if("expected_state_sha256" in input&&state.sha256!==input.expected_state_sha256)return finish("conflict","skill_state_conflict",current?.sha256??null,state.sha256);
 const target=await this.#directory(input.scope,input.name,true),stateMutation="expected_state_sha256" in input,directory=stateMutation?target.root:target.directory;const parent=await open(directory,constants.O_RDONLY|constants.O_DIRECTORY|noFollow);let dispatched=false;
 try{const directoryInfo=await lstat(directory),pinned=await parent.stat();if(!directoryInfo.isDirectory()||directoryInfo.isSymbolicLink()||directoryInfo.ino!==pinned.ino||directoryInfo.dev!==pinned.dev)throw privateError("skill_scope_unsafe","Skill directory changed before writing",403);const prefix=process.platform==="darwin"?`/dev/fd/${parent.fd}`:`/proc/self/fd/${parent.fd}`;const file=join(process.platform==="darwin"?directory:prefix,stateMutation?".enablement.json":"SKILL.md");let nextHash=current?.sha256??null;
 const nextState=stateMutation?{revision:state.revision+1,disabled:[...new Set(input.type==="set-enabled"?(input.enabled?state.disabled.filter(name=>name!==input.name):[...state.disabled,input.name]):state.disabled)].sort(),removed:[...new Set(input.type==="remove"?[...state.removed,input.name]:input.type==="restore"?state.removed.filter(name=>name!==input.name):state.removed)].sort()}:undefined;
 const bytes=Buffer.from(nextState?JSON.stringify(nextState):("content" in input?input.content:""),"utf8");const exists=stateMutation?await lstat(file).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;}):current?.info;
 if(nextState&&(nextState.disabled.length>256||nextState.removed.length>256||bytes.length>32*1024))return finish("failed","skill_state_limit",current?.sha256??null,state.sha256);
 // Creating the fixed file is an external effect, so dispatch precedes O_EXCL.
 await this.#append(input.scope,input.command_id,"workbench.command_requested","dispatch",{phase:"dispatch",action_digest:digest});dispatched=true;
 await this.#context.beforeWriteTargetOpen?.();
 const handle=await open(file,(exists?constants.O_RDWR:constants.O_RDWR|constants.O_CREAT|constants.O_EXCL)|noFollow,0o600);
 try{const stat=await handle.stat(),parentNow=await lstat(directory),pathNow=await lstat(file);if(!stat.isFile()||stat.nlink!==1||parentNow.isSymbolicLink()||parentNow.ino!==pinned.ino||parentNow.dev!==pinned.dev||pathNow.ino!==stat.ino||pathNow.dev!==stat.dev||(exists&&(stat.ino!==exists.ino||stat.dev!==exists.dev)))throw privateError("skill_file_unsafe","Skill write target identity changed",403);
  if(exists){const previous=await boundedBytes(handle,stateMutation?32*1024:MAX_MANAGED_SKILL_BYTES);const expected=stateMutation?state.sha256:input.expected_sha256;if(hash(previous)!==expected)throw privateError("skill_revision_conflict","Skill content changed before writing");}
  let offset=0;while(offset<bytes.length){const written=await handle.write(bytes,offset,bytes.length-offset,offset);if(!written.bytesWritten)throw new Error("Write stalled");offset+=written.bytesWritten;}await handle.truncate(bytes.length);await handle.sync();if(!stateMutation)nextHash=hash(bytes);
 }finally{await handle.close();}
 await this.#context.afterEffect?.();const observed=await this.#read(input.scope,input.name);const observedState=await this.#state(input.scope);if((observed?.sha256??null)!==nextHash||(nextState&&observedState.sha256!==hash(JSON.stringify(nextState))))throw new Error("Skill state did not match the intended effect");return await finish("succeeded","skill_updated",nextHash,observedState.sha256);
 }catch(error){if(dispatched)return {command_id:input.command_id,scope:input.scope,name:input.name,status:"unknown",code:"skill_effect_unknown",sha256:input.expected_sha256,effective:"new-run"};throw error;}finally{await parent.close();}
 }catch(error){const code=(error as {code?:unknown}).code;return finish(code==="skill_revision_conflict"?"conflict":"failed",typeof code==="string"&&/^skill_[a-z_]+$/u.test(code)?code:"skill_operation_failed",input.expected_sha256);}finally{lease?.release();}
 }
 async receipt(commandId:string):Promise<ManagedSkillCommandReceipt>{const events=await this.ledger.list(runId(commandId));if(!events.length)return {command_id:commandId,state:"not_found"};const completed=events.find(event=>event.type==="workbench.command_completed");if(completed)return {command_id:commandId,state:"completed",result:{...completed.data.result as ManagedSkillCommandResult,receipt_event_id:completed.event_id}};const intent=events[0]!.data.intent as {scope:ManagedSkillScope;name:string};let observed_sha256:ManagedSkillCommandReceipt["observed_sha256"];try{observed_sha256=(await this.#read(intent.scope,intent.name))?.sha256??null;}catch{/* Inspection failure never proves success or permission. */}return {command_id:commandId,state:"unknown",code:"skill_effect_unknown",...(observed_sha256===undefined?{}:{observed_sha256})};}
}

async function boundedBytes(handle:import("node:fs/promises").FileHandle,maximum:number):Promise<Buffer>{const bytes=Buffer.alloc(maximum+1);let length=0;while(length<bytes.length){const next=await handle.read(bytes,length,bytes.length-length,length);if(!next.bytesRead)break;length+=next.bytesRead;}if(length>maximum)throw privateError("skill_too_large","Skill text exceeds its bound",413);return bytes.subarray(0,length);}
