import {execFile} from "node:child_process";
import {createHash} from "node:crypto";
import {mkdir,mkdtemp,readFile,readdir,rm,symlink,link,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {promisify} from "node:util";
import {afterEach,describe,expect,it} from "vitest";
import {BUILTIN_PERMISSION_PRESETS,SubagentRunLinkSchema,SubagentSpecSchema,type WorkspaceHandle} from "@tracegraph/contracts";
import {createManagedWorkspaceHandle,createEffectivePermissionPolicy,type SubagentWorkspaceRequest} from "@tracegraph/core";
import {SubagentWorktreeController,MAX_AGENT_BASELINE_FILE_BYTES} from "./subagent-worktrees.js";
import {WorkspaceCoordinator} from "./workspace-coordinator.js";
import {WorkbenchJournal} from "./workbench-journal.js";
const execute=promisify(execFile),git=process.platform==="darwin"?"/Library/Developer/CommandLineTools/usr/bin/git":"/usr/bin/git";
const sha=(bytes:string|Uint8Array)=>`sha256:${createHash("sha256").update(bytes).digest("hex")}`;
const roots:string[]=[];
afterEach(async()=>{for(const root of roots.splice(0))await rm(root,{recursive:true,force:true});});
async function command(root:string,args:string[]){return (await execute(git,["-c","core.hooksPath=/dev/null",...args],{cwd:root})).stdout;}
async function fixture(){const root=await mkdtemp(join(tmpdir(),"outlive-team-baseline-"));roots.push(root);const source=join(root,"source");await mkdir(source);await command(source,["init","-q"]);await command(source,["config","user.email","fixture@example.invalid"]);await command(source,["config","user.name","Fixture"]);await writeFile(join(source,"value.txt"),"HEAD\n");await writeFile(join(source,"removed.txt"),"old\n");await writeFile(join(source,".gitignore"),"node_modules/\n");await command(source,["add","--","value.txt","removed.txt",".gitignore"]);await command(source,["commit","-qm","baseline"]);await writeFile(join(source,"value.txt"),"STAGED\n");await command(source,["add","--","value.txt"]);await writeFile(join(source,"value.txt"),"STAGED+UNSTAGED\n");await command(source,["rm","-q","--","removed.txt"]);await writeFile(join(source,"new.txt"),"UNTRACKED\n");await mkdir(join(source,"node_modules"));await writeFile(join(source,"node_modules","ignored.txt"),"not baseline\n");const workspace=await createManagedWorkspaceHandle({projectId:"project:dirty",root:source});const coordinator=new WorkspaceCoordinator();coordinator.setMaxParallelRuns(1);const control=await SubagentWorktreeController.create({profileRoot:join(root,"profile"),workspaceCoordinator:coordinator});return {root,source,workspace,coordinator,control};}
function request(workspace:WorkspaceHandle,id="one"):SubagentWorkspaceRequest{const link=SubagentRunLinkSchema.parse({subagent_id:`agent:${id}`,parent_run_id:"run:parent",parent_session_id:"session:parent",child_run_id:`run:${id}`,child_session_id:`session:${id}`});return {parentWorkspace:workspace,parentPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"]}),signal:new AbortController().signal,link,spec:SubagentSpecSchema.parse({subagent_id:link.subagent_id,parent_run_id:link.parent_run_id,name:"isolated-coder",provider_key:"parent",role_prompt_version:"fixture.v1",role_prompt_hash:sha("role"),tool_allowlist:["read_file","preview_patch","commit_patch","run_test"],context_scope:"isolated",budget:{max_steps:4,max_tokens:10_000},depth:1})};}
async function sourceOracle(source:string){return {head:(await command(source,["rev-parse","HEAD"])).trim(),index:sha(await readFile(join(source,".git","index"))),status:await command(source,["status","--porcelain=v1","-z"]),value:await readFile(join(source,"value.txt"),"utf8"),untracked:await readFile(join(source,"new.txt"),"utf8"),deleted:await readFile(join(source,"removed.txt")).catch(()=>null)};}
// These are actual native workspace-write proofs, not cross-platform claims.
describe.skipIf(process.platform!=="darwin")("TEAM-100 private dirty-baseline worktrees",()=>{
 it("copies staged/unstaged/deleted/untracked bytes, keeps source HEAD/index/tree unchanged, and avoids parent Run capacity deadlock",async()=>{
  const f=await fixture(),before=await sourceOracle(f.source),parentLease=await f.coordinator.acquireWorkspace(f.workspace,{holderId:"run:parent",kind:"run"});
  const first=await f.control.prepare(request(f.workspace));const second=await f.control.prepare(request(f.workspace,"two"));
  expect(first.workspace.real_root).not.toBe(second.workspace.real_root);expect(first.workspace.project_id).toBe(f.workspace.project_id);expect(first.permissionPolicy.preset.sandbox_mode).toBe("workspace-write");
  for(const child of [first,second]){expect(await readFile(join(child.workspace.real_root,"value.txt"),"utf8")).toBe(before.value);expect(await readFile(join(child.workspace.real_root,"new.txt"),"utf8")).toBe(before.untracked);await expect(readFile(join(child.workspace.real_root,"removed.txt"))).rejects.toMatchObject({code:"ENOENT"});await expect(readFile(join(child.workspace.real_root,"node_modules","ignored.txt"))).rejects.toMatchObject({code:"ENOENT"});}
  await writeFile(join(first.workspace.real_root,"value.txt"),"CHILD CHANGED\n");await writeFile(join(first.workspace.real_root,"child-new.txt"),"NEW CHILD FILE\n");const diff=await f.control.inspect(first.binding.binding_id);expect(diff.changes.map(file=>file.path)).toEqual(["child-new.txt","value.txt"]);expect(diff.changes.find(file=>file.path==="value.txt")).toMatchObject({baseline_sha256:sha(before.value),current_sha256:sha("CHILD CHANGED\n")});
  expect(await sourceOracle(f.source)).toEqual(before);expect(f.coordinator.list().map(claim=>claim.kind)).toEqual(["run","subagent","subagent"]);
  first.release();second.release();parentLease.release();expect(f.coordinator.list()).toEqual([]);expect(await readFile(join(first.workspace.real_root,"value.txt"),"utf8")).toBe("CHILD CHANGED\n");
  const repeated=await f.control.prepare(request(f.workspace));expect(repeated.binding).toEqual(first.binding);expect(await readFile(join(repeated.workspace.real_root,"value.txt"),"utf8")).toBe("CHILD CHANGED\n");repeated.release();
  const journal=new WorkbenchJournal(join(f.root,"profile","agent-worktrees","events"));await journal.initialize();const receipt=await journal.inspect("workspace:run:one");expect(receipt.state).toBe("completed");expect(JSON.stringify(receipt)).not.toContain(f.source);expect(JSON.stringify(receipt)).not.toContain("STAGED+UNSTAGED");
 });
 it("never invokes a source smudge filter or hook while generating the baseline",async()=>{
  const f=await fixture();await writeFile(join(f.source,".gitattributes"),"value.txt filter=unsafe\n");await command(f.source,["config","filter.unsafe.smudge",`touch '${join(f.root,"SHOULD_NOT_EXIST")}'`]);await writeFile(join(f.source,".git","hooks","post-checkout"),`#!/bin/sh\ntouch '${join(f.root,"HOOK_SHOULD_NOT_EXIST")}'\n`,{mode:0o700});const child=await f.control.prepare(request(f.workspace));child.release();await expect(readFile(join(f.root,"SHOULD_NOT_EXIST"))).rejects.toMatchObject({code:"ENOENT"});await expect(readFile(join(f.root,"HOOK_SHOULD_NOT_EXIST"))).rejects.toMatchObject({code:"ENOENT"});
 });
 it.each(["symlink","hardlink","private","oversize"] as const)("rejects %s bytes before making a child tree",async kind=>{
  const f=await fixture();if(kind==="symlink")await symlink(join(f.source,"value.txt"),join(f.source,"unsafe.txt"));if(kind==="hardlink")await link(join(f.source,"value.txt"),join(f.source,"unsafe.txt"));if(kind==="private")await writeFile(join(f.source,".env"),"UNAUTHORIZED_SECRET");if(kind==="oversize")await writeFile(join(f.source,"huge.txt"),Buffer.alloc(MAX_AGENT_BASELINE_FILE_BYTES+1));const before=await sourceOracle(f.source);await expect(f.control.prepare(request(f.workspace))).rejects.toMatchObject({code:kind==="private"?"team_private_path_denied":kind==="oversize"?"team_baseline_too_large":"team_file_kind_unsupported"});expect(await readdir(join(f.root,"profile","agent-worktrees","trees"))).toEqual([]);expect(await sourceOracle(f.source)).toEqual(before);
 });
 it.each([".ENV",".npmrc",".ssh/id_rsa","credentials.json","credential.pem"])("applies the real read_file sensitive boundary to %s before creation",async path=>{const f=await fixture();await mkdir(join(f.source,path,".."),{recursive:true});await writeFile(join(f.source,path),"SYNTHETIC PRIVATE CONTENT");const before=await sourceOracle(f.source);await expect(f.control.prepare(request(f.workspace))).rejects.toMatchObject({code:"team_private_path_denied"});expect(await readdir(join(f.root,"profile","agent-worktrees","trees"))).toEqual([]);expect(await sourceOracle(f.source)).toEqual(before);});
 it("rejects an unresolved index and both denied/read-only parent authority",async()=>{
  const f=await fixture();const oid=(await command(f.source,["rev-parse","HEAD:value.txt"])).trim();
  // Real index conflict records are written through Git plumbing, not mocked metadata.
  const conflict=`100644 ${oid} 1\tconflict.txt\n100644 ${oid} 2\tconflict.txt\n`;
  await new Promise<void>((resolve,reject)=>{import("node:child_process").then(({spawn})=>{const child=spawn(git,["update-index","--index-info"],{cwd:f.source,stdio:["pipe","ignore","pipe"]});child.stdin.end(conflict);child.on("exit",code=>code===0?resolve():reject(new Error("fixture conflict failed")));child.on("error",reject);}).catch(reject);});
  await expect(f.control.prepare(request(f.workspace))).rejects.toMatchObject({code:"team_index_conflict"});
  const readonly={...request(f.workspace,"readonly"),parentPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["read-only"]})};await expect(f.control.prepare(readonly)).rejects.toMatchObject({code:"team_write_permission_denied"});
  await expect(f.control.prepare(request({...f.workspace,capabilities:{...f.workspace.capabilities,commit_patch:false}},"cap"))).rejects.toMatchObject({code:"team_write_permission_denied"});expect(await readdir(join(f.root,"profile","agent-worktrees","trees"))).toEqual([]);
 });
 it("retains an unknown preparation and refuses automatic replay after actual source drift",async()=>{
  const f=await fixture();const control=await SubagentWorktreeController.create({profileRoot:join(f.root,"drift-profile"),workspaceCoordinator:f.coordinator,faultInjector:async phase=>{if(phase==="after_copy")await writeFile(join(f.source,"value.txt"),"EXTERNAL USER EDIT\n");}});const input=request(f.workspace,"drift");await expect(control.prepare(input)).rejects.toMatchObject({code:"team_workspace_effect_unknown"});expect(await readdir(join(f.root,"drift-profile","agent-worktrees","trees"))).toHaveLength(1);expect(await readFile(join(f.source,"value.txt"),"utf8")).toBe("EXTERNAL USER EDIT\n");await expect(control.prepare(input)).rejects.toMatchObject({code:"team_workspace_effect_unknown"});const journal=new WorkbenchJournal(join(f.root,"drift-profile","agent-worktrees","events"));await journal.initialize();expect((await journal.inspect("workspace:run:drift")).state).toBe("unknown");expect(f.coordinator.list()).toEqual([]);
 });
 it("rejects blocked baseline reads and cancellation without a filesystem effect",async()=>{const f=await fixture();const denied={...request(f.workspace,"read-policy"),parentPolicy:createEffectivePermissionPolicy({preset:BUILTIN_PERMISSION_PRESETS["full-write"],rules:[{rule_id:"deny-read",priority:1,when:{tool:"read_file",side_effect:"read"},then:"deny",explanation:"No baseline read"}]})};await expect(f.control.prepare(denied)).rejects.toMatchObject({code:"team_baseline_read_denied"});const cancelled={...request(f.workspace,"cancelled"),signal:AbortSignal.abort()};await expect(f.control.prepare(cancelled)).rejects.toMatchObject({code:"team_workspace_cancelled"});expect(await readdir(join(f.root,"profile","agent-worktrees","trees"))).toEqual([]);});
});
