import {createHash} from "node:crypto";
import {constants} from "node:fs";
import {chmod,lstat,mkdir,open,readFile,realpath,unlink,writeFile} from "node:fs/promises";
import {dirname,isAbsolute,join,relative,resolve,sep} from "node:path";
import {z} from "zod";
import {createEffectivePermissionPolicy,createManagedWorkspaceHandle,isSensitiveWorkspacePath,PolicyEngine,probeNativeSandbox,runBoundedProcess,type ResolvedSubagentWorkspace,type SubagentWorkspaceRequest} from "@tracegraph/core";
import {SubagentWorkspaceBindingSchema,WorkspaceHandleSchema,type SubagentWorkspaceBinding,type WorkspaceHandle} from "@tracegraph/contracts";
import {atomicPrivateJson,privateDirectory} from "./local-profile.js";
import {WorkbenchJournal,workbenchError} from "./workbench-journal.js";
import type {WorkspaceCoordinator} from "./workspace-coordinator.js";
export const MAX_AGENT_BASELINE_FILES=2000,MAX_AGENT_BASELINE_FILE_BYTES=1024*1024,MAX_AGENT_BASELINE_TOTAL_BYTES=16*1024*1024;
const GIT=process.platform==="darwin"?"/Library/Developer/CommandLineTools/usr/bin/git":process.platform==="win32"?"git.exe":"/usr/bin/git";
const sha=(value:string|Uint8Array)=>`sha256:${createHash("sha256").update(value).digest("hex")}` as const;
const FileSchema=z.object({path:z.string().min(1).max(4096),sha256:z.string().regex(/^sha256:[a-f0-9]{64}$/u).nullable(),executable:z.boolean(),bytes:z.number().int().nonnegative()}).strict();
const ManifestSchema=z.object({binding:SubagentWorkspaceBindingSchema,workspace:WorkspaceHandleSchema,parent_handle_id:z.string(),files:z.array(FileSchema).max(MAX_AGENT_BASELINE_FILES)}).strict();
type Entry=z.infer<typeof FileSchema> & {content?:Buffer};
const within=(root:string,path:string)=>{const rel=relative(root,path);return rel===""||(!isAbsolute(rel)&&rel!==".."&&!rel.startsWith(`..${sep}`));};
const privatePath=(path:string)=>isSensitiveWorkspacePath(path)||path.toLowerCase().split("/").some(part=>[".git","node_modules",".tracegraph",".outlive"].includes(part));
interface Snapshot {head:string;indexHash:`sha256:${string}`;treeHash:`sha256:${string}`;files:Entry[];}
/** Host-private authority; generated roots are never accepted from model or transport DTOs. */
export class SubagentWorktreeController {
 readonly #root:string;readonly #coordinator:WorkspaceCoordinator;readonly #journal:WorkbenchJournal;
 readonly #faultInjector:((phase:"after_source_snapshot"|"after_copy")=>Promise<void>)|undefined;
 readonly #active=new Map<string,Promise<ResolvedSubagentWorkspace>>();#closed=false;
 private constructor(root:string,coordinator:WorkspaceCoordinator,faultInjector:((phase:"after_source_snapshot"|"after_copy")=>Promise<void>)|undefined){this.#root=root;this.#coordinator=coordinator;this.#faultInjector=faultInjector;this.#journal=new WorkbenchJournal(join(root,"events"));}
 static async create(input:{profileRoot:string;workspaceCoordinator:WorkspaceCoordinator;/** Trusted persistence fault seam; never accepted from transport or model input. */faultInjector?:(phase:"after_source_snapshot"|"after_copy")=>Promise<void>}){const root=await privateDirectory(join(input.profileRoot,"agent-worktrees"));for(const name of ["trees","baselines","manifests"])await privateDirectory(join(root,name));const value=new SubagentWorktreeController(root,input.workspaceCoordinator,input.faultInjector);await value.#journal.initialize();return value;}
 async prepare(request:SubagentWorkspaceRequest):Promise<ResolvedSubagentWorkspace>{
  if(this.#closed)throw workbenchError("team_workspace_closed","Child workspace admission is closed");
  const id=`child:${createHash("sha256").update(request.link.child_run_id).digest("hex")}`;
  const previous=this.#active.get(id);if(previous)return previous;
  const operation=this.#prepare(request,id);this.#active.set(id,operation);
  try{return await operation;}catch(error){this.#active.delete(id);throw error;}
 }
 async #prepare(request:SubagentWorkspaceRequest,id:string):Promise<ResolvedSubagentWorkspace>{
  const parent=request.parentWorkspace;
  if(parent.workspace_kind!=="managed_local"||!parent.capabilities.commit_patch||request.parentPolicy.preset.sandbox_mode==="read-only")throw workbenchError("team_write_permission_denied","The parent workspace does not permit a writable child",403);
  if(within(parent.real_root,this.#root)||within(this.#root,parent.real_root))throw workbenchError("team_workspace_not_disjoint","The private child workspace store must be separate from the source",403);
  const policy=createEffectivePermissionPolicy({preset:{...request.parentPolicy.preset,key:"custom",label:"Isolated child",sandbox_mode:"workspace-write"},rules:request.parentPolicy.host_rules,projectRules:request.parentPolicy.project_rules});
  const sandbox=await probeNativeSandbox({mode:"workspace-write",workspaceRoot:parent.real_root});if(sandbox.enforcement!=="full")throw workbenchError("team_workspace_sandbox_unavailable","The native isolated-write sandbox is unavailable",503);
  const name=id.slice(6),tree=join(this.#root,"trees",name),baseline=join(this.#root,"baselines",name),manifestFile=join(this.#root,"manifests",`${name}.json`);
  const binding=await this.#journal.once(`workspace:${request.link.child_run_id}`,"team.workspace.prepare",{link:request.link,profile:request.spec.name,parent_handle_id:parent.handle_id,policy_digest:request.parentPolicy.policy_digest},async()=>{
   this.#check(request.signal);const source=await realpath(parent.real_root);if(source!==parent.real_root)throw workbenchError("team_workspace_root_changed","The parent workspace identity changed");
   const snapshot=await this.#snapshot(parent,request);await this.#faultInjector?.("after_source_snapshot");let sideEffect=false;
   try{
    // No checkout means repository-defined smudge filters cannot execute. All
    // baseline bytes below come from bounded, policy-checked source reads.
    this.#check(request.signal);sideEffect=true;await this.#git(source,["worktree","add","--detach","--no-checkout","--",tree,snapshot.head],request.signal);
    await privateDirectory(tree);await privateDirectory(baseline);
    for(const entry of snapshot.files){this.#check(request.signal);const destination=await this.#destination(tree,entry.path),saved=await this.#destination(baseline,entry.path);if(entry.content){await mkdir(dirname(destination),{recursive:true,mode:0o700});await this.#writeOrdinary(destination,entry.content);await chmod(destination,entry.executable?0o700:0o600);await mkdir(dirname(saved),{recursive:true,mode:0o700});await this.#writeOrdinary(saved,entry.content);}else await unlink(destination).catch(error=>{if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;});}
    await this.#faultInjector?.("after_copy");
    const after=await this.#snapshot(parent,request);if(after.head!==snapshot.head||after.indexHash!==snapshot.indexHash||after.treeHash!==snapshot.treeHash)throw workbenchError("team_baseline_changed","The source changed while capturing the child baseline");
    const result=SubagentWorkspaceBindingSchema.parse({binding_id:id,source_head:snapshot.head,source_index_hash:snapshot.indexHash,source_tree_hash:snapshot.treeHash,baseline_digest:sha(JSON.stringify([snapshot.head,snapshot.indexHash,snapshot.treeHash]))});
    const workspace=await createManagedWorkspaceHandle({projectId:parent.project_id,root:tree});
    // Capabilities are copied from the admitted parent; no child gets a new capability.
    workspace.capabilities={...parent.capabilities};
    await atomicPrivateJson(manifestFile,{binding:result,workspace,parent_handle_id:parent.handle_id,files:snapshot.files.map(({content:_content,...file})=>file)});
    return result;
   }catch(error){if(sideEffect)throw workbenchError("team_workspace_effect_unknown","Child workspace preparation did not complete. Retain and review the generated worktree before retrying");throw error;}
  });
  const manifest=ManifestSchema.parse(JSON.parse(await readFile(manifestFile,"utf8")));
  if(JSON.stringify(manifest.binding)!==JSON.stringify(binding)||manifest.parent_handle_id!==parent.handle_id||await realpath(manifest.workspace.real_root)!==tree||manifest.workspace.project_id!==parent.project_id)throw workbenchError("team_workspace_binding_invalid","The retained child workspace binding is invalid");
  const lease=await this.#coordinator.acquireWorkspace(manifest.workspace,{holderId:request.link.child_run_id,kind:"subagent",signal:request.signal});let released=false;
  return {workspace:manifest.workspace,permissionPolicy:policy,binding,release:()=>{if(released)return;released=true;lease.release();this.#active.delete(id);}};
 }
 #check(signal:AbortSignal){if(this.#closed||signal.aborted)throw workbenchError("team_workspace_cancelled","Child workspace preparation was cancelled");}
 async #git(root:string,args:string[],signal?:AbortSignal){const result=await runBoundedProcess(GIT,["-C",root,"-c","core.hooksPath=/dev/null","-c","core.fsmonitor=false","-c","diff.external=","-c","protocol.ext.allow=never",...args],{cwd:root,timeoutMs:30000,maxOutputBytes:2*1024*1024,...(signal?{signal}:{})});if(result.exitCode!==0||result.truncated||result.timedOut||result.aborted)throw workbenchError("team_git_unavailable","Git could not complete the bounded child workspace operation",400);return result.stdout;}
 async #snapshot(workspace:WorkspaceHandle,request:SubagentWorkspaceRequest):Promise<Snapshot>{
  const root=workspace.real_root,metadata=await lstat(join(root,".git")).catch(()=>{throw workbenchError("team_git_required","Writable children require an existing Git repository",400);});if(!metadata.isDirectory()||metadata.isSymbolicLink())throw workbenchError("team_source_worktree_unsupported","This slice requires an ordinary Git repository with local metadata",400);
  if(await realpath((await this.#git(root,["rev-parse","--show-toplevel"],request.signal)).trim())!==root)throw workbenchError("team_source_worktree_unsupported","Git workspace metadata points outside the admitted source",400);
  const head=(await this.#git(root,["rev-parse","--verify","HEAD"],request.signal)).trim();if(!/^[a-f0-9]{40,64}$/u.test(head))throw workbenchError("team_git_required","An existing Git HEAD is required",400);
  const listing=await this.#git(root,["ls-files","--stage","-z"],request.signal),headListing=await this.#git(root,["ls-tree","-r","-z","HEAD"],request.signal),untracked=await this.#git(root,["ls-files","--others","--exclude-standard","-z"],request.signal);
  const paths=new Set<string>();for(const row of listing.split("\0").filter(Boolean)){const match=/^(\d+) [a-f0-9]+ (\d+)\t(.+)$/su.exec(row);if(!match||match[2]!=="0")throw workbenchError("team_index_conflict","Resolve Git index conflicts before starting a writable child",409);if(!["100644","100755"].includes(match[1]!))throw workbenchError("team_file_kind_unsupported","Submodules and symbolic links are not supported in a writable baseline",400);paths.add(match[3]!);}
  for(const row of headListing.split("\0").filter(Boolean)){const match=/^(\d+) blob [a-f0-9]+\t(.+)$/su.exec(row);if(!match||!["100644","100755"].includes(match[1]!))throw workbenchError("team_file_kind_unsupported","Submodules and symbolic links are not supported in a writable baseline",400);paths.add(match[2]!);}
  for(const path of untracked.split("\0").filter(Boolean))paths.add(path);if(paths.size>MAX_AGENT_BASELINE_FILES)throw workbenchError("team_baseline_too_large","The authorized baseline exceeds the bounded file count",413);
  const engine=PolicyEngine.fromEffective(request.parentPolicy),files:Entry[]=[];let total=0;
  for(const path of [...paths].sort()){
   this.#check(request.signal);if(!path||isAbsolute(path)||path.split("/").includes("..")||/[\0-\x1f\x7f\\]/u.test(path)||privatePath(path))throw workbenchError("team_private_path_denied","Private or unsafe paths cannot be included in a writable baseline",403);
   const decision=engine.evaluate({toolName:"read_file",sideEffect:"read",capabilityAllowed:workspace.capabilities.read,path});if(decision.kind!=="allow")throw workbenchError("team_baseline_read_denied","The parent's policy does not permit reading the complete baseline",403);
   const value=await this.#read(root,path);if(value){total+=value.content.length;if(total>MAX_AGENT_BASELINE_TOTAL_BYTES)throw workbenchError("team_baseline_too_large","The authorized baseline exceeds the bounded total bytes",413);files.push({path,sha256:sha(value.content),executable:value.executable,bytes:value.content.length,content:value.content});}else files.push({path,sha256:null,executable:false,bytes:0});
  }
  const index=await this.#readIndex(root);return {head,indexHash:sha(index),treeHash:sha(JSON.stringify(files.map(({content:_content,...entry})=>entry))),files};
 }
 async #readIndex(root:string){const path=join(root,".git","index"),info=await lstat(path);if(!info.isFile()||info.isSymbolicLink()||info.nlink!==1||info.size>2*1024*1024)throw workbenchError("team_index_unsupported","The source Git index is not a bounded ordinary file");const handle=await open(path,constants.O_RDONLY|(process.platform==="win32"?0:constants.O_NOFOLLOW));try{const before=await handle.stat();if(before.dev!==info.dev||before.ino!==info.ino||before.nlink!==1)throw workbenchError("team_baseline_changed","The source Git index changed identity");const buffer=Buffer.alloc(2*1024*1024+1);let size=0;while(size<buffer.length){const read=await handle.read(buffer,size,buffer.length-size,size);if(!read.bytesRead)break;size+=read.bytesRead;}const after=await handle.stat();if(size>2*1024*1024||before.size!==after.size||before.mtimeMs!==after.mtimeMs||before.ctimeMs!==after.ctimeMs)throw workbenchError("team_baseline_changed","The source Git index changed while reading");return buffer.subarray(0,size);}finally{await handle.close();}}
 async #writeOrdinary(path:string,content:Buffer){const handle=await open(path,constants.O_WRONLY|constants.O_CREAT|(process.platform==="win32"?0:constants.O_NOFOLLOW),0o600);try{const info=await handle.stat();if(!info.isFile()||info.nlink!==1)throw workbenchError("team_file_kind_unsupported","The child baseline destination changed identity",403);await handle.truncate(0);await handle.writeFile(content);}finally{await handle.close();}}
 async #read(root:string,path:string):Promise<{content:Buffer;executable:boolean}|undefined>{
  let current=root;for(const part of path.split("/")){current=join(current,part);const info=await lstat(current).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});if(!info)return undefined;if(info.isSymbolicLink())throw workbenchError("team_file_kind_unsupported","Symbolic links are not supported in a writable baseline",400);}
  const info=await lstat(current);if(!info.isFile()||info.nlink!==1)throw workbenchError("team_file_kind_unsupported","Only single-link ordinary files can be copied into a writable baseline",400);if(info.size>MAX_AGENT_BASELINE_FILE_BYTES)throw workbenchError("team_baseline_too_large","A baseline file exceeds one MiB",413);
  if(await realpath(current)!==current||!within(root,current))throw workbenchError("team_file_kind_unsupported","A baseline file escaped its authorized root",403);
  const handle=await open(current,constants.O_RDONLY|(process.platform==="win32"?0:constants.O_NOFOLLOW));try{const before=await handle.stat();if(before.ino!==info.ino||before.dev!==info.dev||before.nlink!==1||!before.isFile())throw workbenchError("team_baseline_changed","A baseline file changed identity");const buffer=Buffer.alloc(MAX_AGENT_BASELINE_FILE_BYTES+1);let size=0;while(size<buffer.length){const result=await handle.read(buffer,size,buffer.length-size,size);if(!result.bytesRead)break;size+=result.bytesRead;}if(size>MAX_AGENT_BASELINE_FILE_BYTES)throw workbenchError("team_baseline_too_large","A baseline file exceeds one MiB",413);const after=await handle.stat();if(after.size!==before.size||after.mtimeMs!==before.mtimeMs||after.ctimeMs!==before.ctimeMs)throw workbenchError("team_baseline_changed","A baseline file changed while reading");return {content:buffer.subarray(0,size),executable:Boolean(info.mode&0o111)};}finally{await handle.close();}
 }
 async #destination(root:string,path:string){const target=resolve(root,path);if(!within(root,target)||target===root)throw workbenchError("team_file_kind_unsupported","The child baseline path is unsafe",403);let current=root;for(const part of path.split("/").slice(0,-1)){current=join(current,part);const info=await lstat(current).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});if(info&&(!info.isDirectory()||info.isSymbolicLink()))throw workbenchError("team_file_kind_unsupported","The child baseline parent is not an ordinary directory",403);}const file=await lstat(target).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});if(file&&(!file.isFile()||file.isSymbolicLink()||file.nlink!==1))throw workbenchError("team_file_kind_unsupported","The child baseline destination is not an ordinary file",403);return target;}
 async inspect(bindingId:string):Promise<{binding:SubagentWorkspaceBinding;changes:Array<{path:string;baseline_sha256:string|null;current_sha256:string|null}>}>{const id=SubagentWorkspaceBindingSchema.shape.binding_id.parse(bindingId);if(!/^child:[a-f0-9]{64}$/u.test(id))throw workbenchError("team_workspace_binding_invalid","Invalid child workspace binding");const manifest=ManifestSchema.parse(JSON.parse(await readFile(join(this.#root,"manifests",`${id.slice(6)}.json`),"utf8")));const expected=join(this.#root,"trees",id.slice(6));if(manifest.binding.binding_id!==id||await realpath(manifest.workspace.real_root)!==expected)throw workbenchError("team_workspace_binding_invalid","Invalid child workspace identity");const original=new Map(manifest.files.map(file=>[file.path,file.sha256]));const candidates=new Set([...original.keys(),...(await this.#git(expected,["ls-files","--others","--exclude-standard","-z"])).split("\0").filter(Boolean)]);if(candidates.size>MAX_AGENT_BASELINE_FILES)throw workbenchError("team_baseline_too_large","The child diff exceeds the bounded file count",413);const changes:Array<{path:string;baseline_sha256:string|null;current_sha256:string|null}>=[];let total=0;for(const path of [...candidates].sort()){if(!path||isAbsolute(path)||path.split("/").includes("..")||/[\0-\x1f\x7f\\]/u.test(path)||privatePath(path))throw workbenchError("team_private_path_denied","The child diff contains an unsafe path",403);const current=await this.#read(expected,path),digest=current?sha(current.content):null;total+=current?.content.length??0;if(total>MAX_AGENT_BASELINE_TOTAL_BYTES)throw workbenchError("team_baseline_too_large","The child diff exceeds the bounded total bytes",413);const baseline=original.get(path)??null;if(digest!==baseline)changes.push({path,baseline_sha256:baseline,current_sha256:digest});}return {binding:manifest.binding,changes};}
 close(){this.#closed=true;}
}
