import {execFile} from "node:child_process";
import {createHash} from "node:crypto";
import {mkdir,mkdtemp,readFile,readdir,rm,writeFile} from "node:fs/promises";
import {createServer} from "node:http";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {promisify} from "node:util";
import {describe,expect,it} from "vitest";
import {ConfigurableModelAdapter,SharedRunBudget,type BudgetCheckpoint,type ModelAdapter,type RunProjection} from "@tracegraph/core";
import {BUILTIN_PERMISSION_PRESETS,SubagentStartedDataSchema,WorkbenchSettingsValuesSchema} from "@tracegraph/contracts";
import {createHostComposition} from "./composition/host-composition.js";
import {budgetedFixtureModel} from "../test-support/budgeted-fixture-model.js";
const runFile=promisify(execFile),git=process.platform==="darwin"?"/Library/Developer/CommandLineTools/usr/bin/git":"/usr/bin/git";
const hash=(value:string|Uint8Array)=>`sha256:${createHash("sha256").update(value).digest("hex")}`;
const commandManifest=JSON.stringify({version:1,commands:{verify:{executable:"node",args:["verify.mjs"]}}});
const done=(id:string)=>({decision_id:id,kind:"finish",public_reason:"The isolated result is ready for review",evidence_refs:[],risk:"none",final_answer:"Retained isolated result ready for review"});
const spawn=(id:string)=>({action_id:`spawn:${id}`,tool_name:"spawn_subagent",arguments:{profile_name:"isolated-coder",task_packet:{task:`Edit child ${id}`},context_scope:"isolated"}});
async function fixture(model:ModelAdapter,readonly=false){const root=await mkdtemp(join(tmpdir(),"outlive-team-runtime-")),source=join(root,"source");await mkdir(source);const command=async(args:string[])=>(await runFile(git,args,{cwd:source})).stdout;await command(["init","-q"]);await command(["config","user.email","fixture@example.invalid"]);await command(["config","user.name","Fixture"]);await writeFile(join(source,"value.txt"),"HEAD\n");await command(["add","--","value.txt"]);await writeFile(join(source,"outlive.commands.json"),commandManifest);await writeFile(join(source,"verify.mjs"),'import {readFileSync,writeFileSync} from "node:fs";import assert from "node:assert/strict";const text=readFileSync("value.txt","utf8");assert.match(text,/^CHILD [AB]\\n$/);writeFileSync("command-result.txt","passed:"+text);console.log("Actual child assertion passed");\n');await command(["add","--","outlive.commands.json","verify.mjs"]);await command(["commit","-qm","initial"]);await writeFile(join(source,"value.txt"),"STAGED\n");await command(["add","--","value.txt"]);await writeFile(join(source,"value.txt"),"STAGED+UNSTAGED\n");await writeFile(join(source,"untracked.txt"),"USER NEW FILE\n");
 const composition=await createHostComposition({profileRoot:root,dataDir:join(root,"data"),sessionDir:join(root,"sessions"),permissionConfigPath:join(root,"permission.json"),environment:{TRACEGRAPH_PERMISSION_PRESET:readonly?"read-only":"full-write"},runtimeModel:model.supportsRequestBudget===true?model:budgetedFixtureModel(model),useEnvironmentModel:false,nativePicker:false,nativePermissionPrompts:false,admission:"workspace",settings:WorkbenchSettingsValuesSchema.parse({memory:{memory_recall:false,experience_recall:false},developer:{max_parallel_runs:1}})});const project=await composition.registerProject(source,"read_write");project.workspace.capabilities.index=false;
 const oracle=async()=>({head:(await command(["rev-parse","HEAD"])).trim(),index:hash(await readFile(join(source,".git","index"))),status:await command(["status","--porcelain=v1","-z"]),value:await readFile(join(source,"value.txt"),"utf8"),untracked:await readFile(join(source,"untracked.txt"),"utf8")});
 return {root,source,composition,project,oracle,async close(){await composition.close();await rm(root,{recursive:true,force:true});}};
}
async function settle(f:Awaited<ReturnType<typeof fixture>>,runId:string,approve=false){const approved=new Set<string>();const deadline=Date.now()+10_000;while(Date.now()<deadline){const projection=await f.composition.runtime.getProjection(runId);for(const child of projection.subagents.items){const value=await f.composition.runtime.getProjection(child.link.child_run_id).catch(error=>{if(error.code==="run_not_found")return undefined;throw error;});if(approve&&value?.pending_approval&&!approved.has(value.pending_approval.approval_id)){const pending=value.pending_approval;approved.add(pending.approval_id);await f.composition.runtime.approve({type:"approve",command_id:`approve:${pending.approval_id}`,project_id:value.project_id,run_id:value.run_id,approval_id:pending.approval_id,action_id:pending.action_id});}}if(["completed","failed","cancelled"].includes(projection.status))return projection;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error(`Run did not settle: ${JSON.stringify((await f.composition.runtime.getProjection(runId)).timeline.map(event=>({type:event.type,data:event.data})))}`);}
describe.skipIf(process.platform!=="darwin")("actual standard Host isolated-coder Runtime",()=>{
 it("uses two real child patch receipts, one shared budget and independent retained trees without source writes or root-slot deadlock",async()=>{
  let parentCalls=0;const childCalls=new Map<string,number>(),wireRequests:string[]=[];const server=createServer(async(req,res)=>{let raw="";for await(const chunk of req)raw+=chunk;wireRequests.push(raw);const wire=JSON.parse(raw) as {messages:Array<{content:string}>};const child=wire.messages.some(message=>typeof message.content==="string"&&message.content.includes("Host-provided isolated worktree"));let decision:unknown;if(child){const context=JSON.parse(wire.messages[1]!.content).context as string;const match=/Edit child ([AB])/.exec(context);if(!match)throw new Error("Controlled child task missing from Context: "+context.slice(0,700));const id=match[1]!,count=(childCalls.get(id)??0)+1;childCalls.set(id,count);decision=count===1?{decision_id:`patch:${id}`,kind:"tool_call",public_reason:"Preview a scoped edit in the child baseline",evidence_refs:[],risk:"low",tool_call:{action_id:`patch:${id}`,tool_name:"preview_patch",arguments:{path:"value.txt",expected:"STAGED+UNSTAGED",replacement:`CHILD ${id}`}}}:count===2?{decision_id:`discover:${id}`,kind:"tool_call",public_reason:"Discover the existing child verification command",evidence_refs:[],risk:"low",tool_call:{action_id:`discover:${id}`,tool_name:"discover_project_commands",arguments:{path:"."}}}:count===3?{decision_id:`verify:${id}`,kind:"tool_call",public_reason:"Run the hash-bound child verification",evidence_refs:[],risk:"low",tool_call:{action_id:`verify:${id}`,tool_name:"run_project_command",arguments:{path:"outlive.commands.json",command:"verify",expected_manifest_sha256:hash(commandManifest),timeout_ms:1000}}}:done(`done:${id}`);}else{parentCalls++;decision=parentCalls===1?{decision_id:"spawn:both",kind:"tool_call",public_reason:"Delegate independent isolated edits",evidence_refs:[],risk:"low",tool_calls:[spawn("A"),spawn("B")]}:done("parent:done");}res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(decision)}}],usage:{prompt_tokens:500,completion_tokens:5,total_tokens:505}}));});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error();const model=new ConfigurableModelAdapter({resolveCredential:async()=>"isolated-local-provider-key"});model.configure({provider:"custom",protocol:"openai-chat-completions",baseUrl:`http://127.0.0.1:${address.port}/v1`,model:"team-fixture",credentialRef:"${secret:ISOLATED_TEAM_KEY}"});const f=await fixture(model);const checkpoints:BudgetCheckpoint[]=[];const budget=new SharedRunBudget({identity:"goal:team-budget:1",limits:{max_tokens:200_000,max_time_ms:20_000},checkpoint:async value=>{checkpoints.push(value);}});
  try{const before=await f.oracle();const input={command_id:"command:team-patches",project_id:f.project.workspace.project_id,task:"Delegate two isolated edits",mode:"execute" as const};const admission=await f.composition.conversationControl.prepare(input,f.project.workspace,{requestBudget:budget,backgroundModelDerivation:false});const lease=await f.composition.workspaceCoordinator.acquireWorkspace(f.project.workspace,{holderId:"parent-root-slot",kind:"run"});const started=await admission.start({...input,workspace:f.project.workspace});const completed=await settle(f,started.run_id,true);lease.release();expect(completed.status).toBe("completed");for(const child of completed.subagents.items){const projection=await f.composition.runtime.getProjection(child.link.child_run_id);if(projection.status!=="completed")throw new Error(JSON.stringify({status:projection.status,code:projection.failure_code,task:projection.task,child_value:await readFile(join(f.root,"agent-worktrees","trees",SubagentStartedDataSchema.parse(completed.timeline.find(event=>event.type==="subagent.started"&&(event.data.link as {child_run_id:string})?.child_run_id===child.link.child_run_id)!.data).spec.workspace_binding!.binding_id.slice(6),"value.txt"),"utf8"),source_value:await readFile(join(f.source,"value.txt"),"utf8"),events:projection.timeline.slice(-8).map(event=>({type:event.type,summary:event.summary,code:event.data.code}))}));}expect(parentCalls).toBe(2);expect(childCalls).toEqual(new Map([["A",4],["B",4]]));expect(budget.snapshot()).toMatchObject({request_count:10,charged_tokens:5050,held_tokens:0});expect(await f.oracle()).toEqual(before);expect(completed.subagents.items).toHaveLength(2);const bindings=completed.subagents.items.map(child=>SubagentStartedDataSchema.parse(completed.timeline.find(event=>event.type==="subagent.started"&&(event.data.link as {child_run_id:string})?.child_run_id===child.link.child_run_id)!.data).spec.workspace_binding!);expect(new Set(bindings.map(binding=>binding.binding_id)).size).toBe(2);
   for(const child of completed.subagents.items){const projection=await f.composition.runtime.getProjection(child.link.child_run_id);expect(projection.status).toBe("completed");expect(projection.timeline.some(event=>event.type==="patch.applied")).toBe(true);expect(projection.timeline.find(event=>event.type==="run.created")?.data).toMatchObject({goal_budget:budget.identity,workspace_binding:SubagentStartedDataSchema.parse(completed.timeline.find(event=>event.type==="subagent.started"&&(event.data.link as {child_run_id:string})?.child_run_id===child.link.child_run_id)!.data).spec.workspace_binding});expect(projection.timeline.find(event=>event.type==="permission.configured")?.data).toMatchObject({permission:{sandbox_mode:"workspace-write"}});const diff=await f.composition.subagentWorktrees!.inspect(SubagentStartedDataSchema.parse(completed.timeline.find(event=>event.type==="subagent.started"&&(event.data.link as {child_run_id:string})?.child_run_id===child.link.child_run_id)!.data).spec.workspace_binding!.binding_id);expect(diff.changes.map(file=>file.path)).toEqual(["command-result.txt","value.txt"]);expect(diff.changes.find(file=>file.path==="value.txt")?.baseline_sha256).toBe(hash(before.value));expect(projection.timeline.some(event=>event.type==="tool.completed"&&event.data.receipt && (event.data.receipt as {tool_name?:string}).tool_name==="run_project_command")).toBe(true);}
   expect(new Set(checkpoints.filter(value=>value.phase==="reserved").map(value=>value.run_id))).toEqual(new Set([started.run_id,...completed.subagents.items.map(child=>child.link.child_run_id)]));expect(f.composition.workspaceCoordinator.list()).toEqual([]);expect(wireRequests).toHaveLength(10);expect(JSON.parse(wireRequests[0]!).messages[0].content).toContain("isolated-coder");for(const binding of bindings){const path=join(f.root,"agent-worktrees","trees",binding.binding_id.slice(6),"value.txt");expect(await readFile(path,"utf8")).toMatch(/^CHILD [AB]\n$/u);}
  }finally{budget.dispose();await f.close();server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
 },15_000);
 it("publishes a bounded compiled catalog but denies writable selection for a readonly parent before child creation",async()=>{let calls=0;const model:ModelAdapter={name:"readonly-fixture",async decide(){calls++;return calls===1?{decision_id:"readonly:spawn",kind:"tool_call",public_reason:"Attempt write role",evidence_refs:[],risk:"low",tool_call:spawn("A")}:done("readonly:done");}};const f=await fixture(model,true);try{const input={command_id:"readonly:run",project_id:f.project.workspace.project_id,task:"No parent write authority",mode:"execute" as const};const started=await f.composition.host.runSessions.startRun(input);const result=await settle(f,started.run_id);expect(result.subagents.items).toEqual([]);expect(result.timeline.some(event=>event.type==="subagent.started")).toBe(false);expect(JSON.stringify(result.timeline)).toMatch(/admitted parent does not permit/u);expect(await readdir(join(f.root,"agent-worktrees","trees"))).toEqual([]);expect(await readFile(join(f.source,"value.txt"),"utf8")).toBe("STAGED+UNSTAGED\n");}finally{await f.close();}});
});
