import {createHash,randomUUID} from "node:crypto";
import {constants} from "node:fs";
import {lstat,open,realpath,unlink} from "node:fs/promises";
import {join,resolve} from "node:path";
import {z} from "zod";
import {ArtifactStore} from "@tracegraph/core";
import {ArtifactRefSchema,IdentifierSchema,VisualRetentionSettingsSchema,VisualRetentionUpdateSchema,VisualEvidenceEntrySchema,VisualEvidenceQuerySchema,VisualEvidenceInventorySchema,VisualEvidencePinSchema,VisualEvidenceCleanupRequestSchema,VisualEvidenceCleanupResultSchema,VisualEvidenceCommandReceiptSchema,type ArtifactRef,type VisualRetentionSettings,type VisualRetentionUpdate,type VisualEvidenceEntry,type VisualEvidenceQuery,type VisualEvidencePin,type VisualEvidenceCleanupRequest,type VisualEvidenceCleanupResult,type VisualEvidenceCommandReceipt} from "@tracegraph/contracts";
import {atomicPrivateJson,privateDirectory} from "./local-profile.js";
import {WorkbenchJournal,workbenchError} from "./workbench-journal.js";

export interface VisualEvidenceContext {profileRoot:string;profileId:string;dataRoot:string;now?:()=>Date;automaticIntervalMs?:number;validateRunArtifact(ref:ArtifactRef):Promise<void>;}
export interface BrowserVisualRegistration {evidence_id:string;project_id:string;sha256:string;byte_length:number;captured_at:string;}
export interface VisualEvidenceRecorder {
 registerBrowser(input:BrowserVisualRegistration):Promise<void>;
 registerComputer(artifact:ArtifactRef):Promise<void>;
 registerRunCopy(evidenceId:string,artifact:ArtifactRef):Promise<void>;
}
const Stored=z.object({entry:VisualEvidenceEntrySchema,computer_artifact:ArtifactRefSchema.optional()}).strict().refine(value=>value.entry.source==="browser"?/^browser-evidence:[a-f0-9-]{36}$/u.test(value.entry.evidence_id)&&!value.computer_artifact:Boolean(value.computer_artifact&&value.entry.evidence_id===`computer-evidence:${value.computer_artifact.artifact_id}`&&value.computer_artifact.project_id==="computer:profile"&&/^computer:[a-f0-9]{64}$/u.test(value.computer_artifact.run_id)&&value.computer_artifact.content_hash===value.entry.sha256&&value.computer_artifact.byte_length===value.entry.byte_length&&value.computer_artifact.kind==="image/png"),"Capture provenance is invalid");
const State=z.object({inventory_revision:z.number().int().nonnegative().max(10_000),settings:VisualRetentionSettingsSchema,entries:z.array(Stored).max(10_000)}).strict();
type State=z.infer<typeof State>;type Stored=z.infer<typeof Stored>;
const hash=(bytes:Uint8Array)=>`sha256:${createHash("sha256").update(bytes).digest("hex")}`;
const fail=(code:string,message:string,status=409)=>workbenchError(code,message,status);
/** Only trusted capture seams register bytes. Public callers choose IDs, never paths. */
export class VisualEvidenceController implements VisualEvidenceRecorder {
 readonly #ctx:VisualEvidenceContext;readonly #journal:WorkbenchJournal;readonly #computer:ArtifactStore;readonly #runtime:ArtifactStore;
 #state:State;#projectionUnsettled=false;#queue:Promise<unknown>=Promise.resolve();#closed=false;#timer:ReturnType<typeof setInterval>|undefined;#ownerUpgradePauses=0;#ownerPending=0;
 private constructor(ctx:VisualEvidenceContext,state:State){this.#ctx=ctx;this.#state=state;this.#journal=new WorkbenchJournal(join(ctx.profileRoot,"visual-evidence-events"));this.#computer=new ArtifactStore(join(ctx.profileRoot,"computer-artifacts"));this.#runtime=new ArtifactStore(join(ctx.dataRoot,"artifacts"));}
 static async open(ctx:VisualEvidenceContext){IdentifierSchema.parse(ctx.profileId);if(await realpath(ctx.profileRoot)!==resolve(ctx.profileRoot)||await realpath(ctx.dataRoot)!==resolve(ctx.dataRoot))throw fail("visual_store_invalid","Visual evidence roots must be real private directories",503);await privateDirectory(join(ctx.profileRoot,"visual-evidence-events"));const path=join(ctx.profileRoot,"visual-evidence.json"),raw=await readSafe(path,8*1024*1024).catch(error=>{if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error;});const state=raw?State.parse(JSON.parse(raw.bytes.toString("utf8"))):{inventory_revision:0,settings:VisualRetentionSettingsSchema.parse({schema_version:"outlive.visual-retention.v1",profile_id:ctx.profileId,revision:0,updated_at:null,last_command_id:null,values:{retention_days:30,automatic_cleanup:true},legacy_policy:"retain-unregistered"}),entries:[]};if(state.settings.profile_id!==ctx.profileId)throw fail("visual_profile_mismatch","Visual evidence belongs to another profile",503);if(new Set(state.entries.map(value=>value.entry.evidence_id)).size!==state.entries.length)throw fail("visual_inventory_invalid","Visual evidence inventory contains duplicate identities",503);const self=new VisualEvidenceController(ctx,state);await self.#journal.initialize();await self.#verifyCheckpoint();self.#timer=setInterval(()=>{void self.#automatic().catch(()=>undefined);},ctx.automaticIntervalMs??3_600_000);self.#timer.unref();return self;}
 #now(){return (this.#ctx.now?.()??new Date()).toISOString();}
 #serial<T>(work:()=>Promise<T>):Promise<T>{if(this.#closed)return Promise.reject(fail("visual_closed","Visual evidence controller is closed",503));this.#ownerPending++;const operation=this.#queue.then(()=>{if(this.#closed)throw fail("visual_closed","Visual evidence controller is closed",503);if(this.#projectionUnsettled)throw fail("visual_projection_unknown","Visual evidence inventory needs read-only inspection before further changes",503);return work();}).finally(()=>{this.#ownerPending--;});this.#queue=operation.catch(()=>undefined);return operation;}
 pauseForOwnerUpgrade(){this.#ownerUpgradePauses++;let resumed=false;return {busy:this.#ownerPending>0||this.#projectionUnsettled,resume:()=>{if(!resumed){resumed=true;this.#ownerUpgradePauses--;}}};}
 async #save(state:State){await this.#verifyCheckpoint();if(this.#state.inventory_revision>=10_000)throw fail("visual_checkpoint_limit","Visual evidence checkpoint capacity requires maintenance",413);const next=State.parse({...state,inventory_revision:this.#state.inventory_revision+1});if(Buffer.byteLength(JSON.stringify(next))>8*1024*1024)throw fail("visual_inventory_limit","Visual evidence inventory exceeds its bounded storage capacity",413);await atomicPrivateJson(join(this.#ctx.profileRoot,"visual-evidence.json"),next);this.#state=next;try{await this.#journal.ledger.append({type:"workbench.command_completed",run_id:`visual-inventory:${this.#ctx.profileId}`,project_id:"workbench:profile",operation_id:`visual-checkpoint:${this.#ctx.profileId}:${next.inventory_revision}`,attempt:0,artifact_refs:[],summary:"Recorded visual evidence inventory checkpoint",data:{operation:"visual.inventory.checkpoint",profile_id:this.#ctx.profileId,inventory_revision:next.inventory_revision,projection_sha256:hash(Buffer.from(JSON.stringify(next)))},idempotency_key:`visual-checkpoint:${next.inventory_revision}`});}catch{this.#projectionUnsettled=true;throw fail("visual_projection_unknown","Visual evidence inventory changed but its canonical checkpoint is unavailable",503);}}
 async #verifyCheckpoint(){const events=await this.#journal.ledger.listBounded(`visual-inventory:${this.#ctx.profileId}`,{maxBytes:16*1024*1024,maxEvents:10_000}),latest=events.at(-1);if(!latest){if(this.#state.inventory_revision!==0||this.#state.entries.length||this.#state.settings.revision!==0)throw fail("visual_projection_stale","Visual evidence inventory has no canonical checkpoint; restore its latest verified projection",503);return;}if(latest.type!=="workbench.command_completed"||latest.data.operation!=="visual.inventory.checkpoint"||latest.data.profile_id!==this.#ctx.profileId||latest.data.inventory_revision!==this.#state.inventory_revision||latest.data.projection_sha256!==hash(Buffer.from(JSON.stringify(this.#state))))throw fail("visual_projection_stale","Visual evidence inventory differs from its latest canonical checkpoint; restore the latest verified projection",503);}

 async settings(){if(this.#closed)throw fail("visual_closed","Visual evidence controller is closed",503);return structuredClone(this.#state.settings);}
 updateSettings(value:VisualRetentionUpdate){const input=VisualRetentionUpdateSchema.parse(value);return this.#serial(()=>this.#journal.once(input.command_id,"visual.settings.update",input,async()=>{const state=structuredClone(this.#state);if(input.expected_revision!==state.settings.revision)throw fail("visual_revision_conflict","Retention settings changed; read the latest revision");state.settings=VisualRetentionSettingsSchema.parse({...state.settings,revision:state.settings.revision+1,updated_at:this.#now(),last_command_id:input.command_id,values:input.values});await this.#save(state);return state.settings;}));}
 async list(value:VisualEvidenceQuery){if(this.#closed)throw fail("visual_closed","Visual evidence controller is closed",503);const input=VisualEvidenceQuerySchema.parse(value),entries=this.#state.entries.map(value=>value.entry).filter(entry=>(!input.project_id||entry.project_id===input.project_id||entry.run_artifacts.some(ref=>ref.project_id===input.project_id))&&(!input.run_id||entry.run_artifacts.some(ref=>ref.project_id===input.project_id&&ref.run_id===input.run_id)));const end=input.offset+input.limit;return VisualEvidenceInventorySchema.parse({source:"registered-provenance",entries:entries.slice(input.offset,end).map(entry=>input.run_id?{...entry,run_artifacts:entry.run_artifacts.filter(ref=>ref.project_id===input.project_id&&ref.run_id===input.run_id)}:input.project_id?{...entry,run_artifacts:entry.run_artifacts.filter(ref=>ref.project_id===input.project_id)}:entry),total:entries.length,...(end<entries.length?{next_offset:end}:{}),legacy_policy:"retain-unregistered"});}
 pin(evidenceId:string,value:VisualEvidencePin){IdentifierSchema.parse(evidenceId);const input=VisualEvidencePinSchema.parse(value);return this.#serial(()=>this.#journal.once(input.command_id,"visual.evidence.pin",{evidence_id:evidenceId,...input},async()=>{const state=structuredClone(this.#state),stored=state.entries.find(value=>value.entry.evidence_id===evidenceId);if(!stored)throw fail("visual_evidence_missing","Visual evidence is unavailable",404);if(stored.entry.revision!==input.expected_revision)throw fail("visual_revision_conflict","Visual evidence changed; read its latest revision");if(stored.entry.state!=="retained")throw fail("visual_evidence_settling","Deleted or uncertain evidence cannot be pinned");if(input.pinned&&!stored.entry.pinned&&state.entries.filter(value=>value.entry.pinned).length>=500)throw fail("visual_pin_limit","Unpin an observation before pinning more evidence",413);stored.entry={...stored.entry,pinned:input.pinned,revision:stored.entry.revision+1,last_command_id:input.command_id};await this.#save(state);return stored.entry;}));}
 registerBrowser(input:BrowserVisualRegistration){if(!/^browser-evidence:[a-f0-9-]{36}$/u.test(input.evidence_id))return Promise.reject(fail("visual_provenance_invalid","Browser evidence identity is invalid",503));const entry=VisualEvidenceEntrySchema.parse({...input,source:"browser",mime_type:"image/png",revision:0,pinned:false,state:"retained",run_artifacts:[]});return this.#register({entry},async()=>{const bytes=await this.#browserBytes(entry);if(bytes.bytes.length!==entry.byte_length||hash(bytes.bytes)!==entry.sha256)throw fail("visual_provenance_invalid","Browser evidence bytes did not match capture provenance",503);});}
 registerComputer(value:ArtifactRef){const artifact=ArtifactRefSchema.parse(value);if(artifact.project_id!=="computer:profile"||!/^computer:[a-f0-9]{64}$/u.test(artifact.run_id)||artifact.kind!=="image/png"||artifact.mime_type!=="image/png")return Promise.reject(fail("visual_provenance_invalid","Computer evidence scope is invalid",503));const entry=VisualEvidenceEntrySchema.parse({evidence_id:`computer-evidence:${artifact.artifact_id}`,source:"computer",project_id:artifact.project_id,captured_at:artifact.created_at,sha256:artifact.content_hash,byte_length:artifact.byte_length,mime_type:"image/png",revision:0,pinned:false,state:"retained",run_artifacts:[]});return this.#register({entry,computer_artifact:artifact},async()=>{await this.#verifiedArtifact(this.#computer,artifact);});}
 #register(stored:Stored,verify:()=>Promise<void>){return this.#serial(()=>this.#journal.once(`visual-register:${stored.entry.evidence_id}`,"visual.evidence.register",stored,async()=>{const existing=this.#state.entries.find(value=>value.entry.evidence_id===stored.entry.evidence_id);if(existing){if(existing.entry.sha256!==stored.entry.sha256||existing.entry.project_id!==stored.entry.project_id)throw fail("visual_provenance_conflict","Visual evidence provenance changed",503);return {evidence_id:stored.entry.evidence_id};}if(this.#state.entries.length>=10_000)throw fail("visual_inventory_limit","Visual evidence inventory is full; review retained records",413);await verify();const state=structuredClone(this.#state);state.entries.push(stored);await this.#save(state);return {evidence_id:stored.entry.evidence_id};})).then(()=>undefined);}
 registerRunCopy(evidenceId:string,value:ArtifactRef){const artifact=ArtifactRefSchema.parse(value);return this.#serial(()=>this.#journal.once(`visual-copy:${evidenceId}:${artifact.artifact_id}`,"visual.evidence.copy",{evidence_id:evidenceId,artifact},async()=>{const state=structuredClone(this.#state),stored=state.entries.find(value=>value.entry.evidence_id===evidenceId);if(!stored||stored.entry.state!=="retained")throw fail("visual_provenance_missing","Capture provenance is unavailable",503);if(stored.entry.source==="browser"&&stored.entry.project_id!==artifact.project_id||artifact.content_hash!==stored.entry.sha256||artifact.byte_length!==stored.entry.byte_length||artifact.kind!=="image/png"||artifact.mime_type!=="image/png")throw fail("visual_copy_scope","Run screenshot does not match its capture provenance",403);await this.#ctx.validateRunArtifact(artifact);await this.#verifiedArtifact(this.#runtime,artifact);if(stored.entry.run_artifacts.some(ref=>ref.artifact_id===artifact.artifact_id))return {evidence_id:evidenceId,artifact};if(stored.entry.run_artifacts.length>=16)throw fail("visual_copy_limit","This observation has too many Run copies",413);stored.entry.run_artifacts.push(artifact);stored.entry.revision++;await this.#save(state);return {evidence_id:evidenceId,artifact};})).then(()=>undefined);}
 async #verifiedArtifact(store:ArtifactStore,ref:ArtifactRef){if(await store.inspectBytesInternal(ref)!=="available")throw fail("visual_provenance_invalid","Screenshot Artifact bytes or scope could not be verified",503);}
 async #verifyProvenance(stored:Stored){
  const entry=stored.entry,initial=VisualEvidenceEntrySchema.parse({evidence_id:entry.evidence_id,source:entry.source,project_id:entry.project_id,captured_at:entry.captured_at,sha256:entry.sha256,byte_length:entry.byte_length,mime_type:entry.mime_type,revision:0,pinned:false,state:"retained",run_artifacts:[]});
  if(!await this.#journal.verifyCompleted(`visual-register:${entry.evidence_id}`,"visual.evidence.register",{entry:initial,...(stored.computer_artifact?{computer_artifact:stored.computer_artifact}:{})}))throw fail("visual_provenance_unsettled","Capture provenance has no verified canonical receipt",503);
  for(const ref of entry.run_artifacts)if(!await this.#journal.verifyCompleted(`visual-copy:${entry.evidence_id}:${ref.artifact_id}`,"visual.evidence.copy",{evidence_id:entry.evidence_id,artifact:ref}))throw fail("visual_provenance_unsettled","Run copy provenance has no verified canonical receipt",503);
  if(entry.last_command_id){const pin=await this.#journal.inspect(entry.last_command_id),result=VisualEvidenceEntrySchema.safeParse(pin.result);if(pin.state!=="completed"||pin.operation!=="visual.evidence.pin"||!result.success||result.data.evidence_id!==entry.evidence_id||result.data.pinned!==entry.pinned||result.data.last_command_id!==entry.last_command_id)throw fail("visual_pin_unsettled","Pin authority has no verified canonical receipt",503);}
  // The cleanup reservation adds one revision before this check. Without any
  // pin command, every prior revision must be a registered Run copy.
  else if(entry.revision!==entry.run_artifacts.length+1)throw fail("visual_pin_unsettled","Pin provenance cannot be reconstructed",503);
 }
 async #verifySettings(){const settings=this.#state.settings;if(settings.revision===0){if(settings.last_command_id!==null||settings.values.retention_days!==30||settings.values.automatic_cleanup!==true)throw fail("visual_config_unsettled","Retention policy has no canonical receipt",503);return;}if(!settings.last_command_id)throw fail("visual_config_unsettled","Retention policy has no canonical receipt",503);const receipt=await this.#journal.inspect(settings.last_command_id);if(receipt.state!=="completed"||receipt.operation!=="visual.settings.update"||JSON.stringify(VisualRetentionSettingsSchema.parse(receipt.result))!==JSON.stringify(settings))throw fail("visual_config_unsettled","Retention policy is unsettled; inspect its command",503);}
 #expired(entry:VisualEvidenceEntry){return entry.state==="retained"&&!entry.pinned&&Date.parse(entry.captured_at)+this.#state.settings.values.retention_days*86_400_000<=Date.parse(this.#now());}
 #scope(entry:VisualEvidenceEntry,input:VisualEvidenceCleanupRequest){return (!input.project_id||(entry.project_id===input.project_id||entry.source==="computer"&&entry.run_artifacts.some(ref=>ref.project_id===input.project_id))&&entry.run_artifacts.every(ref=>ref.project_id===input.project_id))&&(!input.run_id||entry.run_artifacts.length>0&&entry.run_artifacts.every(ref=>ref.project_id===input.project_id&&ref.run_id===input.run_id));}
 cleanup(value:VisualEvidenceCleanupRequest):Promise<VisualEvidenceCleanupResult>{const input=VisualEvidenceCleanupRequestSchema.parse(value);return this.#serial(()=>this.#journal.once(input.command_id,"visual.evidence.cleanup",input,async()=>{await this.#verifyCheckpoint();await this.#verifySettings();let state=structuredClone(this.#state);const candidates=state.entries.filter(value=>this.#expired(value.entry)&&this.#scope(value.entry,input)).slice(0,input.limit);for(const value of candidates)value.entry={...value.entry,state:"unknown",cleanup_command_id:input.command_id,revision:value.entry.revision+1};await this.#save(state);const deleted:string[]=[],unknown:string[]=[];let deletedBytes=0;for(const stored of candidates){try{await this.#verifyProvenance(stored);if(stored.entry.source==="browser")deletedBytes+=await this.#deleteBrowser(stored.entry);else if(stored.computer_artifact)deletedBytes+=(await this.#computer.deleteBytesInternal(stored.computer_artifact)).byteLength;else throw fail("visual_provenance_invalid","Capture provenance is incomplete",503);for(const ref of stored.entry.run_artifacts)deletedBytes+=(await this.#runtime.deleteBytesInternal(ref)).byteLength;deleted.push(stored.entry.evidence_id);stored.entry={...stored.entry,state:"deleted",deleted_at:this.#now()};}catch{unknown.push(stored.entry.evidence_id);}}try{await this.#save({...state,inventory_revision:this.#state.inventory_revision});}catch{throw fail("visual_cleanup_effect_unknown","Some screenshot bytes may have expired; inspect the command before another cleanup",503);}return VisualEvidenceCleanupResultSchema.parse({command_id:input.command_id,status:unknown.length?"unknown":"completed",deleted,unknown,deleted_bytes:deletedBytes,checked_at:this.#now(),more_expired:this.#state.entries.some(value=>this.#expired(value.entry)&&this.#scope(value.entry,input))});}));}
 async reconcile(commandId:string):Promise<VisualEvidenceCommandReceipt>{if(this.#closed)throw fail("visual_closed","Visual evidence controller is closed",503);IdentifierSchema.parse(commandId);const receipt=await this.#journal.inspect(commandId),allowed=["visual.settings.update","visual.evidence.pin","visual.evidence.cleanup"];if(!receipt.operation||!allowed.includes(receipt.operation))return {command_id:commandId,state:"not_found"};const observed=[];for(const stored of this.#state.entries.filter(value=>value.entry.cleanup_command_id===commandId).slice(0,100)){let present=0,unverifiable=0;try{if(stored.entry.source==="browser"){const result=await this.#browserBytes(stored.entry);if(result.bytes.length!==stored.entry.byte_length||hash(result.bytes)!==stored.entry.sha256)throw new Error("changed");present++;}else if(stored.computer_artifact){const result=await this.#computer.inspectBytesInternal(stored.computer_artifact);if(result==="available")present++;else if(result!=="absent")unverifiable++;}}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")unverifiable++;}for(const ref of stored.entry.run_artifacts){try{const result=await this.#runtime.inspectBytesInternal(ref);if(result==="available")present++;else if(result!=="absent")unverifiable++;}catch{unverifiable++;}}observed.push({evidence_id:stored.entry.evidence_id,all_registered_bytes_absent:present===0&&unverifiable===0,present_copies:present,unverifiable_copies:unverifiable});}return VisualEvidenceCommandReceiptSchema.parse({command_id:commandId,state:receipt.state!=="completed"&&(observed.length||this.#state.settings.last_command_id===commandId||this.#state.entries.some(value=>value.entry.last_command_id===commandId))?"unknown":receipt.state,operation:receipt.operation,...(receipt.result===undefined?{}:{result:receipt.result}),...(receipt.code?{code:receipt.code}:{}),...(observed.length?{observed_bytes:observed}:{})});}
 async #browserBytes(entry:VisualEvidenceEntry){const root=join(this.#ctx.profileRoot,"browser-evidence");if(await realpath(root)!==resolve(root))throw fail("visual_store_invalid","Browser evidence store changed",503);return readSafe(join(root,entry.evidence_id.slice("browser-evidence:".length)+".png"),8*1024*1024);}
 async #deleteBrowser(entry:VisualEvidenceEntry){let file;try{file=await this.#browserBytes(entry);}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return 0;throw error;}if(file.bytes.length!==entry.byte_length||hash(file.bytes)!==entry.sha256)throw fail("visual_bytes_changed","Visual evidence bytes changed",409);const path=join(this.#ctx.profileRoot,"browser-evidence",entry.evidence_id.slice("browser-evidence:".length)+".png"),current=await lstat(path);if(current.dev!==file.dev||current.ino!==file.ino||!current.isFile()||current.isSymbolicLink()||current.nlink!==1)throw fail("visual_bytes_changed","Visual evidence identity changed",409);await unlink(path);return entry.byte_length;}
 async #automatic(){if(this.#closed||this.#ownerUpgradePauses||!this.#state.settings.values.automatic_cleanup||!this.#state.entries.some(value=>this.#expired(value.entry)))return;await this.cleanup({command_id:`visual-cleanup:${randomUUID()}`,limit:50});}
 async close(){this.#closed=true;if(this.#timer)clearInterval(this.#timer);await this.#queue;}
}
async function readSafe(path:string,maximum:number){const before=await lstat(path);if(!before.isFile()||before.isSymbolicLink()||before.nlink!==1||before.size>maximum||(typeof process.getuid==="function"&&before.uid!==process.getuid()))throw fail("visual_file_invalid","Visual evidence requires a bounded private regular file",503);const handle=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));try{const info=await handle.stat();if(info.dev!==before.dev||info.ino!==before.ino||!info.isFile()||info.nlink!==1||info.size>maximum)throw fail("visual_file_invalid","Visual evidence identity changed",503);const buffer=Buffer.alloc(maximum+1);let offset=0;while(offset<buffer.length){const part=await handle.read(buffer,offset,buffer.length-offset,offset);if(!part.bytesRead)break;offset+=part.bytesRead;}if(offset>maximum)throw fail("visual_file_invalid","Visual evidence exceeds its bound",503);return {bytes:buffer.subarray(0,offset),dev:info.dev,ino:info.ino};}finally{await handle.close();}}
