import {createServer} from "node:http";
import {mkdtemp,realpath,mkdir,readFile,writeFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createHash,randomUUID} from "node:crypto";
import {describe,it,expect,vi} from "vitest";
import {startLocalHost,connectLocalHost} from "../dist/index.js";
import {JsonlEventLedger} from "@tracegraph/core";
const png=Buffer.from("89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000b49444154789c636000020000050001a5f645400000000049454e44ae426082","hex");
describe("optional screenshot retention recovery isolation",()=>{
 it.each(["stale","corrupt"])("keeps real shared Host/Plan usable with %s retention metadata and never deletes pixels",async kind=>{const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-visual-optional-")));let calls=0;const provider=createServer(async(request,response)=>{let body="";for await(const bytes of request)body+=String(bytes);const value=JSON.parse(body);response.setHeader("content-type","application/json");const background=String(value.messages?.[0]?.content??"").startsWith("You extract");if(!background)calls++;response.end(JSON.stringify({choices:[{message:{content:JSON.stringify(background?{summary:"No reusable facts",candidates:[]}:{decision_id:"decision:retention-isolation",kind:"finish",finish_intent:"answer",public_reason:"Answer without executing",evidence_refs:[],risk:"none",final_answer:"Plan remains available"})}}]}));});await new Promise<void>(done=>provider.listen(0,"127.0.0.1",done));const address=provider.address() as {port:number};let owner=await startLocalHost({profileRoot:root,httpPort:0,credentialBackend:"private-file"}),client=await connectLocalHost({profileRoot:root});let rawPath="";
 try{await client.client.configureModel({provider:"custom",protocol:"openai-chat-completions",base_url:`http://127.0.0.1:${address.port}/v1`,model:"retention-isolation-fixture",api_key:"isolated-dummy-retention-key"});await mkdir(join(root,"project"));const project=await client.native.registerProject({selectedPath:join(root,"project"),access:"read_write"});const id=`browser-evidence:${randomUUID()}`;rawPath=join(root,"browser-evidence",id.split(':')[1]+".png");await writeFile(rawPath,png,{mode:0o600});await owner.composition.visualEvidence!.registerBrowser({evidence_id:id,project_id:project.project_id,captured_at:new Date(Date.now()-40*86_400_000).toISOString(),sha256:`sha256:${createHash("sha256").update(png).digest("hex")}`,byte_length:png.length});const before=await readFile(join(root,"visual-evidence.json"));await client.client.pinVisualEvidence(id,{command_id:"pin:optional",expected_revision:0,pinned:true});await client.client.updateVisualRetentionSettings({command_id:"settings:optional",expected_revision:0,values:{retention_days:365,automatic_cleanup:false}});await client.close();await owner.close();await writeFile(join(root,"visual-evidence.json"),kind==="stale"?before:Buffer.from('{"invalid":"projection"}'));owner=await startLocalHost({profileRoot:root,httpPort:0,credentialBackend:"private-file"});client=await connectLocalHost({profileRoot:root});expect(owner.composition.visualEvidence).toBeUndefined();const capabilities=await client.client.getCapabilities();expect(capabilities.capabilities.filter(value=>value.operation.startsWith("visual.")).every(value=>value.state==="unavailable"&&Boolean(value.reason))).toBe(true);expect(capabilities.capabilities.filter(value=>value.operation.startsWith("visual."))).toHaveLength(6);const started=await client.client.startRun({command_id:`plan:${kind}`,project_id:project.project_id,task:"Give the public answer in Plan mode",mode:"plan"});await vi.waitFor(async()=>expect((await client.client.getRun(started.run_id)).status).toBe("completed"));expect((await client.client.getRun(started.run_id)).timeline.find(event=>event.type==="run.completed")?.data.outcome).toBe("Plan remains available");expect(await readFile(rawPath)).toEqual(png);const events=new JsonlEventLedger(join(root,"visual-evidence-events"));for await(const ids of events.iterateRunIdBatches(10))for(const id of ids)expect((await events.list(id)).some(event=>event.data.operation==="visual.evidence.cleanup")).toBe(false);expect(calls).toBe(1);}
 finally{await client.close();await owner.close();await new Promise<void>((resolve,reject)=>provider.close(error=>error?reject(error):resolve()));await rm(root,{recursive:true,force:true});}
 },20_000);
});
