import {createServer} from "node:http";
import {once} from "node:events";
import {mkdtemp,mkdir,realpath,readFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {describe,it,expect} from "vitest";
import {chromium} from "playwright-core";
import {ArtifactStore,type TraceGraphExtension} from "@tracegraph/core";
import type {ArtifactRef,ComputerTarget} from "@tracegraph/contracts";
import {VisualEvidenceController} from "./visual-evidence-control.js";
import {BrowserControl} from "./browser-control.js";
import {browserTools} from "./browser-tools.js";
import {ComputerControl,type NativeComputerBackend} from "./computer-control.js";
import {computerTools} from "./computer-tools.js";
async function activate(extension:TraceGraphExtension){const tools=new Map<string,{execute:(input:unknown,context:unknown)=>Promise<{facts?:Record<string,unknown>}>}>();await extension.activate!({registerTool:(definition:{name:string})=>{tools.set(definition.name,definition as never);return {dispose(){}};}} as never);return tools;}
const png=Buffer.from("89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000b49444154789c636000020000050001a5f645400000000049454e44ae426082","hex");
describe("real trusted screenshot registration chain",()=>{
 it("registers an actual isolated Chromium screenshot and its Tool-published Run copy, then expires both",async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-browser-retention-"))),data=join(root,"data");await mkdir(data);let now=new Date();const artifacts=new ArtifactStore(join(data,"artifacts"));await artifacts.initialize();const visual=await VisualEvidenceController.open({profileRoot:root,profileId:"profile:browser-retention",dataRoot:data,now:()=>now,validateRunArtifact:async ref=>{expect(ref.project_id).toBe("project:a");expect(ref.run_id).toBe("run:a");}});const service=createServer((_request,response)=>{response.setHeader("content-type","text/html");response.end('<title>Actual screenshot</title><h1>OWNED VISUAL PROVENANCE</h1><button>Continue</button>');});service.listen(0,"127.0.0.1");await once(service,"listening");const origin=`http://127.0.0.1:${(service.address() as {port:number}).port}`;const browser=await BrowserControl.create({profileRoot:root,executablePath:chromium.executablePath(),runtimeKind:"development",resolveProject:async()=>undefined,authorizeGrant:async()=>true,visualEvidence:visual});let extension:TraceGraphExtension|undefined;
 try{const grant=await browser.requestGrant({command_id:"grant:retention",project_id:"project:a",label:"Owned capture fixture",origins:[origin],duration:"once"});const tab=(await browser.command({command_id:"open:retention",type:"open",grant_id:grant.grant_id,url:origin})).tab!;extension=browserTools(browser,()=>{throw new Error("No Runtime/model execution needed by observation");});const tools=await activate(extension),result=await tools.get("browser_observe")!.execute({tab_id:tab.tab_id},{projectId:"project:a",runId:"run:a",operationId:"observe:retention",publishArtifactBytes:async({mimeType,bytes}:{mimeType:"image/png";bytes:Uint8Array})=>artifacts.putBytes({projectId:"project:a",runId:"run:a",kind:mimeType,mimeType,content:bytes})});const inventory=await visual.list({project_id:"project:a",run_id:"run:a",limit:50,offset:0});expect(inventory.entries).toHaveLength(1);const entry=inventory.entries[0]!,ref=result.facts!.artifact as ArtifactRef;expect(entry.run_artifacts).toEqual([ref]);const original=await browser.evidence(entry.evidence_id,"project:a");expect(original.length).toBeGreaterThan(1000);expect(ref.content_hash).toBe(entry.sha256);expect(await artifacts.inspectBytesInternal(ref)).toBe("available");now=new Date(Date.now()+31*86_400_000);expect(await visual.cleanup({command_id:"cleanup:actual-browser",limit:50})).toMatchObject({status:"completed",deleted:[entry.evidence_id],deleted_bytes:original.length*2});await expect(browser.evidence(entry.evidence_id,"project:a")).rejects.toMatchObject({code:"ENOENT"});expect(await artifacts.inspectBytesInternal(ref)).toBe("absent");expect(await visual.reconcile("cleanup:actual-browser")).toMatchObject({state:"completed",observed_bytes:[{all_registered_bytes_absent:true}]});}
 finally{await extension?.deactivate?.();await browser.close();await visual.close();await new Promise<void>((resolve,reject)=>service.close(error=>error?reject(error):resolve()));await rm(root,{recursive:true,force:true});}
 },15_000);
 it("registers actual Computer controller capture bytes and trusted tool Run copy with deterministic native backend",async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-computer-retention-"))),data=join(root,"data");await mkdir(data);let now=new Date();const artifacts=new ArtifactStore(join(data,"artifacts"));await artifacts.initialize();const visual=await VisualEvidenceController.open({profileRoot:root,profileId:"profile:computer-retention",dataRoot:data,now:()=>now,validateRunArtifact:async ref=>{expect(ref.run_id).toBe("run:a");}});const target:ComputerTarget={application_id:"fixture.visual-app",pid:123,title:"Controlled target",identity:"sha256:"+"a".repeat(64),window_id:"owned:window"};let captures=0;const backend:NativeComputerBackend={status:async()=>({platform:"darwin",backend_available:true,accessibility:true,screen_capture:true,input_monitoring:true,locked:false}),targets:async()=>[target],validateTarget:async()=>undefined,focusTarget:async()=>undefined,inspect:async()=>({elements:[{element_id:"element:one",role:"button",title:"Public AX text",enabled:true}],truncated:false}),capture:async()=>{captures++;return png;},watch:async()=>({close:async()=>undefined}),act:async()=>{throw new Error("No native input permitted in this fixture");},close:async()=>undefined};const computer=await ComputerControl.create({profileRoot:root,backend,visualEvidence:visual,answerGrant:async()=>"allow"});let extension:TraceGraphExtension|undefined;
 try{const grant=await computer.requestGrant({command_id:"grant:computer-retention",target,duration:"always"});extension=computerTools(computer,()=>{throw new Error("No Runtime/model execution needed by observation");});const tools=await activate(extension),result=await tools.get("computer_observe")!.execute({grant_id:grant.grant_id,target,capture:true},{projectId:"project:a",runId:"run:a",operationId:"observe:computer-retention",publishArtifactBytes:async({mimeType,bytes}:{mimeType:"image/png";bytes:Uint8Array})=>artifacts.putBytes({projectId:"project:a",runId:"run:a",kind:mimeType,mimeType,content:bytes})});expect(captures).toBe(1);const entry=(await visual.list({project_id:"project:a",run_id:"run:a",limit:50,offset:0})).entries[0]!;expect(entry.source).toBe("computer");expect(entry.run_artifacts).toEqual([result.facts!.screenshot]);now=new Date(Date.now()+31*86_400_000);const resultCleanup=await visual.cleanup({command_id:"cleanup:actual-computer",limit:50});expect(resultCleanup).toMatchObject({status:"completed",deleted_bytes:png.length*2});expect((await visual.reconcile(resultCleanup.command_id)).observed_bytes?.[0]?.all_registered_bytes_absent).toBe(true);const commandReceipt=await computer.reconcile("observe:computer-retention"),observation=commandReceipt.result as {artifact:ArtifactRef};const text=await new ArtifactStore(join(root,"computer-artifacts")).getInternal({artifactId:observation.artifact.artifact_id,runId:observation.artifact.run_id,projectId:observation.artifact.project_id});expect(text.status).toBe("available");expect(JSON.stringify(text)).toContain("Public AX text");expect((await readFile(join(root,"visual-evidence.json"),"utf8"))).not.toContain("89504e47");}
 finally{await extension?.deactivate?.();await computer.close();await visual.close();await rm(root,{recursive:true,force:true});}
 });
});
