import {createHash,randomUUID} from "node:crypto";
import {mkdtemp,mkdir,readFile,writeFile,lstat,symlink,link,unlink,rm,realpath} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {afterEach,describe,it,expect,vi} from "vitest";
import {ArtifactStore,JsonlEventLedger} from "@tracegraph/core";
import {VisualEvidenceController} from "./visual-evidence-control.js";
import {registerVisualEvidenceRoutes} from "./visual-evidence-routes.js";
import Fastify from "fastify";
const png=Buffer.from("89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000b49444154789c636000020000050001a5f645400000000049454e44ae426082","hex");
const hash=(value:Uint8Array)=>`sha256:${createHash("sha256").update(value).digest("hex")}`;
const cleanups:Array<()=>Promise<void>>=[];
afterEach(async()=>{vi.restoreAllMocks();for(const cleanup of cleanups.splice(0).reverse())await cleanup();});
async function fixture(){const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-retention-")));cleanups.push(()=>rm(root,{recursive:true,force:true}));const data=join(root,"data");await mkdir(data);await mkdir(join(root,"browser-evidence"));const computer=new ArtifactStore(join(root,"computer-artifacts")),runtime=new ArtifactStore(join(data,"artifacts"));await computer.initialize();await runtime.initialize();let now=new Date("2026-10-05T00:00:00Z");const validations:string[]=[];const context={profileRoot:root,profileId:"profile:retention",dataRoot:data,now:()=>now,validateRunArtifact:async(ref:{project_id:string;run_id:string})=>{if(ref.project_id!=="project:a"||!['run:a','run:b'].includes(ref.run_id))throw new Error("Run scope denied");validations.push(ref.run_id);}};const control=await VisualEvidenceController.open(context);cleanups.push(()=>control.close());return {root,data,computer,runtime,control,context,validations,setNow:(value:string)=>{now=new Date(value);}};}
async function browser(f:Awaited<ReturnType<typeof fixture>>,captured="2026-08-01T00:00:00Z"){const id=`browser-evidence:${randomUUID()}`,path=join(f.root,"browser-evidence",id.split(':')[1]+".png");await writeFile(path,png,{mode:0o600});await f.control.registerBrowser({evidence_id:id,project_id:"project:a",captured_at:captured,sha256:hash(png),byte_length:png.length});return {id,path};}
async function copy(f:Awaited<ReturnType<typeof fixture>>,id:string,run="run:a"){const ref=await f.runtime.putBytes({projectId:"project:a",runId:run,kind:"image/png",mimeType:"image/png",content:png});await f.control.registerRunCopy(id,ref);return ref;}
describe("registered Browser/Computer screenshot retention",()=>{
 it("rejects a restored pre-pin/pre-settings projection against newer canonical facts",async()=>{const f=await fixture(),capture=await browser(f),path=join(f.root,"visual-evidence.json"),old=await readFile(path);await f.control.pin(capture.id,{command_id:"pin:canonical",expected_revision:0,pinned:true});await f.control.updateSettings({command_id:"settings:canonical",expected_revision:0,values:{retention_days:365,automatic_cleanup:false}});await f.control.close();await writeFile(path,old);await expect(VisualEvidenceController.open(f.context)).rejects.toMatchObject({code:"visual_projection_stale"});expect(await readFile(capture.path)).toEqual(png);});
 it("blocks further mutation after a projection checkpoint loss and never cleans unrecorded bytes",async()=>{const f=await fixture(),capture=await browser(f);const original=JsonlEventLedger.prototype.append;vi.spyOn(JsonlEventLedger.prototype,"append").mockImplementation(async function(event,...rest){if(event.run_id==="visual-inventory:profile:retention"&&event.data.inventory_revision===2)throw new Error("fixture checkpoint loss");return original.call(this,event,...rest);});await expect(f.control.pin(capture.id,{command_id:"pin:checkpoint-lost",expected_revision:0,pinned:true})).rejects.toMatchObject({code:"visual_projection_unknown"});await expect(f.control.cleanup({command_id:"cleanup:checkpoint-lost",limit:50})).rejects.toMatchObject({code:"visual_projection_unknown"});expect(await f.control.reconcile("pin:checkpoint-lost")).toMatchObject({state:"unknown"});expect(await readFile(capture.path)).toEqual(png);await f.control.close();await expect(VisualEvidenceController.open(f.context)).rejects.toMatchObject({code:"visual_projection_stale"});});
 it("refuses replacement Run Artifact links after partial deletion and reports the remaining copy",async()=>{const f=await fixture(),capture=await browser(f),ref=await copy(f,capture.id),path=join(f.data,"artifacts",ref.artifact_id.replace(/[^A-Za-z0-9_.-]/gu,"_")+".data"),outside=join(f.root,"outside-artifact.png");await writeFile(outside,png);await unlink(path);await symlink(outside,path);const result=await f.control.cleanup({command_id:"cleanup:artifact-link",limit:50});expect(result).toMatchObject({status:"unknown",deleted:[],unknown:[capture.id],deleted_bytes:png.length});await expect(lstat(capture.path)).rejects.toMatchObject({code:"ENOENT"});expect(await readFile(outside)).toEqual(png);expect((await f.control.reconcile(result.command_id)).observed_bytes).toMatchObject([{all_registered_bytes_absent:false,unverifiable_copies:1}]);expect((await f.control.cleanup({command_id:"cleanup:artifact-link:new",limit:50})).deleted).toEqual([]);});
 it("rejects malformed persisted provenance before any destructive action",async()=>{const f=await fixture(),capture=await browser(f);await f.control.close();const path=join(f.root,"visual-evidence.json"),state=JSON.parse(await readFile(path,"utf8"));state.entries[0].entry.evidence_id="browser-evidence:../../project-file";await writeFile(path,JSON.stringify(state));await expect(VisualEvidenceController.open(f.context)).rejects.toThrow();expect(await readFile(capture.path)).toEqual(png);});
 it("deletes actual expired original and scoped Run bytes, retaining metadata, Ledger and unrelated data",async()=>{const f=await fixture(),capture=await browser(f),ref=await copy(f,capture.id);const unrelated=await f.runtime.putBytes({projectId:"project:a",runId:"run:a",kind:"image/png",mimeType:"image/png",content:png});await writeFile(join(f.root,"project-file.txt"),"USER FILE");const result=await f.control.cleanup({command_id:"cleanup:actual",limit:50});expect(result).toMatchObject({status:"completed",deleted:[capture.id],deleted_bytes:png.length*2});await expect(lstat(capture.path)).rejects.toMatchObject({code:"ENOENT"});await expect(lstat(join(f.data,"artifacts",ref.artifact_id.replace(/[^A-Za-z0-9_.-]/gu,"_")+".data"))).rejects.toMatchObject({code:"ENOENT"});expect(JSON.parse(await readFile(join(f.data,"artifacts",ref.artifact_id.replace(/[^A-Za-z0-9_.-]/gu,"_")+".json"),"utf8"))).toEqual(ref);expect(await f.runtime.inspectBytesInternal(unrelated)).toBe("available");expect(await readFile(join(f.root,"project-file.txt"),"utf8")).toBe("USER FILE");const receipt=await f.control.reconcile("cleanup:actual");expect(receipt).toMatchObject({state:"completed",result,observed_bytes:[{evidence_id:capture.id,all_registered_bytes_absent:true,present_copies:0,unverifiable_copies:0}]});expect(await f.control.cleanup({command_id:"cleanup:actual",limit:50})).toEqual(result);await expect(f.control.cleanup({command_id:"cleanup:actual",limit:1})).rejects.toMatchObject({code:"command_id_conflict"});const ledger=new JsonlEventLedger(join(f.root,"visual-evidence-events"));let events=0;for await(const ids of ledger.iterateRunIdBatches(10))for(const id of ids)events+=(await ledger.list(id)).length;expect(events).toBe(10);});
 it("pins expired evidence and retains young captures; settings CAS persists across restart",async()=>{const f=await fixture(),old=await browser(f),young=await browser(f,"2026-10-04T00:00:00Z");expect(await f.control.settings()).toMatchObject({revision:0,values:{retention_days:30,automatic_cleanup:true}});const pin=await f.control.pin(old.id,{command_id:"pin:old",expected_revision:0,pinned:true});expect(pin.pinned).toBe(true);const values={retention_days:2,automatic_cleanup:false};await f.control.updateSettings({command_id:"settings:new",expected_revision:0,values});await expect(f.control.updateSettings({command_id:"settings:stale",expected_revision:0,values})).rejects.toMatchObject({code:"visual_revision_conflict"});expect((await f.control.cleanup({command_id:"cleanup:pinned",limit:50})).deleted).toEqual([]);expect(await readFile(old.path)).toEqual(png);expect(await readFile(young.path)).toEqual(png);await f.control.close();const reopened=await VisualEvidenceController.open(f.context);cleanups.push(()=>reopened.close());expect(await reopened.settings()).toMatchObject({revision:1,values,last_command_id:"settings:new"});expect((await reopened.list({limit:50,offset:0})).entries.find(entry=>entry.evidence_id===old.id)?.pinned).toBe(true);});
 it("cleans Computer private capture plus Run copy, preserving accessibility text Artifact",async()=>{const f=await fixture();const runId=`computer:${'a'.repeat(64)}`,capture=await f.computer.putBytes({projectId:"computer:profile",runId,kind:"image/png",mimeType:"image/png",content:png}),text=await f.computer.put({projectId:"computer:profile",runId,kind:"tool_output",mimeType:"application/json",content:'{"elements":[{"text":"AX PUBLIC TEXT"}]}'});await f.control.registerComputer(capture);const id=`computer-evidence:${capture.artifact_id}`,ref=await copy(f,id);f.setNow("2026-12-05T00:00:00Z");const result=await f.control.cleanup({command_id:"cleanup:computer",limit:50});expect(result.deleted).toEqual([id]);expect(await f.computer.inspectBytesInternal(capture)).toBe("absent");expect(await f.runtime.inspectBytesInternal(ref)).toBe("absent");expect((await f.computer.getInternal({projectId:"computer:profile",runId,artifactId:text.artifact_id})).status).toBe("available");});
 it("does not delete a shared observation from one Run filter or accept a forged copy scope",async()=>{const f=await fixture(),capture=await browser(f);const a=await copy(f,capture.id),b=await copy(f,capture.id,"run:b");const scoped=await f.control.list({project_id:"project:a",run_id:"run:a",limit:50,offset:0});expect(scoped.entries[0]?.run_artifacts).toEqual([a]);expect((await f.control.cleanup({command_id:"cleanup:one-run",project_id:"project:a",run_id:"run:a",limit:50})).deleted).toEqual([]);expect(await f.runtime.inspectBytesInternal(b)).toBe("available");const forged=await f.runtime.putBytes({projectId:"project:other",runId:"run:x",kind:"image/png",mimeType:"image/png",content:png});await expect(f.control.registerRunCopy(capture.id,forged)).rejects.toMatchObject({code:"visual_copy_scope"});await expect(f.control.cleanup({command_id:"cleanup:wrong-project",project_id:"project:other",limit:50})).resolves.toMatchObject({deleted:[]});});
 it.each(["symlink","hardlink"])("keeps replacement %s target and marks outcome unknown without retry",async kind=>{const f=await fixture(),capture=await browser(f),ref=await copy(f,capture.id),outside=join(f.root,"outside.png");await writeFile(outside,png);await unlink(capture.path);if(kind==="symlink")await symlink(outside,capture.path);else await link(outside,capture.path);const result=await f.control.cleanup({command_id:`cleanup:${kind}`,limit:50});expect(result.status).toBe("unknown");expect(result.unknown).toEqual([capture.id]);expect(await readFile(outside)).toEqual(png);expect(await f.runtime.inspectBytesInternal(ref)).toBe("available");expect((await f.control.cleanup({command_id:`cleanup:${kind}:new`,limit:50})).deleted).toEqual([]);const receipt=await f.control.reconcile(`cleanup:${kind}`);expect(receipt.observed_bytes?.[0]?.unverifiable_copies).toBe(1);});
 it("keeps lost cleanup receipt unknown with read-only byte reconciliation and no repeat deletion",async()=>{const f=await fixture(),capture=await browser(f);await copy(f,capture.id);const original=JsonlEventLedger.prototype.append;vi.spyOn(JsonlEventLedger.prototype,"append").mockImplementation(async function(event,...rest){if(event.operation_id==="cleanup:lost"&&event.type==="workbench.command_completed")throw new Error("fixture receipt disk failure");return original.call(this,event,...rest);});await expect(f.control.cleanup({command_id:"cleanup:lost",limit:50})).rejects.toThrow("fixture receipt disk failure");const receipt=await f.control.reconcile("cleanup:lost");expect(receipt).toMatchObject({state:"unknown",observed_bytes:[{all_registered_bytes_absent:true,present_copies:0}]});await expect(f.control.cleanup({command_id:"cleanup:lost",limit:50})).rejects.toMatchObject({code:"workbench_failed"});expect((await f.control.cleanup({command_id:"cleanup:new",limit:50})).deleted).toEqual([]);});
 it("serializes cleanup versus pin and uses durable automatic cleanup rather than an unlogged timer",async()=>{const f=await fixture(),capture=await browser(f);const cleanup=f.control.cleanup({command_id:"cleanup:first",limit:50}),pin=f.control.pin(capture.id,{command_id:"pin:late",expected_revision:0,pinned:true});expect((await cleanup).deleted).toEqual([capture.id]);await expect(pin).rejects.toMatchObject({code:"visual_revision_conflict"});const old=await browser(f);await f.control.close();
  // Inventory bytes settle before the command's canonical completed event.
  // Hold that append to prove that readback must not masquerade as success.
  let releaseReceipt!:()=>void,receiptHeld=false;
  const receiptGate=new Promise<void>(resolve=>{releaseReceipt=resolve;}),append=JsonlEventLedger.prototype.append;
  vi.spyOn(JsonlEventLedger.prototype,"append").mockImplementation(async function(event,...rest){
   if(event.type==="workbench.command_completed"&&event.data.operation==="visual.evidence.cleanup"&&!receiptHeld){receiptHeld=true;await receiptGate;}
   return append.call(this,event,...rest);
  });
  const auto=await VisualEvidenceController.open({...f.context,automaticIntervalMs:10});cleanups.push(()=>auto.close());
  try{
   await vi.waitFor(async()=>{expect(receiptHeld).toBe(true);expect((await auto.list({limit:50,offset:0})).entries.find(entry=>entry.evidence_id===old.id)?.state).toBe("deleted");});
   const entry=(await auto.list({limit:50,offset:0})).entries.find(entry=>entry.evidence_id===old.id)!;
   await expect(lstat(old.path)).rejects.toMatchObject({code:"ENOENT"});
   expect(await auto.reconcile(entry.cleanup_command_id!)).toMatchObject({state:"unknown",operation:"visual.evidence.cleanup",observed_bytes:[{all_registered_bytes_absent:true}]});
   releaseReceipt();
   await vi.waitFor(async()=>expect(await auto.reconcile(entry.cleanup_command_id!)).toMatchObject({state:"completed",operation:"visual.evidence.cleanup",result:{status:"completed",deleted:[old.id],unknown:[]}}));
  }finally{releaseReceipt();}});
 it("routes only closed typed IDs/settings and bounded queries",async()=>{const f=await fixture(),app=Fastify();cleanups.push(()=>app.close());registerVisualEvidenceRoutes(app,f.control);expect((await app.inject({url:"/api/workbench/visual-evidence/settings"})).json().values.retention_days).toBe(30);const saved=await app.inject({method:"POST",url:"/api/workbench/visual-evidence/settings",payload:{command_id:"settings:http",expected_revision:0,values:{retention_days:10,automatic_cleanup:false}}});expect(saved.statusCode).toBe(200);expect(saved.json().revision).toBe(1);const invalid=await app.inject({method:"POST",url:"/api/workbench/visual-evidence/cleanup",payload:{command_id:"cleanup:arbitrary",path:"/tmp/private"}});expect(invalid.statusCode).not.toBe(200);expect((await app.inject({url:"/api/workbench/visual-evidence?limit=1000"})).statusCode).not.toBe(200);expect((await f.control.reconcile("settings:http")).state).toBe("completed");});
});
