import { useEffect, useRef, useState } from "react";
import { BrowserGrantRequestSchema, BrowserCommandSchema, type BrowserCommand, type BrowserObservation, type BrowserStatus, type HostCapabilities } from "@tracegraph/contracts";
import type { WorkbenchClient } from "../client";
import { mutationWasRejected } from "../mutation-rejection";
import { useI18n } from "../i18n";
import { capabilityAvailable, capabilityReadable, commandId, safeError } from "./UnifiedSettings";

export function BrowserPanel({ client, projectId, capabilities, online, readOnly, generation, onDiagnostics }: { client: WorkbenchClient; projectId?: string; capabilities: HostCapabilities | null; online: boolean; readOnly: boolean; generation?: number | undefined; onDiagnostics: () => void }) {
  const { t } = useI18n();
  const [status, setStatus] = useState<BrowserStatus | null>(null), [observation, setObservation] = useState<BrowserObservation | null>(null), [selected, setSelected] = useState("");
  const [url, setUrl] = useState(""), [navigationUrl, setNavigationUrl] = useState(""), [label, setLabel] = useState(""), [duration, setDuration] = useState<"once" | "always">("once"), [grantId, setGrantId] = useState("");
  const [ref, setRef] = useState(""), [text, setText] = useState(""), [busy, setBusy] = useState(false), [urgentBusy, setUrgentBusy] = useState(false), [error, setError] = useState<string | null>(null), [message, setMessage] = useState<string | null>(null);
  const [unknown, setUnknown] = useState<string | null>(null), [image, setImage] = useState<string | null>(null), [imageError, setImageError] = useState(false), [key, setKey] = useState<Extract<BrowserCommand, { type: "key" }>["key"]>("Enter");
  const objectUrl = useRef<string | null>(null), mounted = useRef(true), readVersion = useRef(0), observationVersion = useRef(0);
  const readable = online && capabilityReadable(capabilities, "browser.read") && Boolean(client.getBrowserStatus);
  const writable = online && !readOnly && capabilityAvailable(capabilities, "browser.command") && Boolean(client.browserCommand);
  const refresh = async () => { if (!readable) return; const version = ++readVersion.current; try { const next = await client.getBrowserStatus!(); if (mounted.current && version === readVersion.current) { setStatus(next); const visible = next.tabs.filter((tab) => tab.project_id === projectId && !["closed", "interrupted"].includes(tab.state)); setSelected((prior) => visible.some((tab) => tab.tab_id === prior) ? prior : visible[0]?.tab_id ?? ""); } } catch (caught) { if (mounted.current && version === readVersion.current) setError(safeError(caught)); } };
  useEffect(() => { mounted.current = true; if (readable) void refresh(); return () => { mounted.current = false; readVersion.current++; if (objectUrl.current) URL.revokeObjectURL(objectUrl.current); }; }, [client, readable, projectId, generation]);
  const tabs = status?.tabs.filter((tab) => tab.project_id === projectId && !["closed", "interrupted"].includes(tab.state)) ?? [];
  const grants = status?.grants.filter((grant) => grant.project_id === projectId && grant.state === "active") ?? [];
  const tab = tabs.find((tab) => tab.tab_id === selected);
  const display = observation?.tab.tab_id === selected ? observation : null;
  useEffect(() => { setNavigationUrl(tab?.url ?? ""); }, [selected, tab?.url]);
  useEffect(() => { observationVersion.current++; setObservation(null); setRef(""); setImage(null); setImageError(false); if (objectUrl.current) { URL.revokeObjectURL(objectUrl.current); objectUrl.current = null; } }, [selected, online, readOnly, generation]);
  const observe = async () => {
    if (!selected || busy || !online || readOnly || !capabilityAvailable(capabilities, "browser.observe") || !capabilityReadable(capabilities, "browser.evidence.read") || !client.observeBrowser || !client.getBrowserEvidence) return;
    setBusy(true); setError(null); setImageError(false);
    const currentTab = selected, version = ++observationVersion.current;
    try {
      const next = await client.observeBrowser(currentTab), bytes = await client.getBrowserEvidence(next.evidence.evidence_id);
      if (bytes.evidenceId !== next.evidence.evidence_id || bytes.sha256 !== next.evidence.sha256 || bytes.bytes.byteLength !== next.evidence.byte_length) throw new Error("Browser evidence does not match the observed revision.");
      const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", Uint8Array.from(bytes.bytes).buffer));
      if (`sha256:${[...digest].map((value) => value.toString(16).padStart(2, "0")).join("")}` !== next.evidence.sha256) throw new Error("Browser evidence failed its content verification.");
      if (!mounted.current || version !== observationVersion.current) return;
      if (objectUrl.current) URL.revokeObjectURL(objectUrl.current);
      objectUrl.current = URL.createObjectURL(new Blob([Uint8Array.from(bytes.bytes).buffer], { type: "image/png" }));
      setImage(objectUrl.current); setObservation(next); setStatus((prior) => prior ? { ...prior, tabs: prior.tabs.map((tab) => tab.tab_id === next.tab.tab_id ? next.tab : tab) } : prior); setRef("");
    } catch (caught) { if (mounted.current && version === observationVersion.current) setError(safeError(caught)); }
    finally { if (mounted.current) setBusy(false); }
  };
  const execute = async (input: BrowserCommand, urgent = false) => {
    if (!writable || (urgent ? urgentBusy : busy || unknown !== null)) return;
    const parsed = BrowserCommandSchema.parse(input); urgent ? setUrgentBusy(true) : setBusy(true); setError(null); setMessage(null);
    try { const receipt = await client.browserCommand!(parsed); if (!mounted.current) return; setMessage(`${t("Browser action completed")}: ${t(parsed.type)} · ${receipt.command_id}`); if (receipt.tab) { setSelected(receipt.tab.tab_id); setObservation(null); setImage(null); } await refresh(); }
    catch (caught) { if (mounted.current) { setError(safeError(caught)); if (!mutationWasRejected(caught)) setUnknown((prior) => prior ?? parsed.command_id); } }
    finally { if (mounted.current) urgent ? setUrgentBusy(false) : setBusy(false); }
  };
  const grant = async () => {
    if (!projectId || !online || readOnly || busy || unknown || !status?.human_grant_available || !capabilityAvailable(capabilities, "browser.grant") || !client.requestBrowserGrant) return;
    let input; try { input = BrowserGrantRequestSchema.parse({ command_id: commandId(), project_id: projectId, label, duration, origins: [new URL(url).origin] }); } catch { setError(t("Enter a label and an exact HTTP or HTTPS address without credentials.")); return; }
    setBusy(true); setError(null);
    try { const receipt = await client.requestBrowserGrant(input); if (mounted.current) { setGrantId(receipt.grant_id); setMessage(t("Browser permission saved. Open the address explicitly to begin.")); await refresh(); } }
    catch (caught) { if (mounted.current) { setError(safeError(caught)); if (!mutationWasRejected(caught)) setUnknown(input.command_id); } }
    finally { if (mounted.current) setBusy(false); }
  };
  const inspectUnknown = async () => {
    if (!unknown || !online || busy || !client.getBrowserCommandReceipt || !capabilityReadable(capabilities, "browser.read")) return;
    const id = unknown; setBusy(true); setError(null);
    try {
      const receipt = await client.getBrowserCommandReceipt(id);
      if (!mounted.current || receipt.command_id !== id) { if (mounted.current) throw new Error("Browser receipt does not match the original command."); return; }
      if (receipt.state === "completed" && receipt.result?.command_id === id) {
        if (receipt.result.tab) setSelected(receipt.result.tab.tab_id);
        if (receipt.result.grant) setGrantId(receipt.result.grant.grant_id);
        setUnknown(null); setMessage(t("The original browser action has a verified completion receipt. It was not repeated.")); await refresh();
      } else if (receipt.state === "failed" && mutationWasRejected({ status: 409, body: { error: receipt.code } })) {
        setUnknown(null); setMessage(t("The original browser action was refused before execution. Review its reason before sending a new action."));
      } else setMessage(`${t("Browser action is not reconciled")}: ${t(receipt.state)}${receipt.code ? ` · ${receipt.code}` : ""}`);
    } catch (caught) { if (mounted.current) setError(safeError(caught)); }
    finally { if (mounted.current) setBusy(false); }
  };
  return <section className="browser-workspace"><header><h2>{t("Browser")}</h2><button className="button subtle" disabled={!readable || busy} onClick={() => void refresh()} type="button">{t("Refresh")}</button></header><p>{t("Browser authority is separate from file permissions. Actions use the exact observed tab revision and element reference.")}</p>
    {!projectId && <p className="panel-empty">{t("Add or select a project before granting browser access.")}</p>}{!online && <p role="status">{t("Reconnect to load browser status. Existing tabs are not reopened automatically.")}</p>}{readOnly && <p>{t("Replay is read-only. Return to now to make changes.")}</p>}
    {status && !status.available && <div className="feature-repair"><p>{status.reason ?? t("The matching browser component is missing.")}</p><button className="button subtle" onClick={onDiagnostics} type="button">{t("Installation diagnostics")}</button></div>}
    {!status && online && <p>{t(readable ? "Loading browser status…" : "Browser availability has not been confirmed on this installation.")}</p>}
    {error && <p role="alert">{t(error)}</p>}{message && <p role="status">{message}</p>}{unknown && <div role="alert"><p>{t("This browser action has an unknown outcome. Inspect the current tab before any further action; it was not repeated.")}</p><code>{unknown}</code><button className="button subtle" disabled={!online || busy || !client.getBrowserCommandReceipt || !capabilityReadable(capabilities, "browser.read")} onClick={() => void inspectUnknown()} type="button">{t("Inspect original browser action")}</button></div>}
    {status?.available && projectId && <><details className="browser-grants"><summary>{t("Browser permissions")}: {grants.length}</summary>{grants.map((permission) => <div className="settings-extension-row" key={permission.grant_id}><span>{permission.label}<small>{permission.origins.join(", ")} · {t(permission.duration)}</small></span><button className="button danger" disabled={!writable || busy || Boolean(unknown)} onClick={() => void execute({ type: "revoke", command_id: commandId(), grant_id: permission.grant_id, expected_revision: permission.revision })} type="button">{t("Revoke")}</button></div>)}<label>{t("Browser permission label")}<input aria-label={t("Browser permission label")} value={label} onChange={(event) => setLabel(event.target.value)} /></label><label>{t("Browser address")}<input aria-label={t("Browser address")} type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com" /></label><label>{t("Permission duration")}<select aria-label={t("Browser permission duration")} value={duration} onChange={(event) => setDuration(event.target.value as typeof duration)}><option value="once">{t("Once")}</option><option value="always">{t("Always until revoked")}</option></select></label><button className="button subtle" disabled={!online || readOnly || busy || Boolean(unknown) || !status.human_grant_available || !capabilityAvailable(capabilities, "browser.grant")} onClick={() => void grant()} type="button">{t("Request browser permission")}</button>{!status.human_grant_available && <p>{t("Browser permission requires a trusted native confirmation. Open this profile in Desktop to request it.")}</p>}</details>
      <div className="browser-open-row"><select aria-label={t("Approved browser permission")} value={grantId} onChange={(event) => setGrantId(event.target.value)}><option value="">{t("Choose approved permission")}</option>{grants.map((permission) => <option key={permission.grant_id} value={permission.grant_id}>{permission.label}</option>)}</select><input aria-label={t("Open browser address")} type="url" value={url} onChange={(event) => setUrl(event.target.value)} /><button className="button subtle" disabled={!writable || busy || Boolean(unknown) || !grantId || !url.trim()} onClick={() => { try { void execute(BrowserCommandSchema.parse({ type: "open", command_id: commandId(), grant_id: grantId, url })); } catch { setError(t("Enter an HTTP or HTTPS address within the approved origin.")); } }} type="button">{t("Open browser tab")}</button></div>
      {tabs.length > 0 && <select aria-label={t("Browser tab")} value={selected} onChange={(event) => setSelected(event.target.value)}>{tabs.map((tab) => <option key={tab.tab_id} value={tab.tab_id}>{tab.title || tab.url} · {t(tab.state)}</option>)}</select>}
      {tab && <><p className="setting-metadata">{tab.url} · {t("Revision")} {tab.revision} · {t(tab.state)}</p><div className="settings-button-row"><button className="button subtle" disabled={busy || !online || readOnly || !capabilityAvailable(capabilities, "browser.observe")} onClick={() => void observe()} type="button">{t("Observe browser")}</button><button className="button subtle" disabled={!writable || urgentBusy} onClick={() => void execute({ type: "takeover", command_id: commandId(), tab_id: tab.tab_id }, true)} type="button">{t("Take control")}</button>{tab.state === "human" && <button className="button subtle" disabled={!writable || busy || Boolean(unknown)} onClick={() => { if (window.confirm(t("Return this tab to Agent control within its existing browser permission?"))) void execute({ type: "return-control", command_id: commandId(), tab_id: tab.tab_id, expected_revision: tab.revision }); }} type="button">{t("Return control")}</button>}<button className="button subtle" disabled={!writable || urgentBusy} onClick={() => void execute({ type: "close", command_id: commandId(), tab_id: tab.tab_id }, true)} type="button">{t("Close browser tab")}</button></div></>}
      {tab && <form className="browser-open-row" onSubmit={(event) => { event.preventDefault(); try { void execute(BrowserCommandSchema.parse({ type: "navigate", command_id: commandId(), tab_id: tab.tab_id, expected_revision: tab.revision, url: navigationUrl })); } catch { setError(t("Enter an HTTP or HTTPS address within the approved origin.")); } }}><input aria-label={t("Navigate browser address")} type="url" value={navigationUrl} onChange={(event) => setNavigationUrl(event.target.value)} /><button className="button subtle" disabled={!writable || busy || Boolean(unknown) || tab.state !== "agent"} type="submit">{t("Navigate browser")}</button></form>}
      {display && <><figure className="browser-observation">{image && !imageError ? <img alt={t("Verified browser observation")} src={image} onError={() => setImageError(true)} /> : <p role="alert">{t("The verified browser image could not be displayed. Observe the tab again.")}</p>}<figcaption>{display.evidence.evidence_id} · {display.evidence.sha256} · {t("Revision")} {display.tab.revision}</figcaption></figure><h3>{t("Observed elements")}</h3><select aria-label={t("Browser element")} value={ref} onChange={(event) => setRef(event.target.value)}><option value="">{t("Choose observed element")}</option>{display.elements.map((element) => <option key={element.ref} value={element.ref}>{element.role} · {element.text || element.ref}</option>)}</select><input aria-label={t("Browser input text")} value={text} onChange={(event) => setText(event.target.value)} /><div className="settings-button-row"><button className="button subtle" disabled={!writable || busy || Boolean(unknown) || !ref || tab?.state !== "agent"} onClick={() => void execute({ type: "click", command_id: commandId(), tab_id: display.tab.tab_id, expected_revision: display.tab.revision, ref })} type="button">{t("Click selected element")}</button><button className="button subtle" disabled={!writable || busy || Boolean(unknown) || !ref || tab?.state !== "agent"} onClick={() => void execute({ type: "fill", command_id: commandId(), tab_id: display.tab.tab_id, expected_revision: display.tab.revision, ref, text })} type="button">{t("Fill selected element")}</button><select aria-label={t("Browser key")} value={key} onChange={(event) => setKey(event.target.value as typeof key)}>{["Enter", "Escape", "Tab", "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"].map((value) => <option key={value} value={value}>{value}</option>)}</select><button className="button subtle" disabled={!writable || busy || Boolean(unknown) || tab?.state !== "agent"} onClick={() => void execute({ type: "key", command_id: commandId(), tab_id: display.tab.tab_id, expected_revision: display.tab.revision, key })} type="button">{t("Send browser key")}</button></div></>}
      <details><summary>{t("Browser runtime diagnostics")}</summary><p>{status.runtime}</p><p>{t("Native input monitoring and existing Chrome-tab connection require their own platform capability. They are not inferred from this isolated browser.")}</p></details></>}
  </section>;
}
