import { useEffect, useRef, useState } from "react";
import type { WorkbenchSnapshot } from "../model";
import { useI18n } from "../i18n";
import { Icon } from "./Icon";

export function CommandPalette({ snapshot, onClose, onSearch, onSession, onNewChat, onSettings, onMemory, onResources, onReview, onCreateMedia, onHistorySearch }: {
  snapshot: WorkbenchSnapshot; onClose: () => void; onSearch: (query: string) => Promise<void>; onSession: (sessionId: string) => Promise<void>; onNewChat: () => Promise<void>; onSettings: () => void; onMemory: () => void; onResources: () => void; onReview: () => void; onCreateMedia?: () => void; onHistorySearch?: () => void;
}) {
  const { t } = useI18n(); const [query, setQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [selected, setSelected] = useState(0); const input = useRef<HTMLInputElement>(null);
  const actions = [...(onHistorySearch ? [["Search public history", onHistorySearch] as const] : []), ["New chat", onNewChat], ["Settings", onSettings], ["Memory", onMemory], ["Workspace tools", onResources], ["Review changes", onReview], ...(onCreateMedia ? [["Create media", onCreateMedia] as const] : [])] as const;
  const commands = [...actions.filter(([label]) => t(label).toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(([label, run]) => ({ id: label, title: t(label), run })), ...snapshot.sessions.filter((session) => (session.title ?? session.session_id).toLocaleLowerCase().includes(query.toLocaleLowerCase())).map((session) => ({ id: session.session_id, title: session.title ?? session.session_id, run: () => onSession(session.session_id) }))];
  useEffect(() => { input.current?.focus(); }, []);
  useEffect(() => { setSelected(0); const timer = window.setTimeout(() => { void onSearch(query).catch((caught) => setError(caught instanceof Error ? caught.message : String(caught))); }, 200); return () => window.clearTimeout(timer); }, [query]);
  const invoke = (index: number) => { const command = commands[index]; if (!command) return; Promise.resolve().then(command.run).then(onClose).catch((caught) => setError(caught instanceof Error ? caught.message : String(caught))); };
  return <div className="command-palette-backdrop" onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="command-palette" role="dialog" aria-modal="true" aria-label={t("Command palette")} onKeyDown={(event) => { if (event.nativeEvent.isComposing) return; if (event.key === "Escape") { event.stopPropagation(); onClose(); } if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setSelected((index) => Math.max(0, Math.min(commands.length - 1, index + (event.key === "ArrowDown" ? 1 : -1)))); } if (event.key === "Enter") { event.preventDefault(); invoke(selected); } }}><label><Icon name="search" size={17} /><input aria-label={t("Search commands and sessions")} ref={input} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("Search commands and sessions")} aria-controls="palette-results" aria-activedescendant={commands[selected] ? `palette-result-${selected}` : undefined} role="combobox" aria-expanded="true" /></label><div id="palette-results" role="listbox">{commands.map((command, index) => <button id={`palette-result-${index}`} role="option" aria-selected={selected === index} className={selected === index ? "active" : ""} key={command.id} onClick={() => invoke(index)} type="button">{command.title}</button>)}{commands.length === 0 && <p>{t("No results")}</p>}</div>{error && <p role="alert">{error}</p>}<footer>↑↓ {t("Navigate")} · Enter {t("Open")} · Esc {t("Close")}</footer></section></div>;
}
