import { useEffect, useState } from "react";
import { GoalCreateRequestSchema, GoalProposalSchema, type GoalCommandRequest, type GoalSnapshot, type HostCapabilities } from "@tracegraph/contracts";
import type { WorkbenchClient } from "../client";
import { mutationWasRejected } from "../mutation-rejection";
import { useI18n } from "../i18n";
import { Icon } from "./Icon";
import { capabilityAvailable, capabilityReadable, commandId, safeError } from "./UnifiedSettings";

export function GoalWorkspace({ client, projectId, sessionId, capabilities, online, readOnly, initialCreate = false, onClose, onInspectRun }: { client: WorkbenchClient; projectId?: string; sessionId?: string; capabilities: HostCapabilities | null; online: boolean; readOnly: boolean; initialCreate?: boolean; onClose: () => void; onInspectRun?: (runId: string) => Promise<void> }) {
  const { t } = useI18n();
  const [goals, setGoals] = useState<readonly GoalSnapshot[]>([]), [selected, setSelected] = useState<string | null>(null), [form, setForm] = useState(initialCreate), [editing, setEditing] = useState<GoalSnapshot | null>(null), [visibleCount, setVisibleCount] = useState(100);
  const [title, setTitle] = useState(""), [objective, setObjective] = useState(""), [conditions, setConditions] = useState(""), [tokens, setTokens] = useState(""), [minutes, setMinutes] = useState("");
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [unknown, setUnknown] = useState<{ command_id: string; goal_id?: string } | null>(null), [message, setMessage] = useState<string | null>(null), [accepted, setAccepted] = useState<ReadonlySet<string>>(new Set()), [acknowledge, setAcknowledge] = useState(false);
  const readable = online && capabilityReadable(capabilities, "goals.read") && Boolean(client.listGoals);
  const writable = online && !readOnly && !busy && unknown === null && capabilityAvailable(capabilities, "goals.write") && Boolean(client.createGoal && client.goalCommand);
  const goal = goals.find((goal) => goal.goal_id === selected);
  const read = async () => { if (!readable) return; setLoading(true); try { const snapshot = await client.listGoals!(); setGoals(snapshot.goals); setSelected((current) => current && snapshot.goals.some((goal) => goal.goal_id === current) ? current : snapshot.goals[0]?.goal_id ?? null); } catch (caught) { setError(safeError(caught)); } finally { setLoading(false); } };
  useEffect(() => { if (!readable) { setLoading(false); return; } let current = true; setLoading(true); void client.listGoals!().then((snapshot) => { if (current) { setGoals(snapshot.goals); setSelected((prior) => prior ?? snapshot.goals[0]?.goal_id ?? null); } }).catch((caught) => { if (current) setError(safeError(caught)); }).finally(() => { if (current) setLoading(false); }); return () => { current = false; }; }, [client, readable]);
  useEffect(() => { setAccepted(new Set()); setAcknowledge(false); }, [selected, goal?.proposal_revision]);
  useEffect(() => { if (!readable || !goal || goal.status !== "running" || !client.getGoal) return; let current = true; const timer = window.setInterval(() => { void client.getGoal!(goal.goal_id).then((next) => { if (current) setGoals((prior) => prior.map((item) => item.goal_id === next.goal_id ? next : item)); }).catch((caught) => { if (current) setError(safeError(caught)); }); }, 3_000); return () => { current = false; window.clearInterval(timer); }; }, [client, readable, goal?.goal_id, goal?.status]);
  const receive = (next: GoalSnapshot) => { setGoals((prior) => [next, ...prior.filter((goal) => goal.goal_id !== next.goal_id)]); setSelected(next.goal_id); };
  const failure = (caught: unknown, id: string, goalId?: string) => { setError(safeError(caught)); if (!mutationWasRejected(caught)) setUnknown({ command_id: id, ...(goalId ? { goal_id: goalId } : {}) }); };
  const command = async (input: GoalCommandRequest) => { if (!goal || !writable) return; setBusy(true); setError(null); try { receive(await client.goalCommand!(goal.goal_id, input)); } catch (caught) { failure(caught, input.command_id, goal.goal_id); } finally { setBusy(false); } };
  const save = async () => {
    if (!writable || !projectId) return;
    let input;
    try { input = GoalCreateRequestSchema.parse({ command_id: commandId(), project_id: editing?.proposal.project_id ?? projectId, ...((editing?.proposal.session_id ?? sessionId) ? { session_id: editing?.proposal.session_id ?? sessionId } : {}), title, objective, done_conditions: conditions.split("\n").map((line) => line.trim()).filter(Boolean), budget: { ...(tokens.trim() ? { max_tokens: Number(tokens) } : {}), ...(minutes.trim() ? { max_time_ms: Math.round(Number(minutes) * 60_000) } : {}) } }); }
    catch { setError(t("Provide a title, objective, distinct completion conditions and at least one finite token or time limit.")); return; }
    setBusy(true); setError(null);
    try { const next = editing ? await client.goalCommand!(editing.goal_id, { command_id: input.command_id, expected_revision: editing.revision, operation: "revise", proposal: GoalProposalSchema.parse({ ...editing.proposal, title: input.title, objective: input.objective, done_conditions: input.done_conditions, budget: input.budget }) }) : await client.createGoal!(input); receive(next); setForm(false); setEditing(null); }
    catch (caught) { failure(caught, input.command_id, editing?.goal_id); }
    finally { setBusy(false); }
  };
  const openForm = (existing?: GoalSnapshot) => { setEditing(existing ?? null); setTitle(existing?.proposal.title ?? ""); setObjective(existing?.proposal.objective ?? ""); setConditions(existing?.proposal.done_conditions.join("\n") ?? ""); setTokens(existing?.proposal.budget.max_tokens?.toString() ?? ""); setMinutes(existing?.proposal.budget.max_time_ms ? String(existing.proposal.budget.max_time_ms / 60_000) : ""); setError(null); setForm(true); };
  const inspectUnknown = async () => {
    if (!unknown || !online || busy || !(unknown.goal_id ? client.getGoalCommandReceipt : client.getGoalCreationReceipt) || !capabilityReadable(capabilities, "goals.read")) return;
    setBusy(true); setError(null);
    try {
      const receipt = unknown.goal_id ? await client.getGoalCommandReceipt!(unknown.goal_id, unknown.command_id) : await client.getGoalCreationReceipt!(unknown.command_id);
      if (receipt.command_id !== unknown.command_id || unknown.goal_id && receipt.goal_id !== unknown.goal_id) throw new Error("Goal receipt does not match the original command.");
      if (receipt.state === "completed" && receipt.result) { receive(receipt.result); setUnknown(null); setForm(false); setMessage(t("The original Goal command has a verified completion receipt. It was not repeated.")); }
      else if (receipt.state === "failed" && mutationWasRejected({ status: 409, body: { error: receipt.code } })) { setUnknown(null); setMessage(t("The original Goal command was refused. Review the current proposal before sending another command.")); }
      else setMessage(`${t("Goal command is not reconciled")}: ${t(receipt.state)}${receipt.code ? ` · ${receipt.code}` : ""}`);
    } catch (caught) { setError(safeError(caught)); }
    finally { setBusy(false); }
  };
  return <section className="goal-workspace product-page" aria-label={t("Goals")}><header><div><h1>{t("Goals")}</h1><p>{t("Approve a finite scope and budget, inspect the work, then make the final acceptance decision yourself.")}</p></div><button className="icon-button" aria-label={t("Close Goals")} onClick={onClose} type="button"><Icon name="close" size={16} /></button></header><div className="settings-button-row"><button className="button subtle" disabled={!readable || busy} onClick={() => void read()} type="button">{t("Refresh")}</button><button className="button primary" disabled={!writable || !projectId} onClick={() => openForm()} type="button">{t("New Goal")}</button></div>
    {!projectId && <p>{t("Add or select a project before creating a Goal. Existing Goals can still be inspected.")}</p>}{!online && <p>{t("Reconnect to inspect Goals. Work is never resumed automatically by opening this page.")}</p>}{online && !readable && <p>{t("Goal controls are unavailable on this installation. Your ordinary conversations are still available.")}</p>}{error && <p role="alert">{t(error)}</p>}{message && <p role="status">{message}</p>}{unknown && <div role="alert"><p>{t("This Goal command has an unknown outcome. Refresh and inspect its original state before any further write. It was not repeated.")}</p><code>{unknown.command_id}</code><button className="button subtle" disabled={!online || busy || !(unknown.goal_id ? client.getGoalCommandReceipt : client.getGoalCreationReceipt) || !capabilityReadable(capabilities, "goals.read")} onClick={() => void inspectUnknown()} type="button">{t("Inspect original Goal command")}</button></div>}
    {form && <form className="goal-proposal-form" onSubmit={(event) => { event.preventDefault(); void save(); }}><h2>{t(editing ? "Revise Goal proposal" : "New Goal proposal")}</h2><label>{t("Goal title")}<input aria-label={t("Goal title")} maxLength={200} required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>{t("Objective")}<textarea aria-label={t("Goal objective")} maxLength={8000} rows={4} required value={objective} onChange={(event) => setObjective(event.target.value)} /></label><label>{t("Completion conditions, one per line")}<textarea aria-label={t("Goal completion conditions")} required rows={4} value={conditions} onChange={(event) => setConditions(event.target.value)} /></label><div className="goal-budget-input"><label>{t("Total token limit")}<input aria-label={t("Goal token limit")} type="number" min={1} max={100000000} value={tokens} onChange={(event) => setTokens(event.target.value)} /></label><label>{t("Total time limit in minutes")}<input aria-label={t("Goal time limit")} type="number" min={0.01} max={10080} step="any" value={minutes} onChange={(event) => setMinutes(event.target.value)} /></label></div><p>{t("Budget is shared across admitted work and recovery; revising a Goal does not erase spent usage. Costs remain unknown when the provider does not report them.")}</p>{editing && <p>{t("Saving a revised proposal invalidates its previous approval.")}</p>}<div className="settings-button-row"><button className="button primary" disabled={!writable} type="submit">{t("Save Goal proposal")}</button><button className="button subtle" disabled={busy} onClick={() => setForm(false)} type="button">{t("Cancel")}</button></div></form>}
    {!form && <div className="goal-content"><nav aria-label={t("Goal list")}>{goals.slice(0, visibleCount).map((item) => <button key={item.goal_id} aria-current={selected === item.goal_id ? "page" : undefined} onClick={() => setSelected(item.goal_id)} type="button"><strong>{item.proposal.title}</strong><small>{t(item.status)} · {t("Revision")} {item.revision}</small></button>)}{goals.length > visibleCount && <button className="button subtle" onClick={() => setVisibleCount((count) => count + 100)} type="button">{t("Show more Goals")}</button>}</nav>{loading ? <p role="status">{t("Loading…")}</p> : goal ? <article><header><h2>{goal.proposal.title}</h2><span className={`goal-status status-${goal.status}`}>{t(goal.status)}</span></header><p>{goal.proposal.objective}</p><div className="goal-budget-facts"><strong>{t("Budget")}</strong><span>{t("Charged tokens")}: {goal.budget.charged_tokens} / {goal.budget.limits.max_tokens ?? t("No token ceiling")}</span><span>{t("Reserved tokens")}: {goal.budget.held_tokens} · {t("Reserved requests")}: {goal.budget.held_request_count}</span><span>{t("Elapsed")}: {Math.round(goal.budget.elapsed_ms / 1000)}s / {goal.budget.limits.max_time_ms ? `${Math.round(goal.budget.limits.max_time_ms / 1000)}s` : t("No time ceiling")}</span><span>{t("Requests")}: {goal.budget.request_count} · {t("Unknown usage")}: {goal.budget.unknown_request_count}</span>{goal.budget.stop_reason && <p role="status">{t("Stopped because")}: {t(goal.budget.stop_reason)}</p>}</div><h3>{t("Completion conditions")}</h3><div className="goal-conditions">{goal.proposal.done_conditions.map((condition) => <label key={condition}><input type="checkbox" disabled={goal.status !== "awaiting_final_acceptance" || !writable} checked={accepted.has(condition)} onChange={(event) => setAccepted((prior) => { const next = new Set(prior); event.target.checked ? next.add(condition) : next.delete(condition); return next; })} /><span>{condition}</span></label>)}</div><p className="setting-metadata">{t("Proposal revision")}: {goal.proposal_revision} · {t("Approved revision")}: {goal.approved_proposal_revision ?? t("Not approved")}</p><div className="settings-button-row">
      {goal.status === "awaiting_approval" && <button className="button primary" disabled={!writable} onClick={() => { if (window.confirm(t("Approve this exact Goal proposal, scope, completion conditions and finite budget?"))) void command({ operation: "approve", command_id: commandId(), expected_revision: goal.revision, proposal_revision: goal.proposal_revision }); }} type="button">{t("Approve Goal proposal")}</button>}
      {goal.status === "approved" && <button className="button primary" disabled={!writable} onClick={() => void command({ operation: "start", command_id: commandId(), expected_revision: goal.revision })} type="button">{t("Start Goal")}</button>}
      {goal.status === "running" && <button className="button subtle" disabled={!writable} onClick={() => void command({ operation: "pause", command_id: commandId(), expected_revision: goal.revision })} type="button">{t("Pause Goal")}</button>}
      {["paused", "blocked"].includes(goal.status) && <button className="button primary" disabled={!writable || goal.budget.unknown_request_count > 0 && !acknowledge || ["unknown_side_effect", "launch_unknown"].includes(goal.last_run_status ?? "")} onClick={() => void command({ operation: "resume", command_id: commandId(), expected_revision: goal.revision, ...(goal.budget.unknown_request_count > 0 ? { acknowledge_unknown_usage: true } : {}) })} type="button">{t("Resume Goal explicitly")}</button>}
      {goal.status === "awaiting_final_acceptance" && <button className="button primary" disabled={!writable || accepted.size !== goal.proposal.done_conditions.length} onClick={() => { if (window.confirm(t("I have reviewed the recorded work and explicitly accept every completion condition."))) void command({ operation: "accept", command_id: commandId(), expected_revision: goal.revision, confirmed: true, accepted_conditions: [...accepted] }); }} type="button">{t("Accept completed Goal")}</button>}
      {!["completed", "cancelled", "running"].includes(goal.status) && <button className="button subtle" disabled={!writable} onClick={() => openForm(goal)} type="button">{t("Revise proposal")}</button>}
      {!["completed", "cancelled"].includes(goal.status) && <button className="button danger" disabled={!writable} onClick={() => { if (window.confirm(t("Cancel this Goal and stop its active work at a safe boundary?"))) void command({ operation: "cancel", command_id: commandId(), expected_revision: goal.revision }); }} type="button">{t("Cancel Goal")}</button>}</div>
      {goal.budget.unknown_request_count > 0 && <label className="goal-unknown-consent"><input type="checkbox" checked={acknowledge} onChange={(event) => setAcknowledge(event.target.checked)} />{t("I reviewed the unknown usage. Its full reservation remains charged before continuing.")}</label>}{["unknown_side_effect", "launch_unknown"].includes(goal.last_run_status ?? "") && <p role="alert">{t("Unknown work must be reconciled before a new execution can be admitted.")}</p>}
      {goal.run_ids.length > 0 && <section><h3>{t("Recorded tasks")}</h3>{goal.run_ids.map((id) => <button className="button subtle" key={id} disabled={!onInspectRun || busy} onClick={() => { setBusy(true); void onInspectRun?.(id).catch((caught) => setError(safeError(caught))).finally(() => setBusy(false)); }} type="button">{t("Inspect task")}: {id}</button>)}</section>}<details><summary>{t("Goal receipt")}</summary><code>{goal.receipt_event_id}</code><p>{t("A successful task is awaiting your final acceptance; it is not automatically a completed Goal.")}</p></details></article> : <p>{t("No Goals yet. Create one with a project and a finite total budget.")}</p>}</div>}
  </section>;
}
