import { useEffect, useRef, useState } from "react";
import { PublicSessionSearchQuerySchema, RunStatusSchema, type HostCapabilities, type PublicSessionSearchHit, type PublicSessionSearchQuery, type PublicSessionSearchResult } from "@tracegraph/contracts";
import type { WorkbenchClient } from "../client";
import { useI18n } from "../i18n";
import { Icon } from "./Icon";
import { capabilityReadable, safeError } from "./UnifiedSettings";

const hitKey = (hit: PublicSessionSearchHit) => `${hit.run_id}:${hit.event_id}:${hit.source}:${hit.path ?? ""}:${hit.turn_id ?? ""}`;
export function PublicSessionSearch({ client, capabilities, online, generation, onClose, onOpenResult }: { client: WorkbenchClient; capabilities: HostCapabilities | null; online: boolean; generation?: number | undefined; onClose: () => void; onOpenResult: (hit: PublicSessionSearchHit) => Promise<void> }) {
  const { t } = useI18n(); const [q, setQ] = useState(""), [project, setProject] = useState(""), [session, setSession] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState(""), [status, setStatus] = useState(""), [archive, setArchive] = useState<PublicSessionSearchQuery["archive"]>("active");
  const [result, setResult] = useState<PublicSessionSearchResult | null>(null), [hits, setHits] = useState<PublicSessionSearchHit[]>([]), [query, setQuery] = useState<PublicSessionSearchQuery | null>(null), [loading, setLoading] = useState(false), [opening, setOpening] = useState<string | null>(null), [error, setError] = useState<string | null>(null);
  const readVersion = useRef(0), readable = online && capabilityReadable(capabilities, "search.public") && Boolean(client.searchPublicSessions);
  const dialog = useRef<HTMLElement>(null), closeAction = useRef(onClose); closeAction.current = onClose;
  useEffect(() => { const previous = document.activeElement; const element = dialog.current; element?.querySelector<HTMLInputElement>("input")?.focus(); const handle = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); closeAction.current(); return; } if (event.key !== "Tab" || !element) return; const controls = [...element.querySelectorAll<HTMLElement>("button:not([disabled]), input:not([disabled]), select:not([disabled])")], first = controls[0], last = controls.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }; element?.addEventListener("keydown", handle); return () => { element?.removeEventListener("keydown", handle); if (previous instanceof HTMLElement) previous.focus(); }; }, []);
  useEffect(() => { setLoading(false); return () => { readVersion.current++; }; }, [client, online, generation]);
  const load = async (input: PublicSessionSearchQuery, append: boolean) => {
    if (!readable || loading) return; const version = ++readVersion.current; setLoading(true); setError(null);
    try { const next = await client.searchPublicSessions!(input); if (version !== readVersion.current) return; if (next.query !== input.q) throw new Error("Search results do not match the submitted query."); const { cursor: _cursor, ...base } = input; setQuery(base); setResult(next); setHits((prior) => { const existing = append ? prior : [], keys = new Set(existing.map(hitKey)); return [...existing, ...next.hits.filter((hit) => { const key = hitKey(hit); if (keys.has(key)) return false; keys.add(key); return true; })]; }); }
    catch (caught) { if (version === readVersion.current) setError(safeError(caught)); }
    finally { if (version === readVersion.current) setLoading(false); }
  };
  const submit = () => { let input; try { input = PublicSessionSearchQuerySchema.parse({ q, archive, limit: 20, ...(project ? { project_id: project } : {}), ...(session ? { session_id: session } : {}), ...(from ? { from: new Date(from).toISOString() } : {}), ...(to ? { to: new Date(to).toISOString() } : {}), ...(status ? { status } : {}) }); } catch { setError(t("Enter a search phrase of at most 200 characters and a valid time range.")); return; } void load(input, false); };
  const open = async (hit: PublicSessionSearchHit) => { if (!online || opening !== null) return; setOpening(hitKey(hit)); setError(null); try { await onOpenResult(hit); onClose(); } catch (caught) { setError(safeError(caught)); } finally { setOpening(null); } };
  return <section ref={dialog} className="public-session-search product-page" role="dialog" aria-modal="true" aria-label={t("Search public history")}><header><div><h2>{t("Search public history")}</h2><p>{t("Search saved titles, public tasks, answers and file references. Private reasoning, credentials and raw tool arguments are excluded.")}</p></div><button className="icon-button" aria-label={t("Close history search")} onClick={onClose} type="button"><Icon name="close" size={16} /></button></header>
    <form onSubmit={(event) => { event.preventDefault(); submit(); }}><label className="settings-search"><Icon name="search" size={14} /><input autoFocus aria-label={t("Public history query")} value={q} maxLength={200} onChange={(event) => setQ(event.target.value)} placeholder={t("Search tasks, answers or file names")} /></label><div className="usage-filter-row"><label>{t("Project")}<select aria-label={t("History search project")} value={project} onChange={(event) => { setProject(event.target.value); setSession(""); }}><option value="">{t("All projects")}</option>{client.getSnapshot().availableProjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t("Session")}<select aria-label={t("History search session")} value={session} onChange={(event) => setSession(event.target.value)}><option value="">{t("All sessions")}</option>{client.getSnapshot().sessions.filter((item) => !project || item.project_id === project).map((item) => <option key={item.session_id} value={item.session_id}>{item.title ?? item.session_id}</option>)}</select></label><label>{t("From")}<input aria-label={t("History search from")} type="datetime-local" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>{t("To")}<input aria-label={t("History search to")} type="datetime-local" value={to} onChange={(event) => setTo(event.target.value)} /></label><label>{t("Status")}<select aria-label={t("History search status")} value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{t("All task states")}</option>{RunStatusSchema.options.map((value) => <option key={value} value={value}>{t(value)}</option>)}</select></label><label>{t("Archive")}<select aria-label={t("History search archive")} value={archive} onChange={(event) => setArchive(event.target.value as typeof archive)}><option value="active">{t("Active conversations")}</option><option value="archived">{t("Archived conversations")}</option><option value="all">{t("All conversations")}</option></select></label><button className="button primary" disabled={!readable || loading || !q.trim()} type="submit">{t("Search")}</button></div></form>
    {!online && <p role="status">{t("Reconnect to search or open recorded tasks. Your query and existing results are preserved.")}</p>}{online && !readable && <p>{t("Public history search is unavailable in this installation. Recent conversations remain available in the sidebar.")}</p>}{error && <p role="alert">{t(error)}</p>}{loading && <p role="status">{t("Searching saved public records…")}</p>}{result && <><p className="setting-metadata">{t("Results follow the saved inventory scan order; they are not a global relevance ranking.")} · {t("As of")}: {result.page.as_of}</p><div className="public-search-results">{hits.map((hit) => <article key={hitKey(hit)}><button className="public-search-hit" disabled={!online || opening !== null} onClick={() => void open(hit)} type="button"><strong>{hit.title || t("Untitled task")}</strong><span>{hit.excerpt}</span><small>{t(hit.source)} · {t(hit.status)} · {hit.occurred_at}{hit.archived ? ` · ${t("Archived")}` : ""}</small>{hit.path && <code>{hit.path}</code>}</button></article>)}</div>{hits.length === 0 && <p>{t(result.page.complete && result.page.inventory_complete ? "No matching public records were found." : "No matches in the records scanned so far. Continue the scan if more records are available.")}</p>}<div role="status"><p>{t(result.page.complete && result.page.inventory_complete && result.page.skipped_runs === 0 && result.page.skipped_events === 0 ? "The available inventory scan is complete." : "Search is partial; some records have not been scanned or could not be read.")}</p><small>{t("Scanned tasks")}: {result.page.total_scanned_runs} · {t("Skipped tasks")}: {result.page.skipped_runs} · {t("Skipped events")}: {result.page.skipped_events}</small>{result.page.scan_limit_reached && <p>{t("The search scan limit was reached. Narrow the project or time filters.")}</p>}{result.page.next_cursor && <button className="button subtle" disabled={!readable || loading || !query} onClick={() => { if (query) void load({ ...query, cursor: result.page.next_cursor }, true); }} type="button">{t("Continue history scan")}</button>}</div></>}
  </section>;
}
