import { useEffect, useState } from "react";
import type { HostCapabilities, WorkbenchResources } from "@tracegraph/contracts";
import type { WorkbenchClient } from "../client";
import { useI18n } from "../i18n";
import { capabilityAvailable, capabilityReadable, commandId, safeError, type SettingsCategory } from "./UnifiedSettings";

const guides = {
  profile: { title: "Private local profile", text: "Your conversations and settings belong to this local profile. Credentials are kept separately and are never shown here.", operation: "settings.read", help: "Use Models to manage credentials and Usage and diagnostics to inspect local activity.", target: "usage" },
  shortcuts: { title: "Shortcut customization", text: "The send shortcut above is configurable. Navigation, command palette and settings shortcuts are listed here; remapping them is not available in this installed version.", operation: "shortcuts.write", help: "Use the command palette to find existing actions without remembering a shortcut.", target: "general" },
  personalization: { title: "Personal instructions", text: "A saved personal-instructions controller is not available in this installed version. Instructions written in a message apply to that task.", operation: "personalization.write", help: "Reviewed Memory can retain explicitly approved information. Recall remains off until you enable it.", target: "memory" },
  browser: { title: "Browser access", text: "Open Workspace tools → Browser to request a project-bound website permission and inspect the isolated browser. File permissions and project previews do not grant browser control.", operation: "browser.observe", help: "Select a project, expand Browser permissions and confirm the exact website origin in Desktop. Opening the panel does not request permission or open a tab.", target: "permissions" },
  computer: { title: "Native computer access", text: "Native application observation and input require a platform controller and explicit grant. File Full access does not authorize computer control.", operation: "computer.observe", help: "Check installation diagnostics for available platform components. No application input is sent from this page.", target: "about" },
  git: { title: "Review and version control", text: "Use the Workspace panel to inspect actual changes, stage files and manage branches or worktrees. No commit is made automatically.", operation: "git.status", help: "Worktree paths and external editor preferences are managed in Development environment.", target: "developer" },
  tasks: { title: "Task scope and continuation", text: "Conversation mode and permissions apply to the next admitted task. Existing tasks keep their original snapshots. Queued work and active resources can be inspected in Workspace tools.", operation: "resources.read", help: "A finite Goal controller and independent Agent budgets must be available before they can be configured here.", target: "permissions" },
} as const;

export function SettingsCapabilityGuide({ category, capabilities, online, client, onNavigate, onOpenBrowser }: { category: SettingsCategory; capabilities: HostCapabilities | null; online: boolean; client: WorkbenchClient; onNavigate: (category: SettingsCategory) => void; onOpenBrowser?: () => void }) {
  const { t } = useI18n();
  const [resources, setResources] = useState<WorkbenchResources | null>(null), [busy, setBusy] = useState<string | null>(null), [error, setError] = useState<string | null>(null);
  useEffect(() => { if (category !== "archive" || !online || !capabilityReadable(capabilities, "resources.read")) return; let current = true; setError(null); void client.getWorkbenchResources().then((next) => { if (current) setResources(next); }).catch((caught) => { if (current) setError(safeError(caught)); }); return () => { current = false; }; }, [category, client, online, capabilities]);
  if (category === "archive") return <section className="settings-feature-guide"><p>{t("Archived conversations stay in your local profile. Restoring one makes it visible in Recents without executing its tasks.")}</p>{error && <p role="alert">{error}</p>}{!online ? <p>{t("Reconnect to load archived conversations.")}</p> : !capabilityReadable(capabilities, "resources.read") ? <p>{t("Archive status is unavailable on this installation.")}</p> : resources === null ? <p role="status">{t("Loading…")}</p> : resources.archived_session_ids.length === 0 ? <p>{t("No archived conversations")}</p> : resources.archived_session_ids.map((id) => <div className="settings-extension-row" key={id}><span>{client.getSnapshot().sessions.find((session) => session.session_id === id)?.title ?? id}</span><button className="button subtle" disabled={busy !== null || !capabilityAvailable(capabilities, "sessions.unarchive")} type="button" onClick={() => { setBusy(id); setError(null); void client.workbenchCommand({ type: "sessions.unarchive", command_id: commandId(), session_id: id }).then(async () => { setResources(await client.getWorkbenchResources()); await client.searchSessions(""); }).catch((caught) => setError(safeError(caught))).finally(() => setBusy(null)); }}>{t("Restore conversation")}</button></div>)}</section>;
  const guide = guides[category as keyof typeof guides];
  if (!guide) return null;
  const capability = capabilities?.capabilities.find((entry) => entry.operation === guide.operation);
  return <section className="settings-feature-guide"><h3>{t(guide.title)}</h3><p>{t(guide.text)}</p>{category === "profile" && <dl className="settings-scope-facts"><dt>{t("Profile")}</dt><dd>{capabilities?.profile_id ?? t("Reconnect to load this value")}</dd><dt>{t("Scope")}</dt><dd>{t("Local profile")}</dd></dl>}{category === "browser" && onOpenBrowser && <button className="button subtle" onClick={onOpenBrowser} type="button">{t("Open browser controls")}</button>}<p className="setting-metadata">{t("Status")}: {t(!online ? "Connection unavailable" : capability?.state ?? "Not available in this installed version")}{capability?.reason && ` · ${capability.reason}`}</p><details className="setting-help"><summary>{t("Help and next steps")}</summary><p>{t(guide.help)}</p><button className="button subtle" onClick={() => onNavigate(guide.target)} type="button">{t(guide.target === "about" ? "Installation diagnostics" : guide.target === "memory" ? "Memory and privacy" : guide.target === "developer" ? "Development environment" : guide.target === "usage" ? "Usage and diagnostics" : guide.target === "permissions" ? "Permissions" : "General")}</button></details></section>;
}
