import {useEffect,useRef,useState,useSyncExternalStore} from "react";
import {ManagedSkillCommandSchema,MAX_MANAGED_SKILL_BYTES,type HostCapabilities,type ManagedSkillCommand,type ManagedSkillCommandResult,type ManagedSkillDocument,type ManagedSkillScope,type ManagedSkillsSnapshot,type ManagedSkillValidation} from "@tracegraph/contracts";
import type {WorkbenchClient} from "../client";
import {useI18n} from "../i18n";
import {capabilityAvailable,capabilityReadable,commandId,safeError} from "./UnifiedSettings";

const scopeKey=(scope:ManagedSkillScope)=>scope.kind==="global"?"global":scope.project_id;
const initialText=(t:(text:string)=>string)=>`---
name: new-skill
description: ${t("Describe when to use this Skill")}
version: 1.0.0
allowed_tools: [read_file]
---
${t("Write the local Skill instructions here.")}
`;
const sourceLabel=(source:string)=>source==="user"?"Global on this device":source==="project"?"Project":source;
const resultMessages:Readonly<Record<string,string>>={
 skill_updated:"Skill change completed.",
 skill_revision_conflict:"This Skill changed. Read the current file before saving your draft.",
 skill_state_conflict:"Skill scope changed. Refresh before choosing another change.",
 skill_exists:"This Skill name is already in use.",
 skill_not_found:"This Skill is no longer available. Refresh its scope.",
 skill_policy_changed:"Permissions changed. Review the current settings before trying again.",
 skill_policy_denied:"Your current permissions do not allow this Skill change.",
 skill_approval_denied:"You rejected this Skill change.",
 skill_scoped_write_platform_unavailable:"Skill changes are unavailable on this system.",
 skill_document_invalid:"The Skill document is invalid. Validate it before saving.",
 skill_state_limit:"This Skill scope has reached its limit. Review its loaded and removed Skills.",
};
interface Draft{name:string;content:string;document:ManagedSkillDocument|null;}
interface Pending {input:ManagedSkillCommand;result?:ManagedSkillCommandResult;}
const draftsByClient=new WeakMap<WorkbenchClient,Map<string,Draft>>();
const pendingByClient=new WeakMap<WorkbenchClient,Pending>();
export function SkillsManager({client,capabilities}:{client:WorkbenchClient;capabilities:HostCapabilities|null}){
 const {t,language}=useI18n(),snapshot=useSyncExternalStore(listener=>client.subscribe(listener),()=>client.getSnapshot(),()=>client.getSnapshot());
 const [scope,setScope]=useState<ManagedSkillScope>(()=>pendingByClient.get(client)?.input.scope??{kind:"global"}),[list,setList]=useState<ManagedSkillsSnapshot|null>(null),[draft,setDraft]=useState<Draft>({name:"new-skill",content:initialText(t),document:null});
 const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[resultCode,setResultCode]=useState<string|null>(null),[validation,setValidation]=useState<ManagedSkillValidation|null>(null);
 const [pending,setPendingState]=useState<Pending|null>(()=>pendingByClient.get(client)??null),[version,setVersion]=useState(0);
 const setPending=(value:Pending|null)=>{if(value)pendingByClient.set(client,value);else pendingByClient.delete(client);setPendingState(value);};
 const generation=useRef(0),scopeRef=useRef(scope);scopeRef.current=scope;
 let drafts=draftsByClient.get(client);if(!drafts){drafts=new Map();draftsByClient.set(client,drafts);}
 const online=snapshot.connection.state==="live"&&!snapshot.replay,readable=online&&capabilityReadable(capabilities,"skills.manage.read")&&Boolean(client.listManagedSkills),writable=readable&&capabilityAvailable(capabilities,"skills.manage.write")&&Boolean(client.managedSkillCommand)&&!loading&&!busy&&!pending;
 useEffect(()=>{const token=++generation.current;if(!readable)return;setLoading(true);setError(null);void client.listManagedSkills!(scope).then(next=>{if(token===generation.current){setList(next);setDraft(drafts!.get(scopeKey(scope))??{name:"new-skill",content:initialText(t),document:null});}}).catch(caught=>{if(token===generation.current)setError(safeError(caught));}).finally(()=>{if(token===generation.current)setLoading(false);});return()=>{generation.current++;};},[client,readable,scope,snapshot.connection.generation,version,language]);
 const resultNotice=(result:ManagedSkillCommandResult)=>`${t(Object.hasOwn(resultMessages,result.code)?resultMessages[result.code]!:result.status)}${result.status==="succeeded"?` · ${t("Applies to new tasks")}`:""}`;
 const edit=(next:Draft)=>{setDraft(next);drafts!.set(scopeKey(scope),next);setValidation(null);setNotice(null);setResultCode(null);};
 const read=async(name:string)=>{if(!readable||!client.readManagedSkill||busy||pending)return;const token=generation.current;setBusy(true);setError(null);try{const document=await client.readManagedSkill({scope,name});if(token===generation.current)edit({name,content:document.content,document});}catch(caught){if(token===generation.current)setError(safeError(caught));}finally{setBusy(false);}};
 const validate=async()=>{if(!online||!client.validateManagedSkill||!capabilityAvailable(capabilities,"skills.manage.validate"))return;setBusy(true);setError(null);try{setValidation(await client.validateManagedSkill({name:draft.name,content:draft.content}));}catch(caught){setError(safeError(caught));}finally{setBusy(false);}};
 const deliver=async(input:ManagedSkillCommand)=>{if(!online||!client.managedSkillCommand||busy)return;if(!ManagedSkillCommandSchema.safeParse(input).success||("content" in input&&new TextEncoder().encode(input.content).byteLength>MAX_MANAGED_SKILL_BYTES)){setError(t("Use a valid Skill name and UTF-8 SKILL.md text of 256 KiB or less."));return;}setBusy(true);setError(null);setNotice(null);setResultCode(null);setPending({input});try{const result=await client.managedSkillCommand(input);if(result.command_id!==input.command_id||result.name!==input.name||scopeKey(result.scope)!==scopeKey(input.scope))throw new Error(t("The Skill receipt did not match this command."));if(result.status==="awaiting_approval"||result.status==="unknown"){setPending({input,result});setNotice(t(result.status==="unknown"?"Skill change has an unknown result. Inspect the original command before making another change.":"Approve this exact local Skill change."));}else{setPending(null);if(result.status==="succeeded"){if("content" in input){const next:Draft={...draft,document:{scope:input.scope,name:input.name,sha256:result.sha256!,byte_length:new TextEncoder().encode(input.content).byteLength,enabled:draft.document?.enabled??true,removed:draft.document?.removed??false,diagnostics:[],content:input.content}};edit(next);}setVersion(v=>v+1);}setNotice(resultNotice(result));setResultCode(result.code);}}catch(caught){const e=caught as {admission?:unknown;code?:unknown;body?:{error?:unknown}};if(e.admission==="rejected"||e.code==="command_id_conflict"||e.body?.error==="command_id_conflict"){setPending(null);setError(t("The Skill change was not accepted. Your draft is preserved; repair the connection or refresh before retrying."));}else{setPending({input,result:{command_id:input.command_id,scope:input.scope,name:input.name,status:"unknown",code:"skill_effect_unknown",sha256:input.expected_sha256,effective:"new-run"}});setError(t("Skill change has an unknown result. Inspect the original command before making another change."));}}finally{setBusy(false);}};
 const inspect=async()=>{if(!pending||!online||busy||!client.getManagedSkillCommandReceipt||!capabilityReadable(capabilities,"skills.manage.reconcile"))return;setBusy(true);setError(null);try{const receipt=await client.getManagedSkillCommandReceipt(pending.input.command_id);if(receipt.command_id!==pending.input.command_id)throw new Error(t("The Skill receipt did not match this command."));if(receipt.state==="completed"&&receipt.result){setNotice(resultNotice(receipt.result));setResultCode(receipt.result.code);setPending(null);setVersion(v=>v+1);}else setNotice(t("No completed Skill receipt was found. Observed file hashes do not prove that the command completed."));}catch(caught){setError(safeError(caught));}finally{setBusy(false);}};
 const command=(type:"remove"|"restore"|"set-enabled",name:string,sha256:string,enabled?:boolean)=>{if(!list||!writable)return;const base={command_id:commandId(),scope,name,expected_sha256:sha256,expected_state_sha256:list.state_sha256};void deliver(type==="set-enabled"?{...base,type,enabled:enabled??false}:{...base,type});};
 const importFile=async(file:File)=>{if(!writable)return;const token=generation.current,key=scopeKey(scope);if(file.size>MAX_MANAGED_SKILL_BYTES){setError(t("Use UTF-8 SKILL.md text of 256 KiB or less."));return;}try{const bytes=await file.arrayBuffer();if(bytes.byteLength>MAX_MANAGED_SKILL_BYTES)throw new Error("Skill text limit");const content=new TextDecoder("utf8",{fatal:true}).decode(bytes);if(token!==generation.current||key!==scopeKey(scopeRef.current))return;edit({...draft,content});setNotice(t("Local file selected. Validate it, then save explicitly to the displayed scope."));}catch{if(token===generation.current)setError(t("Use UTF-8 SKILL.md text of 256 KiB or less."));}};
 return <section className="skills-manager" aria-label={t("Manage local Skills")}><h3>{t("Manage local Skills")}</h3><p>{t("Global Skills are available without a project. Project Skills override the same global name. Changes apply to new tasks; current tasks keep their frozen Skills.")}</p><label>{t("Skill scope")}<select aria-label={t("Skill scope")} disabled={busy||Boolean(pending)} value={scopeKey(scope)} onChange={event=>{drafts!.set(scopeKey(scope),draft);setList(null);setScope(event.target.value==="global"?{kind:"global"}:{kind:"project",project_id:event.target.value});setValidation(null);}}><option value="global">{t("Global on this device")}</option>{snapshot.availableProjects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
 {!online?<p role="status">{t(snapshot.replay?"Replay is read-only. Return to now to manage Skills.":"Reconnect to manage Skills. Your draft is preserved.")}</p>:!capabilities?<p role="status">{t("Loading…")}</p>:!readable?<p role="status">{t("Skill management is unavailable on this installation")}</p>:null}{loading&&<p role="status">{t("Loading Skills…")}</p>}
 {list&&<><small>{t("Scope state revision")}: {list.state_revision} · {t("Applies to new tasks")}</small><div className="managed-skill-list">{list.entries.map(entry=><article className="settings-skill-row" key={entry.name}><div><button className="button subtle" disabled={!readable||busy||Boolean(pending)} onClick={()=>void read(entry.name)} type="button">{entry.name}</button><small>{entry.catalog?.version??t("Invalid document")} · {t(sourceLabel(entry.catalog?.source??(scope.kind==="global"?"user":"project")))} · {t(entry.removed?"Removed, file retained":entry.enabled?"Enabled":"Disabled")}</small><p>{entry.catalog?.description}</p>{entry.diagnostics.map(diagnostic=><p key={diagnostic}>{t(diagnostic)}</p>)}<code title={entry.sha256}>{entry.sha256}</code></div><div className="settings-button-row"><button className="button subtle" disabled={!writable||entry.removed} onClick={()=>command("set-enabled",entry.name,entry.sha256,!entry.enabled)} type="button">{t(entry.enabled?"Disable Skill":"Enable Skill")}</button><button className="button subtle" disabled={!writable} onClick={()=>{if(entry.removed||window.confirm(t("Remove this Skill from loaded Skills and keep its local file?")))command(entry.removed?"restore":"remove",entry.name,entry.sha256);}} type="button">{t(entry.removed?"Restore Skill":"Remove from loaded Skills (keep file)")}</button></div></article>)}</div>{!list.entries.length&&<p>{t("No Skills in this scope. Create one or import a local SKILL.md.")}</p>}{Boolean(list.conflicts.length||list.diagnostics.length)&&<details><summary>{t("Conflicts and validation diagnostics")}</summary>{list.conflicts.map(conflict=><p key={conflict.name}>{conflict.name} · {t(conflict.winner)} → {t(conflict.loser)} · {t(conflict.reason)}</p>)}{list.diagnostics.map((item,i)=><p key={i}>{t(item)}</p>)}</details>}{Boolean(list.legacy_disabled_names.length)&&<p>{t("Some Skills are also disabled by shared tool settings. Enabling a scope cannot override that restriction.")}</p>}</>}
 <div className="managed-skill-editor"><h4>{t(draft.document?"Edit local Skill":"Create local Skill")}</h4><button className="button subtle" disabled={!writable} onClick={()=>edit({name:"new-skill",content:initialText(t),document:null})} type="button">{t("New Skill")}</button><label>{t("Skill name")}<input aria-label={t("Skill name")} value={draft.name} disabled={!writable||Boolean(draft.document)} onChange={event=>edit({...draft,name:event.target.value})}/></label><label>{t("SKILL.md content")}<textarea aria-label={t("SKILL.md content")} rows={12} value={draft.content} disabled={!writable} onChange={event=>edit({...draft,content:event.target.value})}/></label><label>{t("Import local SKILL.md")}<input aria-label={t("Import local SKILL.md")} type="file" accept=".md,text/markdown,text/plain" disabled={!writable} onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(file)void importFile(file);}}/></label><p>{t("Only explicitly selected Markdown content is imported. No remote URL, script or credential is installed. Declared tools can only restrict existing permissions.")}</p><div className="settings-button-row"><button className="button subtle" disabled={!online||busy||Boolean(pending)||!client.validateManagedSkill||!capabilityAvailable(capabilities,"skills.manage.validate")} onClick={()=>void validate()} type="button">{t("Validate Skill document")}</button><button className="button primary" disabled={!writable||!draft.name.trim()||!draft.content.trim()} onClick={()=>void deliver({type:draft.document?"save":"create",command_id:commandId(),scope,name:draft.name,expected_sha256:draft.document?.sha256??null,content:draft.content})} type="button">{t("Save Skill")}</button><button className="button subtle" disabled={!readable||busy||Boolean(pending)} onClick={()=>setVersion(v=>v+1)} type="button">{t("Refresh Skills")}</button></div>{validation&&<p role="status">{t(validation.valid?"Skill document is valid":"Invalid document")} · {validation.sha256}{validation.diagnostics.map(item=><span key={item}>{t(item)}</span>)}</p>}</div>
 {pending&&<section className="settings-command-pending"><p>{t("Scope")}: {t(pending.input.scope.kind)} · {pending.input.name}</p><code>{pending.input.expected_sha256??t("New file")} · {pending.input.command_id}</code>{pending.result?.status==="awaiting_approval"?<><p>{t("Approve this exact local Skill change.")}</p><button className="button primary" disabled={!online||busy} onClick={()=>void deliver({...pending.input,approval:{approval_id:pending.result!.approval_id!,decision:"approve"}})} type="button">{t("Approve Skill change")}</button><button className="button subtle" disabled={!online||busy} onClick={()=>void deliver({...pending.input,approval:{approval_id:pending.result!.approval_id!,decision:"deny"}})} type="button">{t("Reject Skill change")}</button></>:<button className="button subtle" disabled={!online||busy||!client.getManagedSkillCommandReceipt||!capabilityReadable(capabilities,"skills.manage.reconcile")} onClick={()=>void inspect()} type="button">{t("Inspect Skill command result")}</button>}</section>}{error&&<p role="alert">{t(error)}</p>}{notice&&<p role="status">{notice}</p>}{resultCode&&<details className="skill-result-diagnostics"><summary>{t("Skill change diagnostics")}</summary><code>{resultCode}</code></details>}
 </section>;
}
