import { useEffect, useRef, useState } from "react";
import { PersonalUsageQuerySchema, type DailyUsageBucket, type HostCapabilities, type PersonalUsageQuery, type PersonalUsageSnapshot } from "@tracegraph/contracts";
import type { WorkbenchClient } from "../client";
import { useI18n } from "../i18n";
import { capabilityReadable, safeError } from "./UnifiedSettings";

export function usageActivitySummary(days: readonly DailyUsageBucket[]) {
  let longest = 0, streak = 0, previous: number | null = null, peak: DailyUsageBucket | null = null;
  for (const day of [...days].sort((a, b) => a.day.localeCompare(b.day))) {
    const timestamp = Date.parse(`${day.day}T00:00:00.000Z`), active = day.run_count > 0 || day.model_call_count > 0;
    streak = active ? previous !== null && timestamp - previous === 86400000 ? streak + 1 : 1 : 0;
    longest = Math.max(longest, streak); previous = timestamp;
    if (!peak || day.total_tokens > peak.total_tokens) peak = day;
  }
  return { longestActiveStreak: longest, peakTokenDay: peak?.day ?? null, peakTokens: peak?.total_tokens ?? null };
}
function periodDays(from: string, to: string) { const days: string[] = []; for (let date = Date.parse(`${from}T00:00:00.000Z`), end = Date.parse(`${to}T00:00:00.000Z`); date <= end && days.length < 366; date += 86400000) days.push(new Date(date).toISOString().slice(0, 10)); return days; }

export function UsageOverview({ client, capabilities, online, generation }: { client: WorkbenchClient; capabilities: HostCapabilities | null; online: boolean; generation?: number | undefined }) {
  const { t } = useI18n(); const today = new Date().toISOString().slice(0, 10), earlier = new Date(Date.parse(`${today}T00:00:00Z`) - 89 * 86400000).toISOString().slice(0, 10);
  const [from, setFrom] = useState(earlier), [to, setTo] = useState(today), [project, setProject] = useState(""), [session, setSession] = useState("");
  const [data, setData] = useState<PersonalUsageSnapshot | null>(null), [query, setQuery] = useState<PersonalUsageQuery | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState<string | null>(null), [selectedDay, setSelectedDay] = useState<string | null>(null);
  const readVersion = useRef(0), lastQuery = useRef<PersonalUsageQuery | null>(null), readable = online && capabilityReadable(capabilities, "usage.daily") && Boolean(client.queryPersonalUsage);
  const load = async (next: PersonalUsageQuery) => { if (!readable) return; const version = ++readVersion.current; setLoading(true); setError(null); try { const result = await client.queryPersonalUsage!(next); if (version !== readVersion.current) return; const { cursor: _cursor, ...base } = next; lastQuery.current = base; setData(result); setQuery(base); } catch (caught) { if (version === readVersion.current) setError(safeError(caught)); } finally { if (version === readVersion.current) setLoading(false); } };
  const submit = () => { if (loading) return; let next; try { next = PersonalUsageQuerySchema.parse({ from_day: from, to_day: to, ...(project ? { project_id: project } : {}), ...(session ? { session_id: session } : {}) }); } catch { setError(t("Choose a valid UTC range of no more than 366 days.")); return; } void load(next); };
  useEffect(() => { if (readable) void load(lastQuery.current ?? PersonalUsageQuerySchema.parse({ from_day: earlier, to_day: today })); else setLoading(false); return () => { readVersion.current++; }; }, [client, readable, generation]);
  const summary = usageActivitySummary(data?.days ?? []), buckets = new Map(data?.days.map((day) => [day.day, day])), selected = selectedDay ? buckets.get(selectedDay) : null;
  const cost = (bucket: Pick<DailyUsageBucket, "cost_status" | "costs">) => bucket.costs.length ? `${bucket.cost_status === "partial" ? `${t("Partial reported cost")}: ` : ""}${bucket.costs.map((cost) => `${cost.amount.toLocaleString(undefined, { maximumFractionDigits: 8 })} ${cost.currency}`).join(" · ")}` : t("Unknown");
  const count = (label: string, value: number) => <div><small>{t(label)}</small><strong>{value.toLocaleString()}</strong></div>;
  return <section className="usage-overview"><h3>{t("Your recorded activity")}</h3><p>{t("This overview uses saved public activity. Dates use UTC. Missing or partial provider costs remain explicit.")}</p>{!online && <p role="status">{t("Reconnect to refresh usage. The last loaded values are shown below.")}</p>}{online && !readable && <p>{t("Daily usage is unavailable in this installation. Open Usage and diagnostics for available totals.")}</p>}
    <form className="usage-filter-row" onSubmit={(event) => { event.preventDefault(); submit(); }}><label>{t("From day (UTC)")}<input aria-label={t("Usage overview from day")} type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>{t("To day (UTC)")}<input aria-label={t("Usage overview to day")} type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><label>{t("Project")}<select aria-label={t("Usage overview project")} value={project} onChange={(event) => { setProject(event.target.value); setSession(""); }}><option value="">{t("All projects")}</option>{client.getSnapshot().availableProjects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label>{t("Session")}<select aria-label={t("Usage overview session")} value={session} onChange={(event) => setSession(event.target.value)}><option value="">{t("All sessions")}</option>{client.getSnapshot().sessions.filter((session) => !project || session.project_id === project).map((session) => <option value={session.session_id} key={session.session_id}>{session.title ?? session.session_id}</option>)}</select></label><button className="button subtle" disabled={!readable || loading} type="submit">{t("Refresh overview")}</button></form>{error && <p role="alert">{t(error)}</p>}{loading && <p role="status">{t("Loading recorded usage…")}</p>}
    {data && <><div className="usage-overview-metrics">{count("Tasks in scanned records", data.totals.run_count)}{count("Completed tasks", data.totals.completed_runs)}{count("Model requests", data.totals.model_call_count)}{count("Total tokens", data.totals.total_tokens)}{count("Projects in scanned records", data.project_count)}{count("Conversations in scanned records", data.session_count)}</div><div className="usage-overview-summary"><span>{t("Peak recorded token day")}: {summary.peakTokenDay ?? t("Unknown")} · {summary.peakTokens?.toLocaleString() ?? t("Unknown")}</span><span>{t("Longest recorded active streak")}: {summary.longestActiveStreak} {t("days")}</span><span>{t("Reported costs")}: {cost(data.totals)}</span><span>{t("Requests without reported usage")}: {data.totals.unreported_model_call_count}</span></div>
      <figure className="usage-heatmap"><figcaption>{t("Recorded daily activity")} · {data.from_day} — {data.to_day} · UTC</figcaption><div className="usage-day-grid">{periodDays(data.from_day, data.to_day).map((day) => { const bucket = buckets.get(day), intensity = bucket ? Math.min(4, Math.ceil(Math.log2(1 + bucket.run_count + bucket.model_call_count))) : null; const title = bucket ? `${day}: ${bucket.run_count} ${t("tasks")}, ${bucket.model_call_count} ${t("requests")}, ${bucket.total_tokens} Token` : `${day}: ${t("No recorded bucket was returned for this day")}`; return <button className={`usage-day ${intensity === null ? "is-unknown" : `level-${intensity}`}`} key={day} title={title} aria-label={title} aria-pressed={selectedDay === day} onClick={() => setSelectedDay(day)} type="button" data-known={bucket ? "true" : "false"} />; })}</div><p>{t("Color reflects task and model-request counts, not task quality or verified completion.")}</p></figure>
      {selectedDay && <section className="usage-selected-day"><h4>{selectedDay} · UTC</h4>{selected ? <><p>{t("Tasks")}: {selected.run_count} · {t("Completed tasks")}: {selected.completed_runs} · {t("Model requests")}: {selected.model_call_count}</p><p>{t("Input")}: {selected.input_tokens} · {t("Output")}: {selected.output_tokens} · {t("Total tokens")}: {selected.total_tokens}</p><p>{t("Reported costs")}: {cost(selected)}</p></> : <p>{t("No recorded bucket was returned for this day. It is not treated as zero usage.")}</p>}</section>}
      <div className="usage-page-state" role="status"><p>{t(data.page.complete && data.page.inventory_complete && data.page.skipped_runs === 0 && data.page.skipped_events === 0 ? "All available records in this scan were included." : "This overview is partial and includes only the records successfully scanned so far.")}</p><small>{t("Scanned tasks")}: {data.page.total_scanned_runs} · {t("Skipped tasks")}: {data.page.skipped_runs} · {t("Skipped events")}: {data.page.skipped_events} · {t("As of")}: {data.page.as_of}</small>{data.page.scan_limit_reached && <p>{t("The scan limit was reached. Narrow the project or time range to inspect more detail.")}</p>}{data.page.next_cursor && <button className="button subtle" disabled={!readable || loading || !query} onClick={() => { if (query) void load({ ...query, cursor: data.page.next_cursor }); }} type="button">{t("Continue usage scan")}</button>}</div>
    </>}
  </section>;
}
