import {useEffect,useRef,useState,useSyncExternalStore} from "react";
import {VisualEvidenceCleanupResultSchema,VisualEvidenceEntrySchema,VisualRetentionSettingsSchema,type HostCapabilities,type VisualEvidenceEntry,type VisualEvidenceCleanupRequest,type VisualEvidencePin,type VisualRetentionUpdate,type VisualRetentionSettings} from "@tracegraph/contracts";
import type {WorkbenchClient} from "../client";
import {useI18n} from "../i18n";
import {capabilityAvailable,capabilityFor,capabilityReadable,commandId} from "./UnifiedSettings";

type Inventory=Awaited<ReturnType<NonNullable<WorkbenchClient["listVisualEvidence"]>>>;
type Pending={kind:"settings";id:string;input:VisualRetentionUpdate}|{kind:"pin";id:string;evidence_id:string;input:VisualEvidencePin}|{kind:"cleanup";id:string;input:VisualEvidenceCleanupRequest};
const pendingByClient=new WeakMap<WorkbenchClient,Pending>();
const operationFor=(pending:Pending)=>pending.kind==="settings"?"visual.settings.update":pending.kind==="pin"?"visual.evidence.pin":"visual.evidence.cleanup";
export function isExpiredVisualEvidence(entry:VisualEvidenceEntry,days:number,now:number){return entry.state==="retained"&&!entry.pinned&&Date.parse(entry.captured_at)+days*86400000<=now;}

export function VisualRetentionSettingsPanel({client,capabilities}:{client:WorkbenchClient;capabilities:HostCapabilities|null}){
 const {t}=useI18n(),snapshot=useSyncExternalStore(listener=>client.subscribe(listener),()=>client.getSnapshot(),()=>client.getSnapshot());
 const online=snapshot.connection.state==="live"&&!snapshot.replay;
 const [settings,setSettings]=useState<VisualRetentionSettings|null>(null),[days,setDays]=useState(String(pendingByClient.get(client)?.kind==="settings"?(pendingByClient.get(client) as Extract<Pending,{kind:"settings"}>).input.values.retention_days:30)),[automatic,setAutomatic]=useState(pendingByClient.get(client)?.kind==="settings"?(pendingByClient.get(client) as Extract<Pending,{kind:"settings"}>).input.values.automatic_cleanup:true),[inventory,setInventory]=useState<Inventory|null>(null);
 const stored=pendingByClient.get(client);
 const [project,setProject]=useState(stored?.kind==="cleanup"?stored.input.project_id??"":""),[run,setRun]=useState(stored?.kind==="cleanup"?stored.input.run_id??"":""),[pending,setPendingState]=useState<Pending|null>(stored??null);
 const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[review,setReview]=useState(false),[version,setVersion]=useState(0),[cleanupResult,setCleanupResult]=useState<Awaited<ReturnType<NonNullable<WorkbenchClient["cleanupVisualEvidence"]>>>|null>(null);
 const generation=useRef(0),active=useRef(false),settingsDirty=useRef(stored?.kind==="settings");
 const readable=online&&capabilityReadable(capabilities,"visual.retention.read")&&Boolean(client.getVisualRetentionSettings),canList=online&&capabilityReadable(capabilities,"visual.evidence.read")&&Boolean(client.listVisualEvidence);
 const can=(operation:string)=>online&&!busy&&!loading&&!pending&&capabilityAvailable(capabilities,operation);
 const setPending=(value:Pending|null)=>{if(value)pendingByClient.set(client,value);else pendingByClient.delete(client);setPendingState(value);};
 const query={...(project?{project_id:project}:{}),...(project&&run.trim()?{run_id:run.trim()}:{}),limit:50,offset:0};
 useEffect(()=>{
  const token=++generation.current;if(!online)return;setLoading(true);setError(null);setReview(false);
  const reads:Promise<void>[]=[];
  if(readable)reads.push(client.getVisualRetentionSettings!().then(value=>{if(token!==generation.current)return;setSettings(value);if(!pendingByClient.get(client)&&!settingsDirty.current){setDays(String(value.values.retention_days));setAutomatic(value.values.automatic_cleanup);}}));
  if(canList)reads.push(client.listVisualEvidence!(query).then(value=>{if(token===generation.current)setInventory(value);}));
  void Promise.allSettled(reads).then(results=>{if(token!==generation.current)return;if(results.some(value=>value.status==="rejected"))setError(t("Screenshot settings or inventory could not be loaded. Refresh to inspect the current state."));setLoading(false);});
  return()=>{generation.current++;};
 },[client,online,readable,canList,snapshot.connection.generation,project,run,version]);
 const receive=(intent:Pending,value:unknown)=>{
  if(intent.kind==="settings"){const result=VisualRetentionSettingsSchema.parse(value);if(result.last_command_id!==intent.id)throw new Error("Visual command identity mismatch");setSettings(result);settingsDirty.current=false;setDays(String(result.values.retention_days));setAutomatic(result.values.automatic_cleanup);setNotice(t("Screenshot retention settings saved."));}
  else if(intent.kind==="pin"){const result=VisualEvidenceEntrySchema.parse(value);if(result.evidence_id!==intent.evidence_id||result.last_command_id!==intent.id)throw new Error("Visual command identity mismatch");setInventory(current=>current?{...current,entries:current.entries.map(entry=>entry.evidence_id===result.evidence_id?result:entry)}:current);setNotice(t(result.pinned?"Screenshot is now pinned and excluded from expiry cleanup.":"Screenshot is no longer pinned; its retention date applies."));}
  else{const result=VisualEvidenceCleanupResultSchema.parse(value);if(result.command_id!==intent.id)throw new Error("Visual command identity mismatch");setCleanupResult(result);if(result.status==="unknown"){setPending(intent);setNotice(t("Screenshot cleanup is uncertain. Inspect the original command; it will not be repeated."));return;}setNotice(t(result.deleted.length?"The cleanup receipt confirms these screenshots were deleted.":"The cleanup receipt reports no screenshots deleted."));setReview(false);}
  setPending(null);setVersion(value=>value+1);
 };
 const mutate=async(intent:Pending,execute:()=>Promise<unknown>)=>{
  if(!online||active.current)return;active.current=true;setBusy(true);setError(null);setNotice(null);setPending(intent);
  try{receive(intent,await execute());}
  catch(caught){const typed=caught as {admission?:unknown;code?:unknown;body?:{error?:unknown}};const code=typed.code??typed.body?.error;if(typed.admission==="rejected"||code==="visual_revision_conflict"||code==="command_id_conflict"||code==="visual_evidence_missing"||code==="visual_pin_limit"||code==="visual_evidence_settling"){setPending(null);setError(t("This screenshot change was refused. Refresh its current revision before deciding to retry."));}else{setError(t("Screenshot change has an unknown result. Inspect the original command before making another change."));}}
  finally{active.current=false;setBusy(false);}
 };
 const inspect=async()=>{
  if(!pending||!online||active.current||!client.getVisualEvidenceCommandReceipt||!capabilityReadable(capabilities,"visual.evidence.reconcile"))return;active.current=true;setBusy(true);setError(null);
  try{const receipt=await client.getVisualEvidenceCommandReceipt(pending.id);if(receipt.command_id!==pending.id||receipt.operation&&receipt.operation!==operationFor(pending))throw new Error("Visual command identity mismatch");if(receipt.state==="completed"&&receipt.result)receive(pending,receipt.result);else if(receipt.state==="failed"){setPending(null);setError(t("The original screenshot command has a failed receipt. Refresh before deciding on a new change."));}else setNotice(t("No settled screenshot receipt was found. Observed bytes do not prove cleanup completed."));}
  catch{setError(t("Could not verify the original screenshot command. Keep its ID and inspect again after reconnecting."));}
  finally{active.current=false;setBusy(false);}
 };
 const more=async()=>{if(!canList||busy||!inventory?.next_offset)return;const token=generation.current;setBusy(true);setError(null);try{const next=await client.listVisualEvidence!({...query,offset:inventory.next_offset});if(token===generation.current)setInventory(current=>{const entries=new Map(current?.entries.map(entry=>[entry.evidence_id,entry]));for(const entry of next.entries)entries.set(entry.evidence_id,entry);return {...next,entries:[...entries.values()]};});}catch{setError(t("Screenshot inventory could not be continued. The loaded records are retained."));}finally{setBusy(false);}};
 const expires=settings?inventory?.entries.filter(entry=>isExpiredVisualEvidence(entry,settings.values.retention_days,Date.now()))??[]:[];
 const stateCopy=!online?snapshot.replay?"Replay is read-only. Return to now to manage screenshots.":"Reconnect to manage screenshots. Pending commands will not repeat.":!capabilities?"Loading…":!readable?capabilityFor(capabilities,"visual.retention.read")?.state==="policy-denied"?"Your current permissions do not allow screenshot retention settings.":"Screenshot retention is unavailable on this installation.":null;
 return <section className="visual-retention-settings" aria-label={t("Screenshots and visual evidence")}>
  <h3>{t("Screenshots and visual evidence")}</h3><p>{t("Browser and computer screenshots are retained for 30 days by default. Pin important evidence to keep it. Messages, Ledger records and generated media are not deleted by this setting.")}</p>
  {stateCopy&&<p role="status">{t(stateCopy)}</p>}{loading&&<p role="status">{t("Loading screenshot retention…")}</p>}
  {settings&&<>{online&&!capabilityAvailable(capabilities,"visual.retention.write")&&<p role="status">{t(capabilityFor(capabilities,"visual.retention.write")?.state==="policy-denied"?"Your current permissions allow reading screenshot retention but not changing it.":"Screenshot retention can be inspected, but changes are unavailable on this installation.")}</p>}<label>{t("Screenshot retention days")}<input aria-label={t("Screenshot retention days")} type="number" min={1} max={365} value={days} disabled={!can("visual.retention.write")} onChange={event=>{settingsDirty.current=true;setDays(event.target.value);}}/></label><label><input aria-label={t("Automatically clean expired screenshots")} type="checkbox" checked={automatic} disabled={!can("visual.retention.write")} onChange={event=>{settingsDirty.current=true;setAutomatic(event.target.checked);}}/>{t("Automatically clean expired screenshots")}</label><p>{t("Automatic cleanup uses the background service's periodic checks. Opening this page only reads records; it does not start cleanup.")}</p><button className="button subtle" type="button" disabled={!can("visual.retention.write")||!client.updateVisualRetentionSettings||!Number.isInteger(Number(days))||Number(days)<1||Number(days)>365} onClick={()=>{const id=commandId(),input={command_id:id,expected_revision:settings.revision,values:{retention_days:Number(days),automatic_cleanup:automatic}};void mutate({kind:"settings",id,input},()=>client.updateVisualRetentionSettings!(input));}}>{t("Save screenshot retention")}</button><small>{t("Revision")}: {settings.revision}</small></>}
  <p>{t("Older screenshots without verified provenance are kept. This list contains only registered browser and computer evidence.")}</p>
  <div className="settings-button-row"><label>{t("Screenshot project scope")}<select aria-label={t("Screenshot project scope")} disabled={busy||Boolean(pending)} value={project} onChange={event=>{setProject(event.target.value);setRun("");setInventory(null);setReview(false);}}><option value="">{t("All projects")}</option>{snapshot.availableProjects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t("Screenshot task scope")}<input aria-label={t("Screenshot task scope")} disabled={!project||busy||Boolean(pending)} placeholder={t("Optional task ID")} value={run} onChange={event=>{setRun(event.target.value);setInventory(null);setReview(false);}}/></label><button className="button subtle" disabled={!online||busy||loading} onClick={()=>setVersion(value=>value+1)} type="button">{t("Refresh screenshots")}</button></div>
  {!canList&&online&&!loading&&<p role="status">{t(capabilityFor(capabilities,"visual.evidence.read")?.state==="policy-denied"?"Your current permissions do not allow screenshot records.":"Screenshot inventory is unavailable on this installation.")}</p>}
  {inventory&&<><small>{t("Loaded screenshot records")}: {inventory.entries.length} / {inventory.total}</small>{!inventory.entries.length?<p>{t("No registered screenshots were found in this scope. This is not a cleanup receipt.")}</p>:<div className="visual-evidence-list">{inventory.entries.map(entry=><article key={entry.evidence_id}><div><strong>{t(entry.source==="browser"?"Browser screenshot":"Computer screenshot")}</strong><small>{entry.captured_at} · {entry.byte_length} {t("bytes")} · {t(entry.state==="deleted"?"Screenshot deleted":entry.state)} · {t(entry.pinned?"Pinned screenshot":"Not pinned")}</small><code>{entry.evidence_id}</code></div><button className="button subtle" disabled={!can("visual.evidence.pin")||!client.pinVisualEvidence||entry.state!=="retained"} onClick={()=>{const id=commandId(),input={command_id:id,expected_revision:entry.revision,pinned:!entry.pinned};void mutate({kind:"pin",id,evidence_id:entry.evidence_id,input},()=>client.pinVisualEvidence!(entry.evidence_id,input));}} type="button">{t(entry.pinned?"Unpin screenshot":"Pin screenshot")}</button></article>)}</div>}{inventory.next_offset!==undefined&&<button className="button subtle" disabled={!canList||busy} onClick={()=>void more()} type="button">{t("Load more screenshot records")}</button>}</>}
  {canList&&!capabilityAvailable(capabilities,"visual.evidence.cleanup")&&<p role="status">{t(capabilityFor(capabilities,"visual.evidence.cleanup")?.state==="policy-denied"?"Your current permissions allow viewing screenshots but not cleaning them up.":"Screenshot records can be inspected, but cleanup is unavailable on this installation.")}</p>}
  <button className="button subtle" disabled={!can("visual.evidence.cleanup")||!client.cleanupVisualEvidence||!inventory||!settings||!expires.length} onClick={()=>setReview(true)} type="button">{t("Review expired screenshots")}</button>
  {review&&settings&&<section className="visual-cleanup-review"><h4>{t("Review screenshot cleanup scope")}</h4><p>{t("Scope")}: {project?snapshot.availableProjects.find(item=>item.id===project)?.name??project:t("All projects")}{run&&` · ${run}`} · {settings.values.retention_days} {t("days")} · {t("Maximum batch")}: 50</p><p>{t("This preview uses loaded records. Cleanup rechecks scope, expiry and pinned state; it may inspect other registered records in the same bounded scope.")}</p><ul>{expires.map(entry=><li key={entry.evidence_id}>{entry.evidence_id} · {entry.captured_at}</li>)}</ul><p>{t("Only registered screenshot bytes and their verified copies are eligible. Messages, Ledger facts, generated media and unregistered old images are kept.")}</p><button className="button primary" disabled={!can("visual.evidence.cleanup")||!client.cleanupVisualEvidence} onClick={()=>{const id=commandId(),input={command_id:id,...(project?{project_id:project}:{}),...(project&&run.trim()?{run_id:run.trim()}:{}),limit:50};void mutate({kind:"cleanup",id,input},()=>client.cleanupVisualEvidence!(input));}} type="button">{t("Confirm screenshot cleanup")}</button><button className="button subtle" disabled={busy} onClick={()=>setReview(false)} type="button">{t("Cancel")}</button></section>}
  {cleanupResult&&<section aria-label={t("Screenshot cleanup receipt")}><p>{t("Deleted screenshots")}: {cleanupResult.deleted.length} · {cleanupResult.deleted_bytes} {t("bytes")} · {t("Unknown screenshots")}: {cleanupResult.unknown.length}</p><code>{cleanupResult.command_id}</code>{cleanupResult.more_expired&&<p>{t("More expired evidence remains. Review the next batch explicitly.")}</p>}</section>}
  {pending&&<section className="settings-command-pending"><p>{t("Pending screenshot command")}</p><code>{pending.id}</code><button className="button subtle" disabled={!online||busy||!client.getVisualEvidenceCommandReceipt||!capabilityReadable(capabilities,"visual.evidence.reconcile")} onClick={()=>void inspect()} type="button">{t("Inspect original screenshot command")}</button></section>}
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </section>;
}
