import {createHash,randomUUID} from "node:crypto";
import {mkdtemp,mkdir,realpath,readFile,writeFile,rm,lstat} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {describe,it,expect,vi} from "vitest";
import {ArtifactStore,createAgentRuntime,createManagedWorkspaceHandle,DurableSessionController,JsonlSessionStore} from "@tracegraph/core";
import {createTraceGraphHost,VisualEvidenceController,registerVisualEvidenceRoutes,type ConnectedLocalHost} from "@tracegraph/host";
import {TraceGraphClient} from "@tracegraph/sdk";
import {maybeRunWorkbenchCommand} from "./workbench-command.js";
const png=Buffer.from("89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000b49444154789c636000020000050001a5f645400000000049454e44ae426082","hex");
describe("actual HTTP SDK and CLI screenshot retention",()=>{
 it("cleans only registered expired bytes through authenticated public routes and rejects replay writes",async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),"outlive-cli-retention-"))),data=join(root,"data"),project=join(root,"project");await mkdir(data);await mkdir(project);await mkdir(join(root,"browser-evidence"));await writeFile(join(project,"user-file.txt"),"USER BYTES");const store=new JsonlSessionStore(join(root,"sessions"));let modelCalls=0;const runtime=await createAgentRuntime({dataDir:data,sessionStore:store,model:{name:"local-retention-fixture",decide:async()=>{modelCalls++;return {decision_id:"decision:retention",kind:"finish",finish_intent:"answer",public_reason:"Controlled test",evidence_refs:[],risk:"none",final_answer:"Retention test complete"};}},sandboxMode:"danger-full-access"});const workspace=await createManagedWorkspaceHandle({projectId:"project:retention",root:project}),host=await createTraceGraphHost({runtime,projects:[{label:"Owned retention fixture",workspace}],sessions:new DurableSessionController({runtime,store}),capabilityToken:"isolated-retention-fixture"});const visual=await VisualEvidenceController.open({profileRoot:root,profileId:"profile:cli-retention",dataRoot:data,validateRunArtifact:async ref=>{const projection=await runtime.getProjection(ref.run_id);if(projection.project_id!==ref.project_id)throw new Error("Run scope mismatch");}});registerVisualEvidenceRoutes(host.app,visual);const address=await host.listen({port:0}),client=new TraceGraphClient({baseUrl:address});const output:string[]=[];const connection={client,close:async()=>undefined,status:{profile_id:"profile:cli-retention"}} as unknown as ConnectedLocalHost,options={connect:async()=>connection,write:(text:string)=>output.push(text),writeError:(text:string)=>output.push(text)};
 try{await client.bootstrap();const started=await client.startRun({command_id:"run:retention",project_id:workspace.project_id,task:"Return the controlled public answer",mode:"plan"});await vi.waitFor(async()=>expect((await client.getRun(started.run_id)).status).toBe("completed"));const complete=await client.getRun(started.run_id);const artifacts=new ArtifactStore(join(data,"artifacts"));const make=async()=>{const id=`browser-evidence:${randomUUID()}`,path=join(root,"browser-evidence",id.split(':')[1]+".png");await writeFile(path,png,{mode:0o600});await visual.registerBrowser({evidence_id:id,project_id:workspace.project_id,captured_at:new Date(Date.now()-31*86_400_000).toISOString(),sha256:`sha256:${createHash("sha256").update(png).digest("hex")}`,byte_length:png.length});const ref=await artifacts.putBytes({projectId:workspace.project_id,runId:started.run_id,kind:"image/png",mimeType:"image/png",content:png});await visual.registerRunCopy(id,ref);return {id,path,ref};};const expired=await make(),pinned=await make();expect(await maybeRunWorkbenchCommand(["evidence","pin",pinned.id,"--state","pinned","--expected-revision","1","--command-id","pin:cli"],options),output.join("\n")).toBe(0);expect(await maybeRunWorkbenchCommand(["evidence","settings-set","--command-id","settings:cli","--input-json",JSON.stringify({expected_revision:0,values:{retention_days:30,automatic_cleanup:false}})],options),output.join("\n")).toBe(0);expect(await maybeRunWorkbenchCommand(["evidence","cleanup","--project-id",workspace.project_id,"--run-id",started.run_id,"--command-id","cleanup:cli"],options),output.join("\n")).toBe(0);const receipt=await client.getVisualEvidenceCommandReceipt("cleanup:cli");expect(receipt).toMatchObject({state:"completed",result:{status:"completed",deleted:[expired.id],deleted_bytes:png.length*2}});await expect(lstat(expired.path)).rejects.toMatchObject({code:"ENOENT"});expect(await artifacts.inspectBytesInternal(expired.ref)).toBe("absent");expect(await readFile(pinned.path)).toEqual(png);expect(await artifacts.inspectBytesInternal(pinned.ref)).toBe("available");expect(await readFile(join(project,"user-file.txt"),"utf8")).toBe("USER BYTES");const eventsBefore=(await client.getRun(started.run_id)).timeline.map(event=>event.event_id);await client.createReplay({session_id:complete.session_id!,run_id:started.run_id,until_sequence:complete.last_sequence});await expect(client.cleanupVisualEvidence({command_id:"cleanup:replay",limit:50})).rejects.toMatchObject({status:403,body:{error:"replay_read_only"}});await expect(client.getVisualRetentionSettings()).rejects.toMatchObject({status:403,body:{error:"replay_read_only"}});expect((await runtime.getProjection(started.run_id)).timeline.map(event=>event.event_id)).toEqual(eventsBefore);expect(await visual.reconcile("cleanup:replay")).toEqual({command_id:"cleanup:replay",state:"not_found"});expect(modelCalls).toBe(1);expect(output.join('')).not.toContain(png.toString('base64'));}
 finally{await host.close();await runtime.shutdownRuns?.();await runtime.shutdownBackgroundWork?.();await visual.close();await rm(root,{recursive:true,force:true});}
 },15_000);
});
